import type { SiteLangDict } from '../../../types';
import en from './en';
const p='tool_record_a_voice_memo_in_the_browser_';
const de: SiteLangDict={...en,
[p+'title']:'Eine Sprachmemo im Browser aufnehmen',[p+'desc']:'Nehmen Sie das Mikrofon auf, prüfen Sie den Pegel und spielen oder laden Sie die Memo herunter – ohne Upload.',[p+'description']:'Nehmen Sie eine Sprachmemo direkt im Browser auf, beobachten Sie den Mikrofonpegel, pausieren Sie bei Bedarf und spielen oder laden Sie das Ergebnis anschließend herunter. Das Audio bleibt auf Ihrem Gerät und wird nicht an einen Server hochgeladen. Klicken Sie auf Aufnahme starten, erlauben Sie das Mikrofon, sprechen Sie, stoppen Sie und laden Sie die Datei herunter. Das Beispiel erzeugt ohne Mikrofonfreigabe eine 3-Sekunden-WAV-Datei.',[p+'article']:'Dieser Online-Sprachrekorder eignet sich für kurze Notizen, Mikrofontests und Voiceover-Entwürfe. Die Berechtigung wird erst nach dem Start angefordert. Laden Sie das Ergebnis vor dem Schließen des Tabs herunter.',
[p+'start']:'Aufnahme starten',[p+'pause']:'Pause',[p+'resume']:'Fortsetzen',[p+'stop']:'Stoppen',[p+'play']:'Abspielen',[p+'pause_playback']:'Wiedergabe pausieren',[p+'download']:'Aufnahme herunterladen',[p+'sample']:'Beispiel laden',[p+'clear']:'Löschen',[p+'ready']:'Aufnahmebereit. Start fordert die Mikrofonberechtigung an.',[p+'recording']:'Aufnahme läuft…',[p+'paused']:'Aufnahme pausiert.',[p+'done']:'Aufnahme bereit: {dur} s · {type}',[p+'level']:'Mikrofonpegel',[p+'timer']:'{dur} / 10:00',[p+'format']:'Browser-Ausgabe: {type}',[p+'sample_name']:'Erzeugtes 3-Sekunden-WAV-Beispiel',
[p+'err_support']:'Dieser Browser unterstützt keine Mikrofonaufnahme. Versuchen Sie eine aktuelle Version von Chrome, Edge, Firefox oder Safari.',[p+'err_secure']:'Der Mikrofonzugriff erfordert HTTPS oder localhost. Öffnen Sie die Seite über eine sichere Verbindung.',[p+'err_permission']:'Der Mikrofonzugriff wurde nicht erlaubt. Prüfen Sie die Websiteberechtigung und starten Sie erneut.',[p+'err_device']:'Kein funktionierendes Mikrofon gefunden. Schließen Sie eines an oder aktivieren Sie es.',[p+'err_empty']:'Der Rekorder hat kein Audio geliefert. Prüfen Sie den Eingangspegel.',[p+'err_interrupted']:'Der Mikrofonstream wurde vor Abschluss der Aufnahme beendet.',
[p+'hud_title']:'Fortschritt der Sprachmemo',[p+'hud_permission']:'Warte auf Mikrofonberechtigung…',[p+'hud_recording']:'Sprechen Sie jetzt und beobachten Sie den Mikrofonpegel.',[p+'hud_paused']:'Pausiert. Setzen Sie fort, wenn Sie bereit sind.',[p+'hud_ready']:'Fertig. Spielen Sie die Aufnahme ab oder laden Sie sie herunter.',[p+'hud_sample']:'Beispiel bereit. Abspielen oder WAV herunterladen.',[p+'hud_fail']:'Aufnahme beendet',[p+'hud_step_permission']:'Berechtigung',[p+'hud_step_recording']:'Aufnahme',[p+'hud_step_ready']:'Bereit',
[p+'how_title']:'So funktioniert es',[p+'how_body']:'Nehmen Sie in diesem Tab eine Mikrofon-Memo auf, prüfen Sie den Toneingang und speichern Sie die vom Browser erzeugte Datei.',[p+'how_item_1']:'Klicken Sie auf Aufnahme starten und erlauben Sie den Mikrofonzugriff.',[p+'how_item_2']:'Sprechen Sie, während Timer und Pegel laufen; nutzen Sie bei Bedarf Pause und Fortsetzen.',[p+'how_item_3']:'Klicken Sie auf Stoppen und prüfen Sie die Memo durch Abspielen.',[p+'how_item_4']:'Laden Sie die Aufnahme vor dem Schließen oder Neuladen des Tabs herunter.',
[p+'why_choose_title']:'Warum unser Tool Eine Sprachmemo im Browser aufnehmen wählen',[p+'why_choose_body']:'Die Oberfläche zeigt Berechtigung, Eingang, echtes Format und Zeitlimit deutlich an.',[p+'why_choose_item_1']:'Der Live-Pegel bestätigt, dass das Mikrofon tatsächlich Ton liefert.',[p+'why_choose_item_2']:'MIME-Typ und Dateiendung entsprechen dem Ergebnis; es wird nicht fälschlich MP3 genannt.',[p+'why_choose_item_3']:'Stream und Datei bleiben auf Ihrem Gerät und werden nicht an einen Server hochgeladen.',[p+'why_choose_item_4']:'Das Beispiel testet Wiedergabe und Download ohne Mikrofonfreigabe.',
[p+'rules_title']:'Aufnahmeregeln und Grenzen',[p+'rules_body']:'MediaRecorder erfasst das erlaubte Mikrofon. Das Format hängt vom Browser ab; nach 10 Minuten wird gestoppt.',[p+'rules_item_1']:'Das Mikrofon funktioniert nur über HTTPS oder localhost und erst nach Ihrem Klick.',[p+'rules_item_2']:'WebM/Opus, Ogg/Opus oder MP4 sind möglich. Anzeige und Endung stimmen überein; MP3 wird nicht versprochen.',[p+'rules_item_3']:'Das Limit beträgt 10 Minuten. Eine nicht heruntergeladene Memo verschwindet beim Schließen oder Neuladen.',[p+'rules_item_4']:'Das Tool zeichnet keine Anrufe oder geschützten Systemton auf und transkribiert oder entrauscht nicht.',
[p+'example_title']:'Beispiel',[p+'example']:'Beispiel laden erzeugt im Speicher eine rund 3 Sekunden lange WAV-Datei mit drei Tönen. Wiedergabe und Download funktionieren ohne Mikrofonfreigabe.',[p+'usecases_title']:'Geeignete Anwendungen',[p+'usecase_1']:'Sprechen Sie eine kurze Aufgabe oder Idee ein und laden Sie sie vor Verlassen des Tabs herunter.',[p+'usecase_2']:'Nehmen Sie eine Voiceover-Zeile oder Ausspracheübung auf und hören Sie sie sofort ab.',[p+'usecase_3']:'Prüfen Sie ein Headset vor einem Gespräch mit Pegel und kurzer Aufnahme.',[p+'references_title']:'Quellen',
[p+'faq_q1']:'Wird mein Mikrofonton hochgeladen?',[p+'faq_a1']:'Nein. Der erlaubte Stream und der Aufnahme-Blob bleiben in diesem Browser-Tab auf Ihrem Gerät und werden nicht an unsere Server gesendet.',[p+'faq_q2']:'Ist dies ein Online-Sprachrekorder und Mikrofontest?',[p+'faq_a2']:'Ja, für eine Mikrofon-Memo: starten, pausieren, fortsetzen, stoppen, abspielen und herunterladen. Anrufe oder geschützter Systemton werden nicht erfasst.',[p+'faq_q3']:'Warum ist der Download nicht immer MP3?',[p+'faq_a3']:'MediaRecorder-Formate unterscheiden sich je Browser. Die Seite wählt ein unterstütztes Opus- oder MP4-Format und verwendet dessen echte Endung.',[p+'faq_q4']:'Warum wurde die Mikrofonberechtigung verweigert?',[p+'faq_a4']:'Die Seite benötigt HTTPS oder localhost. Browser und Betriebssystem müssen dieser Website den Mikrofonzugriff erlauben.',[p+'faq_q5']:'Wie lange kann ich aufnehmen und bleibt die Memo nach Neuladen erhalten?',[p+'faq_a5']:'Das Limit ist 10 Minuten. Laden Sie vor Schließen oder Neuladen herunter, da es kein Konto und keinen Cloudspeicher gibt.',[p+'faq_q6']:'Kann ich hier schneiden, entrauschen, transkribieren oder einen Klingelton erstellen?',[p+'faq_a6']:'Diese Seite nimmt eine Memo auf. Nutzen Sie die verwandten Tools zum Schneiden oder für Klingeltöne; Transkription und Entrauschen sind eigene Aufgaben.'};
export default de;
