import type { SiteLangDict } from '../../../types';
const es: SiteLangDict = {
tool_record_a_voice_memo_in_the_browser_references_title:'Referencias',
tool_record_a_voice_memo_in_the_browser_title:'Graba una nota de voz en el navegador',
tool_record_a_voice_memo_in_the_browser_desc:'Graba el micrófono, comprueba el nivel y descarga la nota; queda en tu dispositivo y no se sube al servidor.',
tool_record_a_voice_memo_in_the_browser_description:'Graba una nota de voz en el navegador, mira el nivel del micrófono, pausa o continúa y después escucha y descarga. El audio queda en tu dispositivo y no se sube a un servidor. Pasos: Iniciar grabación, permitir el micrófono, hablar, Detener y Descargar grabación. Ejemplo: Cargar ejemplo crea un WAV de 3 segundos sin pedir acceso al micrófono. Esta grabadora de voz online conserva el formato compatible real, sin prometer MP3.',
tool_record_a_voice_memo_in_the_browser_article:'Sirve para una nota hablada, probar el micro o ensayar una locución. Solo pide permiso al iniciar; descarga antes de cerrar la pestaña.',
tool_record_a_voice_memo_in_the_browser_start:'Iniciar grabación',tool_record_a_voice_memo_in_the_browser_pause:'Pausar',tool_record_a_voice_memo_in_the_browser_resume:'Continuar',tool_record_a_voice_memo_in_the_browser_stop:'Detener',tool_record_a_voice_memo_in_the_browser_play:'Reproducir',tool_record_a_voice_memo_in_the_browser_pause_playback:'Pausar audio',tool_record_a_voice_memo_in_the_browser_download:'Descargar grabación',tool_record_a_voice_memo_in_the_browser_sample:'Cargar ejemplo',tool_record_a_voice_memo_in_the_browser_clear:'Borrar',tool_record_a_voice_memo_in_the_browser_ready:'Listo. El permiso se solicita al iniciar la grabación.',tool_record_a_voice_memo_in_the_browser_recording:'Grabando…',tool_record_a_voice_memo_in_the_browser_paused:'Grabación en pausa.',tool_record_a_voice_memo_in_the_browser_done:'Grabación lista: {dur} s · {type}',tool_record_a_voice_memo_in_the_browser_level:'Nivel del micrófono',tool_record_a_voice_memo_in_the_browser_timer:'{dur} / 10:00',tool_record_a_voice_memo_in_the_browser_format:'Formato del navegador: {type}',tool_record_a_voice_memo_in_the_browser_sample_name:'Ejemplo WAV de 3 segundos generado',
tool_record_a_voice_memo_in_the_browser_err_support:'Este navegador no permite grabar el micrófono. Prueba una versión reciente de Chrome, Edge, Firefox o Safari.',tool_record_a_voice_memo_in_the_browser_err_secure:'El micrófono necesita HTTPS o localhost. Abre una conexión segura.',tool_record_a_voice_memo_in_the_browser_err_permission:'No se permitió el micrófono. Revisa el permiso del sitio e inténtalo otra vez.',tool_record_a_voice_memo_in_the_browser_err_device:'No se encontró un micrófono operativo.',tool_record_a_voice_memo_in_the_browser_err_empty:'No se recibió audio. Comprueba el nivel e inténtalo de nuevo.',tool_record_a_voice_memo_in_the_browser_err_interrupted:'El flujo del micrófono se interrumpió antes de terminar.',
tool_record_a_voice_memo_in_the_browser_hud_title:'Progreso de la nota de voz',tool_record_a_voice_memo_in_the_browser_hud_permission:'Esperando permiso para usar el micrófono…',tool_record_a_voice_memo_in_the_browser_hud_recording:'Habla ahora y comprueba que se mueve el nivel.',tool_record_a_voice_memo_in_the_browser_hud_paused:'En pausa; continúa cuando quieras.',tool_record_a_voice_memo_in_the_browser_hud_ready:'Terminado. Ahora puedes escuchar o descargar.',tool_record_a_voice_memo_in_the_browser_hud_sample:'Ejemplo listo para reproducir o descargar.',tool_record_a_voice_memo_in_the_browser_hud_fail:'Grabación detenida',tool_record_a_voice_memo_in_the_browser_hud_step_permission:'Permiso',tool_record_a_voice_memo_in_the_browser_hud_step_recording:'Grabación',tool_record_a_voice_memo_in_the_browser_hud_step_ready:'Lista',
tool_record_a_voice_memo_in_the_browser_how_title:'Cómo grabar la nota',tool_record_a_voice_memo_in_the_browser_how_body:'Captura una nota del micrófono en esta pestaña, verifica la entrada y guarda el archivo reproducible.',tool_record_a_voice_memo_in_the_browser_how_item_1:'Pulsa Iniciar grabación y permite el micrófono.',tool_record_a_voice_memo_in_the_browser_how_item_2:'Habla mirando el tiempo y el nivel; usa Pausar y Continuar si hace falta.',tool_record_a_voice_memo_in_the_browser_how_item_3:'Pulsa Detener y reproduce la nota para revisarla.',tool_record_a_voice_memo_in_the_browser_how_item_4:'Pulsa Descargar grabación antes de cerrar o recargar.',
tool_record_a_voice_memo_in_the_browser_why_choose_title:'Por qué usar esta grabadora de notas de voz en el navegador',tool_record_a_voice_memo_in_the_browser_why_choose_body:'Muestra permiso, entrada, formato y límites que suelen quedar ocultos.',tool_record_a_voice_memo_in_the_browser_why_choose_item_1:'El medidor confirma que el micrófono elegido recibe sonido.',tool_record_a_voice_memo_in_the_browser_why_choose_item_2:'El tipo MIME y la extensión coinciden; no se cambia el nombre para fingir un MP3.',tool_record_a_voice_memo_in_the_browser_why_choose_item_3:'El flujo y el archivo permanecen en el dispositivo y no se suben al servidor.',tool_record_a_voice_memo_in_the_browser_why_choose_item_4:'El ejemplo prueba reproducción y descarga sin abrir el permiso del micro.',
tool_record_a_voice_memo_in_the_browser_rules_title:'Límites de la grabación',tool_record_a_voice_memo_in_the_browser_rules_body:'MediaRecorder captura el micrófono autorizado. El formato depende del navegador y el límite es de 10 minutos.',tool_record_a_voice_memo_in_the_browser_rules_item_1:'Solo funciona por HTTPS o localhost y pide permiso después de pulsar Iniciar.',tool_record_a_voice_memo_in_the_browser_rules_item_2:'Puede producir WebM/Opus, Ogg/Opus o MP4; se muestra el tipo real y no se promete MP3.',tool_record_a_voice_memo_in_the_browser_rules_item_3:'Se detiene a los 10 minutos; recargar elimina una nota no descargada.',tool_record_a_voice_memo_in_the_browser_rules_item_4:'Graba solo el micrófono autorizado, no llamadas, audio protegido del sistema, transcripción ni reducción de ruido.',
tool_record_a_voice_memo_in_the_browser_example_title:'Ejemplo',tool_record_a_voice_memo_in_the_browser_example:'Cargar ejemplo genera en memoria un WAV de unos 3 segundos con tres tonos. Queda listo sin solicitar el micrófono.',tool_record_a_voice_memo_in_the_browser_usecases_title:'Cuándo resulta útil',tool_record_a_voice_memo_in_the_browser_usecase_1:'Dicta una tarea o idea breve y descárgala antes de salir.',tool_record_a_voice_memo_in_the_browser_usecase_2:'Ensaya una frase de locución o pronunciación y escúchala enseguida.',tool_record_a_voice_memo_in_the_browser_usecase_3:'Comprueba unos auriculares antes de una llamada con el nivel y una grabación corta.',
tool_record_a_voice_memo_in_the_browser_faq_q1:'¿Se sube el audio del micrófono?',tool_record_a_voice_memo_in_the_browser_faq_a1:'No. El flujo autorizado y el Blob quedan en esta pestaña de tu dispositivo; no llegan a nuestros servidores.',tool_record_a_voice_memo_in_the_browser_faq_q2:'¿Sirve como grabadora de voz online, grabador de audio o prueba de micrófono?',tool_record_a_voice_memo_in_the_browser_faq_a2:'Sí para una nota de micrófono con pausa, reproducción y descarga. No captura llamadas ni audio protegido del sistema.',tool_record_a_voice_memo_in_the_browser_faq_q3:'¿Por qué la descarga no siempre es MP3?',tool_record_a_voice_memo_in_the_browser_faq_a3:'Cada navegador admite formatos distintos. Se conserva y muestra el formato real con su extensión correcta.',tool_record_a_voice_memo_in_the_browser_faq_q4:'¿Por qué se denegó el micrófono?',tool_record_a_voice_memo_in_the_browser_faq_a4:'Necesitas HTTPS o localhost y permiso del navegador y del sistema operativo para este sitio.',tool_record_a_voice_memo_in_the_browser_faq_q5:'¿Cuánto puedo grabar y se conserva al recargar?',tool_record_a_voice_memo_in_the_browser_faq_a5:'Hasta 10 minutos. Descarga antes de recargar: no hay cuenta ni almacenamiento en la nube.',tool_record_a_voice_memo_in_the_browser_faq_q6:'¿Puedo recortar, limpiar ruido, transcribir o crear un tono?',tool_record_a_voice_memo_in_the_browser_faq_a6:'Aquí solo grabas y descargas. Usa las herramientas relacionadas para recortar o crear un tono; las otras tareas requieren otro flujo.'
}; export default es;
