import type { SiteLangDict } from '../../../types';
import en from './en';
const p='tool_record_a_voice_memo_in_the_browser_';
const fr: SiteLangDict={...en,
[p+'title']:'Enregistrez un mémo vocal dans le navigateur',
[p+'desc']:'Enregistrez votre voix, vérifiez le niveau du micro, puis écoutez et téléchargez le mémo sans l’envoyer.',
[p+'description']:'Enregistrez un mémo vocal dans votre navigateur, surveillez le niveau du microphone, mettez en pause puis écoutez et téléchargez le résultat. Le son reste sur votre appareil et n’est envoyé à aucun serveur. Démarrez, autorisez le micro, parlez, arrêtez puis téléchargez le fichier. L’exemple crée un WAV de 3 secondes sans demander le micro.',
[p+'article']:'Cet enregistreur vocal en ligne convient aux mémos, essais de micro et brouillons de voix off. L’autorisation n’est demandée qu’après un clic sur Démarrer. Téléchargez le résultat avant de fermer l’onglet.',
[p+'start']:'Démarrer l’enregistrement',[p+'pause']:'Pause',[p+'resume']:'Reprendre',[p+'stop']:'Arrêter',[p+'play']:'Lire',[p+'pause_playback']:'Suspendre la lecture',[p+'download']:'Télécharger l’enregistrement',[p+'sample']:'Charger l’exemple',[p+'clear']:'Effacer',
[p+'ready']:'Prêt. Démarrer demandera l’accès au microphone.',[p+'recording']:'Enregistrement…',[p+'paused']:'Enregistrement en pause.',[p+'done']:'Enregistrement prêt : {dur} s · {type}',[p+'level']:'Niveau du microphone',[p+'timer']:'{dur} / 10:00',[p+'format']:'Format du navigateur : {type}',[p+'sample_name']:'Exemple WAV de 3 secondes généré',
[p+'err_support']:'Ce navigateur ne permet pas l’enregistrement du microphone. Essayez une version récente de Chrome, Edge, Firefox ou Safari.',[p+'err_secure']:'Le microphone exige HTTPS ou localhost. Ouvrez cette page avec une connexion sécurisée.',[p+'err_permission']:'L’accès au microphone a été refusé. Modifiez l’autorisation du site puis réessayez.',[p+'err_device']:'Aucun microphone fonctionnel n’a été trouvé. Branchez-en ou activez-en un.',[p+'err_empty']:'Aucun son n’a été produit. Vérifiez le niveau d’entrée puis réessayez.',[p+'err_interrupted']:'Le flux du microphone s’est arrêté avant la fin de l’enregistrement.',
[p+'hud_title']:'Progression du mémo vocal',[p+'hud_permission']:'En attente de l’autorisation du microphone…',[p+'hud_recording']:'Parlez maintenant et surveillez le niveau du micro.',[p+'hud_paused']:'En pause. Reprenez quand vous êtes prêt.',[p+'hud_ready']:'Terminé. Écoutez ou téléchargez l’enregistrement.',[p+'hud_sample']:'Exemple prêt. Écoutez-le ou téléchargez le WAV.',[p+'hud_fail']:'Enregistrement arrêté',[p+'hud_step_permission']:'Autorisation',[p+'hud_step_recording']:'Enregistrement',[p+'hud_step_ready']:'Prêt',
[p+'how_title']:'Fonctionnement',[p+'how_body']:'Capturez un mémo avec le microphone dans cet onglet, vérifiez le son puis sauvegardez le fichier lisible créé par le navigateur.',[p+'how_item_1']:'Cliquez sur Démarrer et autorisez le microphone.',[p+'how_item_2']:'Parlez en surveillant le minuteur et le niveau ; utilisez Pause et Reprendre au besoin.',[p+'how_item_3']:'Cliquez sur Arrêter, puis écoutez le mémo.',[p+'how_item_4']:'Téléchargez l’enregistrement avant de fermer ou actualiser l’onglet.',
[p+'why_choose_title']:'Pourquoi choisir notre outil Enregistrez un mémo vocal dans le navigateur',[p+'why_choose_body']:'Les commandes rendent visibles l’autorisation, le niveau d’entrée, le format réel et la durée maximale.',[p+'why_choose_item_1']:'Le vumètre confirme que le microphone transmet réellement du son.',[p+'why_choose_item_2']:'Le type MIME et l’extension correspondent au fichier produit ; il n’est pas renommé à tort en MP3.',[p+'why_choose_item_3']:'Le flux et le fichier restent sur votre appareil et ne sont pas envoyés à un serveur.',[p+'why_choose_item_4']:'L’exemple teste lecture et téléchargement sans demander le microphone.',
[p+'rules_title']:'Règles et limites',[p+'rules_body']:'MediaRecorder capture le microphone autorisé. Le format dépend du navigateur et l’enregistrement s’arrête après 10 minutes.',[p+'rules_item_1']:'Le micro fonctionne sur HTTPS ou localhost et seulement après votre clic.',[p+'rules_item_2']:'WebM/Opus, Ogg/Opus ou MP4 peut être choisi ; le type affiché et l’extension concordent. MP3 n’est pas garanti.',[p+'rules_item_3']:'La limite est de 10 minutes. Un mémo non téléchargé disparaît si l’onglet est fermé ou actualisé.',[p+'rules_item_4']:'L’outil n’enregistre ni appels ni audio système protégé, et ne transcrit ni ne débruite.',
[p+'example_title']:'Exemple',[p+'example']:'Charger l’exemple génère en mémoire un WAV d’environ 3 secondes avec trois tons. Il permet de tester lecture et téléchargement sans demander le microphone.',[p+'usecases_title']:'Usages adaptés',[p+'usecase_1']:'Dictez une idée ou une tâche courte et téléchargez-la avant de quitter la page.',[p+'usecase_2']:'Enregistrez une phrase de voix off ou de prononciation et réécoutez-la aussitôt.',[p+'usecase_3']:'Testez un casque avant un appel avec le niveau du micro et un court enregistrement.',[p+'references_title']:'Références',
[p+'faq_q1']:'Mon son est-il envoyé en ligne ?',[p+'faq_a1']:'Non. Le flux autorisé et le Blob restent dans cet onglet sur votre appareil et ne sont pas envoyés à nos serveurs.',[p+'faq_q2']:'Est-ce un enregistreur vocal ou micro en ligne ?',[p+'faq_a2']:'Oui, pour un mémo au microphone : démarrer, suspendre, reprendre, arrêter, écouter et télécharger. Il n’enregistre pas les appels ni l’audio système protégé.',[p+'faq_q3']:'Pourquoi le fichier n’est-il pas toujours MP3 ?',[p+'faq_a3']:'Les formats MediaRecorder varient. La page choisit un format Opus ou MP4 pris en charge et conserve son extension réelle.',[p+'faq_q4']:'Pourquoi l’accès au micro est-il refusé ?',[p+'faq_a4']:'La page doit être en HTTPS ou localhost, et le navigateur ainsi que le système doivent autoriser ce site à utiliser le micro.',[p+'faq_q5']:'Quelle est la durée maximale et le mémo survit-il à une actualisation ?',[p+'faq_a5']:'La limite est de 10 minutes. Téléchargez avant de fermer ou actualiser : il n’existe ni compte ni stockage cloud.',[p+'faq_q6']:'Puis-je couper, débruiter, transcrire ou créer une sonnerie ici ?',[p+'faq_a6']:'Cette page enregistre un mémo. Utilisez les outils liés pour couper le son ou créer une sonnerie ; transcription et débruitage sont d’autres tâches.'};
export default fr;
