import type { SiteLangDict } from '../../../types';
import en from './en';
const p='tool_record_a_voice_memo_in_the_browser_';
const id: SiteLangDict={...en,
[p+'title']:'Rekam memo suara di browser',[p+'desc']:'Rekam dari mikrofon, pantau level, lalu putar dan unduh memo tanpa mengunggahnya.',
[p+'description']:'Rekam memo suara langsung di browser, lihat level mikrofon, jeda atau lanjutkan, lalu putar dan unduh hasilnya. Audio tetap di perangkat Anda dan tidak diunggah ke server. Klik Mulai merekam, izinkan mikrofon, bicara, berhenti, lalu unduh. Contoh membuat WAV 3 detik tanpa meminta izin mikrofon.',
[p+'article']:'Perekam suara online ini cocok untuk memo singkat, pemeriksaan mikrofon, atau draf sulih suara. Izin baru diminta setelah Anda menekan Mulai merekam. Unduh hasil sebelum menutup tab.',
[p+'start']:'Mulai merekam',[p+'pause']:'Jeda',[p+'resume']:'Lanjutkan',[p+'stop']:'Berhenti',[p+'play']:'Putar',[p+'pause_playback']:'Jeda pemutaran',[p+'download']:'Unduh rekaman',[p+'sample']:'Muat contoh',[p+'clear']:'Bersihkan',[p+'ready']:'Siap merekam. Tombol mulai akan meminta izin mikrofon.',[p+'recording']:'Merekam…',[p+'paused']:'Rekaman dijeda.',[p+'done']:'Rekaman siap: {dur} dtk · {type}',[p+'level']:'Level mikrofon',[p+'timer']:'{dur} / 10:00',[p+'format']:'Keluaran browser: {type}',[p+'sample_name']:'Contoh WAV 3 detik yang dibuat',
[p+'err_support']:'Browser ini tidak mendukung perekaman mikrofon. Coba Chrome, Edge, Firefox, atau Safari terbaru.',[p+'err_secure']:'Akses mikrofon memerlukan HTTPS atau localhost. Buka halaman melalui koneksi aman.',[p+'err_permission']:'Akses mikrofon tidak diizinkan. Periksa izin situs lalu mulai lagi.',[p+'err_device']:'Mikrofon yang berfungsi tidak ditemukan. Sambungkan atau aktifkan mikrofon.',[p+'err_empty']:'Perekam tidak menghasilkan audio. Periksa level masukan lalu coba lagi.',[p+'err_interrupted']:'Aliran mikrofon berhenti sebelum rekaman selesai.',
[p+'hud_title']:'Progres memo suara',[p+'hud_permission']:'Menunggu izin mikrofon…',[p+'hud_recording']:'Bicaralah sekarang dan pantau level mikrofon.',[p+'hud_paused']:'Dijeda. Lanjutkan saat siap.',[p+'hud_ready']:'Selesai. Putar atau unduh rekaman.',[p+'hud_sample']:'Contoh siap. Putar atau unduh WAV.',[p+'hud_fail']:'Perekaman berhenti',[p+'hud_step_permission']:'Izin',[p+'hud_step_recording']:'Merekam',[p+'hud_step_ready']:'Siap',
[p+'how_title']:'Cara kerja',[p+'how_body']:'Tangkap satu memo mikrofon di tab ini, pastikan suara masuk, lalu simpan file yang dibuat browser.',[p+'how_item_1']:'Klik Mulai merekam dan izinkan akses mikrofon.',[p+'how_item_2']:'Bicara sambil melihat pewaktu dan level; gunakan Jeda dan Lanjutkan bila perlu.',[p+'how_item_3']:'Klik Berhenti, kemudian putar untuk memeriksa memo.',[p+'how_item_4']:'Unduh rekaman sebelum menutup atau memuat ulang tab.',
[p+'why_choose_title']:'Mengapa memilih alat Rekam memo suara di browser kami',[p+'why_choose_body']:'Kontrol menampilkan izin, masukan, format sebenarnya, dan batas durasi secara jelas.',[p+'why_choose_item_1']:'Meter langsung memastikan mikrofon benar-benar mengirim suara.',[p+'why_choose_item_2']:'Jenis MIME dan ekstensi unduhan sesuai hasil, bukan diberi nama MP3 palsu.',[p+'why_choose_item_3']:'Aliran dan Blob tetap di perangkat serta tidak diunggah ke server.',[p+'why_choose_item_4']:'Contoh menguji putar dan unduh tanpa membuka permintaan izin mikrofon.',
[p+'rules_title']:'Aturan dan batas',[p+'rules_body']:'MediaRecorder menangkap mikrofon yang diizinkan. Format bergantung pada browser dan batasnya 10 menit.',[p+'rules_item_1']:'Mikrofon hanya bekerja melalui HTTPS atau localhost dan dimulai setelah Anda mengeklik tombol.',[p+'rules_item_2']:'Browser dapat memilih WebM/Opus, Ogg/Opus, atau MP4. Jenis dan ekstensi cocok; MP3 tidak dijanjikan.',[p+'rules_item_3']:'Rekaman berhenti pada 10 menit. Memo yang belum diunduh hilang saat tab ditutup atau dimuat ulang.',[p+'rules_item_4']:'Alat ini tidak merekam panggilan, audio sistem terlindungi, transkripsi, atau pengurangan bising.',
[p+'example_title']:'Contoh',[p+'example']:'Muat contoh membuat WAV sekitar 3 detik dengan tiga nada di memori. Anda dapat menguji Putar dan Unduh tanpa izin mikrofon.',[p+'usecases_title']:'Cocok untuk',[p+'usecase_1']:'Ucapkan memo tugas atau ide singkat lalu unduh sebelum meninggalkan tab.',[p+'usecase_2']:'Rekam satu baris sulih suara atau latihan pelafalan dan langsung putar kembali.',[p+'usecase_3']:'Periksa headset sebelum panggilan memakai level mikrofon dan rekaman singkat.',[p+'references_title']:'Referensi',
[p+'faq_q1']:'Apakah audio mikrofon saya diunggah?',[p+'faq_a1']:'Tidak. Aliran dan Blob rekaman tetap di tab browser pada perangkat Anda dan tidak dikirim ke server kami.',[p+'faq_q2']:'Apakah ini perekam suara atau mikrofon online?',[p+'faq_a2']:'Ya, untuk memo mikrofon: mulai, jeda, lanjutkan, berhenti, putar, dan unduh. Ini tidak merekam panggilan atau audio sistem terlindungi.',[p+'faq_q3']:'Mengapa unduhan tidak selalu MP3?',[p+'faq_a3']:'Format MediaRecorder berbeda tiap browser. Halaman memilih Opus atau MP4 yang didukung dan memakai ekstensi sebenarnya.',[p+'faq_q4']:'Mengapa izin mikrofon ditolak?',[p+'faq_a4']:'Halaman harus memakai HTTPS atau localhost, dan izin browser serta sistem operasi harus mengizinkan mikrofon.',[p+'faq_q5']:'Berapa lama saya bisa merekam dan apakah tetap ada setelah dimuat ulang?',[p+'faq_a5']:'Batasnya 10 menit. Unduh sebelum menutup atau memuat ulang karena tidak ada akun atau penyimpanan cloud.',[p+'faq_q6']:'Bisakah saya memangkas, membersihkan bising, mentranskripsi, atau membuat nada dering?',[p+'faq_a6']:'Halaman ini merekam satu memo. Gunakan alat terkait untuk memangkas atau membuat nada dering; tugas lain memerlukan alat berbeda.'};
export default id;
