import type { SiteLangDict } from '../../../types';
const zh: SiteLangDict = {
  tool_record_a_voice_memo_in_the_browser_references_title:'参考资料',
  tool_record_a_voice_memo_in_the_browser_title:'在浏览器录一段语音备忘', tool_record_a_voice_memo_in_the_browser_desc:'用麦克风录音、查看输入电平，然后试听并下载；录音留在设备，不上传服务器。',
  tool_record_a_voice_memo_in_the_browser_description:'在浏览器录一段语音备忘：查看麦克风电平，可暂停和继续，停止后试听并下载。音频留在你的设备和当前标签页，不上传服务器。步骤：开始录音并授权麦克风，说话后停止，再下载录音。示例：加载示例会生成约 3 秒 WAV，不请求麦克风权限。网页录音机按浏览器实际支持格式保存，不虚假承诺 MP3。',
  tool_record_a_voice_memo_in_the_browser_article:'适合快速口述待办、试麦或录一句旁白草稿。只有点击开始录音才请求权限；停止后请在关闭标签页前下载。',
  tool_record_a_voice_memo_in_the_browser_start:'开始录音',tool_record_a_voice_memo_in_the_browser_pause:'暂停',tool_record_a_voice_memo_in_the_browser_resume:'继续',tool_record_a_voice_memo_in_the_browser_stop:'停止',tool_record_a_voice_memo_in_the_browser_play:'播放',tool_record_a_voice_memo_in_the_browser_pause_playback:'暂停播放',tool_record_a_voice_memo_in_the_browser_download:'下载录音',tool_record_a_voice_memo_in_the_browser_sample:'加载示例',tool_record_a_voice_memo_in_the_browser_clear:'清除',tool_record_a_voice_memo_in_the_browser_ready:'可以开始。点击开始录音后才会请求麦克风权限。',tool_record_a_voice_memo_in_the_browser_recording:'正在录音…',tool_record_a_voice_memo_in_the_browser_paused:'录音已暂停。',tool_record_a_voice_memo_in_the_browser_done:'录音已就绪：{dur} 秒 · {type}',tool_record_a_voice_memo_in_the_browser_level:'麦克风电平',tool_record_a_voice_memo_in_the_browser_timer:'{dur} / 10:00',tool_record_a_voice_memo_in_the_browser_format:'浏览器输出：{type}',tool_record_a_voice_memo_in_the_browser_sample_name:'已生成 3 秒 WAV 示例',
  tool_record_a_voice_memo_in_the_browser_err_support:'此浏览器不支持麦克风录音，请换用新版 Chrome、Edge、Firefox 或 Safari。',tool_record_a_voice_memo_in_the_browser_err_secure:'麦克风需要 HTTPS 或 localhost，请通过安全连接打开。',tool_record_a_voice_memo_in_the_browser_err_permission:'未获麦克风权限，请检查本站权限后重试。',tool_record_a_voice_memo_in_the_browser_err_device:'没有找到可用麦克风，请连接或启用设备。',tool_record_a_voice_memo_in_the_browser_err_empty:'没有录到音频，请检查电平后重试。',tool_record_a_voice_memo_in_the_browser_err_interrupted:'麦克风流意外停止，请重新开始。',
  tool_record_a_voice_memo_in_the_browser_hud_title:'语音备忘录制进度',tool_record_a_voice_memo_in_the_browser_hud_permission:'等待麦克风授权…',tool_record_a_voice_memo_in_the_browser_hud_recording:'现在说话，观察电平确认麦克风有输入。',tool_record_a_voice_memo_in_the_browser_hud_paused:'已暂停，准备好后继续。',tool_record_a_voice_memo_in_the_browser_hud_ready:'已完成，下一步可试听或下载录音。',tool_record_a_voice_memo_in_the_browser_hud_sample:'示例已就绪，可播放或下载 WAV。',tool_record_a_voice_memo_in_the_browser_hud_fail:'录音已停止',tool_record_a_voice_memo_in_the_browser_hud_step_permission:'授权',tool_record_a_voice_memo_in_the_browser_hud_step_recording:'录音',tool_record_a_voice_memo_in_the_browser_hud_step_ready:'就绪',
  tool_record_a_voice_memo_in_the_browser_how_title:'怎么使用',tool_record_a_voice_memo_in_the_browser_how_body:'在当前标签页录一段麦克风声音，确认有输入，再保存浏览器生成的音频文件。',tool_record_a_voice_memo_in_the_browser_how_item_1:'点击“开始录音”并允许麦克风访问。',tool_record_a_voice_memo_in_the_browser_how_item_2:'说话时观察计时和电平，需要时暂停或继续。',tool_record_a_voice_memo_in_the_browser_how_item_3:'点击“停止”，再播放检查录音。',tool_record_a_voice_memo_in_the_browser_how_item_4:'关闭或刷新标签页前点击“下载录音”。',
  tool_record_a_voice_memo_in_the_browser_why_choose_title:'为什么用本站的浏览器语音备忘录',tool_record_a_voice_memo_in_the_browser_why_choose_body:'录音时真正需要确认的权限、输入、格式和保存边界都直接显示。',tool_record_a_voice_memo_in_the_browser_why_choose_item_1:'实时电平能确认当前麦克风是否真的收到声音。',tool_record_a_voice_memo_in_the_browser_why_choose_item_2:'结果显示真实 MIME 和匹配扩展名，不把其他编码冒充 MP3。',tool_record_a_voice_memo_in_the_browser_why_choose_item_3:'麦克风流和录音文件留在设备，不上传服务器。',tool_record_a_voice_memo_in_the_browser_why_choose_item_4:'加载示例无需打开麦克风权限弹窗。',
  tool_record_a_voice_memo_in_the_browser_rules_title:'录音规则和限制',tool_record_a_voice_memo_in_the_browser_rules_body:'浏览器录制你授权的麦克风；输出格式随浏览器而异，最长 10 分钟。',tool_record_a_voice_memo_in_the_browser_rules_item_1:'只有 HTTPS 或 localhost 可用，且只在点击开始后请求权限。',tool_record_a_voice_memo_in_the_browser_rules_item_2:'可能输出 WebM/Opus、Ogg/Opus 或 MP4；显示类型和扩展名保持一致，不承诺 MP3。',tool_record_a_voice_memo_in_the_browser_rules_item_3:'满 10 分钟自动停止；刷新或关闭会丢失未下载录音。',tool_record_a_voice_memo_in_the_browser_rules_item_4:'只录获授权麦克风，不录通话、受保护系统声音，也不转写或降噪。',
  tool_record_a_voice_memo_in_the_browser_example_title:'示例',tool_record_a_voice_memo_in_the_browser_example:'加载示例会在内存生成约 3 秒、含三个音调的 WAV，直接进入就绪状态，不请求麦克风权限。',tool_record_a_voice_memo_in_the_browser_usecases_title:'适合这些场景',tool_record_a_voice_memo_in_the_browser_usecase_1:'口述一条待办或灵感，在离开标签页前下载。',tool_record_a_voice_memo_in_the_browser_usecase_2:'录一句旁白或发音练习并马上回听。',tool_record_a_voice_memo_in_the_browser_usecase_3:'通话前用在线麦克风电平和短录音检查耳麦。',
  tool_record_a_voice_memo_in_the_browser_faq_q1:'麦克风录音会上传吗？',tool_record_a_voice_memo_in_the_browser_faq_a1:'不会。授权的音频流和录音 Blob 留在设备的当前标签页，不上传到我们的服务器。',tool_record_a_voice_memo_in_the_browser_faq_q2:'在线录音、网页录音机或麦克风录音是这个工具吗？',tool_record_a_voice_memo_in_the_browser_faq_a2:'如果任务是录麦克风、暂停继续、停止、试听和下载，就是本工具；它不录通话或系统声音。',tool_record_a_voice_memo_in_the_browser_faq_q3:'为什么下载的不一定是 MP3？',tool_record_a_voice_memo_in_the_browser_faq_a3:'各浏览器支持的录制格式不同。本页显示真实类型并使用匹配扩展名，避免错误改名。',tool_record_a_voice_memo_in_the_browser_faq_q4:'为什么麦克风权限被拒绝？',tool_record_a_voice_memo_in_the_browser_faq_a4:'页面须使用 HTTPS 或 localhost，浏览器和系统也须允许本站使用麦克风。',tool_record_a_voice_memo_in_the_browser_faq_q5:'最长能录多久，刷新后还在吗？',tool_record_a_voice_memo_in_the_browser_faq_a5:'最长 10 分钟。刷新或关闭前必须下载；本站没有云端保存。',tool_record_a_voice_memo_in_the_browser_faq_q6:'能在这里裁剪、降噪、转写或做铃声吗？',tool_record_a_voice_memo_in_the_browser_faq_a6:'本页只录制并下载。起止裁剪和 30 秒铃声请使用相关工具；转写和降噪是不同任务。'
}; export default zh;
