/**
 * §12 #62 how-to-calculate-acceleration
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"v0_label": "Initial velocity v0",
		"v0_ph": "e.g. 0",
		"v_label": "Final velocity v",
		"v_ph": "e.g. 10",
		"t_label": "Time t",
		"t_ph": "e.g. 2",
		"accOut_label": "Acceleration",
		"result_note": "a = (v − v0) / t for constant acceleration.",
		"err_generic": "Enter finite v0, v and t > 0.",
		"how_title": "How it works",
		"how_body": "Enter initial and final velocity and the elapsed time.",
		"formula_title": "Formula",
		"formula_body": "a=(v−v0)/t. Notes:",
		"formula_item_1": "Assumes constant acceleration.",
		"formula_item_2": "Signs follow your velocity convention.",
		"formula_item_3": "Pair with velocity / Ohm tools.",
		"example_title": "Example",
		"example": "Example: v0=0, v=10, t=2 → a=5.",
		"usecases_title": "When to use it",
		"usecase_1": "Physics homework.",
		"usecase_2": "Quick a check.",
		"usecase_3": "Compare with velocity tool.",
		"faq_q1": "Sample?",
		"faq_a1": "(10−0)/2=5.",
		"faq_q2": "Negative a?",
		"faq_a2": "Allowed if v < v0.",
		"faq_q3": "t=0?",
		"faq_a3": "Rejected.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Acceleration",
		"disclaimer": "Educational acceleration only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — Acceleration",
		"ref_b_label": "Wikipedia — Kinematics",
	}),
	zh: withBtns("zh", {
		"v0_label": "初速度 v0",
		"v0_ph": "例如 0",
		"v_label": "末速度 v",
		"v_ph": "例如 10",
		"t_label": "时间 t",
		"t_ph": "例如 2",
		"accOut_label": "加速度",
		"result_note": "结果按加速度公式在浏览器本地计算。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算加速度。",
		"formula_title": "公式",
		"formula_body": "加速度相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：v0=0、v=10、t=2 → a=5。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：v0=0、v=10、t=2 → a=5。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "加速度",
		"disclaimer": "结果仅为加速度学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"v0_label": "v0",
		"v0_ph": "p. ej. 0",
		"v_label": "v",
		"v_ph": "p. ej. 10",
		"t_label": "t",
		"t_ph": "p. ej. 2",
		"accOut_label": "Aceleración",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce v0, v y t.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce v0, v y t.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: a=5.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: a=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de aceleración",
		"disclaimer": "Solo ilustración educativa (acceleration).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"v0_label": "v0",
		"v0_ph": "مثال 0",
		"v_label": "v",
		"v_ph": "مثال 10",
		"t_label": "t",
		"t_ph": "مثال 2",
		"accOut_label": "التسارع",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل v0 و v و t.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل v0 و v و t.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: a=5.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: a=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة التسارع",
		"disclaimer": "توضيح تعليمي فقط (acceleration).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"v0_label": "v0",
		"v0_ph": "ex. 0",
		"v_label": "v",
		"v_ph": "ex. 10",
		"t_label": "t",
		"t_ph": "ex. 2",
		"accOut_label": "Aceleração",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe v0, v e t.",
		"formula_title": "Fórmula",
		"formula_body": "Informe v0, v e t.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: a=5.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: a=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de aceleração",
		"disclaimer": "Apenas ilustração educativa (acceleration).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"v0_label": "v0",
		"v0_ph": "mis. 0",
		"v_label": "v",
		"v_ph": "mis. 10",
		"t_label": "t",
		"t_ph": "mis. 2",
		"accOut_label": "Percepatan",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi v0, v, dan t.",
		"formula_title": "Rumus",
		"formula_body": "Isi v0, v, dan t.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: a=5.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: a=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator percepatan",
		"disclaimer": "Hanya ilustrasi edukatif (acceleration).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"v0_label": "v0",
		"v0_ph": "ex. 0",
		"v_label": "v",
		"v_ph": "ex. 10",
		"t_label": "t",
		"t_ph": "ex. 2",
		"accOut_label": "Accélération",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez v0, v et t.",
		"formula_title": "Formule",
		"formula_body": "Saisissez v0, v et t.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : a=5.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : a=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur d’accélération",
		"disclaimer": "Illustration éducative (acceleration) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"v0_label": "初速度 v0",
		"v0_ph": "例 0",
		"v_label": "終速度 v",
		"v_ph": "例 10",
		"t_label": "時間 t",
		"t_ph": "例 2",
		"accOut_label": "加速度",
		"result_note": "加速度の公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れて加速度を計算します。",
		"formula_title": "計算式",
		"formula_body": "加速度の式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：v0=0、v=10、t=2 → a=5。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：v0=0、v=10、t=2 → a=5。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "加速度",
		"disclaimer": "加速度の学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"v0_label": "v0",
		"v0_ph": "напр. 0",
		"v_label": "v",
		"v_ph": "напр. 10",
		"t_label": "t",
		"t_ph": "напр. 2",
		"accOut_label": "Ускорение",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите v0, v и t.",
		"formula_title": "Формула",
		"formula_body": "Введите v0, v и t.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: a=5.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: a=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор ускорения",
		"disclaimer": "Только учебная иллюстрация (acceleration).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"v0_label": "v0",
		"v0_ph": "z. B. 0",
		"v_label": "v",
		"v_ph": "z. B. 10",
		"t_label": "t",
		"t_ph": "z. B. 2",
		"accOut_label": "Beschleunigung",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "v0, v und t eingeben.",
		"formula_title": "Formel",
		"formula_body": "v0, v und t eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: a=5.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: a=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Beschleunigungsrechner",
		"disclaimer": "Nur zur Veranschaulichung (acceleration).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 62,
	slug: "how-to-calculate-acceleration",
	prefix: "tool_acceleration",
	pageFile: "howToCalculateAccelerationPage",
	pageExport: "renderHowToCalculateAccelerationPage",
	nameZh: "加速度计算器",
	ymyl: false,
	related: ["how-to-calculate-velocity","how-to-calculate-ohms-law"],
	anchor: "acceleration",
	glyph: "M6 18h8l8-10",
	sampleHint: "v0=0 v=10 t=2 → a=5",
	titles: {
		en: "Acceleration Calculator — Change in Velocity",
		zh: "加速度计算器 — 速度变化",
		es: "Calculadora de aceleración",
		ar: "حاسبة التسارع",
		pt: "Calculadora de aceleração",
		id: "Kalkulator percepatan",
		fr: "Calculateur d’accélération",
		ja: "加速度計算ツール — 速度の変化",
		ru: "Калькулятор ускорения",
		de: "Beschleunigungsrechner",
	},
	descriptions: {
		en: "Compute constant acceleration a = (v − v0) / t. Sample: v0=0, v=10, t=2 → a=5. Browser-only.",
		zh: "计算匀加速 a = (v − v0) / t。示例：v0=0、v=10、t=2 → a=5。浏览器本地计算。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Calcula a=(v−v0)/t. Ejemplo: 0, 10, 2 → 5.",
		ar: "احسب a=(v−v0)/t. مثال: 0 و10 و2 → 5.",
		pt: "Calcule a=(v−v0)/t. Exemplo: 0, 10, 2 → 5.",
		id: "Hitung a=(v−v0)/t. Contoh: 0, 10, 2 → 5.",
		fr: "Calculez a=(v−v0)/t. Exemple : 0, 10, 2 → 5.",
		ja: "等加速度 a=(v−v0)/t を計算します。例：v0=0、v=10、t=2 → a=5。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Считайте a=(v−v0)/t. Пример: 0, 10, 2 → 5.",
		de: "a=(v−v0)/t. Beispiel: 0, 10, 2 → 5.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "v0",
	    "type": "number",
	    "half": true,
	    "labelKey": "v0_label",
	    "phKey": "v0_ph"
	  },
	  {
	    "id": "v",
	    "type": "number",
	    "half": true,
	    "labelKey": "v_label",
	    "phKey": "v_ph"
	  },
	  {
	    "id": "t",
	    "type": "number",
	    "half": true,
	    "labelKey": "t_label",
	    "phKey": "t_ph"
	  }
	],
	results: [
	  {
	    "id": "accOut",
	    "labelKey": "accOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Acceleration"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Kinematics"
	  }
	],
	computeJs: `
        var v0=parseFloat(v0El.value), v=parseFloat(vEl.value), t=parseFloat(tEl.value);
        if(!Number.isFinite(v0)||!Number.isFinite(v)||!(t>0)) return {ok:false,error:msgErr};
        return {ok:true, values:{ accOut:fmt((v-v0)/t) }};
`,
	sampleJs: `
        v0El.value='0';
        vEl.value='10';
        tEl.value='2';
`,
};
