/**
 * §12 #46 how-to-calculate-age
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"birth_label": "Birth date",
		"asof_label": "As-of date",
		"yearsOut_label": "Years",
		"monthsOut_label": "Months",
		"daysOut_label": "Days",
		"totalDaysOut_label": "Total days",
		"result_note": "Calendar age in years / months / days using UTC calendar dates (not clock time).",
		"err_generic": "Enter valid YYYY-MM-DD dates; as-of must be on or after birth.",
		"how_title": "How it works",
		"how_body": "Pick a birth date and an as-of date. Age is the calendar difference (years, then leftover months and days), plus total whole days between the dates.",
		"formula_title": "Formula",
		"formula_body": "Parse YYYY-MM-DD as UTC midnight. Subtract calendar components with month/day borrow; totalDays = (asof−birth)/86400000. Notes:",
		"formula_item_1": "Uses calendar months, not a fixed 30-day month.",
		"formula_item_2": "Ignores local timezone offsets by using UTC date parts.",
		"formula_item_3": "Leap days affect day totals when they fall in the interval.",
		"example_title": "Example",
		"example": "Example: birth 2000-01-01, as-of 2026-08-09 → 26 years, 7 months, 8 days.",
		"usecases_title": "When to use it",
		"usecase_1": "Forms that need age in Y/M/D.",
		"usecase_2": "Homework on calendar differences.",
		"usecase_3": "Pair with date-difference for span drills.",
		"faq_q1": "Sample?",
		"faq_a1": "2000-01-01 to 2026-08-09 → 26y 7m 8d.",
		"faq_q2": "Timezone?",
		"faq_a2": "Dates are treated as UTC calendar days.",
		"faq_q3": "Future birth?",
		"faq_a3": "As-of must be ≥ birth.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Calendar age",
		"disclaimer": "Educational age only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — Ageing",
		"ref_b_label": "Wikipedia — Calendar date",
	}),
	zh: withBtns("zh", {
		"birth_label": "出生日期",
		"asof_label": "截止日期",
		"yearsOut_label": "岁（年）",
		"monthsOut_label": "月",
		"daysOut_label": "天",
		"totalDaysOut_label": "总天数",
		"result_note": "按 UTC 日历日期计算岁/月/天。",
		"err_generic": "请填写有效 YYYY-MM-DD；截止 ≥ 出生。",
		"how_title": "怎么用",
		"how_body": "填写出生与截止日期，输出岁/月/天与总天数。",
		"formula_title": "公式",
		"formula_body": "UTC 解析后借位相减。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：2000-01-01 → 2026-08-09 = 26岁7月8天。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：2000-01-01 → 2026-08-09 = 26岁7月8天。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "日历年龄",
		"disclaimer": "结果仅为年龄学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia — Ageing",
		"ref_b_label": "Wikipedia — Calendar date",
	}),
	es: withBtns("es", {
		"birth_label": "Fecha de nacimiento",
		"asof_label": "Fecha de corte",
		"yearsOut_label": "Años",
		"monthsOut_label": "Meses",
		"daysOut_label": "Días",
		"totalDaysOut_label": "Días totales",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce nacimiento y fecha de corte.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce nacimiento y fecha de corte.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: 26a 7m 8d.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: 26a 7m 8d.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de edad desde el nacimiento",
		"disclaimer": "Solo ilustración educativa (age).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"birth_label": "تاريخ الميلاد",
		"asof_label": "تاريخ القطع",
		"yearsOut_label": "سنوات",
		"monthsOut_label": "أشهر",
		"daysOut_label": "أيام",
		"totalDaysOut_label": "إجمالي الأيام",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل تاريخ الميلاد وتاريخ القطع.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل تاريخ الميلاد وتاريخ القطع.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: 26س 7ش 8ي.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: 26س 7ش 8ي.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة العمر من تاريخ الميلاد",
		"disclaimer": "توضيح تعليمي فقط (age).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"birth_label": "Data de nascimento",
		"asof_label": "Data de referência",
		"yearsOut_label": "Anos",
		"monthsOut_label": "Meses",
		"daysOut_label": "Dias",
		"totalDaysOut_label": "Dias totais",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe nascimento e data de referência.",
		"formula_title": "Fórmula",
		"formula_body": "Informe nascimento e data de referência.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: 26a 7m 8d.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: 26a 7m 8d.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de idade a partir do nascimento",
		"disclaimer": "Apenas ilustração educativa (age).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"birth_label": "Tanggal lahir",
		"asof_label": "Tanggal acuan",
		"yearsOut_label": "Tahun",
		"monthsOut_label": "Bulan",
		"daysOut_label": "Hari",
		"totalDaysOut_label": "Total hari",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi tanggal lahir dan tanggal acuan.",
		"formula_title": "Rumus",
		"formula_body": "Isi tanggal lahir dan tanggal acuan.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: 26t 7b 8h.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: 26t 7b 8h.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator usia dari tanggal lahir",
		"disclaimer": "Hanya ilustrasi edukatif (age).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"birth_label": "Date de naissance",
		"asof_label": "Date de référence",
		"yearsOut_label": "Années",
		"monthsOut_label": "Mois",
		"daysOut_label": "Jours",
		"totalDaysOut_label": "Jours totaux",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez naissance et date de référence.",
		"formula_title": "Formule",
		"formula_body": "Saisissez naissance et date de référence.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : 26a 7m 8j.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : 26a 7m 8j.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur d’âge depuis la naissance",
		"disclaimer": "Illustration éducative (age) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"birth_label": "生年月日",
		"asof_label": "基準日",
		"yearsOut_label": "年",
		"monthsOut_label": "月",
		"daysOut_label": "日",
		"totalDaysOut_label": "総日数",
		"result_note": "UTC暦日で年/月/日。",
		"err_generic": "有効なYYYY-MM-DD。基準日≥生年月日。",
		"how_title": "使い方",
		"how_body": "生年月日と基準日を入力。",
		"formula_title": "計算式",
		"formula_body": "UTC解釈し借りて減算。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：2000-01-01 → 2026-08-09 = 26歳7か月8日。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：2000-01-01 → 2026-08-09 = 26歳7か月8日。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "暦年齢",
		"disclaimer": "年齢の学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia — Ageing",
		"ref_b_label": "Wikipedia — Calendar date",
	}),
	ru: withBtns("ru", {
		"birth_label": "Дата рождения",
		"asof_label": "Дата отсчёта",
		"yearsOut_label": "Годы",
		"monthsOut_label": "Месяцы",
		"daysOut_label": "Дни",
		"totalDaysOut_label": "Всего дней",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите дату рождения и дату отсчёта.",
		"formula_title": "Формула",
		"formula_body": "Введите дату рождения и дату отсчёта.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: 26л 7м 8д.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: 26л 7м 8д.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор возраста от даты рождения",
		"disclaimer": "Только учебная иллюстрация (age).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"birth_label": "Geburtsdatum",
		"asof_label": "Stichtag",
		"yearsOut_label": "Jahre",
		"monthsOut_label": "Monate",
		"daysOut_label": "Tage",
		"totalDaysOut_label": "Tage gesamt",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Geburts- und Stichtag eingeben.",
		"formula_title": "Formel",
		"formula_body": "Geburts- und Stichtag eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: 26J 7M 8T.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: 26J 7M 8T.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Altersrechner — Alter aus Geburtsdatum",
		"disclaimer": "Nur zur Veranschaulichung (age).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 46,
	slug: "how-to-calculate-age",
	prefix: "tool_age",
	pageFile: "howToCalculateAgePage",
	pageExport: "renderHowToCalculateAgePage",
	nameZh: "年龄计算器",
	ymyl: false,
	related: ["how-to-calculate-date-difference","how-to-calculate-tip"],
	anchor: "age",
	glyph: "M8 8h16v4H8zm4 6h8v8h-8z",
	sampleHint: "birth 2000-01-01 asof 2026-08-09 → 26y 7m 8d",
	titles: {
		en: "Age Calculator — Chronological Age from Birthdate",
		zh: "年龄计算器 — 由出生日期算周岁",
		es: "Calculadora de edad desde el nacimiento",
		ar: "حاسبة العمر من تاريخ الميلاد",
		pt: "Calculadora de idade a partir do nascimento",
		id: "Kalkulator usia dari tanggal lahir",
		fr: "Calculateur d’âge depuis la naissance",
		ja: "年齢計算ツール — 生年月日から満年齢",
		ru: "Калькулятор возраста от даты рождения",
		de: "Altersrechner — Alter aus Geburtsdatum",
	},
	descriptions: {
		en: "Calculate calendar age from a birth date and an as-of date (UTC YYYY-MM-DD). Sample: born 2000-01-01 as of 2026-08-09 → 26 years, 7 months, 8 days. Browser-only.",
		zh: "按出生日期与截止日期（UTC YYYY-MM-DD）计算日历年龄。示例：2000-01-01 出生、截至 2026-08-09 → 26 岁 7 个月 8 天。浏览器本地计算，数据不上传。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Calcula la edad calendario desde nacimiento y fecha de corte (UTC). Ejemplo: 2000-01-01 a 2026-08-09 → 26 años, 7 meses, 8 días.",
		ar: "احسب العمر التقويمي من تاريخ الميلاد وتاريخ القطع (UTC). مثال: 2000-01-01 حتى 2026-08-09 → 26 سنة و7 أشهر و8 أيام.",
		pt: "Calcule a idade calendário a partir do nascimento e da data de referência (UTC). Exemplo: 2000-01-01 até 2026-08-09 → 26 anos, 7 meses, 8 dias.",
		id: "Hitung usia kalender dari tanggal lahir dan tanggal acuan (UTC). Contoh: 2000-01-01 s/d 2026-08-09 → 26 tahun, 7 bulan, 8 hari.",
		fr: "Calculez l’âge calendaire à partir de la naissance et d’une date de référence (UTC). Exemple : 2000-01-01 au 2026-08-09 → 26 ans, 7 mois, 8 jours.",
		ja: "生年月日と基準日（UTC YYYY-MM-DD）から暦年齢を計算します。例：2000-01-01 生まれ、2026-08-09 時点 → 26歳7か月8日。ブラウザ内計算です。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Считайте календарный возраст от даты рождения и даты отсчёта (UTC). Пример: 2000-01-01 на 2026-08-09 → 26 лет, 7 месяцев, 8 дней.",
		de: "Kalenderalter aus Geburts- und Stichtag (UTC). Beispiel: geboren 2000-01-01, Stichtag 2026-08-09 → 26 Jahre, 7 Monate, 8 Tage.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "birth",
	    "type": "date",
	    "half": true,
	    "labelKey": "birth_label"
	  },
	  {
	    "id": "asof",
	    "type": "date",
	    "half": true,
	    "labelKey": "asof_label"
	  }
	],
	results: [
	  {
	    "id": "yearsOut",
	    "labelKey": "yearsOut_label"
	  },
	  {
	    "id": "monthsOut",
	    "labelKey": "monthsOut_label"
	  },
	  {
	    "id": "daysOut",
	    "labelKey": "daysOut_label"
	  },
	  {
	    "id": "totalDaysOut",
	    "labelKey": "totalDaysOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Ageing"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Calendar_date"
	  }
	],
	computeJs: `
        function parseYMD(s){
          var m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(s||'').trim());
          if(!m) return null;
          var y=+m[1], mo=+m[2]-1, d=+m[3];
          var dt=new Date(Date.UTC(y,mo,d));
          if(dt.getUTCFullYear()!==y||dt.getUTCMonth()!==mo||dt.getUTCDate()!==d) return null;
          return dt;
        }
        var birth=parseYMD(birthEl.value), asof=parseYMD(asofEl.value);
        if(!birth||!asof||asof.getTime()<birth.getTime()) return {ok:false,error:msgErr};
        var years=asof.getUTCFullYear()-birth.getUTCFullYear();
        var months=asof.getUTCMonth()-birth.getUTCMonth();
        var days=asof.getUTCDate()-birth.getUTCDate();
        if(days<0){
          months--;
          var prev=new Date(Date.UTC(asof.getUTCFullYear(), asof.getUTCMonth(), 0));
          days+=prev.getUTCDate();
        }
        if(months<0){ years--; months+=12; }
        var totalDays=Math.round((asof.getTime()-birth.getTime())/86400000);
        return {ok:true, values:{ yearsOut:String(years), monthsOut:String(months), daysOut:String(days), totalDaysOut:String(totalDays) }};
`,
	sampleJs: `
        birthEl.value='2000-01-01';
        asofEl.value='2026-08-09';
`,
};
