/**
 * §12 #53 how-to-calculate-circle
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"r_label": "Radius",
		"r_ph": "e.g. 7",
		"areaOut_label": "Area",
		"circOut_label": "Circumference",
		"result_note": "Area = πr²; circumference = 2πr (JS Math.PI).",
		"err_generic": "Enter radius > 0.",
		"how_title": "How it works",
		"how_body": "Enter the radius. Results use the browser Math.PI constant.",
		"formula_title": "Formula",
		"formula_body": "A=πr²; C=2πr. Notes:",
		"formula_item_1": "Diameter is not a separate input — use r = d/2.",
		"formula_item_2": "Units are those of r, squared for area.",
		"formula_item_3": "Pair with triangle / volume tools.",
		"example_title": "Example",
		"example": "Example: r=7 → area ≈ 153.94, circumference ≈ 43.98.",
		"usecases_title": "When to use it",
		"usecase_1": "Geometry homework.",
		"usecase_2": "Quick circle check.",
		"usecase_3": "Compare related shape tools.",
		"faq_q1": "Sample?",
		"faq_a1": "r=7 → ≈153.94 and ≈43.98.",
		"faq_q2": "Diameter?",
		"faq_a2": "Halve it to get r.",
		"faq_q3": "Exact π?",
		"faq_a3": "Uses Math.PI.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Circle area and circumference",
		"disclaimer": "Educational circle only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — Circle",
		"ref_b_label": "Wikipedia — Circumference",
	}),
	zh: withBtns("zh", {
		"r_label": "半径",
		"r_ph": "例如 7",
		"areaOut_label": "面积",
		"circOut_label": "周长",
		"result_note": "结果按圆公式在浏览器本地计算。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算圆。",
		"formula_title": "公式",
		"formula_body": "圆相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：r=7 → 面积约 153.94、周长约 43.98。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：r=7 → 面积约 153.94、周长约 43.98。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "圆",
		"disclaimer": "结果仅为圆学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"r_label": "Radio",
		"r_ph": "p. ej. 7",
		"areaOut_label": "Área",
		"circOut_label": "Circunferencia",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce el radio.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce el radio.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: r=7.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: r=7.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de círculo",
		"disclaimer": "Solo ilustración educativa (circle).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"r_label": "نصف القطر",
		"r_ph": "مثال 7",
		"areaOut_label": "المساحة",
		"circOut_label": "المحيط",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل نصف القطر.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل نصف القطر.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: r=7.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: r=7.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة الدائرة",
		"disclaimer": "توضيح تعليمي فقط (circle).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"r_label": "Raio",
		"r_ph": "ex. 7",
		"areaOut_label": "Área",
		"circOut_label": "Circunferência",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe o raio.",
		"formula_title": "Fórmula",
		"formula_body": "Informe o raio.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: r=7.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: r=7.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de círculo",
		"disclaimer": "Apenas ilustração educativa (circle).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"r_label": "Jari-jari",
		"r_ph": "mis. 7",
		"areaOut_label": "Luas",
		"circOut_label": "Keliling",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi jari-jari.",
		"formula_title": "Rumus",
		"formula_body": "Isi jari-jari.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: r=7.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: r=7.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator lingkaran",
		"disclaimer": "Hanya ilustrasi edukatif (circle).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"r_label": "Rayon",
		"r_ph": "ex. 7",
		"areaOut_label": "Aire",
		"circOut_label": "Circonférence",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez le rayon.",
		"formula_title": "Formule",
		"formula_body": "Saisissez le rayon.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : r=7.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : r=7.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de cercle",
		"disclaimer": "Illustration éducative (circle) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"r_label": "半径",
		"r_ph": "例 7",
		"areaOut_label": "面積",
		"circOut_label": "周長",
		"result_note": "円の公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れて円を計算します。",
		"formula_title": "計算式",
		"formula_body": "円の式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：r=7 → 面積約153.94、周長約43.98。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：r=7 → 面積約153.94、周長約43.98。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "円",
		"disclaimer": "円の学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"r_label": "Радиус",
		"r_ph": "напр. 7",
		"areaOut_label": "Площадь",
		"circOut_label": "Длина окружности",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите радиус.",
		"formula_title": "Формула",
		"formula_body": "Введите радиус.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: r=7.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: r=7.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор круга",
		"disclaimer": "Только учебная иллюстрация (circle).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"r_label": "Radius",
		"r_ph": "z. B. 7",
		"areaOut_label": "Fläche",
		"circOut_label": "Umfang",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Radius eingeben.",
		"formula_title": "Formel",
		"formula_body": "Radius eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: r=7.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: r=7.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kreisrechner — Fläche und Umfang",
		"disclaimer": "Nur zur Veranschaulichung (circle).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 53,
	slug: "how-to-calculate-circle",
	prefix: "tool_circle",
	pageFile: "howToCalculateCirclePage",
	pageExport: "renderHowToCalculateCirclePage",
	nameZh: "圆面积与周长计算器",
	ymyl: false,
	related: ["how-to-calculate-triangle-area","how-to-calculate-volume"],
	anchor: "circle",
	glyph: "M16 6a10 10 0 1 0 0.001 0",
	sampleHint: "r=7 → area≈153.94 circ≈43.98",
	titles: {
		en: "Circle Calculator — Area and Circumference",
		zh: "圆计算器 — 面积与周长",
		es: "Calculadora de círculo",
		ar: "حاسبة الدائرة",
		pt: "Calculadora de círculo",
		id: "Kalkulator lingkaran",
		fr: "Calculateur de cercle",
		ja: "円の計算ツール — 面積と周長",
		ru: "Калькулятор круга",
		de: "Kreisrechner — Fläche und Umfang",
	},
	descriptions: {
		en: "Compute circle area (πr²) and circumference (2πr). Sample: r=7 → area ≈ 153.94, circumference ≈ 43.98. Browser-only.",
		zh: "计算圆面积 πr² 与周长 2πr。示例：r=7 → 面积约 153.94、周长约 43.98。浏览器本地计算。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Calcula área πr² y circunferencia 2πr. Ejemplo: r=7 → ≈153.94 / ≈43.98.",
		ar: "احسب المساحة πr² والمحيط 2πr. مثال: r=7 → ≈153.94 / ≈43.98.",
		pt: "Calcule área πr² e circunferência 2πr. Exemplo: r=7 → ≈153.94 / ≈43.98.",
		id: "Hitung luas πr² dan keliling 2πr. Contoh: r=7 → ≈153.94 / ≈43.98.",
		fr: "Calculez aire πr² et circonférence 2πr. Exemple : r=7 → ≈153.94 / ≈43.98.",
		ja: "円の面積πr²と周長2πrを計算します。例：r=7 → 面積約153.94、周長約43.98。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Считайте площадь πr² и длину 2πr. Пример: r=7 → ≈153.94 / ≈43.98.",
		de: "Fläche πr² und Umfang 2πr. Beispiel: r=7 → ≈153.94 / ≈43.98.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "r",
	    "type": "number",
	    "half": true,
	    "labelKey": "r_label",
	    "phKey": "r_ph"
	  }
	],
	results: [
	  {
	    "id": "areaOut",
	    "labelKey": "areaOut_label"
	  },
	  {
	    "id": "circOut",
	    "labelKey": "circOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Circle"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Circumference"
	  }
	],
	computeJs: `
        var r=parseFloat(rEl.value);
        if(!(r>0)) return {ok:false,error:msgErr};
        return {ok:true, values:{ areaOut:fmt(Math.PI*r*r), circOut:fmt(2*Math.PI*r) }};
`,
	sampleJs: `
        rEl.value='7';
`,
};
