/**
 * §12 #37 how-to-calculate-contribution-margin
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"price_label": "Price per unit",
		"price_ph": "e.g. 50",
		"vc_label": "Variable cost per unit",
		"vc_ph": "e.g. 30",
		"cmOut_label": "Contribution margin",
		"cmrOut_label": "CM ratio",
		"result_note": "CM = price − VC; ratio = CM / price. Educational only.",
		"err_generic": "Enter price > 0 and variable cost ≥ 0.",
		"how_title": "How it works",
		"how_body": "Enter unit price and unit variable cost. Contribution margin is what remains to cover fixed costs and profit.",
		"formula_title": "Formula",
		"formula_body": "CM = P − VC; CM ratio = CM / P. Notes:",
		"formula_item_1": "Variable cost should move with units; fixed costs belong in break-even analysis.",
		"formula_item_2": "Price must be > 0.",
		"formula_item_3": "Taxes and multi-product mixes are not modeled.",
		"example_title": "Example",
		"example": "Example: price 50, VC 30 → CM = 20; ratio = 20/50 = 40%.",
		"usecases_title": "When to use it",
		"usecase_1": "Homework: unit contribution before break-even.",
		"usecase_2": "See how a VC change moves the ratio.",
		"usecase_3": "Pair with the break-even calculator for fixed costs.",
		"faq_q1": "Sample result?",
		"faq_a1": "P=50, VC=30 → CM 20 and 40%.",
		"faq_q2": "CM vs gross margin?",
		"faq_a2": "CM uses variable cost; gross margin uses COGS which may include other items.",
		"faq_q3": "Need quantity?",
		"faq_a3": "Unit CM does not need quantity; total CM = CM × units.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Contribution Margin Calculator — Price Minus Variable Cost",
		"disclaimer": "Educational contribution margin only — not financial, tax, or investment advice.",
		"references": "Investopedia and standard textbook formulas.",
		"ref_a_label": "Investopedia — Contribution margin",
		"ref_b_label": "Investopedia — Break-even",
	}),
	zh: withBtns("zh", {
		"price_label": "单价",
		"price_ph": "例如 50",
		"vc_label": "单位变动成本",
		"vc_ph": "例如 30",
		"cmOut_label": "边际贡献",
		"cmrOut_label": "贡献率",
		"result_note": "边际贡献 = 单价 − 变动成本；贡献率 = 边际贡献 / 单价。仅供学习。",
		"err_generic": "请填写单价 > 0，变动成本 ≥ 0。",
		"how_title": "怎么用",
		"how_body": "填入单价与单位变动成本。边际贡献用于覆盖固定成本并形成利润。",
		"formula_title": "公式",
		"formula_body": "CM = P − VC；贡献率 = CM / P。注意：",
		"formula_item_1": "变动成本随销量变化；固定成本请用盈亏平衡工具。",
		"formula_item_2": "单价必须 > 0。",
		"formula_item_3": "多产品与税费不建模。",
		"example_title": "示例",
		"example": "示例：单价 50、变动成本 30 → CM=20；贡献率=40%。",
		"usecases_title": "适合什么场景",
		"usecase_1": "作业：求单位边际贡献。",
		"usecase_2": "观察变动成本变动对贡献率的影响。",
		"usecase_3": "配合盈亏平衡看固定成本。",
		"faq_q1": "样例？",
		"faq_a1": "50 与 30 → CM 20、率 40%。",
		"faq_q2": "与毛利率差别？",
		"faq_a2": "边际贡献用变动成本；毛利常用 COGS。",
		"faq_q3": "需要销量吗？",
		"faq_a3": "单位 CM 不需要；总额 = CM×销量。",
		"faq_q4": "经营建议？",
		"faq_a4": "不是。",
		"article": "边际贡献计算器 — 单价减变动成本",
		"disclaimer": "结果仅为边际贡献学习演示，不构成投资、理财或税务建议。",
		"references": "Investopedia 与常见教材公式。",
		"ref_a_label": "Investopedia — Contribution margin",
		"ref_b_label": "Investopedia — Break-even",
	}),
	es: withBtns("es", {
		"price_label": "Precio unitario",
		"price_ph": "p. ej. 50",
		"vc_label": "Costo variable unitario",
		"vc_ph": "p. ej. 30",
		"cmOut_label": "Margen de contribución",
		"cmrOut_label": "Ratio MC",
		"result_note": "Educativo.",
		"err_generic": "Precio > 0 y CV ≥ 0.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce precio y costo variable unitario.",
		"formula_title": "Fórmula",
		"formula_body": "MC = P − CV; ratio = MC / P.",
		"formula_item_1": "VC with units; fixed costs → break-even.",
		"formula_item_2": "Price > 0.",
		"formula_item_3": "Simplified.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: 50 y 30 → MC 20 (40%).",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Unit CM homework.",
		"usecase_2": "VC sensitivity.",
		"usecase_3": "With break-even tool.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "20 / 40%",
		"faq_q2": "CM vs gross?",
		"faq_a2": "VC vs COGS.",
		"faq_q3": "Qty needed?",
		"faq_a3": "Not for unit CM.",
		"faq_q4": "Advice?",
		"faq_a4": "No.",
		"article": "Calculadora de margen de contribución",
		"disclaimer": "Solo ilustración educativa (contribution margin); no es consejo financiero.",
		"references": "Investopedia y fórmulas de libro.",
		"ref_a_label": "Investopedia — Contribution margin",
		"ref_b_label": "Investopedia — Break-even",
	}),
	ar: withBtns("ar", {
		"price_label": "سعر الوحدة",
		"price_ph": "مثال 50",
		"vc_label": "تكلفة متغيرة للوحدة",
		"vc_ph": "مثال 30",
		"cmOut_label": "هامش المساهمة",
		"cmrOut_label": "نسبة الهامش",
		"result_note": "تعليمي.",
		"err_generic": "سعر > 0 وتكلفة ≥ 0.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل السعر والتكلفة المتغيرة.",
		"formula_title": "الصيغة",
		"formula_body": "CM = P − VC؛ النسبة = CM / P.",
		"formula_item_1": "VC with units; fixed costs → break-even.",
		"formula_item_2": "Price > 0.",
		"formula_item_3": "Simplified.",
		"example_title": "مثال",
		"example": "مثال: 50 و30 → 20 (40٪).",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Unit CM homework.",
		"usecase_2": "VC sensitivity.",
		"usecase_3": "With break-even tool.",
		"faq_q1": "المثال؟",
		"faq_a1": "20 / 40%",
		"faq_q2": "CM vs gross?",
		"faq_a2": "VC vs COGS.",
		"faq_q3": "Qty needed?",
		"faq_a3": "Not for unit CM.",
		"faq_q4": "Advice?",
		"faq_a4": "No.",
		"article": "حاسبة هامش المساهمة",
		"disclaimer": "توضيح تعليمي فقط (contribution margin) وليس نصيحة مالية.",
		"references": "Investopedia وصيغ دراسية.",
		"ref_a_label": "Investopedia — Contribution margin",
		"ref_b_label": "Investopedia — Break-even",
	}),
	pt: withBtns("pt", {
		"price_label": "Preço unitário",
		"price_ph": "ex. 50",
		"vc_label": "Custo variável unitário",
		"vc_ph": "ex. 30",
		"cmOut_label": "Margem de contribuição",
		"cmrOut_label": "Razão MC",
		"result_note": "Educativo.",
		"err_generic": "Preço > 0 e CV ≥ 0.",
		"how_title": "Como funciona",
		"how_body": "Informe preço e custo variável unitário.",
		"formula_title": "Fórmula",
		"formula_body": "MC = P − CV; razão = MC / P.",
		"formula_item_1": "VC with units; fixed costs → break-even.",
		"formula_item_2": "Price > 0.",
		"formula_item_3": "Simplified.",
		"example_title": "Exemplo",
		"example": "Exemplo: 50 e 30 → 20 (40%).",
		"usecases_title": "Quando usar",
		"usecase_1": "Unit CM homework.",
		"usecase_2": "VC sensitivity.",
		"usecase_3": "With break-even tool.",
		"faq_q1": "Exemplo?",
		"faq_a1": "20 / 40%",
		"faq_q2": "CM vs gross?",
		"faq_a2": "VC vs COGS.",
		"faq_q3": "Qty needed?",
		"faq_a3": "Not for unit CM.",
		"faq_q4": "Advice?",
		"faq_a4": "No.",
		"article": "Calculadora de margem de contribuição",
		"disclaimer": "Apenas ilustração educativa (contribution margin); não é conselho financeiro.",
		"references": "Investopedia e fórmulas didáticas.",
		"ref_a_label": "Investopedia — Contribution margin",
		"ref_b_label": "Investopedia — Break-even",
	}),
	id: withBtns("id", {
		"price_label": "Harga satuan",
		"price_ph": "mis. 50",
		"vc_label": "Biaya variabel per unit",
		"vc_ph": "mis. 30",
		"cmOut_label": "Contribution margin",
		"cmrOut_label": "Rasio CM",
		"result_note": "Edukatif.",
		"err_generic": "Harga > 0 dan VC ≥ 0.",
		"how_title": "Cara kerja",
		"how_body": "Isi harga dan biaya variabel per unit.",
		"formula_title": "Rumus",
		"formula_body": "CM = P − VC; rasio = CM / P.",
		"formula_item_1": "VC with units; fixed costs → break-even.",
		"formula_item_2": "Price > 0.",
		"formula_item_3": "Simplified.",
		"example_title": "Contoh",
		"example": "Contoh: 50 dan 30 → 20 (40%).",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Unit CM homework.",
		"usecase_2": "VC sensitivity.",
		"usecase_3": "With break-even tool.",
		"faq_q1": "Contoh?",
		"faq_a1": "20 / 40%",
		"faq_q2": "CM vs gross?",
		"faq_a2": "VC vs COGS.",
		"faq_q3": "Qty needed?",
		"faq_a3": "Not for unit CM.",
		"faq_q4": "Advice?",
		"faq_a4": "No.",
		"article": "Kalkulator contribution margin",
		"disclaimer": "Hanya ilustrasi edukatif (contribution margin); bukan saran keuangan.",
		"references": "Investopedia dan rumus buku teks.",
		"ref_a_label": "Investopedia — Contribution margin",
		"ref_b_label": "Investopedia — Break-even",
	}),
	fr: withBtns("fr", {
		"price_label": "Prix unitaire",
		"price_ph": "ex. 50",
		"vc_label": "Coût variable unitaire",
		"vc_ph": "ex. 30",
		"cmOut_label": "Marge sur coût variable",
		"cmrOut_label": "Taux de MCV",
		"result_note": "Éducatif.",
		"err_generic": "Prix > 0 et CV ≥ 0.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez prix et coût variable unitaire.",
		"formula_title": "Formule",
		"formula_body": "MCV = P − CV ; taux = MCV / P.",
		"formula_item_1": "VC with units; fixed costs → break-even.",
		"formula_item_2": "Price > 0.",
		"formula_item_3": "Simplified.",
		"example_title": "Exemple",
		"example": "Exemple : 50 et 30 → 20 (40 %).",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Unit CM homework.",
		"usecase_2": "VC sensitivity.",
		"usecase_3": "With break-even tool.",
		"faq_q1": "Exemple ?",
		"faq_a1": "20 / 40%",
		"faq_q2": "CM vs gross?",
		"faq_a2": "VC vs COGS.",
		"faq_q3": "Qty needed?",
		"faq_a3": "Not for unit CM.",
		"faq_q4": "Advice?",
		"faq_a4": "No.",
		"article": "Calculateur de marge sur coût variable",
		"disclaimer": "Illustration éducative (contribution margin) uniquement — pas un conseil financier.",
		"references": "Investopedia et formules de manuel.",
		"ref_a_label": "Investopedia — Contribution margin",
		"ref_b_label": "Investopedia — Break-even",
	}),
	ja: withBtns("ja", {
		"price_label": "単価",
		"price_ph": "例 50",
		"vc_label": "単位変動費",
		"vc_ph": "例 30",
		"cmOut_label": "貢献利益",
		"cmrOut_label": "貢献利益率",
		"result_note": "貢献利益 = 単価 − 変動費。学習用です。",
		"err_generic": "単価 > 0、変動費 ≥ 0。",
		"how_title": "使い方",
		"how_body": "単価と単位変動費を入力します。貢献利益は固定費と利益をまかなう残りです。",
		"formula_title": "計算式",
		"formula_body": "CM = P − VC；率 = CM / P。注意:",
		"formula_item_1": "変動費は数量に連動。固定費は損益分岐へ。",
		"formula_item_2": "単価 > 0。",
		"formula_item_3": "多品種や税は扱いません。",
		"example_title": "例",
		"example": "例：単価50、変動費30 → CM=20、率40%。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題：単位貢献利益。",
		"usecase_2": "変動費変化の影響確認。",
		"usecase_3": "損益分岐ツールと併用。",
		"faq_q1": "例の結果は？",
		"faq_a1": "50と30 → 20（40%）。",
		"faq_q2": "粗利との違いは？",
		"faq_a2": "貢献利益は変動費ベース。",
		"faq_q3": "数量は必要？",
		"faq_a3": "単位CMには不要。",
		"faq_q4": "助言ですか？",
		"faq_a4": "学習用です。",
		"article": "貢献利益の計算ツール — 単価と変動費",
		"disclaimer": "貢献利益の学習用試算であり、投資・税務の助言ではありません。",
		"references": "Investopedia と標準的な教科書公式。",
		"ref_a_label": "Investopedia — Contribution margin",
		"ref_b_label": "Investopedia — Break-even",
	}),
	ru: withBtns("ru", {
		"price_label": "Цена за единицу",
		"price_ph": "напр. 50",
		"vc_label": "Переменные затраты на ед.",
		"vc_ph": "напр. 30",
		"cmOut_label": "Маржинальная прибыль",
		"cmrOut_label": "Доля CM",
		"result_note": "Учебно.",
		"err_generic": "Цена > 0 и VC ≥ 0.",
		"how_title": "Как пользоваться",
		"how_body": "Введите цену и переменные затраты на единицу.",
		"formula_title": "Формула",
		"formula_body": "CM = P − VC; доля = CM / P.",
		"formula_item_1": "VC with units; fixed costs → break-even.",
		"formula_item_2": "Price > 0.",
		"formula_item_3": "Simplified.",
		"example_title": "Пример",
		"example": "Пример: 50 и 30 → 20 (40%).",
		"usecases_title": "Когда использовать",
		"usecase_1": "Unit CM homework.",
		"usecase_2": "VC sensitivity.",
		"usecase_3": "With break-even tool.",
		"faq_q1": "Пример?",
		"faq_a1": "20 / 40%",
		"faq_q2": "CM vs gross?",
		"faq_a2": "VC vs COGS.",
		"faq_q3": "Qty needed?",
		"faq_a3": "Not for unit CM.",
		"faq_q4": "Advice?",
		"faq_a4": "No.",
		"article": "Калькулятор маржинальной прибыли",
		"disclaimer": "Только учебная иллюстрация (contribution margin) — не финансовый совет.",
		"references": "Investopedia и учебные формулы.",
		"ref_a_label": "Investopedia — Contribution margin",
		"ref_b_label": "Investopedia — Break-even",
	}),
	de: withBtns("de", {
		"price_label": "Stückpreis",
		"price_ph": "z. B. 50",
		"vc_label": "Variable Kosten je Stück",
		"vc_ph": "z. B. 30",
		"cmOut_label": "Deckungsbeitrag",
		"cmrOut_label": "DB-Quote",
		"result_note": "Bildungszweck.",
		"err_generic": "Preis > 0 und VK ≥ 0.",
		"how_title": "So funktioniert’s",
		"how_body": "Stückpreis und variable Stückkosten eingeben.",
		"formula_title": "Formel",
		"formula_body": "DB = P − VK; Quote = DB / P.",
		"formula_item_1": "VC with units; fixed costs → break-even.",
		"formula_item_2": "Price > 0.",
		"formula_item_3": "Simplified.",
		"example_title": "Beispiel",
		"example": "Beispiel: 50 und 30 → 20 (40%).",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Unit CM homework.",
		"usecase_2": "VC sensitivity.",
		"usecase_3": "With break-even tool.",
		"faq_q1": "Beispiel?",
		"faq_a1": "20 / 40%",
		"faq_q2": "CM vs gross?",
		"faq_a2": "VC vs COGS.",
		"faq_q3": "Qty needed?",
		"faq_a3": "Not for unit CM.",
		"faq_q4": "Advice?",
		"faq_a4": "No.",
		"article": "Deckungsbeitrag-Rechner",
		"disclaimer": "Nur zur Veranschaulichung (contribution margin) — keine Finanzberatung.",
		"references": "Investopedia und Lehrbuchformeln.",
		"ref_a_label": "Investopedia — Contribution margin",
		"ref_b_label": "Investopedia — Break-even",
	}),
};
export default {
	seq: 37,
	slug: "how-to-calculate-contribution-margin",
	prefix: "tool_contribution_margin",
	pageFile: "howToCalculateContributionMarginPage",
	pageExport: "renderHowToCalculateContributionMarginPage",
	nameZh: "边际贡献计算器",
	ymyl: true,
	related: ["how-to-calculate-break-even","how-to-calculate-gross-margin"],
	anchor: "contribution-margin",
	glyph: "M8 22V12h16v10M12 12V6h8v6",
	sampleHint: "price 50 VC 30 → CM 20 / 40%",
	titles: {
		en: "Contribution Margin Calculator — Price Minus Variable Cost",
		zh: "边际贡献计算器 — 单价减变动成本",
		es: "Calculadora de margen de contribución",
		ar: "حاسبة هامش المساهمة",
		pt: "Calculadora de margem de contribuição",
		id: "Kalkulator contribution margin",
		fr: "Calculateur de marge sur coût variable",
		ja: "貢献利益の計算ツール — 単価と変動費",
		ru: "Калькулятор маржинальной прибыли",
		de: "Deckungsbeitrag-Rechner",
	},
	descriptions: {
		en: "Calculate contribution margin and ratio from price and variable cost. Example: price 50, VC 30 → CM 20 (40%). Links to break-even thinking. Educational — not business advice.",
		zh: "用单价与单位变动成本计算边际贡献与贡献率。示例：单价 50、变动成本 30 → 边际贡献 20（贡献率 40%）。可与盈亏平衡对照。浏览器本地计算；教育用，非经营建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。",
		es: "Calcula el margen de contribución y su ratio con precio y costo variable. Ejemplo: precio 50, CV 30 → MC 20 (40%). Educativo.",
		ar: "احسب هامش المساهمة ونسبته من السعر والتكلفة المتغيرة. مثال: سعر 50 وتكلفة 30 → 20 (40٪). تعليمي.",
		pt: "Calcule a margem de contribuição e a razão com preço e custo variável. Exemplo: preço 50, CV 30 → 20 (40%). Educativo.",
		id: "Hitung contribution margin dan rasionya dari harga dan biaya variabel. Contoh: harga 50, VC 30 → 20 (40%). Edukatif.",
		fr: "Calculez la marge sur coût variable et son ratio. Exemple : prix 50, CV 30 → 20 (40 %). Éducatif.",
		ja: "単価と変動費から貢献利益と貢献利益率を計算します。例：単価 50、変動費 30 → 貢献利益 20（率 40%）。損益分岐の理解にも。学習用です。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり投資・税務・経営の助言ではありません。",
		ru: "Считайте маржинальную прибыль и долю из цены и переменных затрат. Пример: цена 50, VC 30 → 20 (40%). Учебно.",
		de: "Berechnen Sie Deckungsbeitrag und Quote aus Preis und variablen Kosten. Beispiel: Preis 50, VK 30 → 20 (40%). Bildungszweck.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "price",
	    "type": "number",
	    "half": true,
	    "labelKey": "price_label",
	    "phKey": "price_ph"
	  },
	  {
	    "id": "vc",
	    "type": "number",
	    "half": true,
	    "labelKey": "vc_label",
	    "phKey": "vc_ph"
	  }
	],
	results: [
	  {
	    "id": "cmOut",
	    "labelKey": "cmOut_label"
	  },
	  {
	    "id": "cmrOut",
	    "labelKey": "cmrOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://www.investopedia.com/terms/c/contributionmargin.asp"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.investopedia.com/terms/b/breakevenanalysis.asp"
	  }
	],
	computeJs: `
        var P = parseFloat(priceEl.value);
        var VC = parseFloat(vcEl.value);
        if (!(P > 0) || !Number.isFinite(VC) || VC < 0) return { ok:false, error: msgErr };
        var cm = P - VC;
        var ratio = (cm / P) * 100;
        return { ok:true, values:{ cmOut: fmt(cm), cmrOut: fmt(ratio)+'%' } };
`,
	sampleJs: `
        priceEl.value='50';
        vcEl.value='30';
`,
};
