/**
 * §12 #43 how-to-calculate-debt-payoff
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"principal_label": "Principal balance",
		"principal_ph": "e.g. 5000",
		"rate_label": "Annual interest %",
		"rate_ph": "e.g. 12",
		"pay_label": "Monthly payment",
		"pay_ph": "e.g. 200",
		"monthsOut_label": "Months to payoff",
		"interestOut_label": "Total interest (approx)",
		"result_note": "Simple amortization loop; payment must cover first-month interest. Educational only — not lending advice.",
		"err_generic": "Enter principal > 0, rate ≥ 0, and payment that covers monthly interest.",
		"how_title": "How it works",
		"how_body": "Enter balance, annual rate, and fixed monthly payment. The page loops month-by-month until the balance clears or hits a cap.",
		"formula_title": "Formula",
		"formula_body": "Each month: interest = balance × r/12; principal reduction = payment − interest. Notes:",
		"formula_item_1": "If payment ≤ first-month interest, payoff never happens.",
		"formula_item_2": "Fees, penalties, and promotional rates are omitted.",
		"formula_item_3": "Snowball/avalanche strategy tips are narrative only — not separate URLs.",
		"example_title": "Example",
		"example": "Example: 5000 at 12% with 200/mo → about 30 months (approx; depends on rounding).",
		"usecases_title": "When to use it",
		"usecase_1": "Homework amortization months.",
		"usecase_2": "See if a payment clears the balance.",
		"usecase_3": "Compare with the EMI page for payment sizing.",
		"faq_q1": "Will it finish?",
		"faq_a1": "Only if payment exceeds monthly interest.",
		"faq_q2": "Exact sample months?",
		"faq_a2": "About 30 months for 5000 @12% with 200/mo under this loop.",
		"faq_q3": "Snowball page?",
		"faq_a3": "Strategies stay on this page as FAQ — no thin URL split.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Debt payoff months",
		"disclaimer": "Educational debt payoff only — not financial, tax, or investment advice.",
		"references": "Investopedia and standard textbook formulas.",
		"ref_a_label": "Investopedia — Amortization",
		"ref_b_label": "Investopedia — Debt",
	}),
	zh: withBtns("zh", {
		"principal_label": "本金余额",
		"principal_ph": "例如 5000",
		"rate_label": "年利率 %",
		"rate_ph": "例如 12",
		"pay_label": "月供",
		"pay_ph": "例如 200",
		"monthsOut_label": "还清月数",
		"interestOut_label": "利息合计（约）",
		"result_note": "简易逐月摊还；月供须覆盖首月利息。非放贷建议。",
		"err_generic": "本金>0、利率≥0，且月供须覆盖月利息。",
		"how_title": "怎么用",
		"how_body": "填入余额、年利率与固定月供，逐月循环直至还清或达到上限。",
		"formula_title": "公式",
		"formula_body": "每月：利息=余额×r/12；本金减少=月供−利息。注意：",
		"formula_item_1": "月供≤首月利息则无法还清。",
		"formula_item_2": "费用与罚息省略。",
		"formula_item_3": "雪球/雪崩仅作说明，不拆页。",
		"example_title": "示例",
		"example": "示例：5000、12%、月供 200 → 约 30 个月（舍入会影响）。",
		"usecases_title": "适合什么场景",
		"usecase_1": "摊还月数作业。",
		"usecase_2": "检查月供能否还清。",
		"usecase_3": "与 EMI 页对照月供大小。",
		"faq_q1": "能还清吗？",
		"faq_a1": "月供须大于月利息。",
		"faq_q2": "样例约几个月？",
		"faq_a2": "约 30 个月。",
		"faq_q3": "雪球专页？",
		"faq_a3": "同页 FAQ 说明，不拆 URL。",
		"faq_q4": "建议？",
		"faq_a4": "仅供学习。",
		"article": "债务还清月数",
		"disclaimer": "结果仅为债务还清学习演示，不构成投资、理财或税务建议。",
		"references": "Investopedia 与常见教材公式。",
		"ref_a_label": "Investopedia — Amortization",
		"ref_b_label": "Investopedia — Debt",
	}),
	es: withBtns("es", {
		"principal_label": "Saldo",
		"principal_ph": "p. ej. 5000",
		"rate_label": "Interés anual %",
		"rate_ph": "p. ej. 12",
		"pay_label": "Pago mensual",
		"pay_ph": "p. ej. 200",
		"monthsOut_label": "Meses",
		"interestOut_label": "Interés total (aprox.)",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce saldo, tasa y pago mensual.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce saldo, tasa y pago mensual.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: ~30 meses.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: ~30 meses.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de liquidación de deuda",
		"disclaimer": "Solo ilustración educativa (debt payoff); no es consejo financiero.",
		"references": "Investopedia y fórmulas de libro.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ar: withBtns("ar", {
		"principal_label": "الرصيد",
		"principal_ph": "مثال 5000",
		"rate_label": "فائدة سنوية %",
		"rate_ph": "مثال 12",
		"pay_label": "الدفع الشهري",
		"pay_ph": "مثال 200",
		"monthsOut_label": "الأشهر",
		"interestOut_label": "إجمالي الفائدة (تقريبي)",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل الرصيد والمعدل والدفع الشهري.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل الرصيد والمعدل والدفع الشهري.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: نحو 30 شهراً.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: نحو 30 شهراً.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة سداد الدين",
		"disclaimer": "توضيح تعليمي فقط (debt payoff) وليس نصيحة مالية.",
		"references": "Investopedia وصيغ دراسية.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	pt: withBtns("pt", {
		"principal_label": "Saldo",
		"principal_ph": "ex. 5000",
		"rate_label": "Juros anuais %",
		"rate_ph": "ex. 12",
		"pay_label": "Pagamento mensal",
		"pay_ph": "ex. 200",
		"monthsOut_label": "Meses",
		"interestOut_label": "Juros totais (aprox.)",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe saldo, taxa e pagamento mensal.",
		"formula_title": "Fórmula",
		"formula_body": "Informe saldo, taxa e pagamento mensal.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: ~30 meses.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: ~30 meses.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de quitação de dívida",
		"disclaimer": "Apenas ilustração educativa (debt payoff); não é conselho financeiro.",
		"references": "Investopedia e fórmulas didáticas.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	id: withBtns("id", {
		"principal_label": "Saldo",
		"principal_ph": "mis. 5000",
		"rate_label": "Bunga tahunan %",
		"rate_ph": "mis. 12",
		"pay_label": "Cicilan bulanan",
		"pay_ph": "mis. 200",
		"monthsOut_label": "Bulan",
		"interestOut_label": "Total bunga (kira-kira)",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi saldo, suku bunga, dan cicilan.",
		"formula_title": "Rumus",
		"formula_body": "Isi saldo, suku bunga, dan cicilan.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: ~30 bulan.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: ~30 bulan.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator pelunasan utang",
		"disclaimer": "Hanya ilustrasi edukatif (debt payoff); bukan saran keuangan.",
		"references": "Investopedia dan rumus buku teks.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	fr: withBtns("fr", {
		"principal_label": "Solde",
		"principal_ph": "ex. 5000",
		"rate_label": "Taux annuel %",
		"rate_ph": "ex. 12",
		"pay_label": "Paiement mensuel",
		"pay_ph": "ex. 200",
		"monthsOut_label": "Mois",
		"interestOut_label": "Intérêts totaux (approx.)",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez solde, taux et paiement mensuel.",
		"formula_title": "Formule",
		"formula_body": "Saisissez solde, taux et paiement mensuel.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : ~30 mois.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : ~30 mois.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de remboursement de dette",
		"disclaimer": "Illustration éducative (debt payoff) uniquement — pas un conseil financier.",
		"references": "Investopedia et formules de manuel.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ja: withBtns("ja", {
		"principal_label": "残高",
		"principal_ph": "例 5000",
		"rate_label": "年利 %",
		"rate_ph": "例 12",
		"pay_label": "月々の返済額",
		"pay_ph": "例 200",
		"monthsOut_label": "完済までの月数",
		"interestOut_label": "利息合計（目安）",
		"result_note": "簡易月次ループ。返済額が初月利息を上回る必要あり。貸付助言ではありません。",
		"err_generic": "残高>0、利率≥0、返済額が月利息を超えること。",
		"how_title": "使い方",
		"how_body": "残高・年利・固定月額を入力し、完済まで月次で回します。",
		"formula_title": "計算式",
		"formula_body": "毎月：利息=残高×r/12；元金減=返済−利息。注意:",
		"formula_item_1": "返済≤初月利息なら完済不可。",
		"formula_item_2": "手数料や延滞は省略。",
		"formula_item_3": "スノーボール等は説明のみでURL分割しません。",
		"example_title": "例",
		"example": "例：5000、12%、月200 → 約30か月。",
		"usecases_title": "こんなときに",
		"usecase_1": "償却月数の宿題。",
		"usecase_2": "返済額で完済できるか確認。",
		"usecase_3": "EMIページと月額比較。",
		"faq_q1": "完済できる？",
		"faq_a1": "月利息より多い返済が必要。",
		"faq_q2": "例の月数は？",
		"faq_a2": "約30か月。",
		"faq_q3": "スノーボール専用URL？",
		"faq_a3": "ありません。",
		"faq_q4": "助言？",
		"faq_a4": "学習用です。",
		"article": "借金完済月数",
		"disclaimer": "債務返済の学習用試算であり、投資・税務の助言ではありません。",
		"references": "Investopedia と標準的な教科書公式。",
		"ref_a_label": "Investopedia — Amortization",
		"ref_b_label": "Investopedia — Debt",
	}),
	ru: withBtns("ru", {
		"principal_label": "Остаток",
		"principal_ph": "напр. 5000",
		"rate_label": "Годовая ставка %",
		"rate_ph": "напр. 12",
		"pay_label": "Ежемесячный платёж",
		"pay_ph": "напр. 200",
		"monthsOut_label": "Месяцы",
		"interestOut_label": "Всего процентов (прибл.)",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите остаток, ставку и платёж.",
		"formula_title": "Формула",
		"formula_body": "Введите остаток, ставку и платёж.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: ~30 месяцев.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: ~30 месяцев.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор погашения долга",
		"disclaimer": "Только учебная иллюстрация (debt payoff) — не финансовый совет.",
		"references": "Investopedia и учебные формулы.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	de: withBtns("de", {
		"principal_label": "Saldo",
		"principal_ph": "z. B. 5000",
		"rate_label": "Jahreszins %",
		"rate_ph": "z. B. 12",
		"pay_label": "Monatsrate",
		"pay_ph": "z. B. 200",
		"monthsOut_label": "Monate",
		"interestOut_label": "Zinsen gesamt (ca.)",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Saldo, Zins und Monatsrate eingeben.",
		"formula_title": "Formel",
		"formula_body": "Saldo, Zins und Monatsrate eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: ~30 Monate.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: ~30 Monate.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Schulden-Tilgungsrechner",
		"disclaimer": "Nur zur Veranschaulichung (debt payoff) — keine Finanzberatung.",
		"references": "Investopedia und Lehrbuchformeln.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
};
export default {
	seq: 43,
	slug: "how-to-calculate-debt-payoff",
	prefix: "tool_debt_payoff",
	pageFile: "howToCalculateDebtPayoffPage",
	pageExport: "renderHowToCalculateDebtPayoffPage",
	nameZh: "债务还清计算器",
	ymyl: true,
	related: ["how-to-calculate-emi","how-to-calculate-compound-interest"],
	anchor: "debt-payoff",
	glyph: "M6 20h20M10 20V10m6 10V6m6 14v-8",
	sampleHint: "5000 @12% paying 200/mo → months",
	titles: {
		en: "Debt Payoff Calculator — Months to Clear a Balance",
		zh: "债务还清计算器 — 多久还清余额",
		es: "Calculadora de liquidación de deuda",
		ar: "حاسبة سداد الدين",
		pt: "Calculadora de quitação de dívida",
		id: "Kalkulator pelunasan utang",
		fr: "Calculateur de remboursement de dette",
		ja: "借金完済までの月数計算",
		ru: "Калькулятор погашения долга",
		de: "Schulden-Tilgungsrechner",
	},
	descriptions: {
		en: "Estimate months to pay off a balance with a fixed monthly payment and annual interest. Sample: principal 5,000 at 12% paying 200/mo → months to clear. Educational amortization — not lending advice.",
		zh: "按本金、年利率与固定月供估算还清月数（简易摊还）。示例：本金 5000、年利率 12%、月供 200 → 还清月数。浏览器本地计算；借款教育用，非放贷或还款建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。",
		es: "Estima meses para liquidar un saldo con pago mensual fijo e interés anual. Ejemplo: 5000 al 12% pagando 200/mes. Educativo.",
		ar: "قدّر أشهر السداد برصيد وفائدة سنوية ودفع شهري ثابت. مثال: 5000 بفائدة 12٪ ودفع 200/شهر. تعليمي.",
		pt: "Estime meses para quitar um saldo com pagamento mensal fixo e juros anuais. Exemplo: 5000 a 12% pagando 200/mês. Educativo.",
		id: "Perkirakan bulan pelunasan dengan saldo, bunga tahunan, dan cicilan bulanan tetap. Contoh: 5000 @12% bayar 200/bln. Edukatif.",
		fr: "Estimez les mois pour soldes avec paiement mensuel fixe et taux annuel. Exemple : 5000 à 12 % en payant 200/mois. Éducatif.",
		ja: "元金・年利・固定月額返済から完済までの月数を見積もります。例：元金 5000、年利 12%、月々 200 → 完済月数。学習用であり貸付助言ではありません。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり投資・税務・経営の助言ではありません。",
		ru: "Оцените месяцы погашения при фиксированном платеже и годовой ставке. Пример: 5000 при 12% и платеже 200/мес. Учебно.",
		de: "Schätzen Sie Monate bis zur Tilgung bei fester Monatsrate und Jahreszins. Beispiel: 5000 bei 12% mit 200/Monat. Bildungszweck.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "principal",
	    "type": "number",
	    "half": true,
	    "labelKey": "principal_label",
	    "phKey": "principal_ph"
	  },
	  {
	    "id": "rate",
	    "type": "number",
	    "half": true,
	    "labelKey": "rate_label",
	    "phKey": "rate_ph"
	  },
	  {
	    "id": "pay",
	    "type": "number",
	    "half": true,
	    "labelKey": "pay_label",
	    "phKey": "pay_ph"
	  }
	],
	results: [
	  {
	    "id": "monthsOut",
	    "labelKey": "monthsOut_label"
	  },
	  {
	    "id": "interestOut",
	    "labelKey": "interestOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://www.investopedia.com/terms/a/amortization.asp"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.investopedia.com/terms/d/debt.asp"
	  }
	],
	computeJs: `
        var bal=parseFloat(principalEl.value), ratePct=parseFloat(rateEl.value), pay=parseFloat(payEl.value);
        if(!(bal>0)||!Number.isFinite(ratePct)||ratePct<0||!(pay>0)) return {ok:false,error:msgErr};
        var r=ratePct/100/12;
        if(r>0 && pay <= bal*r + 1e-9) return {ok:false,error:msgErr};
        var months=0, interestTotal=0, guard=1200;
        while(bal>0.005 && months<guard){
          var interest = r>0 ? bal*r : 0;
          interestTotal += interest;
          var principalPay = pay - interest;
          if(principalPay <= 0) return {ok:false,error:msgErr};
          if(principalPay > bal){ interestTotal -= interest; interest = bal*r; interestTotal += interest; bal=0; months++; break; }
          bal -= principalPay; months++;
        }
        if(bal>0.005) return {ok:false,error:msgErr};
        return {ok:true, values:{ monthsOut:String(months), interestOut:fmt(interestTotal) }};
`,
	sampleJs: `
        principalEl.value='5000';
        rateEl.value='12';
        payEl.value='200';
`,
};
