/**
 * §12 #60 how-to-calculate-density
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"mass_label": "Mass",
		"mass_ph": "e.g. 10",
		"volume_label": "Volume",
		"volume_ph": "e.g. 2",
		"densOut_label": "Density",
		"result_note": "ρ = mass / volume.",
		"err_generic": "Enter mass ≥ 0 and volume > 0.",
		"how_title": "How it works",
		"how_body": "Enter mass and volume in consistent units (e.g., kg and m³ → kg/m³).",
		"formula_title": "Formula",
		"formula_body": "ρ=m/V. Notes:",
		"formula_item_1": "Volume must be positive.",
		"formula_item_2": "Temperature/pressure effects not modeled.",
		"formula_item_3": "Pair with volume / Ohm tools.",
		"example_title": "Example",
		"example": "Example: m=10, V=2 → density 5.",
		"usecases_title": "When to use it",
		"usecase_1": "Science homework.",
		"usecase_2": "Quick ρ check.",
		"usecase_3": "Compare related physics tools.",
		"faq_q1": "Sample?",
		"faq_a1": "10/2=5.",
		"faq_q2": "Units?",
		"faq_a2": "Keep mass/volume consistent.",
		"faq_q3": "V=0?",
		"faq_a3": "Rejected.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Density",
		"disclaimer": "Educational density only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — Density",
		"ref_b_label": "Wikipedia — Mass",
	}),
	zh: withBtns("zh", {
		"mass_label": "质量",
		"mass_ph": "例如 10",
		"volume_label": "体积",
		"volume_ph": "例如 2",
		"densOut_label": "密度",
		"result_note": "结果按密度公式在浏览器本地计算。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算密度。",
		"formula_title": "公式",
		"formula_body": "密度相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：m=10、V=2 → 5。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：m=10、V=2 → 5。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "密度",
		"disclaimer": "结果仅为密度学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"mass_label": "Masa",
		"mass_ph": "p. ej. 10",
		"volume_label": "Volumen",
		"volume_ph": "p. ej. 2",
		"densOut_label": "Densidad",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce masa y volumen.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce masa y volumen.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: densidad 5.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: densidad 5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de densidad",
		"disclaimer": "Solo ilustración educativa (density).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"mass_label": "الكتلة",
		"mass_ph": "مثال 10",
		"volume_label": "الحجم",
		"volume_ph": "مثال 2",
		"densOut_label": "الكثافة",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل الكتلة والحجم.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل الكتلة والحجم.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: الكثافة 5.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: الكثافة 5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة الكثافة",
		"disclaimer": "توضيح تعليمي فقط (density).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"mass_label": "Massa",
		"mass_ph": "ex. 10",
		"volume_label": "Volume",
		"volume_ph": "ex. 2",
		"densOut_label": "Densidade",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe massa e volume.",
		"formula_title": "Fórmula",
		"formula_body": "Informe massa e volume.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: densidade 5.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: densidade 5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de densidade",
		"disclaimer": "Apenas ilustração educativa (density).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"mass_label": "Massa",
		"mass_ph": "mis. 10",
		"volume_label": "Volume",
		"volume_ph": "mis. 2",
		"densOut_label": "Densitas",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi massa dan volume.",
		"formula_title": "Rumus",
		"formula_body": "Isi massa dan volume.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: densitas 5.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: densitas 5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator massa jenis",
		"disclaimer": "Hanya ilustrasi edukatif (density).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"mass_label": "Masse",
		"mass_ph": "ex. 10",
		"volume_label": "Volume",
		"volume_ph": "ex. 2",
		"densOut_label": "Densité",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez masse et volume.",
		"formula_title": "Formule",
		"formula_body": "Saisissez masse et volume.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : densité 5.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : densité 5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de densité",
		"disclaimer": "Illustration éducative (density) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"mass_label": "質量",
		"mass_ph": "例 10",
		"volume_label": "体積",
		"volume_ph": "例 2",
		"densOut_label": "密度",
		"result_note": "密度の公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れて密度を計算します。",
		"formula_title": "計算式",
		"formula_body": "密度の式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：m=10、V=2 → 5。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：m=10、V=2 → 5。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "密度",
		"disclaimer": "密度の学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"mass_label": "Масса",
		"mass_ph": "напр. 10",
		"volume_label": "Объём",
		"volume_ph": "напр. 2",
		"densOut_label": "Плотность",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите массу и объём.",
		"formula_title": "Формула",
		"formula_body": "Введите массу и объём.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: плотность 5.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: плотность 5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор плотности",
		"disclaimer": "Только учебная иллюстрация (density).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"mass_label": "Masse",
		"mass_ph": "z. B. 10",
		"volume_label": "Volumen",
		"volume_ph": "z. B. 2",
		"densOut_label": "Dichte",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Masse und Volumen eingeben.",
		"formula_title": "Formel",
		"formula_body": "Masse und Volumen eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: Dichte 5.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: Dichte 5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Dichte-Rechner — Masse durch Volumen",
		"disclaimer": "Nur zur Veranschaulichung (density).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 60,
	slug: "how-to-calculate-density",
	prefix: "tool_density",
	pageFile: "howToCalculateDensityPage",
	pageExport: "renderHowToCalculateDensityPage",
	nameZh: "密度计算器",
	ymyl: false,
	related: ["how-to-calculate-volume","how-to-calculate-ohms-law"],
	anchor: "density",
	glyph: "M10 8h12v16H10z",
	sampleHint: "m=10 V=2 → density 5",
	titles: {
		en: "Density Calculator — Mass over Volume",
		zh: "密度计算器 — 质量÷体积",
		es: "Calculadora de densidad",
		ar: "حاسبة الكثافة",
		pt: "Calculadora de densidade",
		id: "Kalkulator massa jenis",
		fr: "Calculateur de densité",
		ja: "密度計算ツール — 質量÷体積",
		ru: "Калькулятор плотности",
		de: "Dichte-Rechner — Masse durch Volumen",
	},
	descriptions: {
		en: "Compute density ρ = m/V. Sample: mass 10, volume 2 → density 5. Browser-only.",
		zh: "计算密度 ρ = m/V。示例：质量 10、体积 2 → 密度 5。浏览器本地计算。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Calcula densidad ρ=m/V. Ejemplo: 10 / 2 → 5.",
		ar: "احسب الكثافة ρ=m/V. مثال: 10 / 2 → 5.",
		pt: "Calcule densidade ρ=m/V. Exemplo: 10 / 2 → 5.",
		id: "Hitung densitas ρ=m/V. Contoh: 10 / 2 → 5.",
		fr: "Calculez la densité ρ=m/V. Exemple : 10 / 2 → 5.",
		ja: "密度ρ=m/Vを計算します。例：質量10、体積2 → 密度5。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Считайте плотность ρ=m/V. Пример: 10 / 2 → 5.",
		de: "Dichte ρ=m/V. Beispiel: 10 / 2 → 5.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "mass",
	    "type": "number",
	    "half": true,
	    "labelKey": "mass_label",
	    "phKey": "mass_ph"
	  },
	  {
	    "id": "volume",
	    "type": "number",
	    "half": true,
	    "labelKey": "volume_label",
	    "phKey": "volume_ph"
	  }
	],
	results: [
	  {
	    "id": "densOut",
	    "labelKey": "densOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Density"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Mass"
	  }
	],
	computeJs: `
        var mass=parseFloat(massEl.value), volume=parseFloat(volumeEl.value);
        if(!(mass>=0)||!(volume>0)) return {ok:false,error:msgErr};
        return {ok:true, values:{ densOut:fmt(mass/volume) }};
`,
	sampleJs: `
        massEl.value='10';
        volumeEl.value='2';
`,
};
