/**
 * §12 #34 how-to-calculate-discount 工具定义（十语独立 UI）。
 */
import { withBtns } from '../locale-ui-common.mjs';

const _ui = {
	en: withBtns("en", {
		"original_label": "Original price",
		"original_ph": "e.g. 100",
		"pct_label": "Discount (% off)",
		"pct_ph": "e.g. 20",
		"pct2_label": "Second discount % (optional)",
		"pct2_ph": "e.g. 10",
		"finalOut_label": "Final price",
		"savedOut_label": "Total saved",
		"result_note": "Second discount, if any, applies to the already reduced price (stack). Educational only.",
		"err_generic": "Enter a positive original price and a discount percent from 0 to 100.",
		"how_title": "How it works",
		"how_body": "Enter the original price and the percent off. Optionally add a second percent that stacks on the reduced amount. The page shows the final price and how much you save. Runs in your browser.",
		"formula_title": "Formula",
		"formula_body": "Final = original × (1 − d₁/100) × (1 − d₂/100) when a second discount is set; otherwise omit the second factor. Notes:",
		"formula_item_1": "d₁ and d₂ are percent-off values (20 means 20% off), not multipliers like 0.8.",
		"formula_item_2": "Leave the second discount empty or 0 to apply a single markdown.",
		"formula_item_3": "Taxes, coupons with fixed amounts, and store rounding rules are not modeled.",
		"example_title": "Example",
		"example": "Example: original 100, 20% off → final = 100 × 0.8 = 80 (saved 20). With a second 10% off → 80 × 0.9 = 72.",
		"usecases_title": "When to use it",
		"usecase_1": "Compare a single sale percent to the checkout total before tax.",
		"usecase_2": "Homework: practice successive percent-off discounts.",
		"usecase_3": "Rough double-discount stacks for marketing math drills.",
		"faq_q1": "How is a double discount applied?",
		"faq_a1": "The second percent multiplies the already discounted price, not the original.",
		"faq_q2": "Is 20% off the same as paying 20%?",
		"faq_a2": "No. 20% off means you pay 80% of the original (multiply by 0.8).",
		"faq_q3": "Does this include sales tax?",
		"faq_a3": "No. Enter pre-tax amounts; tax pages are separate.",
		"faq_q4": "Can I enter a fixed dollar coupon?",
		"faq_a4": "This page uses percent-off only. Subtract a fixed coupon yourself before or after.",
		"disclaimer": "Educational price illustration only — not a store checkout or tax engine.",
		"references": "Investopedia discount overview; standard successive percent-off arithmetic.",
		"ref_a_label": "Investopedia — Discount",
		"ref_b_label": "Wikipedia — Discounting",
		"article": "Percent-off sale price from an original amount, with optional stacked second discount on one page.",
	}),
	zh: withBtns("zh", {
		"original_label": "原价",
		"original_ph": "例如 100",
		"pct_label": "折扣（减价 %）",
		"pct_ph": "例如 20",
		"pct2_label": "第二层折扣 %（可选）",
		"pct2_ph": "例如 10",
		"finalOut_label": "成交价",
		"savedOut_label": "共节省",
		"result_note": "若填写第二层折扣，则在折后价上继续乘（叠折）。仅供学习对照。",
		"err_generic": "请填写大于 0 的原价，以及 0–100 之间的折扣百分比。",
		"how_title": "怎么用",
		"how_body": "填入原价与减价百分比；需要时可再填第二层折扣（作用在折后价上）。页面会给出成交价与节省额。计算在浏览器内完成。",
		"formula_title": "公式",
		"formula_body": "成交价 = 原价 × (1 − d₁/100) × (1 − d₂/100)（有第二层时）；否则去掉第二项。注意：",
		"formula_item_1": "d₁、d₂ 是「减百分之几」（20 表示减 20%），不是 0.8 这种乘数。",
		"formula_item_2": "第二层留空或填 0 即单层折扣。",
		"formula_item_3": "税费、固定金额券与店铺舍入规则不在本页建模。",
		"example_title": "示例",
		"example": "示例：原价 100、减 20% → 成交价 = 100 × 0.8 = 80（省 20）。再减 10% → 80 × 0.9 = 72。",
		"usecases_title": "适合什么场景",
		"usecase_1": "结账前粗算单层折扣后的应付（未含税）。",
		"usecase_2": "作业：练习连续百分比折扣。",
		"usecase_3": "营销叠折的心算对照。",
		"faq_q1": "双层折扣怎么算？",
		"faq_a1": "第二层百分比乘在已经折过的价格上，不是再对原价减一次。",
		"faq_q2": "减 20% 是不是只付 20%？",
		"faq_a2": "不是。减 20% 表示付原价的 80%（乘 0.8）。",
		"faq_q3": "含税吗？",
		"faq_a3": "不含。请填税前金额；税额请用增值税等工具另算。",
		"faq_q4": "固定金额优惠券呢？",
		"faq_a4": "本页只做百分比折扣；固定金额请自行先加减。",
		"disclaimer": "结果仅供价格演算学习，不是店铺收银或税务系统。",
		"references": "Investopedia 折扣说明；连续百分比折扣算术。",
		"ref_a_label": "Investopedia — Discount",
		"ref_b_label": "维基百科 — 折扣",
		"article": "用原价与减价百分比算成交价，可选同页叠第二层折扣。",
	}),
	es: withBtns("es", {
		"original_label": "Precio original",
		"original_ph": "p. ej. 100",
		"pct_label": "Descuento (% off)",
		"pct_ph": "p. ej. 20",
		"pct2_label": "Segundo descuento % (opcional)",
		"pct2_ph": "p. ej. 10",
		"finalOut_label": "Precio final",
		"savedOut_label": "Ahorro total",
		"result_note": "El segundo descuento, si hay, se aplica al precio ya rebajado. Solo educativo.",
		"err_generic": "Introduce un precio original positivo y un % entre 0 y 100.",
		"how_title": "Cómo funciona",
		"how_body": "Indica el precio original y el porcentaje de rebaja. Si quieres, añade un segundo % sobre el precio ya rebajado. Verás el final y el ahorro. En el navegador.",
		"formula_title": "Fórmula",
		"formula_body": "Final = original × (1 − d₁/100) × (1 − d₂/100) si hay segundo descuento. Notas:",
		"formula_item_1": "d₁ y d₂ son porcentajes de rebaja (20 = 20% off), no factores 0,8.",
		"formula_item_2": "Deja el segundo en vacío o 0 para una sola rebaja.",
		"formula_item_3": "Impuestos y cupones de importe fijo no se modelan.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: 100 con 20% → 80. Con otro 10% → 72.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Estimar el total con un % de oferta antes de impuestos.",
		"usecase_2": "Deberes: descuentos sucesivos.",
		"usecase_3": "Practicar dobles rebajas de marketing.",
		"faq_q1": "¿El 20% off es pagar solo el 20%?",
		"faq_a1": "No: pagas el 80% del original.",
		"faq_q2": "¿Cómo se apila el segundo descuento?",
		"faq_a2": "Sobre el precio ya rebajado, no otra vez sobre el original.",
		"faq_q3": "¿Incluye impuestos?",
		"faq_a3": "No; usa importes sin impuesto.",
		"faq_q4": "¿Cupón de cantidad fija?",
		"faq_a4": "Esta página solo usa porcentajes.",
		"disclaimer": "Ilustración educativa de precios; no es una caja ni motor fiscal.",
		"references": "Investopedia sobre descuentos; aritmética de % sucesivos.",
		"ref_a_label": "Investopedia — Discount",
		"ref_b_label": "Wikipedia — Discounting",
		"article": "Precio rebajado desde un original y % off, con segundo descuento opcional en la misma página.",
	}),
	ar: withBtns("ar", {
		"original_label": "السعر الأصلي",
		"original_ph": "مثال 100",
		"pct_label": "الخصم (% off)",
		"pct_ph": "مثال 20",
		"pct2_label": "خصم ثانٍ % (اختياري)",
		"pct2_ph": "مثال 10",
		"finalOut_label": "السعر النهائي",
		"savedOut_label": "إجمالي التوفير",
		"result_note": "الخصم الثاني إن وُجد يُطبَّق على السعر المخفّض. للاستخدام التعليمي.",
		"err_generic": "أدخل سعراً أصلياً موجباً ونسبة خصم بين 0 و100.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل السعر الأصلي ونسبة التخفيض. يمكنك إضافة نسبة ثانية على السعر بعد الخصم. تعرض الصفحة النهائي والتوفير داخل المتصفح.",
		"formula_title": "الصيغة",
		"formula_body": "النهائي = الأصلي × (1 − d₁/100) × (1 − d₂/100) عند وجود خصم ثانٍ. ملاحظات:",
		"formula_item_1": "d₁ وd₂ نسب تخفيض (20 تعني 20٪ خصم) وليست معاملات 0.8.",
		"formula_item_2": "اترك الثاني فارغاً أو 0 لخصم واحد.",
		"formula_item_3": "الضرائب والقسائم ذات المبلغ الثابت غير مُنمذَجة.",
		"example_title": "مثال",
		"example": "مثال: 100 بخصم 20٪ → 80. ثم 10٪ → 72.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "تقدير سعر العرض قبل الضريبة.",
		"usecase_2": "واجب: خصومات متتالية.",
		"usecase_3": "تمرين الخصم المزدوج.",
		"faq_q1": "هل يشمل الضريبة؟",
		"faq_a1": "لا؛ أدخل مبالغ قبل الضريبة.",
		"faq_q2": "كيف يُطبَّق الخصم الثاني؟",
		"faq_a2": "على السعر بعد الخصم الأول لا على الأصلي مجدداً.",
		"faq_q3": "هل 20٪ خصم تعني دفع 20٪؟",
		"faq_a3": "لا؛ تدفع 80٪ من الأصلي.",
		"faq_q4": "قسيمة بمبلغ ثابت؟",
		"faq_a4": "هذه الصفحة للنسب المئوية فقط.",
		"disclaimer": "توضيح تعليمي للأسعار وليس نظام دفع أو ضرائب.",
		"references": "Investopedia عن الخصم؛ حساب النسب المتتالية.",
		"ref_a_label": "Investopedia — Discount",
		"ref_b_label": "ويكيبيديا — الخصم",
		"article": "سعر بعد خصم نسبي من مبلغ أصلي مع خصم ثانٍ اختياري في صفحة واحدة.",
	}),
	pt: withBtns("pt", {
		"original_label": "Preço original",
		"original_ph": "ex. 100",
		"pct_label": "Desconto (% off)",
		"pct_ph": "ex. 20",
		"pct2_label": "Segundo desconto % (opcional)",
		"pct2_ph": "ex. 10",
		"finalOut_label": "Preço final",
		"savedOut_label": "Total economizado",
		"result_note": "O segundo desconto, se houver, aplica-se ao preço já reduzido. Apenas educativo.",
		"err_generic": "Informe preço original positivo e % entre 0 e 100.",
		"how_title": "Como funciona",
		"how_body": "Digite o preço original e o percentual de desconto. Opcionalmente, um segundo % sobre o valor já reduzido. Veja o final e a economia no navegador.",
		"formula_title": "Fórmula",
		"formula_body": "Final = original × (1 − d₁/100) × (1 − d₂/100) com segundo desconto. Notas:",
		"formula_item_1": "d₁ e d₂ são percentuais de abatimento (20 = 20% off).",
		"formula_item_2": "Deixe o segundo vazio ou 0 para um único desconto.",
		"formula_item_3": "Impostos e cupons de valor fixo não entram.",
		"example_title": "Exemplo",
		"example": "Exemplo: 100 com 20% → 80. Com mais 10% → 72.",
		"usecases_title": "Quando usar",
		"usecase_1": "Estimar oferta percentual antes do imposto.",
		"usecase_2": "Tarefa: descontos sucessivos.",
		"usecase_3": "Treinar desconto duplo de marketing.",
		"faq_q1": "Como empilha o segundo desconto?",
		"faq_a1": "Sobre o preço já reduzido.",
		"faq_q2": "20% off é pagar só 20%?",
		"faq_a2": "Não: você paga 80% do original.",
		"faq_q3": "Inclui imposto?",
		"faq_a3": "Não.",
		"faq_q4": "Cupom de valor fixo?",
		"faq_a4": "Esta página só usa percentuais.",
		"disclaimer": "Ilustração educativa de preço; não é caixa nem motor fiscal.",
		"references": "Investopedia sobre desconto; aritmética de % sucessivos.",
		"ref_a_label": "Investopedia — Discount",
		"ref_b_label": "Wikipedia — Discounting",
		"article": "Preço com % off a partir do original, com segundo desconto opcional na mesma página.",
	}),
	id: withBtns("id", {
		"original_label": "Harga asli",
		"original_ph": "mis. 100",
		"pct_label": "Diskon (% off)",
		"pct_ph": "mis. 20",
		"pct2_label": "Diskon kedua % (opsional)",
		"pct2_ph": "mis. 10",
		"finalOut_label": "Harga akhir",
		"savedOut_label": "Total hemat",
		"result_note": "Diskon kedua (jika ada) diterapkan pada harga yang sudah dipotong. Hanya edukasi.",
		"err_generic": "Masukkan harga asli positif dan persen 0–100.",
		"how_title": "Cara kerja",
		"how_body": "Isi harga asli dan persen potongan. Opsional: persen kedua pada harga setelah diskon. Hasil akhir dan hemat dihitung di browser.",
		"formula_title": "Rumus",
		"formula_body": "Akhir = asli × (1 − d₁/100) × (1 − d₂/100) jika ada diskon kedua. Catatan:",
		"formula_item_1": "d₁ dan d₂ adalah persen potongan (20 = 20% off).",
		"formula_item_2": "Kosongkan atau 0 untuk satu lapisan saja.",
		"formula_item_3": "Pajak dan kupon nominal tetap tidak dimodelkan.",
		"example_title": "Contoh",
		"example": "Contoh: 100 diskon 20% → 80. Lalu 10% → 72.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Perkiraan harga promo sebelum pajak.",
		"usecase_2": "PR: diskon beruntun.",
		"usecase_3": "Latihan diskon ganda marketing.",
		"faq_q1": "Apakah termasuk pajak?",
		"faq_a1": "Tidak.",
		"faq_q2": "Diskon kedua dihitung dari mana?",
		"faq_a2": "Dari harga setelah diskon pertama.",
		"faq_q3": "20% off berarti bayar 20%?",
		"faq_a3": "Tidak; bayar 80% dari harga asli.",
		"faq_q4": "Kupon nominal tetap?",
		"faq_a4": "Halaman ini hanya persen.",
		"disclaimer": "Ilustrasi harga untuk belajar; bukan kasir toko.",
		"references": "Investopedia tentang diskon; aritmetika persen beruntun.",
		"ref_a_label": "Investopedia — Discount",
		"ref_b_label": "Wikipedia — Discounting",
		"article": "Harga setelah persen off dari harga asli, dengan diskon kedua opsional di satu halaman.",
	}),
	fr: withBtns("fr", {
		"original_label": "Prix d’origine",
		"original_ph": "ex. 100",
		"pct_label": "Remise (% off)",
		"pct_ph": "ex. 20",
		"pct2_label": "Seconde remise % (optionnel)",
		"pct2_ph": "ex. 10",
		"finalOut_label": "Prix final",
		"savedOut_label": "Économie totale",
		"result_note": "La seconde remise, le cas échéant, s’applique au prix déjà réduit. Usage éducatif.",
		"err_generic": "Saisissez un prix d’origine positif et un % entre 0 et 100.",
		"how_title": "Fonctionnement",
		"how_body": "Indiquez le prix d’origine et le pourcentage de remise. Ajoutez éventuellement une seconde remise sur le montant déjà réduit. Le navigateur affiche le final et l’économie.",
		"formula_title": "Formule",
		"formula_body": "Final = original × (1 − d₁/100) × (1 − d₂/100) s’il y a une seconde remise. Notes :",
		"formula_item_1": "d₁ et d₂ sont des pourcentages de baisse (20 = −20 %).",
		"formula_item_2": "Laissez le second vide ou à 0 pour une seule remise.",
		"formula_item_3": "Taxes et coupons à montant fixe ne sont pas modélisés.",
		"example_title": "Exemple",
		"example": "Exemple : 100 à −20 % → 80. Puis −10 % → 72.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Estimer une promo avant taxe.",
		"usecase_2": "Devoirs : remises successives.",
		"usecase_3": "S’entraîner aux doubles remises.",
		"faq_q1": "Comment s’empile la seconde remise ?",
		"faq_a1": "Sur le prix déjà soldé.",
		"faq_q2": "−20 % signifie payer 20 % ?",
		"faq_a2": "Non : vous payez 80 % du prix d’origine.",
		"faq_q3": "Taxes incluses ?",
		"faq_a3": "Non.",
		"faq_q4": "Coupon à montant fixe ?",
		"faq_a4": "Cette page gère seulement les pourcentages.",
		"disclaimer": "Illustration éducative des prix — pas une caisse ni un moteur fiscal.",
		"references": "Investopedia sur les remises ; arithmétique des % successifs.",
		"ref_a_label": "Investopedia — Discount",
		"ref_b_label": "Wikipédia — Remise",
		"article": "Prix soldé depuis un montant d’origine et un % off, avec seconde remise optionnelle.",
	}),
	ja: withBtns("ja", {
		"original_label": "定価",
		"original_ph": "例 100",
		"pct_label": "割引率（% off）",
		"pct_ph": "例 20",
		"pct2_label": "二重割引 %（任意）",
		"pct2_ph": "例 10",
		"finalOut_label": "セール価格",
		"savedOut_label": "合計割引額",
		"result_note": "二重割引がある場合は、一度値引きしたあとの価格に掛けます。学習用です。",
		"err_generic": "正の定価と 0〜100 の割引率を入力してください。",
		"how_title": "使い方",
		"how_body": "定価と割引率を入れます。必要なら二重割引を値引き後の価格に追加します。最終価格と節約額がブラウザ内で出ます。",
		"formula_title": "計算式",
		"formula_body": "最終 = 定価 × (1 − d₁/100) × (1 − d₂/100)（二重があるとき）。注意:",
		"formula_item_1": "d₁・d₂ はオフ率（20 は 20%オフ）であり、0.8 の乗数表記ではありません。",
		"formula_item_2": "二重を空または 0 にすると一回だけ割引。",
		"formula_item_3": "税や定額クーポンは扱いません。",
		"example_title": "例",
		"example": "例：定価 100、20%オフ → 80。さらに 10%オフ → 72。",
		"usecases_title": "こんなときに",
		"usecase_1": "税込前のセール価格のざっくり確認。",
		"usecase_2": "連続パーセント割引の宿題。",
		"usecase_3": "二重割引の練習。",
		"faq_q1": "二重割引はどう掛けますか？",
		"faq_a1": "一度オフしたあとの価格に次の%を掛けます。",
		"faq_q2": "20%オフは 20% だけ払うこと？",
		"faq_a2": "いいえ。定価の 80% を支払います。",
		"faq_q3": "税込みですか？",
		"faq_a3": "いいえ。税抜き金額を入れてください。",
		"faq_q4": "定額クーポンは？",
		"faq_a4": "このページはパーセント割引のみです。",
		"disclaimer": "価格の学習用試算であり、店舗会計や税務エンジンではありません。",
		"references": "Investopedia の割引解説；連続パーセント割引の計算。",
		"ref_a_label": "Investopedia — Discount",
		"ref_b_label": "Wikipedia — 割引",
		"article": "定価とオフ率からセール価格を求め、任意で二重割引も同じページで扱います。",
	}),
	ru: withBtns("ru", {
		"original_label": "Исходная цена",
		"original_ph": "напр. 100",
		"pct_label": "Скидка (% off)",
		"pct_ph": "напр. 20",
		"pct2_label": "Вторая скидка % (необяз.)",
		"pct2_ph": "напр. 10",
		"finalOut_label": "Итоговая цена",
		"savedOut_label": "Экономия",
		"result_note": "Вторая скидка, если есть, применяется к уже сниженной цене. Только обучение.",
		"err_generic": "Введите положительную исходную цену и процент от 0 до 100.",
		"how_title": "Как пользоваться",
		"how_body": "Укажите исходную цену и процент скидки. При желании добавьте второй процент на уже сниженную сумму. В браузере увидите итог и экономию.",
		"formula_title": "Формула",
		"formula_body": "Итог = исходная × (1 − d₁/100) × (1 − d₂/100) при второй скидке. Замечания:",
		"formula_item_1": "d₁ и d₂ — проценты скидки (20 = минус 20%), не множители 0,8.",
		"formula_item_2": "Оставьте вторую пустой или 0 для одной скидки.",
		"formula_item_3": "Налоги и купоны с фиксированной суммой не моделируются.",
		"example_title": "Пример",
		"example": "Пример: 100 минус 20% → 80. Затем ещё 10% → 72.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Оценить акционную цену до налога.",
		"usecase_2": "Домашка: последовательные проценты.",
		"usecase_3": "Тренировка двойной скидки.",
		"faq_q1": "Как накладывается вторая скидка?",
		"faq_a1": "На уже сниженную цену.",
		"faq_q2": "Минус 20% значит платить 20%?",
		"faq_a2": "Нет: платите 80% исходной.",
		"faq_q3": "С налогом?",
		"faq_a3": "Нет.",
		"faq_q4": "Купон на фиксированную сумму?",
		"faq_a4": "Здесь только проценты.",
		"disclaimer": "Учебная иллюстрация цены — не касса и не налоговый движок.",
		"references": "Investopedia о скидках; арифметика последовательных %.",
		"ref_a_label": "Investopedia — Discount",
		"ref_b_label": "Википедия — Скидка",
		"article": "Цена со скидкой из исходной суммы и % off, с опциональной второй скидкой на одной странице.",
	}),
	de: withBtns("de", {
		"original_label": "Originalpreis",
		"original_ph": "z. B. 100",
		"pct_label": "Rabatt (% off)",
		"pct_ph": "z. B. 20",
		"pct2_label": "Zweiter Rabatt % (optional)",
		"pct2_ph": "z. B. 10",
		"finalOut_label": "Endpreis",
		"savedOut_label": "Gesamtersparnis",
		"result_note": "Ein zweiter Rabatt gilt auf den bereits reduzierten Preis. Nur zur Veranschaulichung.",
		"err_generic": "Bitte positiven Originalpreis und Prozent von 0 bis 100 eingeben.",
		"how_title": "So funktioniert’s",
		"how_body": "Originalpreis und Rabattprozent eingeben. Optional einen zweiten Prozentwert auf den bereits reduzierten Betrag. Endpreis und Ersparnis erscheinen im Browser.",
		"formula_title": "Formel",
		"formula_body": "Endpreis = Original × (1 − d₁/100) × (1 − d₂/100) bei Zweitrabatt. Hinweise:",
		"formula_item_1": "d₁ und d₂ sind Abschläge in Prozent (20 = 20% off), keine Faktoren 0,8.",
		"formula_item_2": "Zweiten Wert leer oder 0 lassen für einen einzelnen Rabatt.",
		"formula_item_3": "Steuern und Festbetragsgutscheine werden nicht modelliert.",
		"example_title": "Beispiel",
		"example": "Beispiel: 100 abzüglich 20% → 80. Dann weitere 10% → 72.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Aktionspreis vor Steuer grob schätzen.",
		"usecase_2": "Hausaufgabe: aufeinanderfolgende Prozente.",
		"usecase_3": "Doppelrabatt üben.",
		"faq_q1": "Wie stapelt der zweite Rabatt?",
		"faq_a1": "Auf den bereits reduzierten Preis.",
		"faq_q2": "Heißt 20% off, nur 20% zahlen?",
		"faq_a2": "Nein: Sie zahlen 80% des Originals.",
		"faq_q3": "Mit Steuer?",
		"faq_a3": "Nein.",
		"faq_q4": "Festbetragsgutschein?",
		"faq_a4": "Diese Seite nutzt nur Prozente.",
		"disclaimer": "Nur zur Veranschaulichung von Preisen — keine Kasse und kein Steuerrechner.",
		"references": "Investopedia zu Rabatten; Arithmetik aufeinanderfolgender %.",
		"ref_a_label": "Investopedia — Discount",
		"ref_b_label": "Wikipedia — Rabatt",
		"article": "Verkaufspreis aus Originalbetrag und % off, optional mit Zweitrabatt auf derselben Seite.",
	}),
};

export default {
	seq: 34,
	slug: "how-to-calculate-discount",
	prefix: "tool_discount",
	pageFile: "howToCalculateDiscountPage",
	pageExport: "renderHowToCalculateDiscountPage",
	nameZh: "折扣计算器",
	ymyl: false,
	related: ["how-to-calculate-markup", "how-to-calculate-gross-margin"],
	anchor: "discount",
	glyph: "M8 16h16M10 10l12 12M22 10L10 22",
	sampleHint: "100 off 20% → 80",
	titles: {
		en: "Discount Calculator — How to Calculate Sale Price",
		zh: "折扣计算器 — 如何算出优惠价",
		es: "Calculadora de descuento — Precio final",
		ar: "حاسبة الخصم — السعر بعد التخفيض",
		pt: "Calculadora de desconto — Preço final",
		id: "Kalkulator diskon — Harga setelah potongan",
		fr: "Calculateur de remise — Prix soldé",
		ja: "割引計算ツール — セール価格の求め方",
		ru: "Калькулятор скидки — Цена со скидкой",
		de: "Rabatt-Rechner — Verkaufspreis berechnen",
	},
	descriptions: {
		en: "Find the final price from an original amount and percent off. Example: 100 off 20% → 80. Optional second discount stacks on the reduced price. Browser-only math for shopping and homework — not a store checkout.",
		zh: "用原价与折扣百分比计算优惠后成交价。示例：原价 100、打 8 折（减 20%）→ 成交价 80。可选第二层折扣在折后价上继续乘。全程浏览器本地计算，数据不上传服务器；仅供购物与作业对照，不是店铺收银系统。",
		es: "Calcula el precio final con el importe original y el % de descuento. Ejemplo: 100 con 20% → 80. Un segundo descuento opcional se aplica sobre el precio ya rebajado. Solo en el navegador; no es una caja de tienda.",
		ar: "احسب السعر النهائي من السعر الأصلي ونسبة الخصم. مثال: 100 بخصم 20٪ → 80. خصم ثانٍ اختياري يُطبَّق على السعر المخفّض. حساب في المتصفح فقط وليس نظام دفع للمتجر.",
		pt: "Calcule o preço final a partir do valor original e do % de desconto. Exemplo: 100 com 20% → 80. Um segundo desconto opcional aplica-se sobre o preço já reduzido. Só no navegador; não é caixa de loja.",
		id: "Hitung harga akhir dari harga asli dan persen diskon. Contoh: 100 diskon 20% → 80. Diskon kedua opsional diterapkan pada harga yang sudah dipotong. Hanya di browser; bukan kasir toko.",
		fr: "Calculez le prix final à partir du montant d’origine et du % de remise. Exemple : 100 à −20 % → 80. Une seconde remise optionnelle s’applique au prix déjà réduit. Dans le navigateur uniquement — pas une caisse magasin.",
		ja: "定価と割引率からセール価格を計算します。例：100 を 20% オフ → 80。任意の二重割引は値引き後の価格に続けて掛けます。ブラウザ内のみの計算で、店舗の会計システムではありません。サーバーにアップロードしません。",
		ru: "Считайте итоговую цену из исходной суммы и процента скидки. Пример: 100 минус 20% → 80. Вторая скидка (по желанию) применяется к уже сниженной цене. Только в браузере — не касса магазина.",
		de: "Berechnen Sie den Endpreis aus Originalbetrag und Rabattprozent. Beispiel: 100 abzüglich 20% → 80. Optionaler Zweitrabatt gilt auf den bereits reduzierten Preis. Nur im Browser — keine Ladenkasse.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "original",
	    "type": "number",
	    "half": true,
	    "labelKey": "original_label",
	    "phKey": "original_ph"
	  },
	  {
	    "id": "pct",
	    "type": "number",
	    "half": true,
	    "labelKey": "pct_label",
	    "phKey": "pct_ph"
	  },
	  {
	    "id": "pct2",
	    "type": "number",
	    "half": true,
	    "labelKey": "pct2_label",
	    "phKey": "pct2_ph"
	  }
	],
	results: [
	  {
	    "id": "finalOut",
	    "labelKey": "finalOut_label"
	  },
	  {
	    "id": "savedOut",
	    "labelKey": "savedOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://www.investopedia.com/terms/d/discount.asp"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Discounting"
	  }
	],
	computeJs: `
        var original = parseFloat(originalEl.value);
        var d1 = parseFloat(pctEl.value);
        var d2Raw = String(pct2El.value || '').trim();
        var d2 = d2Raw === '' ? 0 : parseFloat(d2Raw);
        if (!(original > 0) || !Number.isFinite(d1) || d1 < 0 || d1 > 100 || !Number.isFinite(d2) || d2 < 0 || d2 > 100) {
          return { ok: false, error: msgErr };
        }
        var final = original * (1 - d1 / 100) * (1 - d2 / 100);
        var saved = original - final;
        return { ok: true, values: { finalOut: fmt(final), savedOut: fmt(saved) } };
`,
	sampleJs: `
        originalEl.value = '100';
        pctEl.value = '20';
        pct2El.value = '';
`,
};
