/**
 * §12 #32 how-to-calculate-exponent 工具定义（十语独立 UI）。
 * prefix: tool_exponent；page: howToCalculateExponentPage / renderHowToCalculateExponentPage。
 */
import { withBtns } from '../locale-ui-common.mjs';

/** 十语 UI（how/formula/faq/usecase 等须独立重写，禁止英模同构）。 */
const _ui = {
	ar: withBtns('ar', {
		"base_label": "الأساس a",
		"base_ph": "مثال 2",
		"exp_label": "الأس b",
		"exp_ph": "مثال 10",
		"powerOut_label": "a^b",
		"result_note": "يحسب a^b عبر Math.pow للتعلّم. |b| الكبير قد يفيض إلى Infinity.",
		"err_generic": "أدخل أساسًا وأسًا محدودين.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل a وb. تُرجع a^b. الأساس السالب بأس غير صحيح قد يعطي NaN ويُعد خطأ.",
		"formula_title": "الصيغة",
		"formula_body": "الرفع إلى أس a^b:",
		"formula_item_1": "إذا كان b عددًا صحيحًا غير سالب فـ a^b ضرب متكرر.",
		"formula_item_2": "الأسس الكسرية/السالبة تتبع Math.pow الحقيقي.",
		"formula_item_3": "0^0 تُؤخذ 1 هنا (عرف برمجي) مع وجود جدل.",
		"formula_item_4": "اربطها بصفحة اللوغاريتم للتحقق log_a(a^b)=b.",
		"example_title": "مثال",
		"example": "مثال: 2^10 = 1024.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "واجب: قوى بسيطة مثل 2^10.",
		"usecase_2": "التحقق من عوامل الترميز العلمي.",
		"usecase_3": "مضاهاة اللوغاريتمات العكسية.",
		"disclaimer": "قوى حقيقية تعليمية فقط وليست CAS.",
		"references": "ويكيبيديا الرفع إلى أس.",
		"ref_exp_label": "ويكيبيديا — الرفع إلى أس",
		"ref_pow_label": "ويكيبيديا — الأس",
		"article": "احسب a^b في المتصفح مع ملاحظات المجال.",
		"faq_q1": "ما قيمة 0^0 هنا؟",
		"faq_a1": "تُؤخذ 1 (عرف JS) مع جدل رياضي.",
		"faq_q2": "هل قد تظهر Infinity؟",
		"faq_a2": "نعم عند المقادير الضخمة.",
		"faq_q3": "متى تفشل القواعد السالبة؟",
		"faq_a3": "القوى غير الصحيحة غالبًا NaN في JS.",
		"faq_q4": "التحقق باللوغاريتم؟",
		"faq_a4": "إن عُرّف فإن log_a(a^b)≈b.",
	}),
	de: withBtns('de', {
		"base_label": "Basis a",
		"base_ph": "z. B. 2",
		"exp_label": "Exponent b",
		"exp_ph": "z. B. 10",
		"powerOut_label": "a^b",
		"result_note": "Berechnet a^b mit Math.pow zum Lernen. Sehr großes |b| kann Infinity ergeben.",
		"err_generic": "Endliche Basis und Exponent eingeben.",
		"how_title": "So funktioniert’s",
		"how_body": "Geben Sie a und b ein. Liefert a^b. Negative Basen mit nichtganzzahligen Exponenten können NaN sein und gelten als Fehler.",
		"formula_title": "Formel",
		"formula_body": "Potenzierung a^b:",
		"formula_item_1": "Ist b eine nichtnegative ganze Zahl, bedeutet a^b a mal sich selbst b-mal.",
		"formula_item_2": "Gebrochene/negative Exponenten folgen Math.pow reell.",
		"formula_item_3": "0^0 wird hier als 1 behandelt (Programmierkonvention) — umstritten.",
		"formula_item_4": "Mit der Log-Seite log_a(a^b)=b prüfen, wenn definiert.",
		"example_title": "Beispiel",
		"example": "Beispiel: 2^10 = 1024.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Hausaufgabe: einfache Potenzen wie 2^10.",
		"usecase_2": "Faktoren wissenschaftlicher Notation prüfen.",
		"usecase_3": "Mit inversen Logarithmen abgleichen.",
		"disclaimer": "Nur reelle Lernpotenzen; kein CAS.",
		"references": "Wikipedia Potenzierung.",
		"ref_exp_label": "Wikipedia — Potenzierung",
		"ref_pow_label": "Wikipedia — Exponent",
		"article": "Berechnen Sie a^b im Browser mit klaren Definitionsbereichshinweisen.",
		"faq_q1": "Was ist 0^0 hier?",
		"faq_a1": "Als 1 behandelt (JS-Konvention); mathematisch umstritten.",
		"faq_q2": "Negative Basen?",
		"faq_a2": "Nichtganzzahlige reelle Potenzen sind in JS oft NaN.",
		"faq_q3": "Kann Infinity entstehen?",
		"faq_a3": "Ja bei sehr großen Beträgen.",
		"faq_q4": "Mit Logs prüfen?",
		"faq_a4": "Wenn definiert, ist log_a(a^b)≈b.",
	}),
	en: withBtns('en', {
		"base_label": "Base a",
		"base_ph": "e.g. 2",
		"exp_label": "Exponent b",
		"exp_ph": "e.g. 10",
		"powerOut_label": "a^b",
		"result_note": "Computes a^b with JavaScript Math.pow for learning. Very large |b| may overflow to Infinity.",
		"err_generic": "Enter finite base and exponent values.",
		"how_title": "How it works",
		"how_body": "Enter base a and exponent b. The page returns a^b. Negative bases with non-integer exponents may yield NaN in real arithmetic and are treated as errors.",
		"formula_title": "Formula",
		"formula_body": "Exponentiation a^b:",
		"formula_item_1": "a^b means multiply a by itself b times when b is a non-negative integer.",
		"formula_item_2": "Fractional and negative exponents follow real-power rules via Math.pow.",
		"formula_item_3": "0^0 is treated as 1 here (common programming convention) — note the debate.",
		"formula_item_4": "Pair with the logarithm page to check that log_a(a^b)=b when defined.",
		"example_title": "Example",
		"example": "Example: 2^10 = 1024.",
		"usecases_title": "When to use it",
		"usecase_1": "Homework: evaluate simple powers like 2^10.",
		"usecase_2": "Check scientific-notation scale factors.",
		"usecase_3": "Cross-check logs with inverse powers.",
		"disclaimer": "Educational real powers only; overflow/NaN edge cases are not a CAS.",
		"references": "Wikipedia exponentiation.",
		"ref_exp_label": "Wikipedia — Exponentiation",
		"ref_pow_label": "Wikipedia — Exponent",
		"article": "Calculate a^b powers in your browser with clear domain notes.",
		"faq_q1": "What is 0^0 on this page?",
		"faq_a1": "Treated as 1 (common JS convention); mathematics debates the value.",
		"faq_q2": "Why can negative bases fail?",
		"faq_a2": "Non-integer real powers of negatives are often NaN in JS.",
		"faq_q3": "Can results be Infinity?",
		"faq_a3": "Yes for very large magnitudes — this is not arbitrary-precision math.",
		"faq_q4": "How to check with logs?",
		"faq_a4": "When defined, log_a(a^b) should return about b.",
	}),
	es: withBtns('es', {
		"base_label": "Base a",
		"base_ph": "p. ej. 2",
		"exp_label": "Exponente b",
		"exp_ph": "p. ej. 10",
		"powerOut_label": "a^b",
		"result_note": "Calcula a^b con Math.pow para aprender. |b| muy grande puede dar Infinity.",
		"err_generic": "Introduce base y exponente finitos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce a y b. Devuelve a^b. Bases negativas con exponentes no enteros pueden ser NaN en reales y se tratan como error.",
		"formula_title": "Fórmula",
		"formula_body": "Potenciación a^b:",
		"formula_item_1": "Si b es entero no negativo, a^b es a multiplicado b veces.",
		"formula_item_2": "Exponentes fraccionarios/negativos siguen Math.pow real.",
		"formula_item_3": "0^0 se toma como 1 (convención de programación) — hay debate.",
		"formula_item_4": "Combínalo con la página de logs para comprobar log_a(a^b)=b.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: 2^10 = 1024.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Deberes: potencias simples como 2^10.",
		"usecase_2": "Comprobar factores de notación científica.",
		"usecase_3": "Cruzar con logaritmos inversos.",
		"disclaimer": "Solo potencias reales educativas; no es un CAS.",
		"references": "Wikipedia potenciación.",
		"ref_exp_label": "Wikipedia — Potenciación",
		"ref_pow_label": "Wikipedia — Exponente",
		"article": "Calcula potencias a^b en el navegador con notas de dominio.",
		"faq_q1": "¿0^0 aquí?",
		"faq_a1": "Se toma 1 (convención JS); en matemáticas se debate.",
		"faq_q2": "¿Puede salir Infinity?",
		"faq_a2": "Sí con magnitudes enormes; no es precisión arbitraria.",
		"faq_q3": "¿Bases negativas?",
		"faq_a3": "Potencias reales no enteras suelen ser NaN en JS.",
		"faq_q4": "¿Comprobar con logs?",
		"faq_a4": "Si está definido, log_a(a^b) ≈ b.",
	}),
	fr: withBtns('fr', {
		"base_label": "Base a",
		"base_ph": "ex. 2",
		"exp_label": "Exposant b",
		"exp_ph": "ex. 10",
		"powerOut_label": "a^b",
		"result_note": "Calcule a^b avec Math.pow pour apprendre. Un |b| très grand peut donner Infinity.",
		"err_generic": "Saisissez une base et un exposant finis.",
		"how_title": "Fonctionnement",
		"how_body": "Entrez a et b. Renvoie a^b. Bases négatives avec exposants non entiers peuvent donner NaN et sont traitées comme erreur.",
		"formula_title": "Formule",
		"formula_body": "Exponentiation a^b :",
		"formula_item_1": "Si b est un entier ≥0, a^b est a multiplié b fois.",
		"formula_item_2": "Exposants fractionnaires/négatifs suivent Math.pow réel.",
		"formula_item_3": "0^0 vaut 1 ici (convention de programmation) — débat existant.",
		"formula_item_4": "Associez à la page logs pour vérifier log_a(a^b)=b.",
		"example_title": "Exemple",
		"example": "Exemple : 2^10 = 1024.",
		"usecases_title": "Quand l’utiliser",
		"usecase_1": "Devoir : puissances simples comme 2^10.",
		"usecase_2": "Vérifier des facteurs de notation scientifique.",
		"usecase_3": "Croiser avec des logs inverses.",
		"disclaimer": "Puissances réelles pédagogiques seulement ; pas un CAS.",
		"references": "Wikipedia exponentiation.",
		"ref_exp_label": "Wikipedia — Exponentiation",
		"ref_pow_label": "Wikipedia — Exposant",
		"article": "Calculez a^b dans le navigateur avec des notes de domaine.",
		"faq_q1": "0^0 ici ?",
		"faq_a1": "Pris égal à 1 (convention JS) ; débat mathématique.",
		"faq_q2": "Bases négatives ?",
		"faq_a2": "Puissances réelles non entières souvent NaN en JS.",
		"faq_q3": "Infinity possible ?",
		"faq_a3": "Oui pour de très grandes magnitudes.",
		"faq_q4": "Vérifier avec logs ?",
		"faq_a4": "Si défini, log_a(a^b)≈b.",
	}),
	id: withBtns('id', {
		"base_label": "Basis a",
		"base_ph": "mis. 2",
		"exp_label": "Eksponen b",
		"exp_ph": "mis. 10",
		"powerOut_label": "a^b",
		"result_note": "Menghitung a^b dengan Math.pow untuk belajar. |b| sangat besar bisa Infinity.",
		"err_generic": "Masukkan basis dan eksponen hingga.",
		"how_title": "Cara kerja",
		"how_body": "Masukkan a dan b. Mengembalikan a^b. Basis negatif dengan eksponen non-integer bisa NaN dan dianggap error.",
		"formula_title": "Rumus",
		"formula_body": "Eksponensiasi a^b:",
		"formula_item_1": "Jika b bilangan bulat non-negatif, a^b adalah perkalian berulang.",
		"formula_item_2": "Eksponen pecahan/negatif mengikuti Math.pow real.",
		"formula_item_3": "0^0 diambil 1 di sini (konvensi pemrograman) — ada perdebatan.",
		"formula_item_4": "Padankan dengan halaman log untuk cek log_a(a^b)=b.",
		"example_title": "Contoh",
		"example": "Contoh: 2^10 = 1024.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "PR: pangkat sederhana seperti 2^10.",
		"usecase_2": "Cek faktor notasi ilmiah.",
		"usecase_3": "Silang-cek log dengan pangkat balik.",
		"disclaimer": "Hanya pangkat real edukasi; bukan CAS.",
		"references": "Wikipedia exponentiation.",
		"ref_exp_label": "Wikipedia — Exponentiation",
		"ref_pow_label": "Wikipedia — Exponent",
		"article": "Hitung pangkat a^b di browser dengan catatan domain.",
		"faq_q1": "Bisakah hasil Infinity?",
		"faq_a1": "Ya untuk magnitudo sangat besar.",
		"faq_q2": "0^0 di halaman ini?",
		"faq_a2": "Diambil 1 (konvensi JS); ada perdebatan.",
		"faq_q3": "Basis negatif gagal kapan?",
		"faq_a3": "Pangkat real non-integer sering NaN di JS.",
		"faq_q4": "Cek dengan log?",
		"faq_a4": "Jika terdefinisi, log_a(a^b)≈b.",
	}),
	ja: withBtns('ja', {
		"base_label": "底 a",
		"base_ph": "例: 2",
		"exp_label": "指数 b",
		"exp_ph": "例: 10",
		"powerOut_label": "a^b",
		"result_note": "学習用に Math.pow で a^b を計算。|b| が大きいと Infinity になり得ます。",
		"err_generic": "有限の底と指数を入力してください。",
		"how_title": "使い方",
		"how_body": "底 a と指数 b を入れると a^b を返します。負の底と非整数指数は実数で NaN になり得、エラー扱いです。",
		"formula_title": "式",
		"formula_body": "累乗 a^b：",
		"formula_item_1": "b が非負整数なら a を b 回掛ける意味。",
		"formula_item_2": "分数・負の指数は Math.pow の実数規則。",
		"formula_item_3": "ここでの 0^0 は 1（よくあるプログラミング慣習）——議論あり。",
		"formula_item_4": "対数ページで定義されるとき log_a(a^b)=b を確認。",
		"example_title": "例",
		"example": "例：2^10 = 1024。",
		"usecases_title": "こんなときに",
		"usecase_1": "2^10 のような簡単な累乗の宿題。",
		"usecase_2": "科学表記の桁因子を確認。",
		"usecase_3": "対数の逆演算と照合。",
		"disclaimer": "実数の学習用累乗のみで、CAS の代わりではありません。",
		"references": "Wikipedia の冪乗。",
		"ref_exp_label": "Wikipedia — 冪乗",
		"ref_pow_label": "Wikipedia — 指数",
		"article": "ブラウザで a^b を計算し、定義域の注意を明示します。",
		"faq_q1": "負の底はいつ失敗？",
		"faq_a1": "非整数の実数累乗は JS では NaN になりがちです。",
		"faq_q2": "このページの 0^0 は？",
		"faq_a2": "1 とします（よくある JS 慣習）。数学では議論があります。",
		"faq_q3": "Infinity になる？",
		"faq_a3": "桁が極端に大きいとあり得ます。",
		"faq_q4": "対数で確認は？",
		"faq_a4": "定義されるとき log_a(a^b)≈b。",
	}),
	pt: withBtns('pt', {
		"base_label": "Base a",
		"base_ph": "ex.: 2",
		"exp_label": "Expoente b",
		"exp_ph": "ex.: 10",
		"powerOut_label": "a^b",
		"result_note": "Calcula a^b com Math.pow para estudar. |b| muito grande pode virar Infinity.",
		"err_generic": "Informe base e expoente finitos.",
		"how_title": "Como funciona",
		"how_body": "Digite a e b. Devolve a^b. Bases negativas com expoentes não inteiros podem ser NaN e viram erro.",
		"formula_title": "Fórmula",
		"formula_body": "Exponenciação a^b:",
		"formula_item_1": "Se b é inteiro não negativo, a^b é a multiplicado b vezes.",
		"formula_item_2": "Expoentes fracionários/negativos seguem Math.pow real.",
		"formula_item_3": "0^0 é 1 aqui (convenção de programação) — há debate.",
		"formula_item_4": "Combine com a página de logs para checar log_a(a^b)=b.",
		"example_title": "Exemplo",
		"example": "Exemplo: 2^10 = 1024.",
		"usecases_title": "Quando usar",
		"usecase_1": "Tarefa: potências simples como 2^10.",
		"usecase_2": "Checar fatores de notação científica.",
		"usecase_3": "Conferir logs com potências inversas.",
		"disclaimer": "Apenas potências reais educativas; não é um CAS.",
		"references": "Wikipedia exponenciação.",
		"ref_exp_label": "Wikipedia — Exponenciação",
		"ref_pow_label": "Wikipedia — Expoente",
		"article": "Calcule potências a^b no navegador com notas de domínio.",
		"faq_q1": "0^0 nesta página?",
		"faq_a1": "Tratado como 1 (convenção JS); há debate matemático.",
		"faq_q2": "Bases negativas?",
		"faq_a2": "Potências reais não inteiras costumam ser NaN em JS.",
		"faq_q3": "Pode dar Infinity?",
		"faq_a3": "Sim para magnitudes enormes.",
		"faq_q4": "Checar com logs?",
		"faq_a4": "Quando definido, log_a(a^b)≈b.",
	}),
	ru: withBtns('ru', {
		"base_label": "Основание a",
		"base_ph": "напр. 2",
		"exp_label": "Показатель b",
		"exp_ph": "напр. 10",
		"powerOut_label": "a^b",
		"result_note": "Считает a^b через Math.pow для обучения. Очень большой |b| может дать Infinity.",
		"err_generic": "Введите конечные основание и показатель.",
		"how_title": "Как пользоваться",
		"how_body": "Введите a и b. Возвращает a^b. Отрицательное основание с нецелым показателем может дать NaN и считается ошибкой.",
		"formula_title": "Формула",
		"formula_body": "Возведение в степень a^b:",
		"formula_item_1": "Если b — неотрицательное целое, a^b — умножение a на себя b раз.",
		"formula_item_2": "Дробные/отрицательные показатели по правилам Math.pow.",
		"formula_item_3": "0^0 здесь равно 1 (программистская условность) — есть споры.",
		"formula_item_4": "Сверьте со страницей логов: log_a(a^b)=b, когда определено.",
		"example_title": "Пример",
		"example": "Пример: 2^10 = 1024.",
		"usecases_title": "Когда применять",
		"usecase_1": "Домашнее задание: простые степени вроде 2^10.",
		"usecase_2": "Проверить масштаб научной записи.",
		"usecase_3": "Сверить с обратными логарифмами.",
		"disclaimer": "Только учебные вещественные степени; не CAS.",
		"references": "Wikipedia о возведении в степень.",
		"ref_exp_label": "Wikipedia — Возведение в степень",
		"ref_pow_label": "Wikipedia — Показатель степени",
		"article": "Считайте степени a^b в браузере с заметками об области.",
		"faq_q1": "Что с 0^0?",
		"faq_a1": "Здесь 1 (привычка JS); в математике спорно.",
		"faq_q2": "Отрицательное основание?",
		"faq_a2": "Нецелые вещественные степени часто дают NaN в JS.",
		"faq_q3": "Возможен Infinity?",
		"faq_a3": "Да при огромных величинах.",
		"faq_q4": "Проверка логарифмом?",
		"faq_a4": "Если определено, log_a(a^b)≈b.",
	}),
	zh: withBtns('zh', {
		"base_label": "底数 a",
		"base_ph": "例如 2",
		"exp_label": "指数 b",
		"exp_ph": "例如 10",
		"powerOut_label": "a^b",
		"result_note": "用 JavaScript Math.pow 计算 a^b 供学习。|b| 很大时可能溢出为 Infinity。",
		"err_generic": "请输入有限的底数与指数。",
		"how_title": "怎么用",
		"how_body": "输入底数 a 与指数 b，返回 a^b。负底配非整数指数在实数下可能为 NaN，本页视为错误。",
		"formula_title": "公式",
		"formula_body": "幂运算 a^b：",
		"formula_item_1": "b 为非负整数时，a^b 表示 a 自乘 b 次。",
		"formula_item_2": "分数与负指数按 Math.pow 的实数幂规则。",
		"formula_item_3": "此处 0^0 按常见编程约定取 1——学界有争议。",
		"formula_item_4": "可配合对数页在有定义时核对 log_a(a^b)=b。",
		"example_title": "示例",
		"example": "示例：2^10=1024。",
		"usecases_title": "适合什么场景",
		"usecase_1": "作业：计算 2^10 这类简单幂。",
		"usecase_2": "核对科学计数的数量级因子。",
		"usecase_3": "用逆运算核对对数。",
		"disclaimer": "仅为实数教育用幂运算；溢出/NaN 边角不能替代 CAS。",
		"references": "维基百科幂运算。",
		"ref_exp_label": "维基百科 — 幂",
		"ref_pow_label": "维基百科 — 指数",
		"article": "在浏览器内计算 a^b，并写明定义域注意事项。",
		"faq_q1": "很大时会怎样？",
		"faq_a1": "可能得到 Infinity，本页不是任意精度运算。",
		"faq_q2": "本页 0^0 是多少？",
		"faq_a2": "按常见 JS 约定取 1；数学上有争议。",
		"faq_q3": "负底何时失败？",
		"faq_a3": "负底配非整数实数幂在 JS 中常为 NaN。",
		"faq_q4": "如何用对数核对？",
		"faq_a4": "有定义时 log_a(a^b) 应约等于 b。",
	}),
};

export default {
	seq: 32,
	slug: "how-to-calculate-exponent",
	prefix: "tool_exponent",
	nameZh: "指数幂计算器",
	category: 'calculator',
	ymyl: false,
	pageFile: "howToCalculateExponentPage",
	pageExport: "renderHowToCalculateExponentPage",
	anchor: "exponent",
	related: ["how-to-calculate-logarithm", "how-to-calculate-scientific-notation"],
	glyph: "M8 24V8h4l10 16h4V8",
	sampleHint: "2^10=1024",
	titles: {
		"en": "Exponent Calculator — How to Calculate Powers",
		"zh": "指数幂计算器 — 如何计算 a 的 b 次方",
		"es": "Calculadora de exponentes — Cómo calcular potencias",
		"ar": "حاسبة الأس — كيفية حساب القوى",
		"pt": "Calculadora de expoentes — Como calcular potências",
		"id": "Kalkulator eksponen — Cara menghitung pangkat",
		"fr": "Calculateur d’exposants — Comment calculer des puissances",
		"ja": "指数計算ツール — a の b 乗の求め方",
		"ru": "Калькулятор степеней — Как вычислить a^b",
		"de": "Potenzrechner — Potenzen berechnen"
	},
	descriptions: {
		"en": "Calculate powers a^b with a clear example 2^10 = 1024. Notes overflow to Infinity for huge magnitudes and NaN cases for some negative bases with non-integer exponents. Browser learning tool paired with logs and scientific notation.",
		"zh": "计算幂 a^b，示例 2^10=1024。写明极大结果可能溢出为 Infinity，以及负底配非整数指数时可能出现 NaN。浏览器内计算，适合作业，并可与对数页、科学计数法页互相核对逆运算与数量级因子；同时注明本页对 0^0 的编程约定处理。",
		"es": "Calcula potencias a^b con el ejemplo 2^10=1024. Advierte Infinity por magnitudes enormes y NaN en algunas bases negativas con exponentes no enteros. En el navegador, con logs y notación científica.",
		"ar": "احسب القوى a^b مع مثال 2^10=1024. يوضح Infinity للمقادير الضخمة وNaN لبعض القواعد السالبة بأس غير صحيح. في المتصفح مع اللوغاريتم والترميز العلمي.",
		"pt": "Calcule potências a^b com o exemplo 2^10=1024. Avisa Infinity para magnitudes enormes e NaN em algumas bases negativas com expoentes não inteiros. No navegador, com logs e notação científica.",
		"id": "Hitung pangkat a^b dengan contoh 2^10=1024. Menuliskan Infinity untuk magnitudo besar dan NaN untuk basis negatif dengan eksponen non-integer. Di browser bersama log dan notasi ilmiah.",
		"fr": "Calculez a^b avec l’exemple 2^10=1024. Signale Infinity pour de grandes magnitudes et NaN pour certaines bases négatives à exposant non entier. Dans le navigateur, avec logs et notation scientifique.",
		"ja": "累乗 a^b を計算します。例：2^10=1024。桁が極端に大きいと Infinity、負の底と非整数指数では NaN になり得ることを明示。ブラウザ内で宿題向けで、対数ページや科学表記ページと逆演算・桁合わせを照合でき、0^0 の扱いも注記します。",
		"ru": "Считайте степени a^b с примером 2^10=1024. Указывает Infinity при огромных величинах и NaN для некоторых отрицательных оснований с нецелым показателем. В браузере вместе с логарифмами и научной записью.",
		"de": "Berechnen Sie Potenzen a^b mit dem Beispiel 2^10=1024. Weist auf Infinity bei großen Beträgen und NaN bei manchen negativen Basen mit nichtganzzahligem Exponenten hin. Im Browser mit Logs und wissenschaftlicher Notation."
	},
	ui: _ui,
	fields: [
		{
			"id": "base",
			"type": "number",
			"half": true,
			"labelKey": "base_label",
			"phKey": "base_ph"
		},
		{
			"id": "exp",
			"type": "number",
			"half": true,
			"labelKey": "exp_label",
			"phKey": "exp_ph"
		}
	],
	results: [
		{
			"id": "powerOut",
			"labelKey": "powerOut_label"
		}
	],
	refs: [
		{
			"labelKey": "ref_exp_label",
			"href": "https://en.wikipedia.org/wiki/Exponentiation"
		},
		{
			"labelKey": "ref_pow_label",
			"href": "https://en.wikipedia.org/wiki/Exponent"
		}
	],
	computeJs: `
        var a = parseFloat(baseEl.value);
        var b = parseFloat(expEl.value);
        if (!Number.isFinite(a) || !Number.isFinite(b)) {
          return { ok: false, error: msgErr };
        }
        /** 0^0 按常见 JS 约定取 1。 */
        var y = (a === 0 && b === 0) ? 1 : Math.pow(a, b);
        if (!Number.isFinite(y)) {
          return { ok: false, error: msgErr };
        }
        return { ok: true, values: { powerOut: fmt(y, 8) } };
`,
	sampleJs: `
        baseEl.value = '2';
        expEl.value = '10';
`,
};
