/**
 * §12 #56 how-to-calculate-heart-rate
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"age_label": "Age (years)",
		"age_ph": "e.g. 30",
		"maxOut_label": "Estimated max HR",
		"z1Out_label": "Zone 1 (50–60%)",
		"z2Out_label": "Zone 2 (60–70%)",
		"z3Out_label": "Zone 3 (70–85%)",
		"result_note": "max ≈ 220−age. Zones shown as bpm ranges from percent of max (educational 50–60 / 60–70 / 70–85).",
		"err_generic": "Enter age between 1 and 120.",
		"how_title": "How it works",
		"how_body": "Enter age to sketch max HR and three percent-based zones. Formulas vary by lab — this is a classroom classic, not a clinical test.",
		"formula_title": "Formula",
		"formula_body": "max=220−age; zone = [lo%, hi%] × max. Notes:",
		"formula_item_1": "220−age is a rough teaching estimate.",
		"formula_item_2": "Stop exercise and seek care for symptoms — not advice.",
		"formula_item_3": "Pair with macros / BMR–TDEE for education.",
		"example_title": "Example",
		"example": "Example: age 30 → max 190; moderate band often cited near 50–70% of max.",
		"usecases_title": "When to use it",
		"usecase_1": "Classroom zone math.",
		"usecase_2": "Compare percent bands.",
		"usecase_3": "Educational pairing with macros.",
		"faq_q1": "Sample?",
		"faq_a1": "Age 30 → max 190.",
		"faq_q2": "Medical advice?",
		"faq_a2": "No.",
		"faq_q3": "Why these %?",
		"faq_a3": "Common teaching bands; protocols differ.",
		"faq_q4": "Symptoms?",
		"faq_a4": "Seek a clinician — not this tool.",
		"article": "Heart-rate zones",
		"disclaimer": "Educational heart rate zones only — not medical advice. Consult a qualified clinician.",
		"references": "CDC / ACSM-style educational references.",
		"ref_a_label": "Wikipedia — Heart rate",
		"ref_b_label": "CDC heart rate",
	}),
	zh: withBtns("zh", {
		"age_label": "年龄（岁）",
		"age_ph": "例如 30",
		"maxOut_label": "估算最大心率",
		"z1Out_label": "区间 1（50–60%）",
		"z2Out_label": "区间 2（60–70%）",
		"z3Out_label": "区间 3（70–85%）",
		"result_note": "结果按心率区间公式在浏览器本地计算。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算心率区间。",
		"formula_title": "公式",
		"formula_body": "心率区间相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：年龄 30 → 最大 190。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：年龄 30 → 最大 190。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "心率区间",
		"disclaimer": "结果仅为心率区间健康教育演示，不构成医疗诊断或治疗建议。请咨询专业人士。",
		"references": "CDC / ACSM 等公开教育资料。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"age_label": "Edad (años)",
		"age_ph": "p. ej. 30",
		"maxOut_label": "FC máx estimada",
		"z1Out_label": "Zona 1 (50–60%)",
		"z2Out_label": "Zona 2 (60–70%)",
		"z3Out_label": "Zona 3 (70–85%)",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce la edad.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce la edad.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: edad 30 → máx 190.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: edad 30 → máx 190.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de zonas de frecuencia cardíaca",
		"disclaimer": "Solo ilustración educativa (heart rate zones); no es consejo médico.",
		"references": "Referencias educativas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"age_label": "العمر (سنوات)",
		"age_ph": "مثال 30",
		"maxOut_label": "أقصى معدل تقديري",
		"z1Out_label": "المنطقة 1 (50–60%)",
		"z2Out_label": "المنطقة 2 (60–70%)",
		"z3Out_label": "المنطقة 3 (70–85%)",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل العمر.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل العمر.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: عمر 30 → 190.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: عمر 30 → 190.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة مناطق معدل ضربات القلب",
		"disclaimer": "توضيح تعليمي فقط (heart rate zones) وليس نصيحة طبية.",
		"references": "مراجع تعليمية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"age_label": "Idade (anos)",
		"age_ph": "ex. 30",
		"maxOut_label": "FC máx estimada",
		"z1Out_label": "Zona 1 (50–60%)",
		"z2Out_label": "Zona 2 (60–70%)",
		"z3Out_label": "Zona 3 (70–85%)",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe a idade.",
		"formula_title": "Fórmula",
		"formula_body": "Informe a idade.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: idade 30 → 190.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: idade 30 → 190.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de zonas de frequência cardíaca",
		"disclaimer": "Apenas ilustração educativa (heart rate zones); não é conselho médico.",
		"references": "Referências educativas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"age_label": "Usia (tahun)",
		"age_ph": "mis. 30",
		"maxOut_label": "HR maks perkiraan",
		"z1Out_label": "Zona 1 (50–60%)",
		"z2Out_label": "Zona 2 (60–70%)",
		"z3Out_label": "Zona 3 (70–85%)",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi usia.",
		"formula_title": "Rumus",
		"formula_body": "Isi usia.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: usia 30 → 190.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: usia 30 → 190.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator zona denyut jantung",
		"disclaimer": "Hanya ilustrasi edukatif (heart rate zones); bukan saran medis.",
		"references": "Referensi edukatif.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"age_label": "Âge (ans)",
		"age_ph": "ex. 30",
		"maxOut_label": "FC max estimée",
		"z1Out_label": "Zone 1 (50–60 %)",
		"z2Out_label": "Zone 2 (60–70 %)",
		"z3Out_label": "Zone 3 (70–85 %)",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez l’âge.",
		"formula_title": "Formule",
		"formula_body": "Saisissez l’âge.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : âge 30 → 190.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : âge 30 → 190.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de zones de fréquence cardiaque",
		"disclaimer": "Illustration éducative (heart rate zones) uniquement — pas un avis médical.",
		"references": "Références éducatives.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"age_label": "年齢（歳）",
		"age_ph": "例 30",
		"maxOut_label": "推定最大心拍",
		"z1Out_label": "ゾーン1（50–60%）",
		"z2Out_label": "ゾーン2（60–70%）",
		"z3Out_label": "ゾーン3（70–85%）",
		"result_note": "心拍ゾーンの公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れて心拍ゾーンを計算します。",
		"formula_title": "計算式",
		"formula_body": "心拍ゾーンの式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：30歳 → 最大190。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：30歳 → 最大190。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "心拍ゾーン",
		"disclaimer": "心拍ゾーンの学習用試算であり、医療診断・治療の助言ではありません。専門家にご相談ください。",
		"references": "CDC/ACSM などの公開資料。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"age_label": "Возраст (лет)",
		"age_ph": "напр. 30",
		"maxOut_label": "Оценка ЧССмакс",
		"z1Out_label": "Зона 1 (50–60%)",
		"z2Out_label": "Зона 2 (60–70%)",
		"z3Out_label": "Зона 3 (70–85%)",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите возраст.",
		"formula_title": "Формула",
		"formula_body": "Введите возраст.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: возраст 30 → 190.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: возраст 30 → 190.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор пульсовых зон",
		"disclaimer": "Только учебная иллюстрация (heart rate zones) — не медицинский совет.",
		"references": "Образовательные ссылки.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"age_label": "Alter (Jahre)",
		"age_ph": "z. B. 30",
		"maxOut_label": "Geschätzte HFmax",
		"z1Out_label": "Zone 1 (50–60 %)",
		"z2Out_label": "Zone 2 (60–70 %)",
		"z3Out_label": "Zone 3 (70–85 %)",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Alter eingeben.",
		"formula_title": "Formel",
		"formula_body": "Alter eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: Alter 30 → 190.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: Alter 30 → 190.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Herzfrequenzzonen-Rechner",
		"disclaimer": "Nur zur Veranschaulichung (heart rate zones) — keine medizinische Beratung.",
		"references": "Bildungsreferenzen.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 56,
	slug: "how-to-calculate-heart-rate",
	prefix: "tool_heart_rate",
	pageFile: "howToCalculateHeartRatePage",
	pageExport: "renderHowToCalculateHeartRatePage",
	nameZh: "心率区间计算器",
	ymyl: true,
	related: ["how-to-calculate-macros","how-to-calculate-bmr-tdee"],
	anchor: "heart-rate",
	glyph: "M6 16c4-8 8 8 12 0s8-8 12 0",
	sampleHint: "age 30 → max 190; zones as % of max",
	titles: {
		en: "Heart Rate Zone Calculator",
		zh: "心率区间计算器",
		es: "Calculadora de zonas de frecuencia cardíaca",
		ar: "حاسبة مناطق معدل ضربات القلب",
		pt: "Calculadora de zonas de frequência cardíaca",
		id: "Kalkulator zona denyut jantung",
		fr: "Calculateur de zones de fréquence cardiaque",
		ja: "心拍ゾーン計算ツール",
		ru: "Калькулятор пульсовых зон",
		de: "Herzfrequenzzonen-Rechner",
	},
	descriptions: {
		en: "Estimate max HR (220−age) and simple training zones as percent ranges of max. Sample: age 30 → max 190; moderate often ~50–70% of max. Educational only — not medical advice.",
		zh: "估算最大心率（220−年龄）及占最大心率百分比的简易训练区间。示例：年龄 30 → 最大 190；中等强度常约 50–70%。健康教育演示，非医疗建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Estima FC máx (220−edad) y zonas %. Ejemplo: 30 → máx 190. Solo educativo.",
		ar: "قدّر أقصى معدل (220−العمر) والمناطق %. مثال: 30 → 190. تعليمي فقط.",
		pt: "Estime FC máx (220−idade) e zonas %. Exemplo: 30 → 190. Apenas educativo.",
		id: "Perkirakan HR maks (220−usia) dan zona %. Contoh: 30 → 190. Edukatif saja.",
		fr: "Estimez FC max (220−âge) et zones %. Exemple : 30 → 190. Éducatif seulement.",
		ja: "最大心拍（220−年齢）とゾーン（最大の%）を見積もります。例：30歳 → 最大190。学習用であり医療助言ではありません。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Оцените ЧССмакс (220−возраст) и зоны %. Пример: 30 → 190. Только учебно.",
		de: "Schätzen Sie HFmax (220−Alter) und Zonen %. Beispiel: 30 → 190. Nur Bildung.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "age",
	    "type": "number",
	    "half": true,
	    "labelKey": "age_label",
	    "phKey": "age_ph"
	  }
	],
	results: [
	  {
	    "id": "maxOut",
	    "labelKey": "maxOut_label"
	  },
	  {
	    "id": "z1Out",
	    "labelKey": "z1Out_label"
	  },
	  {
	    "id": "z2Out",
	    "labelKey": "z2Out_label"
	  },
	  {
	    "id": "z3Out",
	    "labelKey": "z3Out_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Heart_rate"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.cdc.gov/physicalactivity/basics/measuring/heartrate.htm"
	  }
	],
	computeJs: `
        var age=parseFloat(ageEl.value);
        if(!(age>=1)||!(age<=120)||!Number.isFinite(age)) return {ok:false,error:msgErr};
        var max=220-age;
        function band(lo,hi){ return Math.round(max*lo)+'\u2013'+Math.round(max*hi)+' bpm'; }
        return {ok:true, values:{ maxOut:String(Math.round(max)), z1Out:band(0.50,0.60), z2Out:band(0.60,0.70), z3Out:band(0.70,0.85) }};
`,
	sampleJs: `
        ageEl.value='30';
`,
};
