/**
 * §12 #41 how-to-calculate-inflation
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"amount_label": "Present amount",
		"amount_ph": "e.g. 1000",
		"rate_label": "Inflation % / year",
		"rate_ph": "e.g. 3",
		"n_label": "Years",
		"n_ph": "e.g. 5",
		"futOut_label": "Future nominal amount",
		"result_note": "Future = present × (1+i)^n. Educational illustration of purchasing-power erosion.",
		"err_generic": "Enter amount > 0, finite inflation rate, and n > 0.",
		"how_title": "How it works",
		"how_body": "Enter today’s amount, an annual inflation rate, and years. The page compounds forward. Not a CPI country matrix.",
		"formula_title": "Formula",
		"formula_body": "F = P × (1 + i)^n. Notes:",
		"formula_item_1": "Assumes a constant rate each year.",
		"formula_item_2": "Does not load official CPI tables by country.",
		"formula_item_3": "Real vs nominal wages need more context than this sketch.",
		"example_title": "Example",
		"example": "Example: P=1000, i=3%, n=5 → F = 1000×1.03^5 ≈ 1159.27.",
		"usecases_title": "When to use it",
		"usecase_1": "Homework compounding with inflation.",
		"usecase_2": "Rough future sticker-price sketch.",
		"usecase_3": "Pair with CAGR/compound-interest pages.",
		"faq_q1": "Sample?",
		"faq_a1": "≈1159.27.",
		"faq_q2": "Official CPI?",
		"faq_a2": "Enter your own rate; no country matrix.",
		"faq_q3": "Real wages?",
		"faq_a3": "Out of scope — educational compounding only.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Inflation forward",
		"disclaimer": "Educational inflation only — not financial, tax, or investment advice.",
		"references": "Investopedia and standard textbook formulas.",
		"ref_a_label": "Investopedia — Inflation",
		"ref_b_label": "Investopedia — Purchasing power",
	}),
	zh: withBtns("zh", {
		"amount_label": "当前金额",
		"amount_ph": "例如 1000",
		"rate_label": "年通胀率 %",
		"rate_ph": "例如 3",
		"n_label": "年数",
		"n_ph": "例如 5",
		"futOut_label": "未来名义金额",
		"result_note": "未来值 = 现值 × (1+i)^n。购买力示意，非预测。",
		"err_generic": "金额>0、有效通胀率、年数>0。",
		"how_title": "怎么用",
		"how_body": "填入今天的金额、年通胀率与年数，向前复利。不提供各国 CPI 矩阵。",
		"formula_title": "公式",
		"formula_body": "F = P × (1+i)^n。注意：",
		"formula_item_1": "假定各年通胀率不变。",
		"formula_item_2": "不加载官方 CPI 表。",
		"formula_item_3": "实际工资等需更多背景。",
		"example_title": "示例",
		"example": "示例：P=1000、i=3%、n=5 → ≈1159.27。",
		"usecases_title": "适合什么场景",
		"usecase_1": "通胀复利作业。",
		"usecase_2": "未来标价粗算。",
		"usecase_3": "与 CAGR/复利页对照。",
		"faq_q1": "样例？",
		"faq_a1": "约 1159.27。",
		"faq_q2": "官方 CPI？",
		"faq_a2": "请自填利率；无国家矩阵。",
		"faq_q3": "实际工资？",
		"faq_a3": "超出范围。",
		"faq_q4": "建议？",
		"faq_a4": "仅供学习。",
		"article": "通胀推算",
		"disclaimer": "结果仅为通胀学习演示，不构成投资、理财或税务建议。",
		"references": "Investopedia 与常见教材公式。",
		"ref_a_label": "Investopedia — Inflation",
		"ref_b_label": "Investopedia — Purchasing power",
	}),
	es: withBtns("es", {
		"amount_label": "Monto actual",
		"amount_ph": "p. ej. 1000",
		"rate_label": "Inflación % / año",
		"rate_ph": "p. ej. 3",
		"n_label": "Años",
		"n_ph": "p. ej. 5",
		"futOut_label": "Monto futuro",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce monto, tasa y años.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce monto, tasa y años.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: ≈1159,27.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: ≈1159,27.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de inflación",
		"disclaimer": "Solo ilustración educativa (inflation); no es consejo financiero.",
		"references": "Investopedia y fórmulas de libro.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ar: withBtns("ar", {
		"amount_label": "المبلغ الحالي",
		"amount_ph": "مثال 1000",
		"rate_label": "التضخم % / سنة",
		"rate_ph": "مثال 3",
		"n_label": "سنوات",
		"n_ph": "مثال 5",
		"futOut_label": "المبلغ المستقبلي",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل المبلغ والمعدل والسنوات.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل المبلغ والمعدل والسنوات.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: ≈1159.27.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: ≈1159.27.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة التضخم",
		"disclaimer": "توضيح تعليمي فقط (inflation) وليس نصيحة مالية.",
		"references": "Investopedia وصيغ دراسية.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	pt: withBtns("pt", {
		"amount_label": "Valor atual",
		"amount_ph": "ex. 1000",
		"rate_label": "Inflação % / ano",
		"rate_ph": "ex. 3",
		"n_label": "Anos",
		"n_ph": "ex. 5",
		"futOut_label": "Valor futuro",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe valor, taxa e anos.",
		"formula_title": "Fórmula",
		"formula_body": "Informe valor, taxa e anos.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: ≈1159,27.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: ≈1159,27.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de inflação",
		"disclaimer": "Apenas ilustração educativa (inflation); não é conselho financeiro.",
		"references": "Investopedia e fórmulas didáticas.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	id: withBtns("id", {
		"amount_label": "Jumlah sekarang",
		"amount_ph": "mis. 1000",
		"rate_label": "Inflasi % / tahun",
		"rate_ph": "mis. 3",
		"n_label": "Tahun",
		"n_ph": "mis. 5",
		"futOut_label": "Jumlah masa depan",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi jumlah, suku bunga, tahun.",
		"formula_title": "Rumus",
		"formula_body": "Isi jumlah, suku bunga, tahun.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: ≈1159.27.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: ≈1159.27.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator inflasi",
		"disclaimer": "Hanya ilustrasi edukatif (inflation); bukan saran keuangan.",
		"references": "Investopedia dan rumus buku teks.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	fr: withBtns("fr", {
		"amount_label": "Montant actuel",
		"amount_ph": "ex. 1000",
		"rate_label": "Inflation % / an",
		"rate_ph": "ex. 3",
		"n_label": "Années",
		"n_ph": "ex. 5",
		"futOut_label": "Montant futur",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez montant, taux et années.",
		"formula_title": "Formule",
		"formula_body": "Saisissez montant, taux et années.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : ≈1159,27.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : ≈1159,27.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur d’inflation",
		"disclaimer": "Illustration éducative (inflation) uniquement — pas un conseil financier.",
		"references": "Investopedia et formules de manuel.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ja: withBtns("ja", {
		"amount_label": "現在の金額",
		"amount_ph": "例 1000",
		"rate_label": "年インフレ率 %",
		"rate_ph": "例 3",
		"n_label": "年数",
		"n_ph": "例 5",
		"futOut_label": "将来の名目額",
		"result_note": "将来 = 現在 × (1+i)^n。購買力の学習用。",
		"err_generic": "金額>0、有限な率、年数>0。",
		"how_title": "使い方",
		"how_body": "今日の金額・年率・年数を入れ将来へ複利。国別CPI表は載せません。",
		"formula_title": "計算式",
		"formula_body": "F = P × (1+i)^n。注意:",
		"formula_item_1": "毎年一定率を仮定。",
		"formula_item_2": "公式CPI表なし。",
		"formula_item_3": "実質賃金などは範囲外。",
		"example_title": "例",
		"example": "例：P=1000、i=3%、n=5 → ≈1159.27。",
		"usecases_title": "こんなときに",
		"usecase_1": "インフレ複利の宿題。",
		"usecase_2": "将来価格のざっくり。",
		"usecase_3": "CAGR/複利ページと併用。",
		"faq_q1": "例は？",
		"faq_a1": "約1159.27。",
		"faq_q2": "公式CPIは？",
		"faq_a2": "自分で率を入力。",
		"faq_q3": "実質賃金は？",
		"faq_a3": "範囲外。",
		"faq_q4": "助言？",
		"faq_a4": "学習用です。",
		"article": "インフレ将来額",
		"disclaimer": "インフレの学習用試算であり、投資・税務の助言ではありません。",
		"references": "Investopedia と標準的な教科書公式。",
		"ref_a_label": "Investopedia — Inflation",
		"ref_b_label": "Investopedia — Purchasing power",
	}),
	ru: withBtns("ru", {
		"amount_label": "Текущая сумма",
		"amount_ph": "напр. 1000",
		"rate_label": "Инфляция % / год",
		"rate_ph": "напр. 3",
		"n_label": "Лет",
		"n_ph": "напр. 5",
		"futOut_label": "Будущая сумма",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите сумму, ставку и годы.",
		"formula_title": "Формула",
		"formula_body": "Введите сумму, ставку и годы.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: ≈1159.27.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: ≈1159.27.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор инфляции",
		"disclaimer": "Только учебная иллюстрация (inflation) — не финансовый совет.",
		"references": "Investopedia и учебные формулы.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	de: withBtns("de", {
		"amount_label": "Heutiger Betrag",
		"amount_ph": "z. B. 1000",
		"rate_label": "Inflation % / Jahr",
		"rate_ph": "z. B. 3",
		"n_label": "Jahre",
		"n_ph": "z. B. 5",
		"futOut_label": "Zukünftiger Betrag",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Betrag, Satz und Jahre eingeben.",
		"formula_title": "Formel",
		"formula_body": "Betrag, Satz und Jahre eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: ≈1159,27.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: ≈1159,27.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Inflationsrechner",
		"disclaimer": "Nur zur Veranschaulichung (inflation) — keine Finanzberatung.",
		"references": "Investopedia und Lehrbuchformeln.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
};
export default {
	seq: 41,
	slug: "how-to-calculate-inflation",
	prefix: "tool_inflation",
	pageFile: "howToCalculateInflationPage",
	pageExport: "renderHowToCalculateInflationPage",
	nameZh: "通胀计算器",
	ymyl: true,
	related: ["how-to-calculate-cagr","how-to-calculate-compound-interest"],
	anchor: "inflation",
	glyph: "M6 22l10-18h4L10 22H6z",
	sampleHint: "1000 over 5y at 3% → ≈1159.27",
	titles: {
		en: "Inflation Calculator — Future Purchasing Power",
		zh: "通胀计算器 — 未来购买力粗算",
		es: "Calculadora de inflación",
		ar: "حاسبة التضخم",
		pt: "Calculadora de inflação",
		id: "Kalkulator inflasi",
		fr: "Calculateur d’inflation",
		ja: "インフレ計算ツール — 将来の購買力",
		ru: "Калькулятор инфляции",
		de: "Inflationsrechner",
	},
	descriptions: {
		en: "Project a present amount forward with a constant annual inflation rate. Sample: 1,000 over 5 years at 3% → future ≈ 1,159.27. Educational — not economic advice.",
		zh: "按固定年通胀率把当前金额推算到未来。示例：1000 元、5 年、年通胀 3% → 未来约 1159.27。浏览器本地计算；宏观/理财教育用，非经济预测建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。",
		es: "Proyecta un monto actual con inflación anual constante. Ejemplo: 1000 en 5 años al 3% → ≈1159,27. Educativo.",
		ar: "أسقط مبلغاً حالياً بمعدل تضخم سنوي ثابت. مثال: 1000 على 5 سنوات بنسبة 3٪ → ≈1159.27. تعليمي.",
		pt: "Projete um valor atual com inflação anual constante. Exemplo: 1000 em 5 anos a 3% → ≈1159,27. Educativo.",
		id: "Proyeksikan jumlah sekarang dengan inflasi tahunan tetap. Contoh: 1000 selama 5 tahun pada 3% → ≈1159.27. Edukatif.",
		fr: "Projetez un montant actuel avec un taux d’inflation annuel constant. Exemple : 1000 sur 5 ans à 3 % → ≈1159,27. Éducatif.",
		ja: "一定の年インフレ率で現在額を将来へ伸ばします。例：1000、5年、年3% → 将来 ≈1159.27。学習用であり経済予測ではありません。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり投資・税務・経営の助言ではありません。",
		ru: "Спроецируйте текущую сумму при постоянной годовой инфляции. Пример: 1000 за 5 лет при 3% → ≈1159.27. Учебно.",
		de: "Projizieren Sie einen heutigen Betrag mit konstanter Jahresinflation. Beispiel: 1000 über 5 Jahre bei 3% → ≈1159,27. Bildungszweck.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "amount",
	    "type": "number",
	    "half": true,
	    "labelKey": "amount_label",
	    "phKey": "amount_ph"
	  },
	  {
	    "id": "rate",
	    "type": "number",
	    "half": true,
	    "labelKey": "rate_label",
	    "phKey": "rate_ph"
	  },
	  {
	    "id": "n",
	    "type": "number",
	    "half": true,
	    "labelKey": "n_label",
	    "phKey": "n_ph"
	  }
	],
	results: [
	  {
	    "id": "futOut",
	    "labelKey": "futOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://www.investopedia.com/terms/i/inflation.asp"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.investopedia.com/terms/p/purchasingpower.asp"
	  }
	],
	computeJs: `
        var P=parseFloat(amountEl.value), i=parseFloat(rateEl.value), n=parseFloat(nEl.value);
        if(!(P>0)||!Number.isFinite(i)||!(n>0)) return {ok:false,error:msgErr};
        return {ok:true, values:{ futOut: fmt(P*Math.pow(1+i/100,n)) }};
`,
	sampleJs: `
        amountEl.value='1000';
        rateEl.value='3';
        nEl.value='5';
`,
};
