/**
 * §12 #39 how-to-calculate-irr
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"cf_label": "Cash flows (comma/newline; CF0 first)",
		"cf_ph": "e.g. -1000, 300, 420, 680",
		"irrOut_label": "Approx. IRR",
		"result_note": "Newton IRR on annual periods. May fail to converge for odd sign patterns. Educational only.",
		"err_generic": "Enter at least two finite cash flows (CF0 usually negative).",
		"how_title": "How it works",
		"how_body": "Paste CF0…CFn. The tool searches for r where NPV(r)=0 via Newton iterations.",
		"formula_title": "Formula",
		"formula_body": "Find r such that Σ CFt/(1+r)^t = 0. Notes:",
		"formula_item_1": "CF0 is usually the initial outflow (negative).",
		"formula_item_2": "Multiple IRRs can exist with multiple sign changes — this page returns one Newton root if it converges.",
		"formula_item_3": "Not MIRR; modified IRR is out of scope here.",
		"example_title": "Example",
		"example": "Example: −1000, 300, 420, 680 → IRR ≈ 18.9% (approx).",
		"usecases_title": "When to use it",
		"usecase_1": "Homework: solve a short project IRR.",
		"usecase_2": "Compare with NPV at a hurdle rate.",
		"usecase_3": "Sketch before talking to an advisor — not a substitute.",
		"faq_q1": "Sample IRR?",
		"faq_a1": "About 18.9% for −1000, 300, 420, 680.",
		"faq_q2": "Why Newton?",
		"faq_a2": "Fast local root-finding for the NPV polynomial.",
		"faq_q3": "Multiple IRRs?",
		"faq_a3": "Possible with many sign changes; results may not be unique.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "IRR via Newton",
		"disclaimer": "Educational IRR only — not financial, tax, or investment advice.",
		"references": "Investopedia and standard textbook formulas.",
		"ref_a_label": "Investopedia — IRR",
		"ref_b_label": "Investopedia — NPV",
	}),
	zh: withBtns("zh", {
		"cf_label": "现金流（逗号/换行；先写 CF0）",
		"cf_ph": "例如 -1000, 300, 420, 680",
		"irrOut_label": "近似 IRR",
		"result_note": "年期牛顿 IRR。符号模式奇怪时可能不收敛。仅供学习。",
		"err_generic": "请至少填写两个有限现金流（CF0 通常为负）。",
		"how_title": "怎么用",
		"how_body": "粘贴 CF0…CFn。工具用牛顿迭代寻找使 NPV(r)=0 的 r。",
		"formula_title": "公式",
		"formula_body": "求使 Σ CFt/(1+r)^t = 0 的 r。注意：",
		"formula_item_1": "CF0 通常为初始流出（负）。",
		"formula_item_2": "多次变号可能有多个 IRR；本页在收敛时返回一个根。",
		"formula_item_3": "不含 MIRR。",
		"example_title": "示例",
		"example": "示例：−1000, 300, 420, 680 → IRR ≈ 18.9%。",
		"usecases_title": "适合什么场景",
		"usecase_1": "作业：短项目 IRR。",
		"usecase_2": "与门槛利率下的 NPV 对照。",
		"usecase_3": "见顾问前的草算。",
		"faq_q1": "样例 IRR？",
		"faq_a1": "约 18.9%。",
		"faq_q2": "为何用牛顿法？",
		"faq_a2": "对 NPV 多项式快速求根。",
		"faq_q3": "多个 IRR？",
		"faq_a3": "多次变号时可能；结果未必唯一。",
		"faq_q4": "投资建议？",
		"faq_a4": "不是。",
		"article": "IRR 牛顿法",
		"disclaimer": "结果仅为IRR学习演示，不构成投资、理财或税务建议。",
		"references": "Investopedia 与常见教材公式。",
		"ref_a_label": "Investopedia — IRR",
		"ref_b_label": "Investopedia — NPV",
	}),
	es: withBtns("es", {
		"cf_label": "Flujos (coma/línea; CF0 primero)",
		"cf_ph": "p. ej. -1000, 300, 420, 680",
		"irrOut_label": "TIR aprox.",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Pega CF0…CFn. Se busca r con NPV(r)=0 por Newton.",
		"formula_title": "Fórmula",
		"formula_body": "Pega CF0…CFn. Se busca r con NPV(r)=0 por Newton.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: −1000, 300, 420, 680 → TIR ≈ 18,9%.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: −1000, 300, 420, 680 → TIR ≈ 18,9%.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora TIR (IRR)",
		"disclaimer": "Solo ilustración educativa (IRR); no es consejo financiero.",
		"references": "Investopedia y fórmulas de libro.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ar: withBtns("ar", {
		"cf_label": "التدفقات (مفصولة؛ CF0 أولاً)",
		"cf_ph": "مثال -1000, 300, 420, 680",
		"irrOut_label": "IRR تقريبي",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "الصق CF0…CFn. نبحث عن r حيث NPV(r)=0 بطريقة نيوتن.",
		"formula_title": "الصيغة",
		"formula_body": "الصق CF0…CFn. نبحث عن r حيث NPV(r)=0 بطريقة نيوتن.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: −1000، 300، 420، 680 → IRR ≈ 18.9٪.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: −1000، 300، 420، 680 → IRR ≈ 18.9٪.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة معدل العائد الداخلي IRR",
		"disclaimer": "توضيح تعليمي فقط (IRR) وليس نصيحة مالية.",
		"references": "Investopedia وصيغ دراسية.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	pt: withBtns("pt", {
		"cf_label": "Fluxos (vírgula/linha; CF0 primeiro)",
		"cf_ph": "ex. -1000, 300, 420, 680",
		"irrOut_label": "TIR aprox.",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Cole CF0…CFn. Busca-se r com NPV(r)=0 via Newton.",
		"formula_title": "Fórmula",
		"formula_body": "Cole CF0…CFn. Busca-se r com NPV(r)=0 via Newton.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: −1000, 300, 420, 680 → TIR ≈ 18,9%.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: −1000, 300, 420, 680 → TIR ≈ 18,9%.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora TIR (IRR)",
		"disclaimer": "Apenas ilustração educativa (IRR); não é conselho financeiro.",
		"references": "Investopedia e fórmulas didáticas.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	id: withBtns("id", {
		"cf_label": "Arus kas (koma/baris; CF0 dulu)",
		"cf_ph": "mis. -1000, 300, 420, 680",
		"irrOut_label": "IRR perkiraan",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Tempel CF0…CFn. Mencari r agar NPV(r)=0 dengan Newton.",
		"formula_title": "Rumus",
		"formula_body": "Tempel CF0…CFn. Mencari r agar NPV(r)=0 dengan Newton.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: −1000, 300, 420, 680 → IRR ≈ 18.9%.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: −1000, 300, 420, 680 → IRR ≈ 18.9%.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator IRR",
		"disclaimer": "Hanya ilustrasi edukatif (IRR); bukan saran keuangan.",
		"references": "Investopedia dan rumus buku teks.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	fr: withBtns("fr", {
		"cf_label": "Flux (virgule/ligne ; CF0 d’abord)",
		"cf_ph": "ex. -1000, 300, 420, 680",
		"irrOut_label": "TRI approx.",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Collez CF0…CFn. On cherche r tel que NPV(r)=0 par Newton.",
		"formula_title": "Formule",
		"formula_body": "Collez CF0…CFn. On cherche r tel que NPV(r)=0 par Newton.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : −1000, 300, 420, 680 → TRI ≈ 18,9 %.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : −1000, 300, 420, 680 → TRI ≈ 18,9 %.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur TRI (IRR)",
		"disclaimer": "Illustration éducative (IRR) uniquement — pas un conseil financier.",
		"references": "Investopedia et formules de manuel.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ja: withBtns("ja", {
		"cf_label": "キャッシュフロー（カンマ/改行；CF0から）",
		"cf_ph": "例 -1000, 300, 420, 680",
		"irrOut_label": "近似 IRR",
		"result_note": "年次ニュートン IRR。収束しない場合があります。学習用。",
		"err_generic": "有限なキャッシュフローを2つ以上。",
		"how_title": "使い方",
		"how_body": "CF0…CFn を貼り付けます。NPV(r)=0 となる r をニュートン法で探します。",
		"formula_title": "計算式",
		"formula_body": "Σ CFt/(1+r)^t = 0 となる r。注意:",
		"formula_item_1": "CF0 は通常マイナスの初期流出。",
		"formula_item_2": "符号変化が多いと IRR が複数あり得ます。",
		"formula_item_3": "MIRR は扱いません。",
		"example_title": "例",
		"example": "例：−1000, 300, 420, 680 → IRR ≈ 18.9%。",
		"usecases_title": "こんなときに",
		"usecase_1": "短いプロジェクトIRRの宿題。",
		"usecase_2": "ハードルレートのNPVと比較。",
		"usecase_3": "相談前のざっくり試算。",
		"faq_q1": "例のIRRは？",
		"faq_a1": "約18.9%。",
		"faq_q2": "なぜニュートン？",
		"faq_a2": "NPVの根を速く探すため。",
		"faq_q3": "複数IRR？",
		"faq_a3": "あり得ます。",
		"faq_q4": "助言？",
		"faq_a4": "学習用です。",
		"article": "IRRニュートン",
		"disclaimer": "IRRの学習用試算であり、投資・税務の助言ではありません。",
		"references": "Investopedia と標準的な教科書公式。",
		"ref_a_label": "Investopedia — IRR",
		"ref_b_label": "Investopedia — NPV",
	}),
	ru: withBtns("ru", {
		"cf_label": "Потоки (запятая/строка; сначала CF0)",
		"cf_ph": "напр. -1000, 300, 420, 680",
		"irrOut_label": "Прибл. IRR",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Вставьте CF0…CFn. Ищем r с NPV(r)=0 методом Ньютона.",
		"formula_title": "Формула",
		"formula_body": "Вставьте CF0…CFn. Ищем r с NPV(r)=0 методом Ньютона.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: −1000, 300, 420, 680 → IRR ≈ 18.9%.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: −1000, 300, 420, 680 → IRR ≈ 18.9%.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор IRR",
		"disclaimer": "Только учебная иллюстрация (IRR) — не финансовый совет.",
		"references": "Investopedia и учебные формулы.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	de: withBtns("de", {
		"cf_label": "Cashflows (Komma/Zeile; CF0 zuerst)",
		"cf_ph": "z. B. -1000, 300, 420, 680",
		"irrOut_label": "Näherungs-IRR",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "CF0…CFn einfügen. Suche r mit NPV(r)=0 per Newton.",
		"formula_title": "Formel",
		"formula_body": "CF0…CFn einfügen. Suche r mit NPV(r)=0 per Newton.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: −1000, 300, 420, 680 → IRR ≈ 18,9%.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: −1000, 300, 420, 680 → IRR ≈ 18,9%.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "IRR-Rechner (Interner Zinsfuß)",
		"disclaimer": "Nur zur Veranschaulichung (IRR) — keine Finanzberatung.",
		"references": "Investopedia und Lehrbuchformeln.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
};
export default {
	seq: 39,
	slug: "how-to-calculate-irr",
	prefix: "tool_irr",
	pageFile: "howToCalculateIrrPage",
	pageExport: "renderHowToCalculateIrrPage",
	nameZh: "IRR 计算器",
	ymyl: true,
	related: ["how-to-calculate-npv","how-to-calculate-cagr"],
	anchor: "irr",
	glyph: "M7 22V10l6 4 6-8v16",
	sampleHint: "-1000, 300, 420, 680 → approx IRR%",
	titles: {
		en: "IRR Calculator — Internal Rate of Return",
		zh: "IRR 计算器 — 内部收益率",
		es: "Calculadora TIR (IRR)",
		ar: "حاسبة معدل العائد الداخلي IRR",
		pt: "Calculadora TIR (IRR)",
		id: "Kalkulator IRR",
		fr: "Calculateur TRI (IRR)",
		ja: "IRR（内部収益率）計算ツール",
		ru: "Калькулятор IRR",
		de: "IRR-Rechner (Interner Zinsfuß)",
	},
	descriptions: {
		en: "Estimate IRR for a simple cash-flow list with Newton’s method. Sample: −1000, 300, 420, 680 → approximate IRR%. Educational project math — not investment advice.",
		zh: "用牛顿法估算简单现金流序列的 IRR（内部收益率）。示例：−1000、300、420、680 → 近似 IRR%。浏览器本地计算；项目测算学习用，非投资建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。",
		es: "Estima la TIR de una lista de flujos con el método de Newton. Ejemplo: −1000, 300, 420, 680 → TIR aproximada. Educativo.",
		ar: "قدّر IRR لتدفقات نقدية بسيطة بطريقة نيوتن. مثال: −1000، 300، 420، 680 → IRR تقريبي. تعليمي.",
		pt: "Estime a TIR de fluxos simples com o método de Newton. Exemplo: −1000, 300, 420, 680 → TIR aproximada. Educativo.",
		id: "Perkirakan IRR dari daftar arus kas sederhana dengan metode Newton. Contoh: −1000, 300, 420, 680 → IRR perkiraan. Edukatif.",
		fr: "Estimez le TRI d’une liste de flux par Newton. Exemple : −1000, 300, 420, 680 → TRI approximatif. Éducatif.",
		ja: "単純なキャッシュフロー列の IRR をニュートン法で近似します。例：−1000, 300, 420, 680 → おおよその IRR%。学習用であり投資助言ではありません。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり投資・税務・経営の助言ではありません。",
		ru: "Оцените IRR простого ряда денежных потоков методом Ньютона. Пример: −1000, 300, 420, 680 → приблизительный IRR%. Учебно.",
		de: "Schätzen Sie den IRR einer einfachen Zahlungsreihe per Newton. Beispiel: −1000, 300, 420, 680 → näherungsweiser IRR%. Bildungszweck.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "cf",
	    "type": "textarea",
	    "labelKey": "cf_label",
	    "phKey": "cf_ph",
	    "rows": 5
	  }
	],
	results: [
	  {
	    "id": "irrOut",
	    "labelKey": "irrOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://www.investopedia.com/terms/i/irr.asp"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.investopedia.com/terms/n/npv.asp"
	  }
	],
	computeJs: `
        var parts = String(cfEl.value||'').split(/[\s,;，、]+/).filter(Boolean);
        var flows = [];
        for (var i=0;i<parts.length;i++){ var v=parseFloat(parts[i]); if(!Number.isFinite(v)) return {ok:false,error:msgErr}; flows.push(v); }
        if (flows.length < 2) return {ok:false,error:msgErr};
        function npv(r){ var s=0; for (var t=0;t<flows.length;t++) s += flows[t]/Math.pow(1+r,t); return s; }
        function dnpv(r){ var s=0; for (var t=1;t<flows.length;t++) s += -t*flows[t]/Math.pow(1+r,t+1); return s; }
        var r = 0.1;
        for (var k=0;k<50;k++){
          var f = npv(r), df = dnpv(r);
          if (!Number.isFinite(f) || !Number.isFinite(df) || Math.abs(df) < 1e-12) break;
          var nr = r - f/df;
          if (!Number.isFinite(nr) || nr <= -0.999999) break;
          if (Math.abs(nr - r) < 1e-10) { r = nr; break; }
          r = nr;
        }
        if (!Number.isFinite(r) || Math.abs(npv(r)) > 1e-3) return {ok:false,error:msgErr};
        return { ok:true, values:{ irrOut: fmt(r*100) + '%' } };
`,
	sampleJs: `
        cfEl.value='-1000, 300, 420, 680';
`,
};
