/**
 * §12 #55 how-to-calculate-macros
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"cal_label": "Calories (kcal)",
		"cal_ph": "e.g. 2000",
		"pPct_label": "Protein %",
		"pPct_ph": "e.g. 30",
		"cPct_label": "Carb %",
		"cPct_ph": "e.g. 40",
		"fPct_label": "Fat %",
		"fPct_ph": "e.g. 30",
		"pG_label": "Protein (g)",
		"cG_label": "Carbs (g)",
		"fG_label": "Fat (g)",
		"result_note": "Grams = (kcal × percent/100) ÷ kcal-per-gram (P/C=4, fat=9). Percents should sum to 100.",
		"err_generic": "Enter calories > 0 and percents ≥ 0 that sum to 100.",
		"how_title": "How it works",
		"how_body": "Enter daily calories and protein/carb/fat percents. This is textbook energy arithmetic, not a meal plan.",
		"formula_title": "Formula",
		"formula_body": "g_P = kcal×p%/4; g_C = kcal×c%/4; g_F = kcal×f%/9. Notes:",
		"formula_item_1": "Percents must sum to 100 (± tiny float).",
		"formula_item_2": "Not individualized nutrition therapy.",
		"formula_item_3": "Pair with heart-rate / BMR–TDEE tools for education.",
		"example_title": "Example",
		"example": "Example: 2000 kcal at 30/40/30% → 150 g protein, 200 g carbs, ≈66.67 g fat.",
		"usecases_title": "When to use it",
		"usecase_1": "Classroom macro math.",
		"usecase_2": "Compare percent splits.",
		"usecase_3": "Educational pairing with BMR/TDEE.",
		"faq_q1": "Sample?",
		"faq_a1": "2000 @ 30/40/30 → 150/200/≈66.67 g.",
		"faq_q2": "Medical advice?",
		"faq_a2": "No — educational only.",
		"faq_q3": "Why 9 for fat?",
		"faq_a3": "Fat has ~9 kcal/g; P/C ~4.",
		"faq_q4": "Sum ≠100?",
		"faq_a4": "Rejected.",
		"article": "Macronutrient grams",
		"disclaimer": "Educational macronutrients only — not medical advice. Consult a qualified clinician.",
		"references": "CDC / ACSM-style educational references.",
		"ref_a_label": "Wikipedia — Food energy",
		"ref_b_label": "CDC Nutrition",
	}),
	zh: withBtns("zh", {
		"cal_label": "热量 (kcal)",
		"cal_ph": "例如 2000",
		"pPct_label": "蛋白质 %",
		"pPct_ph": "例如 30",
		"cPct_label": "碳水 %",
		"cPct_ph": "例如 40",
		"fPct_label": "脂肪 %",
		"fPct_ph": "例如 30",
		"pG_label": "蛋白质 (g)",
		"cG_label": "碳水 (g)",
		"fG_label": "脂肪 (g)",
		"result_note": "克数=(热量×比例/100)÷每克热量（P/C=4，脂肪=9）。比例宜合计 100%。",
		"err_generic": "热量>0，比例≥0 且合计 100%。",
		"how_title": "怎么用",
		"how_body": "填写热量与三大营养素比例。这是教材能量算术，不是膳食处方。",
		"formula_title": "公式",
		"formula_body": "宏量营养素相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：2000 kcal、30/40/30% → 150/200/约66.67 g。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：2000 kcal、30/40/30% → 150/200/约66.67 g。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "宏量营养素",
		"disclaimer": "结果仅为宏量营养素健康教育演示，不构成医疗诊断或治疗建议。请咨询专业人士。",
		"references": "CDC / ACSM 等公开教育资料。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"cal_label": "Calorías (kcal)",
		"cal_ph": "p. ej. 2000",
		"pPct_label": "Proteína %",
		"pPct_ph": "p. ej. 30",
		"cPct_label": "Carbos %",
		"cPct_ph": "p. ej. 40",
		"fPct_label": "Grasa %",
		"fPct_ph": "p. ej. 30",
		"pG_label": "Proteína (g)",
		"cG_label": "Carbos (g)",
		"fG_label": "Grasa (g)",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce calorías y %.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce calorías y %.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: 150/200/≈66.67 g.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: 150/200/≈66.67 g.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de macros",
		"disclaimer": "Solo ilustración educativa (macronutrients); no es consejo médico.",
		"references": "Referencias educativas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"cal_label": "السعرات (kcal)",
		"cal_ph": "مثال 2000",
		"pPct_label": "بروتين %",
		"pPct_ph": "مثال 30",
		"cPct_label": "كربوهيدرات %",
		"cPct_ph": "مثال 40",
		"fPct_label": "دهون %",
		"fPct_ph": "مثال 30",
		"pG_label": "بروتين (غ)",
		"cG_label": "كربوهيدرات (غ)",
		"fG_label": "دهون (غ)",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل السعرات والنسب.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل السعرات والنسب.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: 150/200/≈66.67 جم.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: 150/200/≈66.67 جم.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة المغذيات الكبرى",
		"disclaimer": "توضيح تعليمي فقط (macronutrients) وليس نصيحة طبية.",
		"references": "مراجع تعليمية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"cal_label": "Calorias (kcal)",
		"cal_ph": "ex. 2000",
		"pPct_label": "Proteína %",
		"pPct_ph": "ex. 30",
		"cPct_label": "Carboidratos %",
		"cPct_ph": "ex. 40",
		"fPct_label": "Gordura %",
		"fPct_ph": "ex. 30",
		"pG_label": "Proteína (g)",
		"cG_label": "Carboidratos (g)",
		"fG_label": "Gordura (g)",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe calorias e %.",
		"formula_title": "Fórmula",
		"formula_body": "Informe calorias e %.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: 150/200/≈66.67 g.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: 150/200/≈66.67 g.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de macros",
		"disclaimer": "Apenas ilustração educativa (macronutrients); não é conselho médico.",
		"references": "Referências educativas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"cal_label": "Kalori (kcal)",
		"cal_ph": "mis. 2000",
		"pPct_label": "Protein %",
		"pPct_ph": "mis. 30",
		"cPct_label": "Karbo %",
		"cPct_ph": "mis. 40",
		"fPct_label": "Lemak %",
		"fPct_ph": "mis. 30",
		"pG_label": "Protein (g)",
		"cG_label": "Karbo (g)",
		"fG_label": "Lemak (g)",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi kalori dan %.",
		"formula_title": "Rumus",
		"formula_body": "Isi kalori dan %.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: 150/200/≈66.67 g.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: 150/200/≈66.67 g.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator makro",
		"disclaimer": "Hanya ilustrasi edukatif (macronutrients); bukan saran medis.",
		"references": "Referensi edukatif.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"cal_label": "Calories (kcal)",
		"cal_ph": "ex. 2000",
		"pPct_label": "Protéines %",
		"pPct_ph": "ex. 30",
		"cPct_label": "Glucides %",
		"cPct_ph": "ex. 40",
		"fPct_label": "Lipides %",
		"fPct_ph": "ex. 30",
		"pG_label": "Protéines (g)",
		"cG_label": "Glucides (g)",
		"fG_label": "Lipides (g)",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez calories et %.",
		"formula_title": "Formule",
		"formula_body": "Saisissez calories et %.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : 150/200/≈66.67 g.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : 150/200/≈66.67 g.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de macros",
		"disclaimer": "Illustration éducative (macronutrients) uniquement — pas un avis médical.",
		"references": "Références éducatives.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"cal_label": "カロリー (kcal)",
		"cal_ph": "例 2000",
		"pPct_label": "たんぱく %",
		"pPct_ph": "例 30",
		"cPct_label": "炭水化物 %",
		"cPct_ph": "例 40",
		"fPct_label": "脂質 %",
		"fPct_ph": "例 30",
		"pG_label": "たんぱく (g)",
		"cG_label": "炭水化物 (g)",
		"fG_label": "脂質 (g)",
		"result_note": "マクロ栄養素の公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れてマクロ栄養素を計算します。",
		"formula_title": "計算式",
		"formula_body": "マクロ栄養素の式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：2000kcal・30/40/30% → 150/200/約66.67g。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：2000kcal・30/40/30% → 150/200/約66.67g。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "マクロ栄養素",
		"disclaimer": "マクロ栄養素の学習用試算であり、医療診断・治療の助言ではありません。専門家にご相談ください。",
		"references": "CDC/ACSM などの公開資料。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"cal_label": "Калории (ккал)",
		"cal_ph": "напр. 2000",
		"pPct_label": "Белки %",
		"pPct_ph": "напр. 30",
		"cPct_label": "Углеводы %",
		"cPct_ph": "напр. 40",
		"fPct_label": "Жиры %",
		"fPct_ph": "напр. 30",
		"pG_label": "Белки (г)",
		"cG_label": "Углеводы (г)",
		"fG_label": "Жиры (г)",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите калории и %.",
		"formula_title": "Формула",
		"formula_body": "Введите калории и %.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: 150/200/≈66.67 г.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: 150/200/≈66.67 г.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор макронутриентов",
		"disclaimer": "Только учебная иллюстрация (macronutrients) — не медицинский совет.",
		"references": "Образовательные ссылки.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"cal_label": "Kalorien (kcal)",
		"cal_ph": "z. B. 2000",
		"pPct_label": "Protein %",
		"pPct_ph": "z. B. 30",
		"cPct_label": "Kohlenhydrate %",
		"cPct_ph": "z. B. 40",
		"fPct_label": "Fett %",
		"fPct_ph": "z. B. 30",
		"pG_label": "Protein (g)",
		"cG_label": "Kohlenhydrate (g)",
		"fG_label": "Fett (g)",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Kalorien und % eingeben.",
		"formula_title": "Formel",
		"formula_body": "Kalorien und % eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: 150/200/≈66.67 g.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: 150/200/≈66.67 g.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Makro-Rechner — Kalorien in Gramm",
		"disclaimer": "Nur zur Veranschaulichung (macronutrients) — keine medizinische Beratung.",
		"references": "Bildungsreferenzen.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 55,
	slug: "how-to-calculate-macros",
	prefix: "tool_macros",
	pageFile: "howToCalculateMacrosPage",
	pageExport: "renderHowToCalculateMacrosPage",
	nameZh: "宏量营养素计算器",
	ymyl: true,
	related: ["how-to-calculate-heart-rate","how-to-calculate-bmr-tdee"],
	anchor: "macros",
	glyph: "M8 8h16v4H8zm4 8h8v8h-8z",
	sampleHint: "2000 kcal 30/40/30 → 150/200/66.67 g",
	titles: {
		en: "Macro Calculator — Calories to Protein Carb Fat Grams",
		zh: "宏量营养素计算器 — 热量分配到克数",
		es: "Calculadora de macros",
		ar: "حاسبة المغذيات الكبرى",
		pt: "Calculadora de macros",
		id: "Kalkulator makro",
		fr: "Calculateur de macros",
		ja: "マクロ栄養素計算ツール — カロリーからグラムへ",
		ru: "Калькулятор макронутриентов",
		de: "Makro-Rechner — Kalorien in Gramm",
	},
	descriptions: {
		en: "Split daily calories into protein, carb, and fat grams (4 / 4 / 9 kcal per gram). Sample: 2000 kcal at 30/40/30% → 150 g / 200 g / ≈66.67 g. Educational only — not medical advice.",
		zh: "按热量与比例把蛋白/碳水/脂肪换成克数（每克 4/4/9 kcal）。示例：2000 kcal、30%/40%/30% → 150 g / 200 g / 约 66.67 g。健康教育演示，非医疗建议；浏览器本地计算。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Reparte calorías en gramos de proteína, carb y grasa (4/4/9). Ejemplo: 2000 a 30/40/30% → 150/200/≈66.67 g. Solo educativo.",
		ar: "قسّم السعرات إلى جرامات بروتين وكربوهيدرات ودهون (4/4/9). مثال: 2000 بنسبة 30/40/30٪ → 150/200/≈66.67 جم. تعليمي فقط.",
		pt: "Divida calorias em gramas de proteína, carbo e gordura (4/4/9). Exemplo: 2000 a 30/40/30% → 150/200/≈66.67 g. Apenas educativo.",
		id: "Bagi kalori jadi gram protein, karbo, lemak (4/4/9). Contoh: 2000 pada 30/40/30% → 150/200/≈66.67 g. Edukatif saja.",
		fr: "Répartissez les calories en grammes P/C/L (4/4/9). Exemple : 2000 à 30/40/30 % → 150/200/≈66.67 g. Éducatif seulement.",
		ja: "カロリーをたんぱく/炭水化物/脂質のグラムに配分（1gあたり4/4/9kcal）。例：2000kcal・30/40/30% → 150/200/約66.67g。学習用であり医療助言ではありません。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Разделите калории на граммы Б/У/Ж (4/4/9). Пример: 2000 при 30/40/30% → 150/200/≈66.67 г. Только учебно.",
		de: "Kalorien in Protein-/Kohlenhydrat-/Fettgramm (4/4/9). Beispiel: 2000 bei 30/40/30% → 150/200/≈66.67 g. Nur Bildung.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "cal",
	    "type": "number",
	    "half": true,
	    "labelKey": "cal_label",
	    "phKey": "cal_ph"
	  },
	  {
	    "id": "pPct",
	    "type": "number",
	    "half": true,
	    "labelKey": "pPct_label",
	    "phKey": "pPct_ph"
	  },
	  {
	    "id": "cPct",
	    "type": "number",
	    "half": true,
	    "labelKey": "cPct_label",
	    "phKey": "cPct_ph"
	  },
	  {
	    "id": "fPct",
	    "type": "number",
	    "half": true,
	    "labelKey": "fPct_label",
	    "phKey": "fPct_ph"
	  }
	],
	results: [
	  {
	    "id": "pG",
	    "labelKey": "pG_label"
	  },
	  {
	    "id": "cG",
	    "labelKey": "cG_label"
	  },
	  {
	    "id": "fG",
	    "labelKey": "fG_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Food_energy"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.cdc.gov/nutrition/"
	  }
	],
	computeJs: `
        var cal=parseFloat(calEl.value), p=parseFloat(pPctEl.value), c=parseFloat(cPctEl.value), f=parseFloat(fPctEl.value);
        if(!(cal>0)||!(p>=0)||!(c>=0)||!(f>=0)||Math.abs(p+c+f-100)>1e-6) return {ok:false,error:msgErr};
        var pG=(cal*p/100)/4, cG=(cal*c/100)/4, fG=(cal*f/100)/9;
        return {ok:true, values:{ pG:fmt(pG), cG:fmt(cG), fG:fmt(fG) }};
`,
	sampleJs: `
        calEl.value='2000';
        pPctEl.value='30';
        cPctEl.value='40';
        fPctEl.value='30';
`,
};
