/**
 * §12 #48 how-to-calculate-mean
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"nums_label": "Numbers",
		"nums_ph": "e.g. 1,2,3,4,5",
		"type_label": "Mean type",
		"type_arithmetic": "Arithmetic",
		"type_geometric": "Geometric",
		"type_harmonic": "Harmonic",
		"meanOut_label": "Mean",
		"result_note": "Arithmetic: sum/n. Geometric: (Πxi)^(1/n) (all > 0). Harmonic: n / Σ(1/xi) (none zero).",
		"err_generic": "Enter a non-empty number list; check type constraints.",
		"how_title": "How it works",
		"how_body": "Paste numbers separated by commas or spaces, choose arithmetic / geometric / harmonic, then calculate.",
		"formula_title": "Formula",
		"formula_body": "Ā = (Σx)/n; G = (Πx)^(1/n); H = n / Σ(1/x). Notes:",
		"formula_item_1": "Geometric mean needs every value > 0.",
		"formula_item_2": "Harmonic mean rejects zeros.",
		"formula_item_3": "Pair with median / SD tools for distribution drills.",
		"example_title": "Example",
		"example": "Example: 1,2,3,4,5 arithmetic → 3.",
		"usecases_title": "When to use it",
		"usecase_1": "Homework averages.",
		"usecase_2": "Quick dataset center.",
		"usecase_3": "Compare with median.",
		"faq_q1": "Sample?",
		"faq_a1": "1–5 arithmetic → 3.",
		"faq_q2": "Geometric of negatives?",
		"faq_a2": "Not defined here.",
		"faq_q3": "Empty list?",
		"faq_a3": "Rejected.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Means",
		"disclaimer": "Educational mean only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — Mean",
		"ref_b_label": "Wikipedia — Average",
	}),
	zh: withBtns("zh", {
		"nums_label": "数字列表",
		"nums_ph": "例如 1,2,3,4,5",
		"type_label": "平均类型",
		"type_arithmetic": "算术平均",
		"type_geometric": "几何平均",
		"type_harmonic": "调和平均",
		"meanOut_label": "平均数",
		"result_note": "结果按平均数公式在浏览器本地计算。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算平均数。",
		"formula_title": "公式",
		"formula_body": "平均数相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：1,2,3,4,5 算术平均 → 3。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：1,2,3,4,5 算术平均 → 3。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "平均数",
		"disclaimer": "结果仅为平均数学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"nums_label": "Números",
		"nums_ph": "p. ej. 1,2,3,4,5",
		"type_label": "Tipo",
		"type_arithmetic": "Aritmética",
		"type_geometric": "Geométrica",
		"type_harmonic": "Armónica",
		"meanOut_label": "Media",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Pega números y elige el tipo.",
		"formula_title": "Fórmula",
		"formula_body": "Pega números y elige el tipo.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: 1–5 → 3.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: 1–5 → 3.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de media",
		"disclaimer": "Solo ilustración educativa (mean).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"nums_label": "الأرقام",
		"nums_ph": "مثال 1,2,3,4,5",
		"type_label": "النوع",
		"type_arithmetic": "حسابي",
		"type_geometric": "هندسي",
		"type_harmonic": "توافقي",
		"meanOut_label": "المتوسط",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "الصق الأرقام واختر النوع.",
		"formula_title": "الصيغة",
		"formula_body": "الصق الأرقام واختر النوع.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: 1–5 → 3.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: 1–5 → 3.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة المتوسط",
		"disclaimer": "توضيح تعليمي فقط (mean).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"nums_label": "Números",
		"nums_ph": "ex. 1,2,3,4,5",
		"type_label": "Tipo",
		"type_arithmetic": "Aritmética",
		"type_geometric": "Geométrica",
		"type_harmonic": "Harmônica",
		"meanOut_label": "Média",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Cole números e escolha o tipo.",
		"formula_title": "Fórmula",
		"formula_body": "Cole números e escolha o tipo.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: 1–5 → 3.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: 1–5 → 3.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de média",
		"disclaimer": "Apenas ilustração educativa (mean).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"nums_label": "Angka",
		"nums_ph": "mis. 1,2,3,4,5",
		"type_label": "Jenis",
		"type_arithmetic": "Aritmetika",
		"type_geometric": "Geometris",
		"type_harmonic": "Harmonik",
		"meanOut_label": "Rata-rata",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Tempel angka dan pilih jenis.",
		"formula_title": "Rumus",
		"formula_body": "Tempel angka dan pilih jenis.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: 1–5 → 3.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: 1–5 → 3.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator rata-rata",
		"disclaimer": "Hanya ilustrasi edukatif (mean).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"nums_label": "Nombres",
		"nums_ph": "ex. 1,2,3,4,5",
		"type_label": "Type",
		"type_arithmetic": "Arithmétique",
		"type_geometric": "Géométrique",
		"type_harmonic": "Harmonique",
		"meanOut_label": "Moyenne",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Collez des nombres et choisissez le type.",
		"formula_title": "Formule",
		"formula_body": "Collez des nombres et choisissez le type.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : 1–5 → 3.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : 1–5 → 3.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de moyenne",
		"disclaimer": "Illustration éducative (mean) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"nums_label": "数値リスト",
		"nums_ph": "例 1,2,3,4,5",
		"type_label": "平均の種類",
		"type_arithmetic": "相加平均",
		"type_geometric": "相乗平均",
		"type_harmonic": "調和平均",
		"meanOut_label": "平均",
		"result_note": "平均の公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れて平均を計算します。",
		"formula_title": "計算式",
		"formula_body": "平均の式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：1,2,3,4,5 の相加平均 → 3。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：1,2,3,4,5 の相加平均 → 3。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "平均",
		"disclaimer": "平均の学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"nums_label": "Числа",
		"nums_ph": "напр. 1,2,3,4,5",
		"type_label": "Тип",
		"type_arithmetic": "Арифметическое",
		"type_geometric": "Геометрическое",
		"type_harmonic": "Гармоническое",
		"meanOut_label": "Среднее",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Вставьте числа и выберите тип.",
		"formula_title": "Формула",
		"formula_body": "Вставьте числа и выберите тип.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: 1–5 → 3.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: 1–5 → 3.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор среднего",
		"disclaimer": "Только учебная иллюстрация (mean).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"nums_label": "Zahlen",
		"nums_ph": "z. B. 1,2,3,4,5",
		"type_label": "Typ",
		"type_arithmetic": "Arithmetisch",
		"type_geometric": "Geometrisch",
		"type_harmonic": "Harmonisch",
		"meanOut_label": "Mittelwert",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Zahlen einfügen und Typ wählen.",
		"formula_title": "Formel",
		"formula_body": "Zahlen einfügen und Typ wählen.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: 1–5 → 3.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: 1–5 → 3.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Mittelwert-Rechner",
		"disclaimer": "Nur zur Veranschaulichung (mean).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 48,
	slug: "how-to-calculate-mean",
	prefix: "tool_mean",
	pageFile: "howToCalculateMeanPage",
	pageExport: "renderHowToCalculateMeanPage",
	nameZh: "平均数计算器",
	ymyl: false,
	related: ["how-to-calculate-median","how-to-calculate-standard-deviation"],
	anchor: "mean",
	glyph: "M8 8h16v4H8zm4 8h8v8h-8z",
	sampleHint: "1,2,3,4,5 arithmetic → 3",
	titles: {
		en: "Mean Calculator — Average of a Number List",
		zh: "平均数计算器 — 列表均值",
		es: "Calculadora de media",
		ar: "حاسبة المتوسط",
		pt: "Calculadora de média",
		id: "Kalkulator rata-rata",
		fr: "Calculateur de moyenne",
		ja: "平均の計算ツール — 相加/相乗/調和",
		ru: "Калькулятор среднего",
		de: "Mittelwert-Rechner",
	},
	descriptions: {
		en: "Compute arithmetic, geometric, or harmonic mean from a number list. Sample: 1,2,3,4,5 arithmetic → 3. Browser-only.",
		zh: "对数字列表计算算术、几何或调和平均数。示例：1,2,3,4,5 算术平均 → 3。浏览器本地计算，数据不上传。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Calcula media aritmética, geométrica o armónica. Ejemplo: 1,2,3,4,5 → 3.",
		ar: "احسب المتوسط الحسابي أو الهندسي أو التوافقي. مثال: 1,2,3,4,5 → 3.",
		pt: "Calcule média aritmética, geométrica ou harmônica. Exemplo: 1,2,3,4,5 → 3.",
		id: "Hitung mean aritmetika, geometris, atau harmonik. Contoh: 1,2,3,4,5 → 3.",
		fr: "Calculez moyenne arithmétique, géométrique ou harmonique. Exemple : 1,2,3,4,5 → 3.",
		ja: "数値リストの相加・相乗・調和平均を計算します。例：1,2,3,4,5 の相加平均 → 3。ブラウザ内計算です。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Считайте среднее арифметическое, геометрическое или гармоническое. Пример: 1,2,3,4,5 → 3.",
		de: "Arithmetisches, geometrisches oder harmonisches Mittel. Beispiel: 1,2,3,4,5 → 3.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "nums",
	    "type": "textarea",
	    "labelKey": "nums_label",
	    "phKey": "nums_ph",
	    "rows": 4
	  },
	  {
	    "id": "type",
	    "type": "select",
	    "half": true,
	    "labelKey": "type_label",
	    "options": [
	      {
	        "value": "arithmetic",
	        "labelKey": "type_arithmetic",
	        "selected": true
	      },
	      {
	        "value": "geometric",
	        "labelKey": "type_geometric"
	      },
	      {
	        "value": "harmonic",
	        "labelKey": "type_harmonic"
	      }
	    ]
	  }
	],
	results: [
	  {
	    "id": "meanOut",
	    "labelKey": "meanOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Mean"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Average"
	  }
	],
	computeJs: `
        var raw=String(numsEl.value||'');
        var parts=raw.split(/[\s,;]+/).map(function(s){return s.trim();}).filter(Boolean);
        var xs=parts.map(parseFloat);
        if(!xs.length||xs.some(function(x){return !Number.isFinite(x);})) return {ok:false,error:msgErr};
        var n=xs.length, kind=typeEl.value, mean;
        if(kind==='geometric'){
          if(xs.some(function(x){return !(x>0);})) return {ok:false,error:msgErr};
          var logSum=0; for(var i=0;i<n;i++) logSum+=Math.log(xs[i]);
          mean=Math.exp(logSum/n);
        } else if(kind==='harmonic'){
          if(xs.some(function(x){return x===0||!Number.isFinite(1/x);})) return {ok:false,error:msgErr};
          var inv=0; for(var j=0;j<n;j++) inv+=1/xs[j];
          mean=n/inv;
        } else {
          var sum=0; for(var k=0;k<n;k++) sum+=xs[k];
          mean=sum/n;
        }
        return {ok:true, values:{ meanOut:fmt(mean) }};
`,
	sampleJs: `
        numsEl.value='1,2,3,4,5';
        typeEl.value='arithmetic';
`,
};
