/**
 * §12 #49 how-to-calculate-median
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"nums_label": "Numbers",
		"nums_ph": "e.g. 1,2,2,3,4",
		"medianOut_label": "Median",
		"modeOut_label": "Mode",
		"result_note": "Sort values; median is middle (or average of two middles). Mode is the most frequent value (ties: smallest).",
		"err_generic": "Enter a non-empty number list.",
		"how_title": "How it works",
		"how_body": "Paste numbers separated by commas or spaces. The tool reports median and a single mode.",
		"formula_title": "Formula",
		"formula_body": "Sort x; odd n → x[(n+1)/2]; even → average of two central. Mode = argmax frequency. Notes:",
		"formula_item_1": "Even-length median uses the mean of the two central values.",
		"formula_item_2": "If all frequencies tie, mode is the smallest value.",
		"formula_item_3": "Pair with mean / SD tools.",
		"example_title": "Example",
		"example": "Example: 1,2,2,3,4 → median 2, mode 2.",
		"usecases_title": "When to use it",
		"usecase_1": "Homework median/mode.",
		"usecase_2": "Quick center vs peak.",
		"usecase_3": "Compare with mean.",
		"faq_q1": "Sample?",
		"faq_a1": "1,2,2,3,4 → 2 and 2.",
		"faq_q2": "Multimodal?",
		"faq_a2": "We return one mode (smallest among ties).",
		"faq_q3": "Empty?",
		"faq_a3": "Rejected.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Median and mode",
		"disclaimer": "Educational median only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — Median",
		"ref_b_label": "Wikipedia — Mode",
	}),
	zh: withBtns("zh", {
		"nums_label": "数字列表",
		"nums_ph": "例如 1,2,2,3,4",
		"medianOut_label": "中位数",
		"modeOut_label": "众数",
		"result_note": "结果按中位数公式在浏览器本地计算。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算中位数。",
		"formula_title": "公式",
		"formula_body": "中位数相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：1,2,2,3,4 → 中位 2、众数 2。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：1,2,2,3,4 → 中位 2、众数 2。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "中位数",
		"disclaimer": "结果仅为中位数学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"nums_label": "Números",
		"nums_ph": "p. ej. 1,2,2,3,4",
		"medianOut_label": "Mediana",
		"modeOut_label": "Moda",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Pega la lista de números.",
		"formula_title": "Fórmula",
		"formula_body": "Pega la lista de números.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: mediana 2, moda 2.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: mediana 2, moda 2.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de mediana y moda",
		"disclaimer": "Solo ilustración educativa (median).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"nums_label": "الأرقام",
		"nums_ph": "مثال 1,2,2,3,4",
		"medianOut_label": "الوسيط",
		"modeOut_label": "المنوال",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "الصق قائمة الأرقام.",
		"formula_title": "الصيغة",
		"formula_body": "الصق قائمة الأرقام.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: وسيط 2 ومنوال 2.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: وسيط 2 ومنوال 2.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة الوسيط والمنوال",
		"disclaimer": "توضيح تعليمي فقط (median).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"nums_label": "Números",
		"nums_ph": "ex. 1,2,2,3,4",
		"medianOut_label": "Mediana",
		"modeOut_label": "Moda",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Cole a lista de números.",
		"formula_title": "Fórmula",
		"formula_body": "Cole a lista de números.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: mediana 2, moda 2.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: mediana 2, moda 2.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de mediana e moda",
		"disclaimer": "Apenas ilustração educativa (median).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"nums_label": "Angka",
		"nums_ph": "mis. 1,2,2,3,4",
		"medianOut_label": "Median",
		"modeOut_label": "Modus",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Tempel daftar angka.",
		"formula_title": "Rumus",
		"formula_body": "Tempel daftar angka.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: median 2, modus 2.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: median 2, modus 2.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator median dan modus",
		"disclaimer": "Hanya ilustrasi edukatif (median).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"nums_label": "Nombres",
		"nums_ph": "ex. 1,2,2,3,4",
		"medianOut_label": "Médiane",
		"modeOut_label": "Mode",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Collez la liste.",
		"formula_title": "Formule",
		"formula_body": "Collez la liste.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : médiane 2, mode 2.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : médiane 2, mode 2.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de médiane et mode",
		"disclaimer": "Illustration éducative (median) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"nums_label": "数値リスト",
		"nums_ph": "例 1,2,2,3,4",
		"medianOut_label": "中央値",
		"modeOut_label": "最頻値",
		"result_note": "中央値の公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れて中央値を計算します。",
		"formula_title": "計算式",
		"formula_body": "中央値の式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：1,2,2,3,4 → 中央値2、最頻値2。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：1,2,2,3,4 → 中央値2、最頻値2。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "中央値",
		"disclaimer": "中央値の学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"nums_label": "Числа",
		"nums_ph": "напр. 1,2,2,3,4",
		"medianOut_label": "Медиана",
		"modeOut_label": "Мода",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Вставьте список чисел.",
		"formula_title": "Формула",
		"formula_body": "Вставьте список чисел.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: медиана 2, мода 2.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: медиана 2, мода 2.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор медианы и моды",
		"disclaimer": "Только учебная иллюстрация (median).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"nums_label": "Zahlen",
		"nums_ph": "z. B. 1,2,2,3,4",
		"medianOut_label": "Median",
		"modeOut_label": "Modalwert",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Zahlenliste einfügen.",
		"formula_title": "Formel",
		"formula_body": "Zahlenliste einfügen.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: Median 2, Modus 2.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: Median 2, Modus 2.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Median- und Modalwert-Rechner",
		"disclaimer": "Nur zur Veranschaulichung (median).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 49,
	slug: "how-to-calculate-median",
	prefix: "tool_median",
	pageFile: "howToCalculateMedianPage",
	pageExport: "renderHowToCalculateMedianPage",
	nameZh: "中位数与众数计算器",
	ymyl: false,
	related: ["how-to-calculate-mean","how-to-calculate-standard-deviation"],
	anchor: "median",
	glyph: "M8 10h16v2H8zm2 6h12v6H10z",
	sampleHint: "1,2,2,3,4 → median 2 mode 2",
	titles: {
		en: "Median and Mode Calculator",
		zh: "中位数与众数计算器",
		es: "Calculadora de mediana y moda",
		ar: "حاسبة الوسيط والمنوال",
		pt: "Calculadora de mediana e moda",
		id: "Kalkulator median dan modus",
		fr: "Calculateur de médiane et mode",
		ja: "中央値と最頻値の計算ツール",
		ru: "Калькулятор медианы и моды",
		de: "Median- und Modalwert-Rechner",
	},
	descriptions: {
		en: "Find the median and mode of a number list. Sample: 1,2,2,3,4 → median 2, mode 2. Browser-only.",
		zh: "计算数字列表的中位数与众数。示例：1,2,2,3,4 → 中位数 2、众数 2。浏览器本地计算，数据不上传。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Calcula mediana y moda. Ejemplo: 1,2,2,3,4 → mediana 2, moda 2.",
		ar: "احسب الوسيط والمنوال. مثال: 1,2,2,3,4 → وسيط 2 ومنوال 2.",
		pt: "Calcule mediana e moda. Exemplo: 1,2,2,3,4 → mediana 2, moda 2.",
		id: "Hitung median dan modus. Contoh: 1,2,2,3,4 → median 2, modus 2.",
		fr: "Calculez médiane et mode. Exemple : 1,2,2,3,4 → médiane 2, mode 2.",
		ja: "数値リストの中央値と最頻値を計算します。例：1,2,2,3,4 → 中央値2、最頻値2。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Считайте медиану и моду. Пример: 1,2,2,3,4 → медиана 2, мода 2.",
		de: "Median und Modalwert. Beispiel: 1,2,2,3,4 → Median 2, Modus 2.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "nums",
	    "type": "textarea",
	    "labelKey": "nums_label",
	    "phKey": "nums_ph",
	    "rows": 4
	  }
	],
	results: [
	  {
	    "id": "medianOut",
	    "labelKey": "medianOut_label"
	  },
	  {
	    "id": "modeOut",
	    "labelKey": "modeOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Median"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Mode_(statistics)"
	  }
	],
	computeJs: `
        var raw=String(numsEl.value||'');
        var parts=raw.split(/[\s,;]+/).map(function(s){return s.trim();}).filter(Boolean);
        var xs=parts.map(parseFloat);
        if(!xs.length||xs.some(function(x){return !Number.isFinite(x);})) return {ok:false,error:msgErr};
        var sorted=xs.slice().sort(function(a,b){return a-b;});
        var n=sorted.length, median;
        if(n%2===1) median=sorted[(n-1)/2];
        else median=(sorted[n/2-1]+sorted[n/2])/2;
        var freq={}, best=sorted[0], bestC=0;
        for(var i=0;i<n;i++){
          var v=sorted[i];
          freq[v]=(freq[v]||0)+1;
          if(freq[v]>bestC||(freq[v]===bestC&&v<best)){ bestC=freq[v]; best=v; }
        }
        return {ok:true, values:{ medianOut:fmt(median), modeOut:fmt(best) }};
`,
	sampleJs: `
        numsEl.value='1,2,2,3,4';
`,
};
