/**
 * §12 #59 how-to-calculate-ohms-law
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"V_label": "Voltage V",
		"V_ph": "e.g. 12",
		"I_label": "Current I",
		"I_ph": "e.g. 2",
		"rOut_label": "Resistance R",
		"pOut_label": "Power P",
		"result_note": "R = V/I; P = V×I (solve R from V and I).",
		"err_generic": "Enter finite V and I with I ≠ 0.",
		"how_title": "How it works",
		"how_body": "Enter voltage and current. This mode solves resistance and also shows power.",
		"formula_title": "Formula",
		"formula_body": "R=V/I; P=VI. Notes:",
		"formula_item_1": "Units must be consistent (e.g., volts and amperes → ohms, watts).",
		"formula_item_2": "Ideal DC form only.",
		"formula_item_3": "Pair with density / velocity tools.",
		"example_title": "Example",
		"example": "Example: V=12, I=2 → R=6, P=24.",
		"usecases_title": "When to use it",
		"usecase_1": "Electronics homework.",
		"usecase_2": "Quick bench check.",
		"usecase_3": "Compare related physics tools.",
		"faq_q1": "Sample?",
		"faq_a1": "12 V / 2 A → 6 Ω, 24 W.",
		"faq_q2": "AC?",
		"faq_a2": "Not modeled.",
		"faq_q3": "I=0?",
		"faq_a3": "Rejected.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Ohm's law",
		"disclaimer": "Educational Ohm's law only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — Ohm's law",
		"ref_b_label": "Wikipedia — Electric power",
	}),
	zh: withBtns("zh", {
		"V_label": "电压 V",
		"V_ph": "例如 12",
		"I_label": "电流 I",
		"I_ph": "例如 2",
		"rOut_label": "电阻 R",
		"pOut_label": "功率 P",
		"result_note": "结果按欧姆定律公式在浏览器本地计算。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算欧姆定律。",
		"formula_title": "公式",
		"formula_body": "欧姆定律相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：V=12、I=2 → R=6、P=24。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：V=12、I=2 → R=6、P=24。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "欧姆定律",
		"disclaimer": "结果仅为欧姆定律学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"V_label": "Voltaje V",
		"V_ph": "p. ej. 12",
		"I_label": "Corriente I",
		"I_ph": "p. ej. 2",
		"rOut_label": "Resistencia R",
		"pOut_label": "Potencia P",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce V e I.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce V e I.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: R=6, P=24.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: R=6, P=24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de la ley de Ohm",
		"disclaimer": "Solo ilustración educativa (Ohm's law).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"V_label": "الجهد V",
		"V_ph": "مثال 12",
		"I_label": "التيار I",
		"I_ph": "مثال 2",
		"rOut_label": "المقاومة R",
		"pOut_label": "القدرة P",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل V و I.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل V و I.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: R=6 و P=24.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: R=6 و P=24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة قانون أوم",
		"disclaimer": "توضيح تعليمي فقط (Ohm's law).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"V_label": "Tensão V",
		"V_ph": "ex. 12",
		"I_label": "Corrente I",
		"I_ph": "ex. 2",
		"rOut_label": "Resistência R",
		"pOut_label": "Potência P",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe V e I.",
		"formula_title": "Fórmula",
		"formula_body": "Informe V e I.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: R=6, P=24.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: R=6, P=24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora da lei de Ohm",
		"disclaimer": "Apenas ilustração educativa (Ohm's law).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"V_label": "Tegangan V",
		"V_ph": "mis. 12",
		"I_label": "Arus I",
		"I_ph": "mis. 2",
		"rOut_label": "Hambatan R",
		"pOut_label": "Daya P",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi V dan I.",
		"formula_title": "Rumus",
		"formula_body": "Isi V dan I.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: R=6, P=24.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: R=6, P=24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator hukum Ohm",
		"disclaimer": "Hanya ilustrasi edukatif (Ohm's law).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"V_label": "Tension V",
		"V_ph": "ex. 12",
		"I_label": "Courant I",
		"I_ph": "ex. 2",
		"rOut_label": "Résistance R",
		"pOut_label": "Puissance P",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez V et I.",
		"formula_title": "Formule",
		"formula_body": "Saisissez V et I.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : R=6, P=24.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : R=6, P=24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de la loi d’Ohm",
		"disclaimer": "Illustration éducative (Ohm's law) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"V_label": "電圧 V",
		"V_ph": "例 12",
		"I_label": "電流 I",
		"I_ph": "例 2",
		"rOut_label": "抵抗 R",
		"pOut_label": "電力 P",
		"result_note": "オームの法則の公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れてオームの法則を計算します。",
		"formula_title": "計算式",
		"formula_body": "オームの法則の式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：V=12、I=2 → R=6、P=24。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：V=12、I=2 → R=6、P=24。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "オームの法則",
		"disclaimer": "オームの法則の学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"V_label": "Напряжение V",
		"V_ph": "напр. 12",
		"I_label": "Ток I",
		"I_ph": "напр. 2",
		"rOut_label": "Сопротивление R",
		"pOut_label": "Мощность P",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите V и I.",
		"formula_title": "Формула",
		"formula_body": "Введите V и I.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: R=6, P=24.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: R=6, P=24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор закона Ома",
		"disclaimer": "Только учебная иллюстрация (Ohm's law).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"V_label": "Spannung V",
		"V_ph": "z. B. 12",
		"I_label": "Strom I",
		"I_ph": "z. B. 2",
		"rOut_label": "Widerstand R",
		"pOut_label": "Leistung P",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "V und I eingeben.",
		"formula_title": "Formel",
		"formula_body": "V und I eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: R=6, P=24.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: R=6, P=24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Ohmsches Gesetz — Widerstand und Leistung",
		"disclaimer": "Nur zur Veranschaulichung (Ohm's law).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 59,
	slug: "how-to-calculate-ohms-law",
	prefix: "tool_ohms_law",
	pageFile: "howToCalculateOhmsLawPage",
	pageExport: "renderHowToCalculateOhmsLawPage",
	nameZh: "欧姆定律计算器",
	ymyl: false,
	related: ["how-to-calculate-density","how-to-calculate-velocity"],
	anchor: "ohms-law",
	glyph: "M6 16h20M10 10v12M22 10v12",
	sampleHint: "V=12 I=2 → R=6 P=24",
	titles: {
		en: "Ohm’s Law Calculator — Resistance and Power",
		zh: "欧姆定律计算器 — 电阻与功率",
		es: "Calculadora de la ley de Ohm",
		ar: "حاسبة قانون أوم",
		pt: "Calculadora da lei de Ohm",
		id: "Kalkulator hukum Ohm",
		fr: "Calculateur de la loi d’Ohm",
		ja: "オームの法則 — 抵抗と電力",
		ru: "Калькулятор закона Ома",
		de: "Ohmsches Gesetz — Widerstand und Leistung",
	},
	descriptions: {
		en: "Solve resistance R=V/I and power P=VI from voltage and current. Sample: V=12, I=2 → R=6, P=24. Browser-only.",
		zh: "由电压与电流求电阻 R=V/I 与功率 P=VI。示例：V=12、I=2 → R=6、P=24。浏览器本地计算。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Calcula R=V/I y P=VI. Ejemplo: V=12, I=2 → R=6, P=24.",
		ar: "احسب R=V/I و P=VI. مثال: V=12 و I=2 → R=6 و P=24.",
		pt: "Calcule R=V/I e P=VI. Exemplo: V=12, I=2 → R=6, P=24.",
		id: "Hitung R=V/I dan P=VI. Contoh: V=12, I=2 → R=6, P=24.",
		fr: "Calculez R=V/I et P=VI. Exemple : V=12, I=2 → R=6, P=24.",
		ja: "電圧と電流から抵抗R=V/Iと電力P=VIを求めます。例：V=12、I=2 → R=6、P=24。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Считайте R=V/I и P=VI. Пример: V=12, I=2 → R=6, P=24.",
		de: "R=V/I und P=VI. Beispiel: V=12, I=2 → R=6, P=24.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "V",
	    "type": "number",
	    "half": true,
	    "labelKey": "V_label",
	    "phKey": "V_ph"
	  },
	  {
	    "id": "I",
	    "type": "number",
	    "half": true,
	    "labelKey": "I_label",
	    "phKey": "I_ph"
	  }
	],
	results: [
	  {
	    "id": "rOut",
	    "labelKey": "rOut_label"
	  },
	  {
	    "id": "pOut",
	    "labelKey": "pOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Ohm%27s_law"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Electric_power"
	  }
	],
	computeJs: `
        var V=parseFloat(VEl.value), I=parseFloat(IEl.value);
        if(!Number.isFinite(V)||!Number.isFinite(I)||I===0) return {ok:false,error:msgErr};
        return {ok:true, values:{ rOut:fmt(V/I), pOut:fmt(V*I) }};
`,
	sampleJs: `
        VEl.value='12';
        IEl.value='2';
`,
};
