/**
 * §12 #58 how-to-calculate-one-rep-max
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"weight_label": "Weight",
		"weight_ph": "e.g. 100",
		"reps_label": "Reps",
		"reps_ph": "e.g. 5",
		"ormOut_label": "Estimated 1RM",
		"result_note": "Epley: 1RM ≈ weight × (1 + reps/30). Warm up; do not max on a rough estimate.",
		"err_generic": "Enter weight > 0 and integer reps ≥ 1 (typically ≤ 10 for this estimate).",
		"how_title": "How it works",
		"how_body": "Enter a submaximal weight and successful reps. Treat the result as a classroom estimate, not a prescription.",
		"formula_title": "Formula",
		"formula_body": "1RM ≈ w(1+r/30). Notes:",
		"formula_item_1": "Accuracy falls as reps get high.",
		"formula_item_2": "Stop if form breaks — safety first.",
		"formula_item_3": "Pair with pace / body-fat educational tools.",
		"example_title": "Example",
		"example": "Example: w=100, reps=5 → 100×(1+5/30)=116.67.",
		"usecases_title": "When to use it",
		"usecase_1": "Classroom strength math.",
		"usecase_2": "Rough program sketch.",
		"usecase_3": "Compare related fitness tools.",
		"faq_q1": "Sample?",
		"faq_a1": "100×5 → ≈116.67.",
		"faq_q2": "Safe to test 1RM?",
		"faq_a2": "Not advice — use care and coaching.",
		"faq_q3": "Other formulas?",
		"faq_a3": "This page uses Epley only.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "One-rep max (Epley)",
		"disclaimer": "Educational one-rep max safety estimate only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — One-repetition maximum",
		"ref_b_label": "Wikipedia — Strength training",
	}),
	zh: withBtns("zh", {
		"weight_label": "重量",
		"weight_ph": "例如 100",
		"reps_label": "次数",
		"reps_ph": "例如 5",
		"ormOut_label": "估算 1RM",
		"result_note": "Epley：1RM≈重量×(1+次数/30)。热身；勿把粗估当极限测试。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算一次最大重量。",
		"formula_title": "公式",
		"formula_body": "一次最大重量相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：100×5 → 约 116.67。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：100×5 → 约 116.67。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "一次最大重量",
		"disclaimer": "结果仅为一次最大重量安全估算学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"weight_label": "Peso",
		"weight_ph": "p. ej. 100",
		"reps_label": "Reps",
		"reps_ph": "p. ej. 5",
		"ormOut_label": "1RM estimado",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce peso y reps.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce peso y reps.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: ≈116.67.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: ≈116.67.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de 1RM (Epley)",
		"disclaimer": "Solo ilustración educativa (one-rep max safety estimate).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"weight_label": "الوزن",
		"weight_ph": "مثال 100",
		"reps_label": "تكرارات",
		"reps_ph": "مثال 5",
		"ormOut_label": "1RM تقديري",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل الوزن والتكرارات.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل الوزن والتكرارات.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: ≈116.67.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: ≈116.67.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة أقصى تكرار واحد (Epley)",
		"disclaimer": "توضيح تعليمي فقط (one-rep max safety estimate).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"weight_label": "Peso",
		"weight_ph": "ex. 100",
		"reps_label": "Repetições",
		"reps_ph": "ex. 5",
		"ormOut_label": "1RM estimado",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe peso e reps.",
		"formula_title": "Fórmula",
		"formula_body": "Informe peso e reps.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: ≈116.67.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: ≈116.67.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de 1RM (Epley)",
		"disclaimer": "Apenas ilustração educativa (one-rep max safety estimate).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"weight_label": "Berat",
		"weight_ph": "mis. 100",
		"reps_label": "Repetisi",
		"reps_ph": "mis. 5",
		"ormOut_label": "1RM perkiraan",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi berat dan repetisi.",
		"formula_title": "Rumus",
		"formula_body": "Isi berat dan repetisi.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: ≈116.67.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: ≈116.67.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator 1RM (Epley)",
		"disclaimer": "Hanya ilustrasi edukatif (one-rep max safety estimate).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"weight_label": "Charge",
		"weight_ph": "ex. 100",
		"reps_label": "Répétitions",
		"reps_ph": "ex. 5",
		"ormOut_label": "1RM estimé",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez charge et reps.",
		"formula_title": "Formule",
		"formula_body": "Saisissez charge et reps.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : ≈116.67.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : ≈116.67.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de 1RM (Epley)",
		"disclaimer": "Illustration éducative (one-rep max safety estimate) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"weight_label": "重量",
		"weight_ph": "例 100",
		"reps_label": "回数",
		"reps_ph": "例 5",
		"ormOut_label": "推定1RM",
		"result_note": "Epley：1RM≈重量×(1+回数/30)。ウォームアップを。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れて1RMを計算します。",
		"formula_title": "計算式",
		"formula_body": "1RMの式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：100×5 → 約116.67。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：100×5 → 約116.67。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "1RM",
		"disclaimer": "1RMの安全な見積もりの学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"weight_label": "Вес",
		"weight_ph": "напр. 100",
		"reps_label": "Повторы",
		"reps_ph": "напр. 5",
		"ormOut_label": "Оценка 1ПМ",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите вес и повторы.",
		"formula_title": "Формула",
		"formula_body": "Введите вес и повторы.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: ≈116.67.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: ≈116.67.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор 1ПМ (Epley)",
		"disclaimer": "Только учебная иллюстрация (one-rep max safety estimate).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"weight_label": "Gewicht",
		"weight_ph": "z. B. 100",
		"reps_label": "Wdhl.",
		"reps_ph": "z. B. 5",
		"ormOut_label": "Geschätztes 1RM",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Gewicht und Wdhl. eingeben.",
		"formula_title": "Formel",
		"formula_body": "Gewicht und Wdhl. eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: ≈116.67.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: ≈116.67.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "1RM-Rechner (Epley)",
		"disclaimer": "Nur zur Veranschaulichung (one-rep max safety estimate).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 58,
	slug: "how-to-calculate-one-rep-max",
	prefix: "tool_one_rep_max",
	pageFile: "howToCalculateOneRepMaxPage",
	pageExport: "renderHowToCalculateOneRepMaxPage",
	nameZh: "一次最大重量计算器",
	ymyl: false,
	related: ["how-to-calculate-pace","how-to-calculate-body-fat"],
	anchor: "one-rep-max",
	glyph: "M8 14h16v4H8zM12 8h8v4h-8z",
	sampleHint: "Epley: 100×5 → 116.67",
	titles: {
		en: "One-Rep Max Calculator (Epley)",
		zh: "一次最大重量计算器（Epley）",
		es: "Calculadora de 1RM (Epley)",
		ar: "حاسبة أقصى تكرار واحد (Epley)",
		pt: "Calculadora de 1RM (Epley)",
		id: "Kalkulator 1RM (Epley)",
		fr: "Calculateur de 1RM (Epley)",
		ja: "1RM計算ツール（Epley）",
		ru: "Калькулятор 1ПМ (Epley)",
		de: "1RM-Rechner (Epley)",
	},
	descriptions: {
		en: "Estimate one-rep max with the Epley formula: 1RM ≈ w×(1+reps/30). Sample: 100 for 5 reps → ≈116.67. Educational estimate with a safety note — not coaching advice.",
		zh: "用 Epley 公式估算 1RM：1RM ≈ w×(1+次数/30)。示例：100×5 次 → 约 116.67。含安全提示的学习估算，非训练指导；浏览器本地计算。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Estima 1RM con Epley: w×(1+reps/30). Ejemplo: 100×5 → ≈116.67. Solo educativo.",
		ar: "قدّر 1RM بصيغة Epley. مثال: 100×5 → ≈116.67. تعليمي فقط.",
		pt: "Estime 1RM com Epley. Exemplo: 100×5 → ≈116.67. Apenas educativo.",
		id: "Perkirakan 1RM dengan Epley. Contoh: 100×5 → ≈116.67. Edukatif saja.",
		fr: "Estimez le 1RM avec Epley. Exemple : 100×5 → ≈116.67. Éducatif seulement.",
		ja: "Epley式で1RMを見積もります：w×(1+回/30)。例：100を5回 → 約116.67。安全注意付きの学習用であり指導ではありません。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Оцените 1ПМ по Эпли. Пример: 100×5 → ≈116.67. Только учебно.",
		de: "1RM nach Epley schätzen. Beispiel: 100×5 → ≈116.67. Nur Bildung.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "weight",
	    "type": "number",
	    "half": true,
	    "labelKey": "weight_label",
	    "phKey": "weight_ph"
	  },
	  {
	    "id": "reps",
	    "type": "number",
	    "half": true,
	    "labelKey": "reps_label",
	    "phKey": "reps_ph"
	  }
	],
	results: [
	  {
	    "id": "ormOut",
	    "labelKey": "ormOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/One-repetition_maximum"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Strength_training"
	  }
	],
	computeJs: `
        var w=parseFloat(weightEl.value), reps=parseFloat(repsEl.value);
        if(!(w>0)||!Number.isInteger(reps)||reps<1) return {ok:false,error:msgErr};
        var orm=w*(1+reps/30);
        return {ok:true, values:{ ormOut:fmt(orm) }};
`,
	sampleJs: `
        weightEl.value='100';
        repsEl.value='5';
`,
};
