/**
 * §12 #23 how-to-calculate-p-value 工具定义（十语独立 UI）。
 */
export default {
	seq: 23,
	slug: 'how-to-calculate-p-value',
	prefix: 'tool_p_value',
	nameZh: 'p 值计算器',
	category: 'calculator',
	ymyl: false,
	pageFile: 'howToCalculatePValuePage',
	pageExport: 'renderHowToCalculatePValuePage',
	anchor: 'p-value',
	related: ['how-to-calculate-standard-deviation', 'how-to-calculate-confidence-interval'],
	glyph: 'M8 22V10M16 22V6M24 22V14M6 24h20',
	titles: {
		en: "P-Value Calculator — How to Calculate a P-Value",
		zh: "p 值计算器 — 如何计算 p 值",
		es: "Calculadora de valor p — Cómo calcular un p-valor",
		ar: "حاسبة قيمة p — كيفية حساب القيمة الاحتمالية",
		pt: "Calculadora de valor-p — Como calcular um p-valor",
		id: "Kalkulator nilai-p — Cara menghitung p-value",
		fr: "Calculateur de p-valeur — Comment calculer une p-value",
		ja: "p値計算ツール — p値の求め方",
		ru: "Калькулятор p-value — Как рассчитать p-значение",
		de: "p-Wert-Rechner — p-Wert berechnen"
	},
	descriptions: {
		en: "Two-tailed normal p-value from a z-score via an erfc approximation. Example: z = 1.96 → two-tailed p ≈ 0.05. States standard-normal and two-tail assumptions clearly. Runs in your browser for coursework and quick learning checks.",
		zh: "由 z 分数用 erfc 近似求双侧正态 p 值。示例：z = 1.96 → 双侧 p ≈ 0.05。写清标准正态与双侧假设。浏览器内计算，适合作业与快速对照学习。 Educational illustration of the two-tailed normal tail probability under stated assumptions.",
		es: "Valor p normal a dos colas desde un z con aproximación erfc. Ejemplo: z = 1,96 → p ≈ 0,05. Deja claros los supuestos de normal estándar y dos colas. En el navegador, para clase y comprobaciones rápidas de aprendizaje.",
		ar: "قيمة p طبيعية ثنائية الطرف من درجة z بتقريب erfc. مثال: z = 1.96 → p ≈ 0.05. يوضح فرضيات الطبيعي المعياري والطرفيْن. في المتصفح للتعلّم والتحقق السريع.",
		pt: "Valor-p normal bicaudal a partir de um z com aproximação erfc. Exemplo: z = 1,96 → p ≈ 0,05. Deixa claros os pressupostos de normal padrão e duas caudas. No navegador, para estudo e checagens rápidas.",
		id: "Nilai-p normal dua sisi dari skor z dengan aproksimasi erfc. Contoh: z = 1,96 → p ≈ 0,05. Menuliskan asumsi normal baku dan dua sisi. Di browser untuk belajar dan cek cepat.",
		fr: "p-valeur normale bilatérale à partir d’un z via approximation erfc. Exemple : z = 1,96 → p ≈ 0,05. Hypothèses normale standard et deux queues explicites. Dans le navigateur, pour cours et vérifications rapides.",
		ja: "z スコアから erfc 近似で両側正規の p 値を求めます。例：z = 1.96 → 両側 p ≈ 0.05。標準正規と両側の前提を明示。ブラウザ内で、宿題やざっくり確認向けです。 Educational illustration of the two-tailed normal tail probability under stated assumptions.",
		ru: "Двустороннее нормальное p из z через аппроксимацию erfc. Пример: z = 1,96 → p ≈ 0,05. Явно указывает допущения стандартной нормали и двух хвостов. В браузере для учёбы и быстрой проверки.",
		de: "Zweiseitiger normaler p-Wert aus einem z-Wert per erfc-Näherung. Beispiel: z = 1,96 → p ≈ 0,05. Macht Standardnormal- und zweiseitige Annahmen klar. Im Browser für Übungen und schnelle Lernchecks."
	},
	ui: {
		en: {
			calculate: "Calculate",
			sample: "Load sample",
			clear: "Clear",
			z_label: "Z-score",
			z_ph: "e.g. 1.96",
			pOut_label: "Two-tailed p-value",
			result_note: "Standard normal, two-tailed approximation for learning — not a full hypothesis-test suite.",
			err_generic: "Enter a finite z-score.",
			how_title: "How it works",
			how_body: "Enter a z-score from a standard normal test. The tool reports a two-tailed p-value using an erfc approximation of the normal tail. Assumptions stay visible: standard normal sampling model and both tails. Runs in your browser for coursework and quick checks.",
			formula_title: "Formula and assumptions",
			formula_body: "Two-tailed p ≈ erfc(|z| / √2) under a standard normal. Keep these limits in mind:",
			formula_item_1: "Assumes a continuous standard normal z (mean 0, variance 1), not a t, χ², or discrete exact test.",
			formula_item_2: "Two-tailed only on this page — both sides of ±|z| are counted.",
			formula_item_3: "Uses a numerical erfc approximation; results are for learning, not certified statistical software.",
			formula_item_4: "A small p-value does not by itself prove a scientific claim.",
			example_title: "Example",
			example: "Example: z = 1.96 → two-tailed p ≈ erfc(1.96 / √2) ≈ 0.05 (about 0.049996 with this approximation).",
			usecases_title: "When to use it",
			usecase_1: "Homework: convert a known z to an approximate two-tailed p.",
			usecase_2: "Quick check after computing z from a mean and SD elsewhere.",
			usecase_3: "Compare the familiar 1.96 ↔ 0.05 rule of thumb with a numeric output.",
			faq_q1: "Is this one-tailed or two-tailed?",
			faq_a1: "Two-tailed. The reported p covers both sides beyond ±|z| under a standard normal.",
			faq_q2: "What distribution is assumed?",
			faq_a2: "A continuous standard normal for z. It is not a t-test, χ², or exact binomial calculator.",
			faq_q3: "Why is z = 1.96 close to 0.05?",
			faq_a3: "Under a standard normal, |z| ≈ 1.96 is the familiar critical value for a two-tailed 5% test; the page’s erfc approximation returns about 0.05.",
			faq_q4: "Does a small p prove the alternative hypothesis?",
			faq_a4: "No. A p-value is a tail probability under stated assumptions, not automatic proof of a claim.",
			disclaimer: "Results are educational approximations under a standard-normal two-tailed model and are not a substitute for statistical software, study design, or professional analysis.",
			references: "Wikipedia p-value and normal distribution articles; complementary error function for normal tails.",
			ref_pvalue_label: "Wikipedia — P-value",
			ref_normal_label: "Wikipedia — Normal distribution",
			article: "Compute a two-tailed normal p-value from a z-score with an erfc approximation. States standard-normal and two-tail assumptions for learning."
		},
		zh: {
			calculate: "计算",
			sample: "加载样例",
			clear: "清空",
			z_label: "z 分数",
			z_ph: "例如 1.96",
			pOut_label: "双侧 p 值",
			result_note: "标准正态、双侧近似，供学习对照——不是完整假设检验套件。",
			err_generic: "请输入有限的 z 分数。",
			how_title: "怎么用",
			how_body: "输入标准正态检验得到的 z 分数。工具用 erfc 近似给出双侧 p 值，并写明假设：标准正态抽样模型、计入两侧尾部。计算在浏览器内完成，适合作业与快速核对。",
			formula_title: "公式与假设",
			formula_body: "双侧 p ≈ erfc(|z| / √2)（标准正态）。请注意：",
			formula_item_1: "假定连续标准正态 z（均值 0、方差 1），不是 t、χ² 或精确离散检验。",
			formula_item_2: "本页只做双侧：计入 ±|z| 外侧两侧。",
			formula_item_3: "使用数值 erfc 近似，供学习，不能当作认证统计软件。",
			formula_item_4: "p 值小并不自动证明科学结论成立。",
			example_title: "示例",
			example: "示例：z = 1.96 → 双侧 p ≈ erfc(1.96 / √2) ≈ 0.05（本近似约 0.049996）。",
			usecases_title: "适合什么场景",
			usecase_1: "作业：已知 z，求近似双侧 p。",
			usecase_2: "在别处算完均值与标准差得到 z 后，快速对照 p。",
			usecase_3: "核对常见的 1.96 ↔ 0.05 经验规则。",
			faq_q1: "这是单侧还是双侧？",
			faq_a1: "双侧。报告的 p 覆盖标准正态下 ±|z| 外侧两侧。",
			faq_q2: "假定什么分布？",
			faq_a2: "连续标准正态。不是 t 检验、χ² 或精确二项计算器。",
			faq_q3: "为什么 z=1.96 接近 0.05？",
			faq_a3: "在标准正态下，|z|≈1.96 是双侧 5% 检验的常用临界值；本页 erfc 近似约得到 0.05。",
			faq_q4: "p 值小就能证明备择假设吗？",
			faq_a4: "不能。p 值是在给定假设下的尾概率，不是自动证明。",
			disclaimer: "结果是在标准正态双侧模型下的教育近似，不能替代统计软件、研究设计或专业分析。",
			references: "维基百科 p 值与正态分布条目；用互补误差函数描述正态尾部。",
			ref_pvalue_label: "维基百科 — P 值",
			ref_normal_label: "维基百科 — 正态分布",
			article: "由 z 分数用 erfc 近似求双侧正态 p 值，并写清标准正态与双侧假设，供学习使用。"
		},
		es: {
			calculate: "Calcular",
			sample: "Cargar ejemplo",
			clear: "Limpiar",
			z_label: "Puntuación z",
			z_ph: "p. ej. 1.96",
			pOut_label: "Valor p bilaterial",
			result_note: "Aproximación normal estándar a dos colas para aprender — no es un paquete completo de contraste.",
			err_generic: "Introduce un valor z finito.",
			how_title: "Cómo funciona",
			how_body: "Introduce un z de un contraste normal estándar. La herramienta estima el valor p a dos colas con una aproximación erfc. Deja claras las hipótesis: modelo normal estándar y ambas colas. En el navegador, para clase y comprobaciones rápidas.",
			formula_title: "Fórmula y supuestos",
			formula_body: "p a dos colas ≈ erfc(|z| / √2) bajo normal estándar. Límites:",
			formula_item_1: "Asume z normal estándar continuo, no t, χ² ni prueba exacta discreta.",
			formula_item_2: "Solo dos colas en esta página.",
			formula_item_3: "Usa una aproximación numérica erfc; para aprendizaje, no software certificado.",
			formula_item_4: "Un p pequeño no prueba por sí solo una afirmación científica.",
			example_title: "Ejemplo",
			example: "Ejemplo: z = 1,96 → p a dos colas ≈ 0,05 (cerca de 0,049996 con esta aproximación).",
			usecases_title: "Cuándo usarlo",
			usecase_1: "Deberes: pasar de un z conocido a un p aproximado a dos colas.",
			usecase_2: "Comprobar tras calcular z a partir de media y desviación.",
			usecase_3: "Contrastar la regla 1,96 ↔ 0,05 con un número concreto.",
			faq_q1: "¿Qué distribución se asume?",
			faq_a1: "Normal estándar continua. No es una calculadora t, χ² o binomial exacta.",
			faq_q2: "¿Una o dos colas?",
			faq_a2: "Dos colas: cuenta ambos lados más allá de ±|z|.",
			faq_q3: "¿Por qué z=1,96 ≈ 0,05?",
			faq_a3: "Es el valor crítico habitual al 5% a dos colas; la aproximación erfc da cerca de 0,05.",
			faq_q4: "¿Un p pequeño demuestra la alternativa?",
			faq_a4: "No. Es una probabilidad de cola bajo supuestos, no una prueba automática.",
			disclaimer: "Resultados educativos bajo un modelo normal estándar a dos colas; no sustituyen software estadístico ni análisis profesional.",
			references: "Artículos de Wikipedia sobre valor p y distribución normal; función de error complementaria.",
			ref_pvalue_label: "Wikipedia — Valor p",
			ref_normal_label: "Wikipedia — Distribución normal",
			article: "Calcula un valor p normal a dos colas desde un z con aproximación erfc, dejando claros los supuestos."
		},
		ar: {
			calculate: "احسب",
			sample: "تحميل مثال",
			clear: "مسح",
			z_label: "درجة z",
			z_ph: "مثال 1.96",
			pOut_label: "قيمة p ثنائية الطرف",
			result_note: "تقريب طبيعي معياري ثنائي الطرف للتعلّم — ليست حزمة اختبار فرضيات كاملة.",
			err_generic: "أدخل درجة z محدودة.",
			how_title: "طريقة الاستخدام",
			how_body: "أدخل درجة z من اختبار طبيعي معياري. تحسب الأداة قيمة p ثنائية الطرف بتقريب erfc مع فرضيات واضحة: نموذج طبيعي معياري وطرفان. في المتصفح للتعلّم والتحقق السريع.",
			formula_title: "الصيغة والافتراضات",
			formula_body: "p ثنائية ≈ erfc(|z| / √2) تحت الطبيعي المعياري. حدود:",
			formula_item_1: "يفترض z طبيعي معياري مستمر، لا t أو χ² أو اختبار دقيق متقطع.",
			formula_item_2: "ثنائي الطرف فقط في هذه الصفحة.",
			formula_item_3: "يستخدم تقريب erfc عدديًا للتعلّم لا كبرنامج معتمد.",
			formula_item_4: "قيمة p الصغيرة لا تثبت وحدها ادعاءً علميًا.",
			example_title: "مثال",
			example: "مثال: z = 1.96 → p ثنائية ≈ 0.05 (حوالي 0.049996 بهذا التقريب).",
			usecases_title: "متى تستخدمه",
			usecase_1: "واجبات: تحويل z معروف إلى p تقريبية ثنائية.",
			usecase_2: "تحقق سريع بعد حساب z من متوسط وانحراف.",
			usecase_3: "مقارنة قاعدة 1.96 ↔ 0.05 مع ناتج رقمي.",
			faq_q1: "أحادي أم ثنائي الطرف؟",
			faq_a1: "ثنائي الطرف؛ يشمل الجانبين خارج ±|z|.",
			faq_q2: "ما التوزيع المفترض؟",
			faq_a2: "طبيعي معياري مستمر. ليست حاسبة t أو χ².",
			faq_q3: "لماذا z=1.96 قريبة من 0.05؟",
			faq_a3: "قيمة حرجة شائعة لاختبار 5% ثنائي؛ تقريب erfc يعطي نحو 0.05.",
			faq_q4: "هل p الصغيرة تثبت الفرض البديل؟",
			faq_a4: "لا. إنها احتمال ذيل تحت افتراضات، وليست إثباتًا تلقائيًا.",
			disclaimer: "نتائج تعليمية تحت نموذج طبيعي معياري ثنائي الطرف ولا تغني عن برمجيات إحصائية أو تحليل متخصص.",
			references: "مقالات ويكيبيديا عن قيمة p والتوزيع الطبيعي؛ دالة الخطأ التكميلية.",
			ref_pvalue_label: "ويكيبيديا — قيمة p",
			ref_normal_label: "ويكيبيديا — التوزيع الطبيعي",
			article: "احسب قيمة p طبيعية ثنائية الطرف من درجة z بتقريب erfc مع فرضيات واضحة للتعلّم."
		},
		pt: {
			calculate: "Calcular",
			sample: "Carregar exemplo",
			clear: "Limpar",
			z_label: "Escore z",
			z_ph: "ex.: 1.96",
			pOut_label: "Valor-p bicaudal",
			result_note: "Aproximação normal padrão bicaudal para estudo — não é um suite completo de testes.",
			err_generic: "Informe um z finito.",
			how_title: "Como funciona",
			how_body: "Digite um z de um teste normal padrão. A ferramenta estima o valor-p bicaudal com aproximação erfc e deixa claros os pressupostos: modelo normal padrão e duas caudas. No navegador, para aula e checagens rápidas.",
			formula_title: "Fórmula e pressupostos",
			formula_body: "p bicaudal ≈ erfc(|z| / √2) sob normal padrão. Limites:",
			formula_item_1: "Assume z normal padrão contínuo, não t, χ² nem teste exato discreto.",
			formula_item_2: "Apenas bicaudal nesta página.",
			formula_item_3: "Usa aproximação numérica erfc; para aprendizado, não software certificado.",
			formula_item_4: "Um p pequeno não prova sozinho uma afirmação científica.",
			example_title: "Exemplo",
			example: "Exemplo: z = 1,96 → p bicaudal ≈ 0,05 (cerca de 0,049996 nesta aproximação).",
			usecases_title: "Quando usar",
			usecase_1: "Tarefa: converter um z conhecido em p bicaudal aproximado.",
			usecase_2: "Conferir após obter z a partir de média e desvio.",
			usecase_3: "Comparar a regra 1,96 ↔ 0,05 com um número.",
			faq_q1: "Qual distribuição é assumida?",
			faq_a1: "Normal padrão contínua. Não é calculadora t, χ² ou binomial exata.",
			faq_q2: "Uni ou bicaudal?",
			faq_a2: "Bicaudal: conta os dois lados além de ±|z|.",
			faq_q3: "Por que z=1,96 ≈ 0,05?",
			faq_a3: "Valor crítico habitual para 5% bicaudal; a erfc dá perto de 0,05.",
			faq_q4: "p pequeno prova a alternativa?",
			faq_a4: "Não. É probabilidade de cauda sob pressupostos, não prova automática.",
			disclaimer: "Resultados educacionais sob modelo normal padrão bicaudal; não substituem software estatístico nem análise profissional.",
			references: "Artigos da Wikipedia sobre valor-p e distribuição normal; função erro complementar.",
			ref_pvalue_label: "Wikipedia — Valor-p",
			ref_normal_label: "Wikipedia — Distribuição normal",
			article: "Calcule um valor-p normal bicaudal a partir de z com aproximação erfc e pressupostos explícitos."
		},
		id: {
			calculate: "Hitung",
			sample: "Muat contoh",
			clear: "Hapus",
			z_label: "Skor z",
			z_ph: "mis. 1.96",
			pOut_label: "Nilai-p dua sisi",
			result_note: "Perkiraan normal baku dua sisi untuk belajar — bukan suite uji hipotesis lengkap.",
			err_generic: "Masukkan skor z hingga.",
			how_title: "Cara kerja",
			how_body: "Masukkan skor z dari uji normal baku. Alat ini memperkirakan nilai-p dua sisi dengan aproksimasi erfc dan menuliskan asumsi: model normal baku serta kedua ekor. Di browser untuk tugas dan cek cepat.",
			formula_title: "Rumus dan asumsi",
			formula_body: "p dua sisi ≈ erfc(|z| / √2) di bawah normal baku. Batasan:",
			formula_item_1: "Mengasumsikan z normal baku kontinu, bukan t, χ², atau uji eksak diskret.",
			formula_item_2: "Hanya dua sisi di halaman ini.",
			formula_item_3: "Memakai aproksimasi erfc numerik untuk belajar, bukan perangkat lunak tersertifikasi.",
			formula_item_4: "p kecil tidak dengan sendirinya membuktikan klaim ilmiah.",
			example_title: "Contoh",
			example: "Contoh: z = 1,96 → p dua sisi ≈ 0,05 (sekitar 0,049996 dengan aproksimasi ini).",
			usecases_title: "Kapan dipakai",
			usecase_1: "PR: ubah z yang diketahui menjadi p dua sisi perkiraan.",
			usecase_2: "Cek cepat setelah menghitung z dari mean dan SD.",
			usecase_3: "Bandingkan aturan 1,96 ↔ 0,05 dengan angka.",
			faq_q1: "Satu sisi atau dua sisi?",
			faq_a1: "Dua sisi; mencakup kedua sisi di luar ±|z|.",
			faq_q2: "Distribusi apa yang diasumsikan?",
			faq_a2: "Normal baku kontinu. Bukan kalkulator t atau χ².",
			faq_q3: "Mengapa z=1,96 mendekati 0,05?",
			faq_a3: "Nilai kritis umum untuk uji 5% dua sisi; erfc memberi sekitar 0,05.",
			faq_q4: "Apakah p kecil membuktikan alternatif?",
			faq_a4: "Tidak. Itu peluang ekor di bawah asumsi, bukan bukti otomatis.",
			disclaimer: "Hasil edukasi di bawah model normal baku dua sisi; tidak menggantikan perangkat lunak statistik atau analisis profesional.",
			references: "Artikel Wikipedia tentang nilai-p dan distribusi normal; fungsi error komplementer.",
			ref_pvalue_label: "Wikipedia — Nilai-p",
			ref_normal_label: "Wikipedia — Distribusi normal",
			article: "Hitung nilai-p normal dua sisi dari skor z dengan aproksimasi erfc dan asumsi yang jelas."
		},
		fr: {
			calculate: "Calculer",
			sample: "Charger l’exemple",
			clear: "Effacer",
			z_label: "Score z",
			z_ph: "ex. 1.96",
			pOut_label: "p-valeur bilatérale",
			result_note: "Approximation normale centrée bilatérale pour apprendre — pas une suite complète de tests.",
			err_generic: "Saisissez un score z fini.",
			how_title: "Fonctionnement",
			how_body: "Entrez un z issu d’un test normal standard. L’outil estime la p-valeur bilatérale via une approximation erfc et rappelle les hypothèses : modèle normal standard et deux queues. Dans le navigateur, pour les cours et vérifications rapides.",
			formula_title: "Formule et hypothèses",
			formula_body: "p bilatérale ≈ erfc(|z| / √2) sous normale standard. Limites :",
			formula_item_1: "Suppose un z normal standard continu, pas un t, χ² ou test exact discret.",
			formula_item_2: "Bilatéral uniquement sur cette page.",
			formula_item_3: "Utilise une approximation numérique erfc ; pour l’apprentissage, pas un logiciel certifié.",
			formula_item_4: "Une petite p ne prouve pas à elle seule une affirmation scientifique.",
			example_title: "Exemple",
			example: "Exemple : z = 1,96 → p bilatérale ≈ 0,05 (environ 0,049996 avec cette approximation).",
			usecases_title: "Quand l’utiliser",
			usecase_1: "Devoir : convertir un z connu en p bilatérale approximative.",
			usecase_2: "Vérifier après avoir calculé z à partir d’une moyenne et d’un écart-type.",
			usecase_3: "Comparer la règle 1,96 ↔ 0,05 à un résultat numérique.",
			faq_q1: "Quelle distribution est supposée ?",
			faq_a1: "Normale standard continue. Ce n’est pas un calculateur t, χ² ou binomial exact.",
			faq_q2: "Unilatéral ou bilatéral ?",
			faq_a2: "Bilatéral : les deux côtés au-delà de ±|z|.",
			faq_q3: "Pourquoi z=1,96 ≈ 0,05 ?",
			faq_a3: "Valeur critique habituelle pour un test à 5 % bilatéral ; l’erfc donne près de 0,05.",
			faq_q4: "Une petite p prouve-t-elle l’alternative ?",
			faq_a4: "Non. C’est une probabilité de queue sous hypothèses, pas une preuve automatique.",
			disclaimer: "Résultats pédagogiques sous un modèle normal standard bilatéral ; ne remplacent pas un logiciel statistique ni une analyse professionnelle.",
			references: "Articles Wikipedia sur la p-valeur et la loi normale ; fonction d’erreur complémentaire.",
			ref_pvalue_label: "Wikipedia — Valeur p",
			ref_normal_label: "Wikipedia — Loi normale",
			article: "Calculez une p-valeur normale bilatérale à partir d’un z avec approximation erfc et hypothèses explicites."
		},
		ja: {
			calculate: "計算する",
			sample: "サンプル",
			clear: "クリア",
			z_label: "z スコア",
			z_ph: "例: 1.96",
			pOut_label: "両側 p 値",
			result_note: "標準正規・両側の近似です。学習用であり、完全な仮説検定ソフトではありません。",
			err_generic: "有限の z スコアを入力してください。",
			how_title: "使い方",
			how_body: "標準正規の検定で得た z を入れます。erfc 近似で両側 p 値を出し、前提（標準正規・両側）を明示します。ブラウザ内で、宿題やざっくり確認向けです。",
			formula_title: "式と前提",
			formula_body: "両側 p ≈ erfc(|z| / √2)（標準正規）。注意点：",
			formula_item_1: "連続の標準正規 z を仮定。t・χ²・離散の正確検定ではありません。",
			formula_item_2: "このページは両側のみ（±|z| の外側）。",
			formula_item_3: "数値 erfc 近似で、学習用であり認定ソフトではありません。",
			formula_item_4: "p が小さくても主張の自動証明にはなりません。",
			example_title: "例",
			example: "例：z = 1.96 → 両側 p ≈ 0.05（本近似では約 0.049996）。",
			usecases_title: "こんなときに",
			usecase_1: "既知の z から両側 p の近似を求める宿題。",
			usecase_2: "平均と標準偏差から z を出したあとの素早い確認。",
			usecase_3: "よく使う 1.96 ↔ 0.05 の目安を数値で確かめる。",
			faq_q1: "片側ですか、両側ですか？",
			faq_a1: "両側です。±|z| の外側両側を数えます。",
			faq_q2: "どの分布を仮定していますか？",
			faq_a2: "連続の標準正規です。t や χ² の計算機ではありません。",
			faq_q3: "なぜ z=1.96 が約 0.05 ですか？",
			faq_a3: "両側 5% 検定のよく使う臨界値で、erfc 近似も約 0.05 になります。",
			faq_q4: "p が小さいと対立仮説が証明されますか？",
			faq_a4: "いいえ。仮定の下での裾確率であり、自動証明ではありません。",
			disclaimer: "結果は標準正規・両側モデルの学習用近似であり、統計ソフトや専門分析の代わりにはなりません。",
			references: "Wikipedia の p値・正規分布；正規裾に対する相補誤差関数。",
			ref_pvalue_label: "Wikipedia — p値",
			ref_normal_label: "Wikipedia — 正規分布",
			article: "z スコアから erfc 近似で両側正規 p 値を求め、標準正規と両側の前提を明示します。"
		},
		ru: {
			calculate: "Рассчитать",
			sample: "Загрузить пример",
			clear: "Очистить",
			z_label: "Z-оценка",
			z_ph: "напр. 1.96",
			pOut_label: "Двустороннее p-значение",
			result_note: "Двусторонняя аппроксимация стандартного нормального для обучения — не полный пакет тестов.",
			err_generic: "Введите конечную z-оценку.",
			how_title: "Как пользоваться",
			how_body: "Введите z из стандартного нормального теста. Инструмент оценивает двустороннее p через аппроксимацию erfc и явно указывает допущения: стандартная нормаль и оба хвоста. В браузере — для учёбы и быстрой проверки.",
			formula_title: "Формула и допущения",
			formula_body: "Двустороннее p ≈ erfc(|z| / √2) при стандартной нормали. Ограничения:",
			formula_item_1: "Предполагается непрерывный стандартный нормальный z, не t, χ² и не точный дискретный тест.",
			formula_item_2: "На этой странице только двусторонний вариант.",
			formula_item_3: "Используется численная аппроксимация erfc; для обучения, не сертифицированное ПО.",
			formula_item_4: "Малое p само по себе не доказывает научное утверждение.",
			example_title: "Пример",
			example: "Пример: z = 1,96 → двустороннее p ≈ 0,05 (около 0,049996 в этой аппроксимации).",
			usecases_title: "Когда применять",
			usecase_1: "Домашнее задание: перевести известный z в приближённое двустороннее p.",
			usecase_2: "Быстрая проверка после расчёта z из среднего и СКО.",
			usecase_3: "Сверить правило 1,96 ↔ 0,05 с числом.",
			faq_q1: "Односторонний или двусторонний?",
			faq_a1: "Двусторонний: учитываются обе стороны за ±|z|.",
			faq_q2: "Какое распределение предполагается?",
			faq_a2: "Непрерывное стандартное нормальное. Это не калькулятор t или χ².",
			faq_q3: "Почему z=1,96 ≈ 0,05?",
			faq_a3: "Привычное критическое значение для двустороннего 5%; erfc даёт около 0,05.",
			faq_q4: "Малое p доказывает альтернативу?",
			faq_a4: "Нет. Это вероятность хвоста при допущениях, не автоматическое доказательство.",
			disclaimer: "Результаты учебные при стандартной нормальной двусторонней модели и не заменяют статистическое ПО или профессиональный анализ.",
			references: "Статьи Wikipedia о p-value и нормальном распределении; дополнительная функция ошибок.",
			ref_pvalue_label: "Wikipedia — P-value",
			ref_normal_label: "Wikipedia — Нормальное распределение",
			article: "Считайте двустороннее нормальное p из z через аппроксимацию erfc с явными допущениями."
		},
		de: {
			calculate: "Berechnen",
			sample: "Beispiel laden",
			clear: "Leeren",
			z_label: "Z-Wert",
			z_ph: "z. B. 1.96",
			pOut_label: "Zweiseitiger p-Wert",
			result_note: "Standardnormale zweiseitige Näherung zum Lernen — keine vollständige Test-Suite.",
			err_generic: "Bitte einen endlichen z-Wert eingeben.",
			how_title: "So funktioniert’s",
			how_body: "Geben Sie einen z-Wert aus einem standardnormalen Test ein. Das Tool schätzt den zweiseitigen p-Wert per erfc-Näherung und macht Annahmen sichtbar: Standardnormal und beide Seiten. Im Browser für Übungen und schnelle Checks.",
			formula_title: "Formel und Annahmen",
			formula_body: "Zweiseitiges p ≈ erfc(|z| / √2) unter Standardnormal. Grenzen:",
			formula_item_1: "Nimmt kontinuierliches standardnormales z an, kein t, χ² oder exakter diskreter Test.",
			formula_item_2: "Nur zweiseitig auf dieser Seite.",
			formula_item_3: "Nutzt eine numerische erfc-Näherung; zum Lernen, nicht zertifizierte Software.",
			formula_item_4: "Ein kleines p beweist allein keine wissenschaftliche Behauptung.",
			example_title: "Beispiel",
			example: "Beispiel: z = 1,96 → zweiseitiges p ≈ 0,05 (etwa 0,049996 mit dieser Näherung).",
			usecases_title: "Wann sinnvoll",
			usecase_1: "Hausaufgabe: bekannten z in ungefähres zweiseitiges p umrechnen.",
			usecase_2: "Schnellcheck nach Berechnung von z aus Mittelwert und SD.",
			usecase_3: "Die Faustregel 1,96 ↔ 0,05 mit einer Zahl vergleichen.",
			faq_q1: "Einseitig oder zweiseitig?",
			faq_a1: "Zweiseitig; beide Seiten jenseits von ±|z|.",
			faq_q2: "Welche Verteilung wird angenommen?",
			faq_a2: "Kontinuierliche Standardnormalverteilung. Kein t-/χ²-Rechner.",
			faq_q3: "Warum z=1,96 ≈ 0,05?",
			faq_a3: "Üblicher kritischer Wert für 5% zweiseitig; die erfc-Näherung liefert etwa 0,05.",
			faq_q4: "Beweist kleines p die Alternative?",
			faq_a4: "Nein. Es ist eine Schwanzwahrscheinlichkeit unter Annahmen, kein automatischer Beweis.",
			disclaimer: "Ergebnisse sind Lernnäherungen unter einem standardnormalen zweiseitigen Modell und ersetzen keine Statistiksoftware oder professionelle Analyse.",
			references: "Wikipedia-Artikel zu p-Wert und Normalverteilung; komplementäre Fehlerfunktion.",
			ref_pvalue_label: "Wikipedia — p-Wert",
			ref_normal_label: "Wikipedia — Normalverteilung",
			article: "Berechnen Sie einen zweiseitigen normalen p-Wert aus z mit erfc-Näherung und klaren Annahmen."
		}
	},
	fields: [
		{ id: 'z', type: 'number', half: false, labelKey: 'z_label', phKey: 'z_ph' },
	],
	results: [
		{ id: 'pOut', labelKey: 'pOut_label' },
	],
	refs: [
		{ labelKey: 'ref_pvalue_label', href: 'https://en.wikipedia.org/wiki/P-value' },
		{ labelKey: 'ref_normal_label', href: 'https://en.wikipedia.org/wiki/Normal_distribution' },
	],
	computeJs: `
        var z = parseFloat(zEl.value);
        if (!Number.isFinite(z)) {
          return { ok: false, error: msgErr };
        }
        /** Abramowitz–Stegun style erfc approximation for normal tails. */
        function erfc(x) {
          var ax = Math.abs(x);
          var t = 1 / (1 + 0.5 * ax);
          var tau = t * Math.exp(
            -ax * ax -
              1.26551223 +
              t *
                (1.00002368 +
                  t *
                    (0.37409196 +
                      t *
                        (0.09678418 +
                          t *
                            (-0.18628806 +
                              t *
                                (0.27886807 +
                                  t *
                                    (-1.13520398 +
                                      t * (1.48851587 + t * (-0.82215223 + t * 0.17087277)))))))
          );
          return x >= 0 ? tau : 2 - tau;
        }
        var p = erfc(Math.abs(z) / Math.SQRT2);
        return { ok: true, values: { pOut: fmt(p, 6) } };
`,
	sampleJs: `
        zEl.value = '1.96';
`,
};
