/**
 * §12 #57 how-to-calculate-pace
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"distKm_label": "Distance (km)",
		"distKm_ph": "e.g. 5",
		"minutes_label": "Time (minutes)",
		"minutes_ph": "e.g. 25",
		"paceOut_label": "Pace",
		"speedOut_label": "Speed (km/h)",
		"result_note": "Pace = minutes/distance as mm:ss per km; speed = distance / (minutes/60).",
		"err_generic": "Enter distance > 0 and minutes > 0.",
		"how_title": "How it works",
		"how_body": "Enter kilometers and total minutes. Pace is formatted as mm:ss /km.",
		"formula_title": "Formula",
		"formula_body": "min_per_km = minutes/dist; speed = dist/(minutes/60). Notes:",
		"formula_item_1": "Does not model elevation or splits.",
		"formula_item_2": "Seconds are rounded to nearest second.",
		"formula_item_3": "Pair with one-rep-max / heart-rate tools.",
		"example_title": "Example",
		"example": "Example: 5 km in 25 min → 5:00 /km, 12 km/h.",
		"usecases_title": "When to use it",
		"usecase_1": "Run workout planning.",
		"usecase_2": "Homework pace math.",
		"usecase_3": "Compare with HR zones educationally.",
		"faq_q1": "Sample?",
		"faq_a1": "5 km / 25 min → 5:00 /km.",
		"faq_q2": "Miles?",
		"faq_a2": "Convert to km first.",
		"faq_q3": "Seconds input?",
		"faq_a3": "Enter decimal minutes if needed.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Running pace",
		"disclaimer": "Educational running pace only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — Pace",
		"ref_b_label": "Wikipedia — Running",
	}),
	zh: withBtns("zh", {
		"distKm_label": "距离 (km)",
		"distKm_ph": "例如 5",
		"minutes_label": "时间（分钟）",
		"minutes_ph": "例如 25",
		"paceOut_label": "配速",
		"speedOut_label": "速度 (km/h)",
		"result_note": "结果按配速公式在浏览器本地计算。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算配速。",
		"formula_title": "公式",
		"formula_body": "配速相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：5 km、25 分钟 → 5:00 /km、12 km/h。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：5 km、25 分钟 → 5:00 /km、12 km/h。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "配速",
		"disclaimer": "结果仅为配速学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"distKm_label": "Distancia (km)",
		"distKm_ph": "p. ej. 5",
		"minutes_label": "Tiempo (min)",
		"minutes_ph": "p. ej. 25",
		"paceOut_label": "Ritmo",
		"speedOut_label": "Velocidad (km/h)",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce km y minutos.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce km y minutos.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: 5:00 /km.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: 5:00 /km.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de ritmo",
		"disclaimer": "Solo ilustración educativa (running pace).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"distKm_label": "المسافة (كم)",
		"distKm_ph": "مثال 5",
		"minutes_label": "الوقت (دقائق)",
		"minutes_ph": "مثال 25",
		"paceOut_label": "الإيقاع",
		"speedOut_label": "السرعة (كم/س)",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل الكم والدقائق.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل الكم والدقائق.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: 5:00 /كم.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: 5:00 /كم.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة الإيقاع",
		"disclaimer": "توضيح تعليمي فقط (running pace).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"distKm_label": "Distância (km)",
		"distKm_ph": "ex. 5",
		"minutes_label": "Tempo (min)",
		"minutes_ph": "ex. 25",
		"paceOut_label": "Ritmo",
		"speedOut_label": "Velocidade (km/h)",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe km e minutos.",
		"formula_title": "Fórmula",
		"formula_body": "Informe km e minutos.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: 5:00 /km.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: 5:00 /km.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de ritmo",
		"disclaimer": "Apenas ilustração educativa (running pace).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"distKm_label": "Jarak (km)",
		"distKm_ph": "mis. 5",
		"minutes_label": "Waktu (menit)",
		"minutes_ph": "mis. 25",
		"paceOut_label": "Pace",
		"speedOut_label": "Kecepatan (km/j)",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi km dan menit.",
		"formula_title": "Rumus",
		"formula_body": "Isi km dan menit.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: 5:00 /km.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: 5:00 /km.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator pace",
		"disclaimer": "Hanya ilustrasi edukatif (running pace).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"distKm_label": "Distance (km)",
		"distKm_ph": "ex. 5",
		"minutes_label": "Temps (min)",
		"minutes_ph": "ex. 25",
		"paceOut_label": "Allure",
		"speedOut_label": "Vitesse (km/h)",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez km et minutes.",
		"formula_title": "Formule",
		"formula_body": "Saisissez km et minutes.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : 5:00 /km.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : 5:00 /km.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur d’allure",
		"disclaimer": "Illustration éducative (running pace) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"distKm_label": "距離 (km)",
		"distKm_ph": "例 5",
		"minutes_label": "時間（分）",
		"minutes_ph": "例 25",
		"paceOut_label": "ペース",
		"speedOut_label": "速度 (km/h)",
		"result_note": "ペースの公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れてペースを計算します。",
		"formula_title": "計算式",
		"formula_body": "ペースの式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：5km・25分 → 5:00/km、12km/h。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：5km・25分 → 5:00/km、12km/h。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "ペース",
		"disclaimer": "ペースの学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"distKm_label": "Дистанция (км)",
		"distKm_ph": "напр. 5",
		"minutes_label": "Время (мин)",
		"minutes_ph": "напр. 25",
		"paceOut_label": "Темп",
		"speedOut_label": "Скорость (км/ч)",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите км и минуты.",
		"formula_title": "Формула",
		"formula_body": "Введите км и минуты.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: 5:00 /км.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: 5:00 /км.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор темпа",
		"disclaimer": "Только учебная иллюстрация (running pace).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"distKm_label": "Distanz (km)",
		"distKm_ph": "z. B. 5",
		"minutes_label": "Zeit (Min)",
		"minutes_ph": "z. B. 25",
		"paceOut_label": "Pace",
		"speedOut_label": "Tempo (km/h)",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "km und Minuten eingeben.",
		"formula_title": "Formel",
		"formula_body": "km und Minuten eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: 5:00 /km.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: 5:00 /km.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Pace-Rechner — min/km und Tempo",
		"disclaimer": "Nur zur Veranschaulichung (running pace).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 57,
	slug: "how-to-calculate-pace",
	prefix: "tool_pace",
	pageFile: "howToCalculatePacePage",
	pageExport: "renderHowToCalculatePacePage",
	nameZh: "配速计算器",
	ymyl: false,
	related: ["how-to-calculate-one-rep-max","how-to-calculate-heart-rate"],
	anchor: "pace",
	glyph: "M8 20h16v2H8zM10 6h4v10h-4z",
	sampleHint: "5 km in 25 min → 5:00 /km",
	titles: {
		en: "Pace Calculator — min/km and Speed",
		zh: "配速计算器 — 分/公里与时速",
		es: "Calculadora de ritmo",
		ar: "حاسبة الإيقاع",
		pt: "Calculadora de ritmo",
		id: "Kalkulator pace",
		fr: "Calculateur d’allure",
		ja: "ペース計算ツール — 分/km と速度",
		ru: "Калькулятор темпа",
		de: "Pace-Rechner — min/km und Tempo",
	},
	descriptions: {
		en: "Convert distance and time into pace (mm:ss per km) and speed (km/h). Sample: 5 km in 25 minutes → 5:00 /km and 12 km/h. Browser-only.",
		zh: "由距离与时间计算配速（分:秒 /km）与速度（km/h）。示例：5 km、25 分钟 → 5:00 /km、12 km/h。浏览器本地计算。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Convierte distancia y tiempo en ritmo y velocidad. Ejemplo: 5 km en 25 min → 5:00 /km.",
		ar: "حوّل المسافة والوقت إلى إيقاع وسرعة. مثال: 5 كم في 25 دقيقة → 5:00 /كم.",
		pt: "Converta distância e tempo em ritmo e velocidade. Exemplo: 5 km em 25 min → 5:00 /km.",
		id: "Ubah jarak dan waktu jadi pace dan kecepatan. Contoh: 5 km dalam 25 menit → 5:00 /km.",
		fr: "Convertissez distance et temps en allure et vitesse. Exemple : 5 km en 25 min → 5:00 /km.",
		ja: "距離と時間からペース（分:秒/km）と速度（km/h）を出します。例：5km・25分 → 5:00/km、12km/h。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Переведите дистанцию и время в темп и скорость. Пример: 5 км за 25 мин → 5:00 /км.",
		de: "Distanz und Zeit in Pace und Tempo. Beispiel: 5 km in 25 min → 5:00 /km.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "distKm",
	    "type": "number",
	    "half": true,
	    "labelKey": "distKm_label",
	    "phKey": "distKm_ph"
	  },
	  {
	    "id": "minutes",
	    "type": "number",
	    "half": true,
	    "labelKey": "minutes_label",
	    "phKey": "minutes_ph"
	  }
	],
	results: [
	  {
	    "id": "paceOut",
	    "labelKey": "paceOut_label"
	  },
	  {
	    "id": "speedOut",
	    "labelKey": "speedOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Pace_(speed)"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Running"
	  }
	],
	computeJs: `
        var dist=parseFloat(distKmEl.value), minutes=parseFloat(minutesEl.value);
        if(!(dist>0)||!(minutes>0)) return {ok:false,error:msgErr};
        var minPerKm=minutes/dist;
        var totalSec=Math.round(minPerKm*60);
        var mm=Math.floor(totalSec/60), ss=totalSec%60;
        var pace=String(mm)+':'+String(ss).padStart(2,'0')+' /km';
        var speed=dist/(minutes/60);
        return {ok:true, values:{ paceOut:pace, speedOut:fmt(speed) }};
`,
	sampleJs: `
        distKmEl.value='5';
        minutesEl.value='25';
`,
};
