/**
 * §12 #40 how-to-calculate-payback-period
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"invest_label": "Initial investment",
		"invest_ph": "e.g. 10000",
		"cf_label": "Annual cash inflow",
		"cf_ph": "e.g. 2500",
		"yearsOut_label": "Payback years",
		"result_note": "Simple payback = investment / annual CF (no discounting). Educational only.",
		"err_generic": "Enter investment > 0 and annual cash inflow > 0.",
		"how_title": "How it works",
		"how_body": "Enter the upfront investment and a constant annual inflow. Years = investment ÷ annual CF. For discounted payback use NPV-style tools.",
		"formula_title": "Formula",
		"formula_body": "Payback years = I0 / CF_annual. Notes:",
		"formula_item_1": "Ignores time value of money and uneven cash flows.",
		"formula_item_2": "Both inputs must be positive.",
		"formula_item_3": "Not a profitability measure by itself.",
		"example_title": "Example",
		"example": "Example: I0=10000, CF=2500 → 10000/2500 = 4 years.",
		"usecases_title": "When to use it",
		"usecase_1": "Homework: simple payback drills.",
		"usecase_2": "Rough screen before NPV/IRR.",
		"usecase_3": "Contrast with discounted methods.",
		"faq_q1": "Sample?",
		"faq_a1": "4 years for 10000 / 2500.",
		"faq_q2": "Discounted?",
		"faq_a2": "Not on this page — simple payback only.",
		"faq_q3": "Uneven CF?",
		"faq_a3": "Use a spreadsheet or NPV-style schedule.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Simple payback",
		"disclaimer": "Educational payback period only — not financial, tax, or investment advice.",
		"references": "Investopedia and standard textbook formulas.",
		"ref_a_label": "Investopedia — Payback period",
		"ref_b_label": "Investopedia — NPV",
	}),
	zh: withBtns("zh", {
		"invest_label": "初始投资",
		"invest_ph": "例如 10000",
		"cf_label": "年现金流入",
		"cf_ph": "例如 2500",
		"yearsOut_label": "回收年数",
		"result_note": "简单回收期 = 投资 / 年现金流（不折现）。仅供学习。",
		"err_generic": "投资与年流入均须 > 0。",
		"how_title": "怎么用",
		"how_body": "填入初始投资与每年等额流入。年数 = 投资 ÷ 年现金流。折现回收请用 NPV 类工具。",
		"formula_title": "公式",
		"formula_body": "回收年数 = I0 / 年 CF。注意：",
		"formula_item_1": "忽略货币时间价值与不均匀现金流。",
		"formula_item_2": "两输入须为正。",
		"formula_item_3": "本身不是盈利能力指标。",
		"example_title": "示例",
		"example": "示例：I0=10000、CF=2500 → 4 年。",
		"usecases_title": "适合什么场景",
		"usecase_1": "作业：简单回收期。",
		"usecase_2": "NPV/IRR 前粗筛。",
		"usecase_3": "与折现方法对照。",
		"faq_q1": "样例？",
		"faq_a1": "10000/2500 → 4 年。",
		"faq_q2": "折现回收？",
		"faq_a2": "本页仅简单法。",
		"faq_q3": "不均匀现金流？",
		"faq_a3": "请用表格或 NPV 日程。",
		"faq_q4": "投资建议？",
		"faq_a4": "不是。",
		"article": "简单回收期",
		"disclaimer": "结果仅为回收期学习演示，不构成投资、理财或税务建议。",
		"references": "Investopedia 与常见教材公式。",
		"ref_a_label": "Investopedia — Payback period",
		"ref_b_label": "Investopedia — NPV",
	}),
	es: withBtns("es", {
		"invest_label": "Inversión inicial",
		"invest_ph": "p. ej. 10000",
		"cf_label": "Flujo anual",
		"cf_ph": "p. ej. 2500",
		"yearsOut_label": "Años de payback",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce inversión y flujo anual constante.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce inversión y flujo anual constante.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: 10000 / 2500 = 4 años.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: 10000 / 2500 = 4 años.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de periodo de recuperación",
		"disclaimer": "Solo ilustración educativa (payback period); no es consejo financiero.",
		"references": "Investopedia y fórmulas de libro.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ar: withBtns("ar", {
		"invest_label": "الاستثمار الابتدائي",
		"invest_ph": "مثال 10000",
		"cf_label": "التدفق السنوي",
		"cf_ph": "مثال 2500",
		"yearsOut_label": "سنوات الاسترداد",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل الاستثمار والتدفق السنوي الثابت.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل الاستثمار والتدفق السنوي الثابت.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: 10000 / 2500 = 4 سنوات.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: 10000 / 2500 = 4 سنوات.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة فترة الاسترداد",
		"disclaimer": "توضيح تعليمي فقط (payback period) وليس نصيحة مالية.",
		"references": "Investopedia وصيغ دراسية.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	pt: withBtns("pt", {
		"invest_label": "Investimento inicial",
		"invest_ph": "ex. 10000",
		"cf_label": "Fluxo anual",
		"cf_ph": "ex. 2500",
		"yearsOut_label": "Anos de payback",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe investimento e fluxo anual constante.",
		"formula_title": "Fórmula",
		"formula_body": "Informe investimento e fluxo anual constante.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: 10000 / 2500 = 4 anos.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: 10000 / 2500 = 4 anos.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de payback",
		"disclaimer": "Apenas ilustração educativa (payback period); não é conselho financeiro.",
		"references": "Investopedia e fórmulas didáticas.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	id: withBtns("id", {
		"invest_label": "Investasi awal",
		"invest_ph": "mis. 10000",
		"cf_label": "Arus kas tahunan",
		"cf_ph": "mis. 2500",
		"yearsOut_label": "Tahun payback",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi investasi dan arus kas tahunan tetap.",
		"formula_title": "Rumus",
		"formula_body": "Isi investasi dan arus kas tahunan tetap.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: 10000 / 2500 = 4 tahun.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: 10000 / 2500 = 4 tahun.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator payback period",
		"disclaimer": "Hanya ilustrasi edukatif (payback period); bukan saran keuangan.",
		"references": "Investopedia dan rumus buku teks.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	fr: withBtns("fr", {
		"invest_label": "Investissement initial",
		"invest_ph": "ex. 10000",
		"cf_label": "Flux annuel",
		"cf_ph": "ex. 2500",
		"yearsOut_label": "Années de payback",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez investissement et flux annuel constant.",
		"formula_title": "Formule",
		"formula_body": "Saisissez investissement et flux annuel constant.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : 10000 / 2500 = 4 ans.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : 10000 / 2500 = 4 ans.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de délai de récupération",
		"disclaimer": "Illustration éducative (payback period) uniquement — pas un conseil financier.",
		"references": "Investopedia et formules de manuel.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ja: withBtns("ja", {
		"invest_label": "初期投資",
		"invest_ph": "例 10000",
		"cf_label": "年間キャッシュ流入",
		"cf_ph": "例 2500",
		"yearsOut_label": "回収年数",
		"result_note": "単純回収 = 投資 / 年CF（割引なし）。学習用。",
		"err_generic": "投資と年流入は > 0。",
		"how_title": "使い方",
		"how_body": "初期投資と毎年一定の流入を入力。年数 = 投資 ÷ 年CF。割引回収はNPV系へ。",
		"formula_title": "計算式",
		"formula_body": "回収年数 = I0 / 年CF。注意:",
		"formula_item_1": "貨幣の時間価値や不均一CFは無視。",
		"formula_item_2": "両方とも正。",
		"formula_item_3": "それ単体では収益性指標ではない。",
		"example_title": "例",
		"example": "例：I0=10000、CF=2500 → 4年。",
		"usecases_title": "こんなときに",
		"usecase_1": "単純回収の宿題。",
		"usecase_2": "NPV/IRR前の粗スクリーニング。",
		"usecase_3": "割引法と対照。",
		"faq_q1": "例は？",
		"faq_a1": "4年。",
		"faq_q2": "割引回収は？",
		"faq_a2": "本ページは単純法のみ。",
		"faq_q3": "不均一CFは？",
		"faq_a3": "表計算やNPVへ。",
		"faq_q4": "助言？",
		"faq_a4": "学習用です。",
		"article": "単純回収期間",
		"disclaimer": "回収期間の学習用試算であり、投資・税務の助言ではありません。",
		"references": "Investopedia と標準的な教科書公式。",
		"ref_a_label": "Investopedia — Payback period",
		"ref_b_label": "Investopedia — NPV",
	}),
	ru: withBtns("ru", {
		"invest_label": "Начальные инвестиции",
		"invest_ph": "напр. 10000",
		"cf_label": "Годовой приток",
		"cf_ph": "напр. 2500",
		"yearsOut_label": "Годы окупаемости",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите инвестиции и постоянный годовой приток.",
		"formula_title": "Формула",
		"formula_body": "Введите инвестиции и постоянный годовой приток.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: 10000 / 2500 = 4 года.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: 10000 / 2500 = 4 года.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор срока окупаемости",
		"disclaimer": "Только учебная иллюстрация (payback period) — не финансовый совет.",
		"references": "Investopedia и учебные формулы.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	de: withBtns("de", {
		"invest_label": "Anfangsinvestition",
		"invest_ph": "z. B. 10000",
		"cf_label": "Jährlicher Zufluss",
		"cf_ph": "z. B. 2500",
		"yearsOut_label": "Amortisationsjahre",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Investition und konstanten Jahreszufluss eingeben.",
		"formula_title": "Formel",
		"formula_body": "Investition und konstanten Jahreszufluss eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: 10000 / 2500 = 4 Jahre.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: 10000 / 2500 = 4 Jahre.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Amortisationsdauer-Rechner",
		"disclaimer": "Nur zur Veranschaulichung (payback period) — keine Finanzberatung.",
		"references": "Investopedia und Lehrbuchformeln.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
};
export default {
	seq: 40,
	slug: "how-to-calculate-payback-period",
	prefix: "tool_payback_period",
	pageFile: "howToCalculatePaybackPeriodPage",
	pageExport: "renderHowToCalculatePaybackPeriodPage",
	nameZh: "回收期计算器",
	ymyl: true,
	related: ["how-to-calculate-npv","how-to-calculate-irr"],
	anchor: "payback-period",
	glyph: "M8 8h16v4H8zm0 8h10v4H8z",
	sampleHint: "invest 10000 CF 2500 → 4 years",
	titles: {
		en: "Payback Period Calculator — Years to Recover Investment",
		zh: "回收期计算器 — 多久收回投资",
		es: "Calculadora de periodo de recuperación",
		ar: "حاسبة فترة الاسترداد",
		pt: "Calculadora de payback",
		id: "Kalkulator payback period",
		fr: "Calculateur de délai de récupération",
		ja: "回収期間の計算ツール",
		ru: "Калькулятор срока окупаемости",
		de: "Amortisationsdauer-Rechner",
	},
	descriptions: {
		en: "Estimate simple payback years from initial investment and constant annual cash inflow. Sample: invest 10,000 with 2,500 per year → 4 years. Educational — not investment advice.",
		zh: "用初始投资与每年等额现金流入估算简单回收期。示例：投资 10000、每年流入 2500 → 4 年。浏览器本地计算；财务教育用，非投资建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。",
		es: "Estima años de payback con inversión inicial y flujo anual constante. Ejemplo: 10.000 con 2.500/año → 4 años. Educativo.",
		ar: "قدّر سنوات الاسترداد من استثمار ابتدائي وتدفق سنوي ثابت. مثال: 10000 و2500 سنوياً → 4 سنوات. تعليمي.",
		pt: "Estime anos de payback com investimento inicial e fluxo anual constante. Exemplo: 10.000 com 2.500/ano → 4 anos. Educativo.",
		id: "Perkirakan tahun payback dari investasi awal dan arus kas tahunan tetap. Contoh: 10000 dengan 2500/tahun → 4 tahun. Edukatif.",
		fr: "Estimez les années de payback avec investissement initial et flux annuel constant. Exemple : 10 000 avec 2 500/an → 4 ans. Éducatif.",
		ja: "初期投資と毎年一定のキャッシュ流入から単純回収年数を見積もります。例：投資 10000、毎年 2500 → 4年。学習用であり投資助言ではありません。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり投資・税務・経営の助言ではありません。",
		ru: "Оцените простой срок окупаемости из инвестиций и постоянного годового притока. Пример: 10000 и 2500/год → 4 года. Учебно.",
		de: "Schätzen Sie die einfache Amortisationsdauer aus Investition und konstantem Jahreszufluss. Beispiel: 10.000 mit 2.500/Jahr → 4 Jahre. Bildungszweck.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "invest",
	    "type": "number",
	    "half": true,
	    "labelKey": "invest_label",
	    "phKey": "invest_ph"
	  },
	  {
	    "id": "cf",
	    "type": "number",
	    "half": true,
	    "labelKey": "cf_label",
	    "phKey": "cf_ph"
	  }
	],
	results: [
	  {
	    "id": "yearsOut",
	    "labelKey": "yearsOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://www.investopedia.com/terms/p/paybackperiod.asp"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.investopedia.com/terms/n/npv.asp"
	  }
	],
	computeJs: `
        var I0=parseFloat(investEl.value), CF=parseFloat(cfEl.value);
        if(!(I0>0)||!(CF>0)) return {ok:false,error:msgErr};
        return {ok:true, values:{ yearsOut: fmt(I0/CF) }};
`,
	sampleJs: `
        investEl.value='10000';
        cfEl.value='2500';
`,
};
