/**
 * §12 #38 how-to-calculate-present-value
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"mode_label": "Mode",
		"mode_pv": "Find present value (from FV)",
		"mode_fv": "Find future value (from PV)",
		"amount_label": "Amount (PV or FV)",
		"amount_ph": "e.g. 10000",
		"rate_label": "Annual rate %",
		"rate_ph": "e.g. 5",
		"n_label": "Years (n)",
		"n_ph": "e.g. 5",
		"out_label": "Result",
		"result_note": "PV = FV/(1+r)^n ; FV = PV×(1+r)^n. Educational — not investment advice.",
		"err_generic": "Enter positive amount, finite rate > -100%, and n > 0.",
		"how_title": "How it works",
		"how_body": "Choose PV or FV mode. Enter the known amount, annual rate, and years. Distinct from NPV (cash-flow series).",
		"formula_title": "Formula",
		"formula_body": "PV = FV / (1+r)^n and FV = PV × (1+r)^n with r as a decimal. Notes:",
		"formula_item_1": "Compounding is annual end-of-year in this simple model.",
		"formula_item_2": "Rate −100% or below is invalid.",
		"formula_item_3": "Annuity streams are not modeled — use NPV for series.",
		"example_title": "Example",
		"example": "Example: FV 10000, r=5%, n=5 → PV = 10000/1.05^5 ≈ 7835.26.",
		"usecases_title": "When to use it",
		"usecase_1": "Homework lump-sum discounting.",
		"usecase_2": "Sketch what a future goal is worth today.",
		"usecase_3": "Contrast with NPV for multi-year cash flows.",
		"faq_q1": "Sample PV?",
		"faq_a1": "≈7835.26 for FV 10000 at 5% over 5 years.",
		"faq_q2": "PV vs NPV?",
		"faq_a2": "PV is one amount; NPV discounts a cash-flow list minus investment.",
		"faq_q3": "Monthly compounding?",
		"faq_a3": "This page uses annual periods only.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Present Value Calculator — PV and FV Modes",
		"disclaimer": "Educational present value only — not financial, tax, or investment advice.",
		"references": "Investopedia and standard textbook formulas.",
		"ref_a_label": "Investopedia — Present value",
		"ref_b_label": "Investopedia — Future value",
	}),
	zh: withBtns("zh", {
		"mode_label": "模式",
		"mode_pv": "求现值（已知终值）",
		"mode_fv": "求终值（已知现值）",
		"amount_label": "金额（PV 或 FV）",
		"amount_ph": "例如 10000",
		"rate_label": "年利率 %",
		"rate_ph": "例如 5",
		"n_label": "年数 n",
		"n_ph": "例如 5",
		"out_label": "结果",
		"result_note": "PV=FV/(1+r)^n；FV=PV×(1+r)^n。非投资建议。",
		"err_generic": "请填写正金额、有效利率（>-100%）与 n>0。",
		"how_title": "怎么用",
		"how_body": "选择求现值或求终值，填入已知金额、年利率与年数。与 NPV（多期现金流）分意图。",
		"formula_title": "公式",
		"formula_body": "PV = FV/(1+r)^n，FV = PV×(1+r)^n。注意：",
		"formula_item_1": "本页按年末复利。",
		"formula_item_2": "利率 ≤ −100% 无效。",
		"formula_item_3": "年金序列请用 NPV。",
		"example_title": "示例",
		"example": "示例：FV=10000、r=5%、n=5 → PV≈7835.26。",
		"usecases_title": "适合什么场景",
		"usecase_1": "作业：单笔折现。",
		"usecase_2": "估算未来目标的今天价值。",
		"usecase_3": "与 NPV 对照多期现金流。",
		"faq_q1": "样例现值？",
		"faq_a1": "约 7835.26。",
		"faq_q2": "与 NPV 差别？",
		"faq_a2": "PV 单笔；NPV 折现现金流序列。",
		"faq_q3": "按月复利？",
		"faq_a3": "本页仅年期。",
		"faq_q4": "投资建议？",
		"faq_a4": "不是。",
		"article": "现值计算器 — 现值与终值互算",
		"disclaimer": "结果仅为现值学习演示，不构成投资、理财或税务建议。",
		"references": "Investopedia 与常见教材公式。",
		"ref_a_label": "Investopedia — Present value",
		"ref_b_label": "Investopedia — Future value",
	}),
	es: withBtns("es", {
		"mode_label": "Modo",
		"mode_pv": "Hallar VA (desde VF)",
		"mode_fv": "Hallar VF (desde VA)",
		"amount_label": "Monto",
		"amount_ph": "p. ej. 10000",
		"rate_label": "Tasa anual %",
		"rate_ph": "p. ej. 5",
		"n_label": "Años",
		"n_ph": "p. ej. 5",
		"out_label": "Resultado",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Elige modo PV/FV e introduce monto, tasa y años.",
		"formula_title": "Fórmula",
		"formula_body": "Elige modo PV/FV e introduce monto, tasa y años.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: VF 10000, 5%, 5 años → VA ≈ 7835,26.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: VF 10000, 5%, 5 años → VA ≈ 7835,26.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de valor presente (PV/FV)",
		"disclaimer": "Solo ilustración educativa (present value); no es consejo financiero.",
		"references": "Investopedia y fórmulas de libro.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ar: withBtns("ar", {
		"mode_label": "الوضع",
		"mode_pv": "أوجد القيمة الحالية",
		"mode_fv": "أوجد القيمة المستقبلية",
		"amount_label": "المبلغ",
		"amount_ph": "مثال 10000",
		"rate_label": "معدل سنوي %",
		"rate_ph": "مثال 5",
		"n_label": "سنوات",
		"n_ph": "مثال 5",
		"out_label": "النتيجة",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "اختر الوضع وأدخل المبلغ والمعدل والسنوات.",
		"formula_title": "الصيغة",
		"formula_body": "اختر الوضع وأدخل المبلغ والمعدل والسنوات.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: مستقبل 10000، 5٪، 5 سنوات → ≈7835.26.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: مستقبل 10000، 5٪، 5 سنوات → ≈7835.26.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة القيمة الحالية والقيمة المستقبلية",
		"disclaimer": "توضيح تعليمي فقط (present value) وليس نصيحة مالية.",
		"references": "Investopedia وصيغ دراسية.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	pt: withBtns("pt", {
		"mode_label": "Modo",
		"mode_pv": "Achar VP (a partir do VF)",
		"mode_fv": "Achar VF (a partir do VP)",
		"amount_label": "Valor",
		"amount_ph": "ex. 10000",
		"rate_label": "Taxa anual %",
		"rate_ph": "ex. 5",
		"n_label": "Anos",
		"n_ph": "ex. 5",
		"out_label": "Resultado",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Escolha o modo PV/FV e informe valor, taxa e anos.",
		"formula_title": "Fórmula",
		"formula_body": "Escolha o modo PV/FV e informe valor, taxa e anos.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: VF 10000, 5%, 5 anos → VP ≈ 7835,26.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: VF 10000, 5%, 5 anos → VP ≈ 7835,26.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de valor presente (PV/FV)",
		"disclaimer": "Apenas ilustração educativa (present value); não é conselho financeiro.",
		"references": "Investopedia e fórmulas didáticas.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	id: withBtns("id", {
		"mode_label": "Mode",
		"mode_pv": "Cari PV (dari FV)",
		"mode_fv": "Cari FV (dari PV)",
		"amount_label": "Jumlah",
		"amount_ph": "mis. 10000",
		"rate_label": "Suku bunga tahunan %",
		"rate_ph": "mis. 5",
		"n_label": "Tahun",
		"n_ph": "mis. 5",
		"out_label": "Hasil",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Pilih mode PV/FV, isi jumlah, suku bunga, dan tahun.",
		"formula_title": "Rumus",
		"formula_body": "Pilih mode PV/FV, isi jumlah, suku bunga, dan tahun.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: FV 10000, 5%, 5 tahun → PV ≈ 7835.26.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: FV 10000, 5%, 5 tahun → PV ≈ 7835.26.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator present value (PV/FV)",
		"disclaimer": "Hanya ilustrasi edukatif (present value); bukan saran keuangan.",
		"references": "Investopedia dan rumus buku teks.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	fr: withBtns("fr", {
		"mode_label": "Mode",
		"mode_pv": "Trouver VA (depuis VF)",
		"mode_fv": "Trouver VF (depuis VA)",
		"amount_label": "Montant",
		"amount_ph": "ex. 10000",
		"rate_label": "Taux annuel %",
		"rate_ph": "ex. 5",
		"n_label": "Années",
		"n_ph": "ex. 5",
		"out_label": "Résultat",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Choisissez le mode PV/FV puis montant, taux et années.",
		"formula_title": "Formule",
		"formula_body": "Choisissez le mode PV/FV puis montant, taux et années.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : VF 10000, 5 %, 5 ans → VA ≈ 7835,26.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : VF 10000, 5 %, 5 ans → VA ≈ 7835,26.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de valeur actuelle (PV/FV)",
		"disclaimer": "Illustration éducative (present value) uniquement — pas un conseil financier.",
		"references": "Investopedia et formules de manuel.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ja: withBtns("ja", {
		"mode_label": "モード",
		"mode_pv": "現在価値を求める（将来価値から）",
		"mode_fv": "将来価値を求める（現在価値から）",
		"amount_label": "金額（PV または FV）",
		"amount_ph": "例 10000",
		"rate_label": "年利 %",
		"rate_ph": "例 5",
		"n_label": "年数 n",
		"n_ph": "例 5",
		"out_label": "結果",
		"result_note": "PV=FV/(1+r)^n。投資助言ではありません。",
		"err_generic": "正の金額、利率(>-100%)、n>0。",
		"how_title": "使い方",
		"how_body": "PV/FVモードを選び、既知の金額・年利・年数を入力。NPV（キャッシュフロー列）とは別です。",
		"formula_title": "計算式",
		"formula_body": "PV = FV/(1+r)^n、FV = PV×(1+r)^n。注意:",
		"formula_item_1": "年末複利の簡易モデル。",
		"formula_item_2": "利率≤-100%は不可。",
		"formula_item_3": "年金系列はNPVへ。",
		"example_title": "例",
		"example": "例：FV10000、r=5%、n=5 → PV≈7835.26。",
		"usecases_title": "こんなときに",
		"usecase_1": "一時金の割引宿題。",
		"usecase_2": "将来目標の現在価値ざっくり。",
		"usecase_3": "NPVと対照。",
		"faq_q1": "例のPVは？",
		"faq_a1": "約7835.26。",
		"faq_q2": "NPVとの違いは？",
		"faq_a2": "PVは一筆、NPVは系列。",
		"faq_q3": "月次複利は？",
		"faq_a3": "本ページは年次のみ。",
		"faq_q4": "助言？",
		"faq_a4": "学習用です。",
		"article": "現在価値・将来価値の計算ツール",
		"disclaimer": "現在価値の学習用試算であり、投資・税務の助言ではありません。",
		"references": "Investopedia と標準的な教科書公式。",
		"ref_a_label": "Investopedia — Present value",
		"ref_b_label": "Investopedia — Future value",
	}),
	ru: withBtns("ru", {
		"mode_label": "Режим",
		"mode_pv": "Найти PV (из FV)",
		"mode_fv": "Найти FV (из PV)",
		"amount_label": "Сумма",
		"amount_ph": "напр. 10000",
		"rate_label": "Годовая ставка %",
		"rate_ph": "напр. 5",
		"n_label": "Лет",
		"n_ph": "напр. 5",
		"out_label": "Результат",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Выберите режим PV/FV и введите сумму, ставку и годы.",
		"formula_title": "Формула",
		"formula_body": "Выберите режим PV/FV и введите сумму, ставку и годы.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: FV 10000, 5%, 5 лет → PV ≈ 7835.26.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: FV 10000, 5%, 5 лет → PV ≈ 7835.26.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор PV и FV",
		"disclaimer": "Только учебная иллюстрация (present value) — не финансовый совет.",
		"references": "Investopedia и учебные формулы.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	de: withBtns("de", {
		"mode_label": "Modus",
		"mode_pv": "Barwert finden (aus EW)",
		"mode_fv": "Endwert finden (aus BW)",
		"amount_label": "Betrag",
		"amount_ph": "z. B. 10000",
		"rate_label": "Jahreszins %",
		"rate_ph": "z. B. 5",
		"n_label": "Jahre",
		"n_ph": "z. B. 5",
		"out_label": "Ergebnis",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "PV/FV-Modus wählen; Betrag, Zins und Jahre eingeben.",
		"formula_title": "Formel",
		"formula_body": "PV/FV-Modus wählen; Betrag, Zins und Jahre eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: EW 10000, 5%, 5 Jahre → BW ≈ 7835,26.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: EW 10000, 5%, 5 Jahre → BW ≈ 7835,26.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Barwert-Rechner (PV/FV)",
		"disclaimer": "Nur zur Veranschaulichung (present value) — keine Finanzberatung.",
		"references": "Investopedia und Lehrbuchformeln.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
};
export default {
	seq: 38,
	slug: "how-to-calculate-present-value",
	prefix: "tool_present_value",
	pageFile: "howToCalculatePresentValuePage",
	pageExport: "renderHowToCalculatePresentValuePage",
	nameZh: "现值/终值计算器",
	ymyl: true,
	related: ["how-to-calculate-npv","how-to-calculate-cagr"],
	anchor: "present-value",
	glyph: "M8 16h16M16 8v16M10 12l6-4 6 4",
	sampleHint: "FV 10000 r 5% n 5 → PV≈7835.26",
	titles: {
		en: "Present Value Calculator — PV and FV Modes",
		zh: "现值计算器 — 现值与终值互算",
		es: "Calculadora de valor presente (PV/FV)",
		ar: "حاسبة القيمة الحالية والقيمة المستقبلية",
		pt: "Calculadora de valor presente (PV/FV)",
		id: "Kalkulator present value (PV/FV)",
		fr: "Calculateur de valeur actuelle (PV/FV)",
		ja: "現在価値・将来価値の計算ツール",
		ru: "Калькулятор PV и FV",
		de: "Barwert-Rechner (PV/FV)",
	},
	descriptions: {
		en: "Switch between present value and future value for a lump sum. Sample: FV 10,000 at 5% for 5 years → PV ≈ 7,835.26. Educational time-value math — not investment advice.",
		zh: "在现值和终值模式间切换，计算单笔金额的时间价值。示例：终值 10000、年利率 5%、5 年 → 现值约 7835.26。浏览器本地计算；财务教育用，非投资建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。",
		es: "Alterna PV y FV para un monto único. Ejemplo: VF 10.000 al 5% en 5 años → VA ≈ 7.835,26. Educativo.",
		ar: "بدّل بين القيمة الحالية والمستقبلية لمبلغ واحد. مثال: مستقبل 10000 بمعدل 5٪ لـ5 سنوات → حالي ≈ 7835.26. تعليمي.",
		pt: "Alterne PV e FV para um montante único. Exemplo: VF 10.000 a 5% em 5 anos → VP ≈ 7.835,26. Educativo.",
		id: "Ganti mode PV dan FV untuk jumlah tunggal. Contoh: FV 10000, 5%, 5 tahun → PV ≈ 7835.26. Edukatif.",
		fr: "Basculez PV/FV pour un montant unique. Exemple : VF 10 000 à 5 % sur 5 ans → VA ≈ 7 835,26. Éducatif.",
		ja: "一時金の現在価値と将来価値を切り替え計算します。例：将来価値 10000、年利 5%、5年 → 現在価値 ≈ 7835.26。学習用であり投資助言ではありません。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり投資・税務・経営の助言ではありません。",
		ru: "Переключайте PV и FV для одной суммы. Пример: FV 10000 при 5% за 5 лет → PV ≈ 7835.26. Учебно.",
		de: "Wechseln Sie zwischen PV und FV für einen Einmalbetrag. Beispiel: EW 10.000 bei 5% über 5 Jahre → BW ≈ 7.835,26. Bildungszweck.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "mode",
	    "type": "select",
	    "half": true,
	    "labelKey": "mode_label",
	    "options": [
	      {
	        "value": "pv",
	        "labelKey": "mode_pv",
	        "selected": true
	      },
	      {
	        "value": "fv",
	        "labelKey": "mode_fv"
	      }
	    ]
	  },
	  {
	    "id": "amount",
	    "type": "number",
	    "half": true,
	    "labelKey": "amount_label",
	    "phKey": "amount_ph"
	  },
	  {
	    "id": "rate",
	    "type": "number",
	    "half": true,
	    "labelKey": "rate_label",
	    "phKey": "rate_ph"
	  },
	  {
	    "id": "n",
	    "type": "number",
	    "half": true,
	    "labelKey": "n_label",
	    "phKey": "n_ph"
	  }
	],
	results: [
	  {
	    "id": "out",
	    "labelKey": "out_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://www.investopedia.com/terms/p/presentvalue.asp"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.investopedia.com/terms/f/futurevalue.asp"
	  }
	],
	computeJs: `
        var mode = modeEl.value;
        var amount = parseFloat(amountEl.value);
        var ratePct = parseFloat(rateEl.value);
        var n = parseFloat(nEl.value);
        if (!(amount > 0) || !Number.isFinite(ratePct) || ratePct <= -100 || !(n > 0)) return { ok:false, error: msgErr };
        var r = ratePct / 100;
        var val = mode === 'fv' ? amount * Math.pow(1 + r, n) : amount / Math.pow(1 + r, n);
        return { ok:true, values:{ out: fmt(val) } };
`,
	sampleJs: `
        modeEl.value='pv';
        amountEl.value='10000';
        rateEl.value='5';
        nEl.value='5';
`,
};
