/**
 * §12 #36 how-to-calculate-profit-margin 工具定义（十语独立 UI）。
 */
import { withBtns } from '../locale-ui-common.mjs';

const _ui = {
	en: withBtns("en", {
		"type_label": "Margin type",
		"type_net": "Net profit margin",
		"type_op": "Operating margin",
		"rev_label": "Revenue",
		"rev_ph": "e.g. 10000",
		"cost_label": "Costs",
		"cost_ph": "e.g. 7000",
		"marginOut_label": "Margin %",
		"profitOut_label": "Profit",
		"result_note": "Margin = profit ÷ revenue. Educational — not business advice.",
		"err_generic": "Enter revenue > 0 and costs ≥ 0.",
		"how_title": "How it works",
		"how_body": "Choose net or operating margin, then enter revenue and the matching cost stack. Margin = profit / revenue × 100. Distinct from markup (cost-based) and from gross margin (COGS-only).",
		"formula_title": "Formula",
		"formula_body": "Margin % = (revenue − costs) / revenue × 100. Notes:",
		"formula_item_1": "Net vs operating is a labeling choice here — use costs that match the definition you need.",
		"formula_item_2": "Revenue must be > 0; costs can be zero.",
		"formula_item_3": "Not a full income statement; taxes and non-cash items are omitted unless included in costs.",
		"example_title": "Example",
		"example": "Example: revenue 10,000, costs 7,000 → profit 3,000 → margin 30%.",
		"usecases_title": "When to use it",
		"usecase_1": "Homework: compute net margin from simplified revenue and costs.",
		"usecase_2": "Compare operating vs net by swapping the cost bundle.",
		"usecase_3": "Cross-check against gross-margin when COGS is the only cost.",
		"faq_q1": "What is the sample result?",
		"faq_a1": "Revenue 10000 and costs 7000 → 30% margin.",
		"faq_q2": "Markup vs margin?",
		"faq_a2": "Markup divides by cost; margin divides by revenue.",
		"faq_q3": "Why two types on one page?",
		"faq_a3": "Net and operating share the same ratio form; pick the cost definition you need.",
		"faq_q4": "Is this business advice?",
		"faq_a4": "No — educational illustration only.",
		"article": "Net or operating profit margin from revenue and costs on one page.",
		"disclaimer": "Educational profit margin only — not financial, tax, or investment advice.",
		"references": "Investopedia and standard textbook formulas.",
		"ref_a_label": "Investopedia — Profit margin",
		"ref_b_label": "Investopedia — Operating margin",
	}),
	zh: withBtns("zh", {
		"type_label": "利润率类型",
		"type_net": "净利润率",
		"type_op": "营业利润率",
		"rev_label": "收入",
		"rev_ph": "例如 10000",
		"cost_label": "成本/费用",
		"cost_ph": "例如 7000",
		"marginOut_label": "利润率 %",
		"profitOut_label": "利润额",
		"result_note": "利润率 = 利润 ÷ 收入。教育演示，非经营建议。",
		"err_generic": "请填写收入 > 0，成本 ≥ 0。",
		"how_title": "怎么用",
		"how_body": "选择净利润率或营业利润率，再填收入与对应成本口径。利润率 = 利润 / 收入 × 100。与加价率（÷成本）和毛利率（仅 COGS）区分。",
		"formula_title": "公式",
		"formula_body": "利润率 % = (收入 − 成本) / 收入 × 100。注意：",
		"formula_item_1": "净利率与营业利润率在此为口径标签——请使用匹配的成本口径。",
		"formula_item_2": "收入必须 > 0；成本可为 0。",
		"formula_item_3": "不是完整损益表；税费与非现金项除非并入成本否则省略。",
		"example_title": "示例",
		"example": "示例：收入 10000、成本 7000 → 利润 3000 → 利润率 30%。",
		"usecases_title": "适合什么场景",
		"usecase_1": "作业：用简化收入与成本算净利率。",
		"usecase_2": "更换成本口径对照营业与净利率。",
		"usecase_3": "仅有销货成本时与毛利率对照。",
		"faq_q1": "样例结果？",
		"faq_a1": "收入 10000、成本 7000 → 30%。",
		"faq_q2": "与加价率差别？",
		"faq_a2": "加价率 ÷ 成本；利润率 ÷ 收入。",
		"faq_q3": "为何同页两种类型？",
		"faq_a3": "公式同形，只需切换成本口径。",
		"faq_q4": "是经营建议吗？",
		"faq_a4": "不是，仅供学习。",
		"article": "同页计算净利率或营业利润率。",
		"disclaimer": "结果仅为利润率学习演示，不构成投资、理财或税务建议。",
		"references": "Investopedia 与常见教材公式。",
		"ref_a_label": "Investopedia — 利润率",
		"ref_b_label": "Investopedia — 营业利润率",
	}),
	es: withBtns("es", {
		"type_label": "Tipo de margen",
		"type_net": "Margen neto",
		"type_op": "Margen operativo",
		"rev_label": "Ingresos",
		"rev_ph": "p. ej. 10000",
		"cost_label": "Costos",
		"cost_ph": "p. ej. 7000",
		"marginOut_label": "Margen %",
		"profitOut_label": "Beneficio",
		"result_note": "Margen = beneficio ÷ ingresos. Educativo.",
		"err_generic": "Ingresos > 0 y costos ≥ 0.",
		"how_title": "Cómo funciona",
		"how_body": "Elige margen neto u operativo e introduce ingresos y costos. Margen = beneficio / ingresos × 100.",
		"formula_title": "Fórmula",
		"formula_body": "Margen % = (ingresos − costos) / ingresos × 100. Notas:",
		"formula_item_1": "Ajusta costos a la definición elegida.",
		"formula_item_2": "Ingresos deben ser > 0.",
		"formula_item_3": "P&L simplificado.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: ingresos 10.000, costos 7.000 → margen 30%.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Deberes de margen neto.",
		"usecase_2": "Comparar operativo vs neto.",
		"usecase_3": "Contrastar con margen bruto.",
		"faq_q1": "¿Resultado del ejemplo?",
		"faq_a1": "30%",
		"faq_q2": "¿Markup vs margen?",
		"faq_a2": "Markup÷costo; margen÷ingresos.",
		"faq_q3": "¿Por qué dos tipos?",
		"faq_a3": "Misma forma; distinta definición de costos.",
		"faq_q4": "¿Consejo de negocio?",
		"faq_a4": "No, solo educativo.",
		"article": "Calculadora de margen de beneficio — Neto u operativo",
		"disclaimer": "Solo ilustración educativa (margen); no es consejo financiero.",
		"references": "Investopedia y fórmulas de libro.",
		"ref_a_label": "Investopedia — Profit margin",
		"ref_b_label": "Investopedia — Operating margin",
	}),
	ar: withBtns("ar", {
		"type_label": "نوع الهامش",
		"type_net": "هامش صافٍ",
		"type_op": "هامش تشغيلي",
		"rev_label": "الإيرادات",
		"rev_ph": "مثال 10000",
		"cost_label": "التكاليف",
		"cost_ph": "مثال 7000",
		"marginOut_label": "الهامش %",
		"profitOut_label": "الربح",
		"result_note": "الهامش = الربح ÷ الإيرادات. تعليمي.",
		"err_generic": "إيرادات > 0 وتكاليف ≥ 0.",
		"how_title": "طريقة الاستخدام",
		"how_body": "اختر النوع ثم أدخل الإيرادات والتكاليف. الهامش = الربح / الإيرادات × 100.",
		"formula_title": "الصيغة",
		"formula_body": "الهامش % = (الإيرادات − التكاليف) / الإيرادات × 100. ملاحظات:",
		"formula_item_1": "طابق التكاليف مع التعريف.",
		"formula_item_2": "الإيرادات > 0.",
		"formula_item_3": "قائمة دخل مبسطة.",
		"example_title": "مثال",
		"example": "مثال: إيراد 10000 وتكلفة 7000 → هامش 30٪.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "واجب الهامش الصافي.",
		"usecase_2": "مقارنة التشغيلي والصافي.",
		"usecase_3": "مقارنته بالهامش الإجمالي.",
		"faq_q1": "Sample / contoh?",
		"faq_a1": "30%",
		"faq_q2": "Markup vs margin?",
		"faq_a2": "Markup÷cost; margin÷revenue.",
		"faq_q3": "Why two types?",
		"faq_a3": "Same form; different cost stacks.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "حاسبة هامش الربح — صافٍ أو تشغيلي",
		"disclaimer": "توضيح تعليمي فقط (margen) وليس نصيحة مالية.",
		"references": "Investopedia وصيغ دراسية.",
		"ref_a_label": "Investopedia — Profit margin",
		"ref_b_label": "Investopedia — Operating margin",
	}),
	pt: withBtns("pt", {
		"type_label": "Tipo de margem",
		"type_net": "Margem líquida",
		"type_op": "Margem operacional",
		"rev_label": "Receita",
		"rev_ph": "ex. 10000",
		"cost_label": "Custos",
		"cost_ph": "ex. 7000",
		"marginOut_label": "Margem %",
		"profitOut_label": "Lucro",
		"result_note": "Margem = lucro ÷ receita. Educativo.",
		"err_generic": "Receita > 0 e custos ≥ 0.",
		"how_title": "Como funciona",
		"how_body": "Escolha o tipo e informe receita e custos. Margem = lucro / receita × 100.",
		"formula_title": "Fórmula",
		"formula_body": "Margem % = (receita − custos) / receita × 100. Notas:",
		"formula_item_1": "Ajuste custos à definição.",
		"formula_item_2": "Receita > 0.",
		"formula_item_3": "DRE simplificada.",
		"example_title": "Exemplo",
		"example": "Exemplo: receita 10.000, custos 7.000 → margem 30%.",
		"usecases_title": "Quando usar",
		"usecase_1": "Tarefa de margem líquida.",
		"usecase_2": "Comparar operacional vs líquida.",
		"usecase_3": "Contrastar com margem bruta.",
		"faq_q1": "Sample / contoh?",
		"faq_a1": "30%",
		"faq_q2": "Markup vs margin?",
		"faq_a2": "Markup÷cost; margin÷revenue.",
		"faq_q3": "Why two types?",
		"faq_a3": "Same form; different cost stacks.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Calculadora de margem de lucro — Líquida ou operacional",
		"disclaimer": "Apenas ilustração educativa (margen); não é conselho financeiro.",
		"references": "Investopedia e fórmulas didáticas.",
		"ref_a_label": "Investopedia — Profit margin",
		"ref_b_label": "Investopedia — Operating margin",
	}),
	id: withBtns("id", {
		"type_label": "Jenis margin",
		"type_net": "Margin laba neto",
		"type_op": "Margin operasional",
		"rev_label": "Pendapatan",
		"rev_ph": "mis. 10000",
		"cost_label": "Biaya",
		"cost_ph": "mis. 7000",
		"marginOut_label": "Margin %",
		"profitOut_label": "Laba",
		"result_note": "Margin = laba ÷ pendapatan. Edukatif.",
		"err_generic": "Pendapatan > 0 dan biaya ≥ 0.",
		"how_title": "Cara kerja",
		"how_body": "Pilih jenis margin, isi pendapatan dan biaya. Margin = laba / pendapatan × 100.",
		"formula_title": "Rumus",
		"formula_body": "Margin % = (pendapatan − biaya) / pendapatan × 100. Catatan:",
		"formula_item_1": "Sesuaikan biaya dengan definisi.",
		"formula_item_2": "Pendapatan > 0.",
		"formula_item_3": "Laba rugi sederhana.",
		"example_title": "Contoh",
		"example": "Contoh: pendapatan 10000, biaya 7000 → margin 30%.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "PR margin neto.",
		"usecase_2": "Bandingkan operasional vs neto.",
		"usecase_3": "Bandingkan dengan gross margin.",
		"faq_q1": "Sample / contoh?",
		"faq_a1": "30%",
		"faq_q2": "Markup vs margin?",
		"faq_a2": "Markup÷cost; margin÷revenue.",
		"faq_q3": "Why two types?",
		"faq_a3": "Same form; different cost stacks.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Kalkulator margin laba — Neto atau operasional",
		"disclaimer": "Hanya ilustrasi edukatif (margen); bukan saran keuangan.",
		"references": "Investopedia dan rumus buku teks.",
		"ref_a_label": "Investopedia — Profit margin",
		"ref_b_label": "Investopedia — Operating margin",
	}),
	fr: withBtns("fr", {
		"type_label": "Type de marge",
		"type_net": "Marge nette",
		"type_op": "Marge d’exploitation",
		"rev_label": "Chiffre d’affaires",
		"rev_ph": "ex. 10000",
		"cost_label": "Coûts",
		"cost_ph": "ex. 7000",
		"marginOut_label": "Marge %",
		"profitOut_label": "Profit",
		"result_note": "Marge = profit ÷ CA. Éducatif.",
		"err_generic": "CA > 0 et coûts ≥ 0.",
		"how_title": "Fonctionnement",
		"how_body": "Choisissez le type, puis CA et coûts. Marge = profit / CA × 100.",
		"formula_title": "Formule",
		"formula_body": "Marge % = (CA − coûts) / CA × 100. Notes :",
		"formula_item_1": "Alignez les coûts sur la définition.",
		"formula_item_2": "CA > 0.",
		"formula_item_3": "Compte de résultat simplifié.",
		"example_title": "Exemple",
		"example": "Exemple : CA 10 000, coûts 7 000 → marge 30 %.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Devoir de marge nette.",
		"usecase_2": "Comparer exploitation vs nette.",
		"usecase_3": "Contraster avec marge brute.",
		"faq_q1": "Sample / contoh?",
		"faq_a1": "30%",
		"faq_q2": "Markup vs marge ?",
		"faq_a2": "Markup÷cost; margin÷revenue.",
		"faq_q3": "Why two types?",
		"faq_a3": "Same form; different cost stacks.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Calculateur de marge — Nette ou d’exploitation",
		"disclaimer": "Illustration éducative (margen) uniquement — pas un conseil financier.",
		"references": "Investopedia et formules de manuel.",
		"ref_a_label": "Investopedia — Profit margin",
		"ref_b_label": "Investopedia — Operating margin",
	}),
	ja: withBtns("ja", {
		"type_label": "利益率の種類",
		"type_net": "純利益率",
		"type_op": "営業利益率",
		"rev_label": "売上",
		"rev_ph": "例 10000",
		"cost_label": "費用",
		"cost_ph": "例 7000",
		"marginOut_label": "利益率 %",
		"profitOut_label": "利益額",
		"result_note": "利益率 = 利益 ÷ 売上。学習用であり経営助言ではありません。",
		"err_generic": "売上 > 0、費用 ≥ 0 を入力。",
		"how_title": "使い方",
		"how_body": "純利益率または営業利益率を選び、売上と対応する費用を入力します。利益率 = 利益 / 売上 × 100。マークアップ（原価割）や粗利率（売上原価のみ）とは別です。",
		"formula_title": "計算式",
		"formula_body": "利益率% = (売上 − 費用) / 売上 × 100。注意:",
		"formula_item_1": "純利益と営業はここでのラベルです。必要な費用口径を使ってください。",
		"formula_item_2": "売上は > 0、費用は 0 可。",
		"formula_item_3": "完全な損益計算書ではありません。",
		"example_title": "例",
		"example": "例：売上 10000、費用 7000 → 利益 3000 → 利益率 30%。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題：簡略な売上と費用で純利益率。",
		"usecase_2": "費用束を替えて営業と純利益を比較。",
		"usecase_3": "売上原価だけのときは粗利率と対照。",
		"faq_q1": "例の結果は？",
		"faq_a1": "売上10000・費用7000 → 30%。",
		"faq_q2": "マークアップとの違いは？",
		"faq_a2": "マークアップは原価割、利益率は売上割。",
		"faq_q3": "なぜ2種類を1ページに？",
		"faq_a3": "同じ比の形で費用口径だけ変えます。",
		"faq_q4": "経営助言ですか？",
		"faq_a4": "いいえ、学習用です。",
		"article": "純利益率または営業利益率を同一ページで計算。",
		"disclaimer": "利益率の学習用試算であり、投資・税務の助言ではありません。",
		"references": "Investopedia と標準的な教科書公式。",
		"ref_a_label": "Investopedia — 利益率",
		"ref_b_label": "Investopedia — 営業利益率",
	}),
	ru: withBtns("ru", {
		"type_label": "Тип маржи",
		"type_net": "Чистая маржа",
		"type_op": "Операционная маржа",
		"rev_label": "Выручка",
		"rev_ph": "напр. 10000",
		"cost_label": "Затраты",
		"cost_ph": "напр. 7000",
		"marginOut_label": "Маржа %",
		"profitOut_label": "Прибыль",
		"result_note": "Маржа = прибыль ÷ выручка. Учебно.",
		"err_generic": "Выручка > 0 и затраты ≥ 0.",
		"how_title": "Как пользоваться",
		"how_body": "Выберите тип, введите выручку и затраты. Маржа = прибыль / выручка × 100.",
		"formula_title": "Формула",
		"formula_body": "Маржа % = (выручка − затраты) / выручка × 100. Замечания:",
		"formula_item_1": "Подберите затраты под определение.",
		"formula_item_2": "Выручка > 0.",
		"formula_item_3": "Упрощённый P&L.",
		"example_title": "Пример",
		"example": "Пример: выручка 10000, затраты 7000 → маржа 30%.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Домашка по чистой марже.",
		"usecase_2": "Сравнить операционную и чистую.",
		"usecase_3": "Сравнить с валовой маржой.",
		"faq_q1": "Sample / contoh?",
		"faq_a1": "30%",
		"faq_q2": "Markup vs margin?",
		"faq_a2": "Markup÷cost; margin÷revenue.",
		"faq_q3": "Why two types?",
		"faq_a3": "Same form; different cost stacks.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Калькулятор маржи прибыли — Чистая или операционная",
		"disclaimer": "Только учебная иллюстрация (margen) — не финансовый совет.",
		"references": "Investopedia и учебные формулы.",
		"ref_a_label": "Investopedia — Profit margin",
		"ref_b_label": "Investopedia — Operating margin",
	}),
	de: withBtns("de", {
		"type_label": "Margentyp",
		"type_net": "Nettomarge",
		"type_op": "Operative Marge",
		"rev_label": "Umsatz",
		"rev_ph": "z. B. 10000",
		"cost_label": "Kosten",
		"cost_ph": "z. B. 7000",
		"marginOut_label": "Marge %",
		"profitOut_label": "Gewinn",
		"result_note": "Marge = Gewinn ÷ Umsatz. Bildungszweck.",
		"err_generic": "Umsatz > 0 und Kosten ≥ 0.",
		"how_title": "So funktioniert’s",
		"how_body": "Margentyp wählen, Umsatz und Kosten eingeben. Marge = Gewinn / Umsatz × 100.",
		"formula_title": "Formel",
		"formula_body": "Marge % = (Umsatz − Kosten) / Umsatz × 100. Hinweise:",
		"formula_item_1": "Kosten zur gewählten Definition passend wählen.",
		"formula_item_2": "Umsatz > 0.",
		"formula_item_3": "Vereinfachte GuV.",
		"example_title": "Beispiel",
		"example": "Beispiel: Umsatz 10.000, Kosten 7.000 → Marge 30%.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Übung Nettomarge.",
		"usecase_2": "Operativ vs Netto vergleichen.",
		"usecase_3": "Mit Bruttomarge kontrastieren.",
		"faq_q1": "Beispielergebnis?",
		"faq_a1": "30%",
		"faq_q2": "Markup vs margin?",
		"faq_a2": "Markup÷cost; margin÷revenue.",
		"faq_q3": "Why two types?",
		"faq_a3": "Same form; different cost stacks.",
		"faq_q4": "Geschäftsberatung?",
		"faq_a4": "Educational only.",
		"article": "Gewinnmargen-Rechner — Netto oder operativ",
		"disclaimer": "Nur zur Veranschaulichung (margen) — keine Finanzberatung.",
		"references": "Investopedia und Lehrbuchformeln.",
		"ref_a_label": "Investopedia — Profit margin",
		"ref_b_label": "Investopedia — Operating margin",
	}),
};

export default {
	seq: 36,
	slug: "how-to-calculate-profit-margin",
	prefix: "tool_profit_margin",
	pageFile: "howToCalculateProfitMarginPage",
	pageExport: "renderHowToCalculateProfitMarginPage",
	nameZh: "利润率计算器",
	ymyl: true,
	related: ["how-to-calculate-gross-margin","how-to-calculate-markup"],
	anchor: "profit-margin",
	glyph: "M6 22V8h8v14M18 22V4h6",
	sampleHint: "revenue 10000 costs 7000 → net 30%",
	titles: {
		en: "Profit Margin Calculator — Net or Operating Margin",
		zh: "利润率计算器 — 净利率与营业利润率",
		es: "Calculadora de margen de beneficio — Neto u operativo",
		ar: "حاسبة هامش الربح — صافٍ أو تشغيلي",
		pt: "Calculadora de margem de lucro — Líquida ou operacional",
		id: "Kalkulator margin laba — Neto atau operasional",
		fr: "Calculateur de marge — Nette ou d’exploitation",
		ja: "利益率計算ツール — 純利益率と営業利益率",
		ru: "Калькулятор маржи прибыли — Чистая или операционная",
		de: "Gewinnmargen-Rechner — Netto oder operativ",
	},
	descriptions: {
		en: "Calculate net or operating profit margin from revenue and costs. Example: revenue 10,000 and costs 7,000 → net margin 30%. Pick the margin type on one page. Educational finance math — not business advice.",
		zh: "按收入与成本计算净利润率或营业利润率（类型可选）。示例：收入 10000、成本 7000 → 净利率 30%。同页切换类型，不拆近义 URL。浏览器本地计算；财务教育用，不构成经营建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。",
		es: "Calcula el margen neto u operativo con ingresos y costos. Ejemplo: ingresos 10.000 y costos 7.000 → margen neto 30%. Elige el tipo en una página. Matemáticas educativas.",
		ar: "احسب هامش الربح الصافي أو التشغيلي من الإيرادات والتكاليف. مثال: إيراد 10000 وتكلفة 7000 → هامش صافٍ 30٪. نوع الهامش في صفحة واحدة. تعليمي.",
		pt: "Calcule a margem líquida ou operacional com receita e custos. Exemplo: receita 10.000 e custos 7.000 → margem líquida 30%. Tipo na mesma página. Educativo.",
		id: "Hitung margin laba neto atau operasional dari pendapatan dan biaya. Contoh: pendapatan 10000, biaya 7000 → margin neto 30%. Jenis di satu halaman. Edukatif.",
		fr: "Calculez la marge nette ou d’exploitation à partir du chiffre d’affaires et des coûts. Exemple : CA 10 000 et coûts 7 000 → marge nette 30 %. Type sur une page. Éducatif.",
		ja: "売上と費用から純利益率または営業利益率を計算します。例：売上 10000、費用 7000 → 純利益率 30%。種類は同一ページのオプションです。学習用であり経営助言ではありません。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり投資・税務・経営の助言ではありません。",
		ru: "Считайте чистую или операционную маржу из выручки и затрат. Пример: выручка 10000, затраты 7000 → чистая маржа 30%. Тип на одной странице. Учебно.",
		de: "Berechnen Sie Netto- oder operative Marge aus Umsatz und Kosten. Beispiel: Umsatz 10.000, Kosten 7.000 → Nettomarge 30%. Typ auf einer Seite. Bildungszweck.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "type",
	    "type": "select",
	    "half": true,
	    "labelKey": "type_label",
	    "options": [
	      {
	        "value": "net",
	        "labelKey": "type_net",
	        "selected": true
	      },
	      {
	        "value": "operating",
	        "labelKey": "type_op"
	      }
	    ]
	  },
	  {
	    "id": "rev",
	    "type": "number",
	    "half": true,
	    "labelKey": "rev_label",
	    "phKey": "rev_ph"
	  },
	  {
	    "id": "cost",
	    "type": "number",
	    "half": true,
	    "labelKey": "cost_label",
	    "phKey": "cost_ph"
	  }
	],
	results: [
	  {
	    "id": "marginOut",
	    "labelKey": "marginOut_label"
	  },
	  {
	    "id": "profitOut",
	    "labelKey": "profitOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://www.investopedia.com/terms/p/profitmargin.asp"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.investopedia.com/terms/o/operatingmargin.asp"
	  }
	],
	computeJs: `
        var rev = parseFloat(revEl.value);
        var cost = parseFloat(costEl.value);
        if (!(rev > 0) || !Number.isFinite(cost) || cost < 0) return { ok: false, error: msgErr };
        var profit = rev - cost;
        var margin = (profit / rev) * 100;
        return { ok: true, values: { marginOut: fmt(margin) + '%', profitOut: fmt(profit) } };
`,
	sampleJs: `
        typeEl.value = 'net';
        revEl.value = '10000';
        costEl.value = '7000';
`,
};
