/**
 * §12 #30 how-to-calculate-pythagorean-theorem 工具定义（十语独立 UI）。
 * prefix: tool_pythagorean；page: howToCalculatePythagoreanTheoremPage / renderHowToCalculatePythagoreanTheoremPage。
 */
import { withBtns } from '../locale-ui-common.mjs';

/** 十语 UI（how/formula/faq/usecase 等须独立重写，禁止英模同构）。 */
const _ui = {
	ar: withBtns('ar', {
		"solve_label": "حل من أجل",
		"solve_c": "الوتر c",
		"solve_a": "الساق a",
		"solve_b": "الساق b",
		"known1_label": "الضلع المعروف الأول",
		"known1_ph": "مثال 3",
		"known2_label": "الضلع المعروف الثاني",
		"known2_ph": "مثال 4",
		"sideOut_label": "الضلع المفقود",
		"result_note": "مثلث قائم: a²+b²=c². عند حل ساق يجب أن يكون الوتر أطول.",
		"err_generic": "أدخل ضلعين موجبين؛ وعند حل ساق يجب أن يكون الوتر أكبر.",
		"how_title": "طريقة الاستخدام",
		"how_body": "اختر الضلع المفقود وأدخل الضلعين الآخرين. لـ c: a وb؛ لـ a: b وc؛ لـ b: a وc. يُرجع الجذر الموجب.",
		"formula_title": "الصيغة",
		"formula_body": "نظرية فيثاغورس a²+b²=c²:",
		"formula_item_1": "نقص c: c=√(a²+b²).",
		"formula_item_2": "نقص a: a=√(c²−b²) مع c>b>0.",
		"formula_item_3": "نقص b: b=√(c²−a²) مع c>a>0.",
		"formula_item_4": "أطوال حقيقية موجبة فقط.",
		"example_title": "مثال",
		"example": "مثال: a=3 وb=4 → c=5.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "هندسة: إيجاد ضلع ناقص.",
		"usecase_2": "التحقق من ثلاثيات 3-4-5.",
		"usecase_3": "تقدير القطر من ساقين متعامدين.",
		"disclaimer": "هندسة إقليدية تعليمية فقط.",
		"references": "ويكيبيديا نظرية فيثاغورس.",
		"ref_py_label": "ويكيبيديا — نظرية فيثاغورس",
		"ref_rt_label": "ويكيبيديا — مثلث قائم",
		"article": "حل الضلع المفقود لمثلث قائم عبر a²+b²=c².",
		"faq_q1": "ماذا أُدخل لإيجاد c؟",
		"faq_a1": "أدخِل الساقين a وb.",
		"faq_q2": "هل تُشترط الوحدات؟",
		"faq_a2": "لا؛ أبقِ الضلعين المعروفين بنفس الوحدة.",
		"faq_q3": "هل للمثلثات المنفرجة؟",
		"faq_a3": "لا؛ فقط علاقة قائم الزاوية a²+b²=c².",
		"faq_q4": "لماذا يُرفض c≤a؟",
		"faq_a4": "يجب أن يكون الوتر أطول بصرامة من كل ساق.",
	}),
	de: withBtns('de', {
		"solve_label": "Lösen nach",
		"solve_c": "Hypotenuse c",
		"solve_a": "Kathete a",
		"solve_b": "Kathete b",
		"known1_label": "Erste bekannte Seite",
		"known1_ph": "z. B. 3",
		"known2_label": "Zweite bekannte Seite",
		"known2_ph": "z. B. 4",
		"sideOut_label": "Fehlende Seite",
		"result_note": "Rechtwinkliges Dreieck: a²+b²=c². Beim Lösen einer Kathete muss die Hypotenuse länger sein.",
		"err_generic": "Zwei positive Seiten eingeben; beim Lösen einer Kathete muss die Hypotenuse größer sein.",
		"how_title": "So funktioniert’s",
		"how_body": "Wählen Sie die fehlende Seite und geben Sie die beiden anderen ein. Für c: a und b; für a: b und c; für b: a und c. Liefert die positive Wurzel.",
		"formula_title": "Formel",
		"formula_body": "Satz des Pythagoras a²+b²=c²:",
		"formula_item_1": "Fehlt c: c=√(a²+b²).",
		"formula_item_2": "Fehlt a: a=√(c²−b²) mit c>b>0.",
		"formula_item_3": "Fehlt b: b=√(c²−a²) mit c>a>0.",
		"formula_item_4": "Nur positive reelle Längen.",
		"example_title": "Beispiel",
		"example": "Beispiel: a=3, b=4 → c=5.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Geometrie: fehlende Seite finden.",
		"usecase_2": "3-4-5-Tripel prüfen.",
		"usecase_3": "Diagonale aus zwei orthogonalen Katheten schätzen.",
		"disclaimer": "Nur euklidische Lerngeometrie.",
		"references": "Wikipedia Satz des Pythagoras.",
		"ref_py_label": "Wikipedia — Satz des Pythagoras",
		"ref_rt_label": "Wikipedia — Rechtwinkliges Dreieck",
		"article": "Berechnen Sie die fehlende Seite eines rechtwinkligen Dreiecks mit a²+b²=c².",
		"faq_q1": "Eingaben für c?",
		"faq_a1": "Die Katheten a und b.",
		"faq_q2": "Einheiten nötig?",
		"faq_a2": "Nein; beide bekannten Seiten in derselben Einheit.",
		"faq_q3": "Stumpfe Dreiecke?",
		"faq_a3": "Nein — nur die Rechtwinkelbeziehung a²+b²=c².",
		"faq_q4": "Warum c≤a ablehnen?",
		"faq_a4": "Die Hypotenuse muss strikt länger als jede Kathete sein.",
	}),
	en: withBtns('en', {
		"solve_label": "Solve for",
		"solve_c": "Hypotenuse c",
		"solve_a": "Leg a",
		"solve_b": "Leg b",
		"known1_label": "First known side",
		"known1_ph": "e.g. 3",
		"known2_label": "Second known side",
		"known2_ph": "e.g. 4",
		"sideOut_label": "Missing side",
		"result_note": "Right triangle: a² + b² = c². For leg unknowns, the hypotenuse must be longer than the other leg.",
		"err_generic": "Enter two positive finite sides; when solving a leg, hypotenuse must be larger.",
		"how_title": "How it works",
		"how_body": "Choose which side is missing. Enter the other two positive lengths. For c, inputs are legs a and b; for a, inputs are b and c; for b, inputs are a and c. Returns the positive square-root solution.",
		"formula_title": "Formula",
		"formula_body": "Pythagorean theorem a² + b² = c²:",
		"formula_item_1": "Missing c: c = √(a² + b²).",
		"formula_item_2": "Missing a: a = √(c² − b²) with c > b > 0.",
		"formula_item_3": "Missing b: b = √(c² − a²) with c > a > 0.",
		"formula_item_4": "Only real positive lengths; not a full trigonometry suite.",
		"example_title": "Example",
		"example": "Example: a = 3, b = 4 → c = 5.",
		"usecases_title": "When to use it",
		"usecase_1": "Geometry homework: find a missing right-triangle side.",
		"usecase_2": "Quick check of 3-4-5 style triples.",
		"usecase_3": "Estimate diagonal length from two orthogonal legs.",
		"disclaimer": "Educational Euclidean plane geometry only.",
		"references": "Wikipedia Pythagorean theorem.",
		"ref_py_label": "Wikipedia — Pythagorean theorem",
		"ref_rt_label": "Wikipedia — Right triangle",
		"article": "Solve for a missing side of a right triangle with a² + b² = c².",
		"faq_q1": "Which inputs when solving for c?",
		"faq_a1": "Enter legs a and b as the two known sides.",
		"faq_q2": "Why reject c ≤ a?",
		"faq_a2": "A hypotenuse must be strictly longer than each leg.",
		"faq_q3": "Are units required?",
		"faq_a3": "No — keep both known sides in the same unit.",
		"faq_q4": "Does this handle obtuse triangles?",
		"faq_a4": "No — only the right-triangle relation a²+b²=c².",
	}),
	es: withBtns('es', {
		"solve_label": "Resolver",
		"solve_c": "Hipotenusa c",
		"solve_a": "Cateto a",
		"solve_b": "Cateto b",
		"known1_label": "Primer lado conocido",
		"known1_ph": "p. ej. 3",
		"known2_label": "Segundo lado conocido",
		"known2_ph": "p. ej. 4",
		"sideOut_label": "Lado faltante",
		"result_note": "Triángulo rectángulo: a²+b²=c². Si falta un cateto, la hipotenusa debe ser mayor.",
		"err_generic": "Introduce dos lados positivos; al resolver un cateto, la hipotenusa debe ser mayor.",
		"how_title": "Cómo funciona",
		"how_body": "Elige el lado que falta e introduce los otros dos. Para c: a y b; para a: b y c; para b: a y c. Devuelve la raíz positiva.",
		"formula_title": "Fórmula",
		"formula_body": "Teorema de Pitágoras a²+b²=c²:",
		"formula_item_1": "Falta c: c=√(a²+b²).",
		"formula_item_2": "Falta a: a=√(c²−b²) con c>b>0.",
		"formula_item_3": "Falta b: b=√(c²−a²) con c>a>0.",
		"formula_item_4": "Solo longitudes reales positivas.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: a=3, b=4 → c=5.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Geometría: hallar un lado faltante.",
		"usecase_2": "Comprobar triples 3-4-5.",
		"usecase_3": "Estimar una diagonal con dos catetos.",
		"disclaimer": "Solo geometría euclídea educativa.",
		"references": "Wikipedia teorema de Pitágoras.",
		"ref_py_label": "Wikipedia — Teorema de Pitágoras",
		"ref_rt_label": "Wikipedia — Triángulo rectángulo",
		"article": "Resuelve el lado faltante de un triángulo rectángulo con a²+b²=c².",
		"faq_q1": "¿Sirve para triángulos obtusos?",
		"faq_a1": "No; solo la relación de rectángulo a²+b²=c².",
		"faq_q2": "¿Qué datos si busco c?",
		"faq_a2": "Los catetos a y b.",
		"faq_q3": "¿Por qué rechazar c≤a?",
		"faq_a3": "La hipotenusa debe ser estrictamente mayor que cada cateto.",
		"faq_q4": "¿Hacen falta unidades?",
		"faq_a4": "No; usa la misma unidad en ambos lados.",
	}),
	fr: withBtns('fr', {
		"solve_label": "Résoudre",
		"solve_c": "Hypoténuse c",
		"solve_a": "Côté a",
		"solve_b": "Côté b",
		"known1_label": "Premier côté connu",
		"known1_ph": "ex. 3",
		"known2_label": "Deuxième côté connu",
		"known2_ph": "ex. 4",
		"sideOut_label": "Côté manquant",
		"result_note": "Triangle rectangle : a²+b²=c². Pour un côté, l’hypoténuse doit être plus longue.",
		"err_generic": "Saisissez deux côtés positifs ; pour un côté, l’hypoténuse doit être plus grande.",
		"how_title": "Fonctionnement",
		"how_body": "Choisissez le côté manquant et entrez les deux autres. Pour c : a et b ; pour a : b et c ; pour b : a et c. Renvoie la racine positive.",
		"formula_title": "Formule",
		"formula_body": "Théorème de Pythagore a²+b²=c² :",
		"formula_item_1": "Manque c : c=√(a²+b²).",
		"formula_item_2": "Manque a : a=√(c²−b²) avec c>b>0.",
		"formula_item_3": "Manque b : b=√(c²−a²) avec c>a>0.",
		"formula_item_4": "Longueurs réelles positives seulement.",
		"example_title": "Exemple",
		"example": "Exemple : a=3, b=4 → c=5.",
		"usecases_title": "Quand l’utiliser",
		"usecase_1": "Géométrie : trouver un côté manquant.",
		"usecase_2": "Vérifier des triplets 3-4-5.",
		"usecase_3": "Estimer une diagonale avec deux côtés orthogonaux.",
		"disclaimer": "Géométrie euclidienne pédagogique seulement.",
		"references": "Wikipedia théorème de Pythagore.",
		"ref_py_label": "Wikipedia — Théorème de Pythagore",
		"ref_rt_label": "Wikipedia — Triangle rectangle",
		"article": "Résolvez le côté manquant d’un triangle rectangle avec a²+b²=c².",
		"faq_q1": "Que saisir pour trouver c ?",
		"faq_a1": "Les côtés a et b.",
		"faq_q2": "Unités obligatoires ?",
		"faq_a2": "Non ; gardez la même unité pour les deux côtés.",
		"faq_q3": "Triangles obtus ?",
		"faq_a3": "Non — seulement a²+b²=c² pour un triangle rectangle.",
		"faq_q4": "Pourquoi refuser c≤a ?",
		"faq_a4": "L’hypoténuse doit être strictement plus longue que chaque côté.",
	}),
	id: withBtns('id', {
		"solve_label": "Selesaikan",
		"solve_c": "Sisi miring c",
		"solve_a": "Kaki a",
		"solve_b": "Kaki b",
		"known1_label": "Sisi diketahui pertama",
		"known1_ph": "mis. 3",
		"known2_label": "Sisi diketahui kedua",
		"known2_ph": "mis. 4",
		"sideOut_label": "Sisi yang dicari",
		"result_note": "Segitiga siku-siku: a²+b²=c². Saat mencari kaki, sisi miring harus lebih panjang.",
		"err_generic": "Masukkan dua sisi positif; saat mencari kaki, sisi miring harus lebih besar.",
		"how_title": "Cara kerja",
		"how_body": "Pilih sisi yang hilang dan masukkan dua sisi lain. Untuk c: a dan b; untuk a: b dan c; untuk b: a dan c. Mengembalikan akar positif.",
		"formula_title": "Rumus",
		"formula_body": "Teorema Pythagoras a²+b²=c²:",
		"formula_item_1": "Cari c: c=√(a²+b²).",
		"formula_item_2": "Cari a: a=√(c²−b²) dengan c>b>0.",
		"formula_item_3": "Cari b: b=√(c²−a²) dengan c>a>0.",
		"formula_item_4": "Hanya panjang real positif.",
		"example_title": "Contoh",
		"example": "Contoh: a=3, b=4 → c=5.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Geometri: cari sisi yang hilang.",
		"usecase_2": "Cek tripels 3-4-5.",
		"usecase_3": "Perkiraan diagonal dari dua kaki tegak lurus.",
		"disclaimer": "Hanya geometri Euclid edukasi.",
		"references": "Wikipedia Pythagorean theorem.",
		"ref_py_label": "Wikipedia — Pythagorean theorem",
		"ref_rt_label": "Wikipedia — Right triangle",
		"article": "Selesaikan sisi hilang segitiga siku-siku dengan a²+b²=c².",
		"faq_q1": "Input apa untuk mencari c?",
		"faq_a1": "Masukkan kaki a dan b.",
		"faq_q2": "Mengapa menolak c≤a?",
		"faq_a2": "Sisi miring harus lebih panjang dari setiap kaki.",
		"faq_q3": "Untuk segitiga tumpul?",
		"faq_a3": "Tidak; hanya relasi siku-siku a²+b²=c².",
		"faq_q4": "Satuan wajib?",
		"faq_a4": "Tidak; pakai satuan yang sama pada kedua sisi.",
	}),
	ja: withBtns('ja', {
		"solve_label": "求める辺",
		"solve_c": "斜辺 c",
		"solve_a": "直角辺 a",
		"solve_b": "直角辺 b",
		"known1_label": "既知の辺 1",
		"known1_ph": "例: 3",
		"known2_label": "既知の辺 2",
		"known2_ph": "例: 4",
		"sideOut_label": "求める辺の長さ",
		"result_note": "直角三角形 a²+b²=c²。直角辺を求めるときは斜辺がもう一方より長い必要あり。",
		"err_generic": "正の有限な二辺を入力。直角辺を求めるときは斜辺の方が大きく。",
		"how_title": "使い方",
		"how_body": "欠けている辺を選び、残りの二辺を入れます。c なら a と b、a なら b と c、b なら a と c。正の平方根解を返します。",
		"formula_title": "公式",
		"formula_body": "三平方の定理 a²+b²=c²：",
		"formula_item_1": "c が未知：c=√(a²+b²)。",
		"formula_item_2": "a が未知：a=√(c²−b²)、c>b>0。",
		"formula_item_3": "b が未知：b=√(c²−a²)、c>a>0。",
		"formula_item_4": "正の実辺のみ。三角法一式ではありません。",
		"example_title": "例",
		"example": "例：a=3、b=4 → c=5。",
		"usecases_title": "こんなときに",
		"usecase_1": "図形：直角三角形の欠けた辺を求める。",
		"usecase_2": "3-4-5 型の検算。",
		"usecase_3": "直交二辺から対角線を見積もる。",
		"disclaimer": "ユークリッド平面幾何の学習用途のみ。",
		"references": "Wikipedia のピタゴラスの定理。",
		"ref_py_label": "Wikipedia — ピタゴラスの定理",
		"ref_rt_label": "Wikipedia — 直角三角形",
		"article": "a²+b²=c² で直角三角形の欠けた辺を求めます。",
		"faq_q1": "鈍角三角形でも使える？",
		"faq_a1": "いいえ。直角の a²+b²=c² のみです。",
		"faq_q2": "c を求める入力は？",
		"faq_a2": "直角辺 a と b を入れます。",
		"faq_q3": "単位は必須？",
		"faq_a3": "不要。二つの既知辺を同じ単位にしてください。",
		"faq_q4": "なぜ c≤a を拒否？",
		"faq_a4": "斜辺は各直角辺より厳密に長くなければなりません。",
	}),
	pt: withBtns('pt', {
		"solve_label": "Resolver",
		"solve_c": "Hipotenusa c",
		"solve_a": "Cateto a",
		"solve_b": "Cateto b",
		"known1_label": "Primeiro lado conhecido",
		"known1_ph": "ex.: 3",
		"known2_label": "Segundo lado conhecido",
		"known2_ph": "ex.: 4",
		"sideOut_label": "Lado faltante",
		"result_note": "Triângulo retângulo: a²+b²=c². Ao resolver um cateto, a hipotenusa deve ser maior.",
		"err_generic": "Informe dois lados positivos; ao resolver um cateto, a hipotenusa deve ser maior.",
		"how_title": "Como funciona",
		"how_body": "Escolha o lado faltante e digite os outros dois. Para c: a e b; para a: b e c; para b: a e c. Devolve a raiz positiva.",
		"formula_title": "Fórmula",
		"formula_body": "Teorema de Pitágoras a²+b²=c²:",
		"formula_item_1": "Falta c: c=√(a²+b²).",
		"formula_item_2": "Falta a: a=√(c²−b²) com c>b>0.",
		"formula_item_3": "Falta b: b=√(c²−a²) com c>a>0.",
		"formula_item_4": "Apenas comprimentos reais positivos.",
		"example_title": "Exemplo",
		"example": "Exemplo: a=3, b=4 → c=5.",
		"usecases_title": "Quando usar",
		"usecase_1": "Geometria: achar lado faltante.",
		"usecase_2": "Checar triplas 3-4-5.",
		"usecase_3": "Estimar diagonal com dois catetos.",
		"disclaimer": "Apenas geometria euclidiana educativa.",
		"references": "Wikipedia teorema de Pitágoras.",
		"ref_py_label": "Wikipedia — Teorema de Pitágoras",
		"ref_rt_label": "Wikipedia — Triângulo retângulo",
		"article": "Resolva o lado faltante de um triângulo retângulo com a²+b²=c².",
		"faq_q1": "Unidades são obrigatórias?",
		"faq_a1": "Não; use a mesma unidade nos dois lados conhecidos.",
		"faq_q2": "O que informar para achar c?",
		"faq_a2": "Os catetos a e b.",
		"faq_q3": "Serve para triângulo obtuso?",
		"faq_a3": "Não — só a relação do retângulo a²+b²=c².",
		"faq_q4": "Por que rejeitar c≤a?",
		"faq_a4": "A hipotenusa deve ser estritamente maior que cada cateto.",
	}),
	ru: withBtns('ru', {
		"solve_label": "Найти",
		"solve_c": "Гипотенузу c",
		"solve_a": "Катет a",
		"solve_b": "Катет b",
		"known1_label": "Первая известная сторона",
		"known1_ph": "напр. 3",
		"known2_label": "Вторая известная сторона",
		"known2_ph": "напр. 4",
		"sideOut_label": "Недостающая сторона",
		"result_note": "Прямоугольный треугольник: a²+b²=c². При поиске катета гипотенуза должна быть длиннее.",
		"err_generic": "Введите две положительные стороны; при поиске катета гипотенуза должна быть больше.",
		"how_title": "Как пользоваться",
		"how_body": "Выберите недостающую сторону и введите две другие. Для c — a и b; для a — b и c; для b — a и c. Возвращает положительный корень.",
		"formula_title": "Формула",
		"formula_body": "Теорема Пифагора a²+b²=c²:",
		"formula_item_1": "Нет c: c=√(a²+b²).",
		"formula_item_2": "Нет a: a=√(c²−b²) при c>b>0.",
		"formula_item_3": "Нет b: b=√(c²−a²) при c>a>0.",
		"formula_item_4": "Только положительные вещественные длины.",
		"example_title": "Пример",
		"example": "Пример: a=3, b=4 → c=5.",
		"usecases_title": "Когда применять",
		"usecase_1": "Геометрия: найти недостающую сторону.",
		"usecase_2": "Проверить тройки 3-4-5.",
		"usecase_3": "Оценить диагональ по двум катетам.",
		"disclaimer": "Только учебная евклидова планиметрия.",
		"references": "Wikipedia о теореме Пифагора.",
		"ref_py_label": "Wikipedia — Теорема Пифагора",
		"ref_rt_label": "Wikipedia — Прямоугольный треугольник",
		"article": "Найдите недостающую сторону прямоугольного треугольника по a²+b²=c².",
		"faq_q1": "Что вводить для c?",
		"faq_a1": "Катеты a и b.",
		"faq_q2": "Нужны ли единицы?",
		"faq_a2": "Нет; обе известные стороны в одной единице.",
		"faq_q3": "Почему отказ при c≤a?",
		"faq_a3": "Гипотенуза должна быть строго длиннее каждого катета.",
		"faq_q4": "Тупоугольные треугольники?",
		"faq_a4": "Нет — только соотношение прямоугольного a²+b²=c².",
	}),
	zh: withBtns('zh', {
		"solve_label": "求解",
		"solve_c": "斜边 c",
		"solve_a": "直角边 a",
		"solve_b": "直角边 b",
		"known1_label": "第一条已知边",
		"known1_ph": "例如 3",
		"known2_label": "第二条已知边",
		"known2_ph": "例如 4",
		"sideOut_label": "所求边",
		"result_note": "直角三角形 a²+b²=c²。求直角边时，斜边必须长于另一已知直角边。",
		"err_generic": "请输入两条有限正边长；求直角边时斜边必须更大。",
		"how_title": "怎么用",
		"how_body": "选择所缺边。输入另外两条正长度。求 c 时输入 a、b；求 a 时输入 b、c；求 b 时输入 a、c。返回正的平方根解。",
		"formula_title": "公式",
		"formula_body": "勾股定理 a²+b²=c²：",
		"formula_item_1": "缺 c：c=√(a²+b²)。",
		"formula_item_2": "缺 a：a=√(c²−b²)，且 c>b>0。",
		"formula_item_3": "缺 b：b=√(c²−a²)，且 c>a>0。",
		"formula_item_4": "仅实数正边长，不是完整三角学套件。",
		"example_title": "示例",
		"example": "示例：a=3，b=4 → c=5。",
		"usecases_title": "适合什么场景",
		"usecase_1": "几何作业：求直角三角形缺边。",
		"usecase_2": "快速核对 3-4-5 型勾股数。",
		"usecase_3": "由两条正交边估对角线。",
		"disclaimer": "仅为欧氏平面几何教育用途。",
		"references": "维基百科勾股定理。",
		"ref_py_label": "维基百科 — 勾股定理",
		"ref_rt_label": "维基百科 — 直角三角形",
		"article": "用 a²+b²=c² 求直角三角形的缺边。",
		"faq_q1": "求斜边时输入什么？",
		"faq_a1": "输入两条直角边 a 与 b。",
		"faq_q2": "单位必须填吗？",
		"faq_a2": "不必，两已知边用同一单位即可。",
		"faq_q3": "为什么拒绝 c≤a？",
		"faq_a3": "斜边必须严格长于每一条直角边。",
		"faq_q4": "钝角三角形可用吗？",
		"faq_a4": "否，仅直角三角形 a²+b²=c²。",
	}),
};

export default {
	seq: 30,
	slug: "how-to-calculate-pythagorean-theorem",
	prefix: "tool_pythagorean",
	nameZh: "勾股定理计算器",
	category: 'calculator',
	ymyl: false,
	pageFile: "howToCalculatePythagoreanTheoremPage",
	pageExport: "renderHowToCalculatePythagoreanTheoremPage",
	anchor: "pythagorean-theorem",
	related: ["how-to-calculate-aspect-ratio", "how-to-calculate-logarithm"],
	glyph: "M6 26V6h20",
	sampleHint: "a=3,b=4 \u2192 c=5",
	titles: {
		"en": "Pythagorean Theorem Calculator — How to Find a Missing Side",
		"zh": "勾股定理计算器 — 如何求直角三角形缺边",
		"es": "Calculadora de Pitágoras — Cómo hallar el lado faltante",
		"ar": "حاسبة فيثاغورس — كيفية إيجاد الضلع المفقود",
		"pt": "Calculadora de Pitágoras — Como achar o lado faltante",
		"id": "Kalkulator Pythagoras — Cara mencari sisi yang hilang",
		"fr": "Calculateur de Pythagore — Trouver le côté manquant",
		"ja": "三平方の定理計算ツール — 欠けた辺の求め方",
		"ru": "Калькулятор Пифагора — Как найти недостающую сторону",
		"de": "Pythagoras-Rechner — Fehlende Seite finden"
	},
	descriptions: {
		"en": "Solve for missing side a, b, or c in a right triangle with a² + b² = c². Example: a = 3, b = 4 → c = 5. Enter two known positive sides; rejects impossible leg/hypotenuse pairs. Browser learning tool.",
		"zh": "用勾股定理 a²+b²=c² 求直角三角形缺边 a、b 或 c。示例：a=3、b=4 → c=5。输入两条已知正边长；不合法的直角边/斜边组合会被拒绝。浏览器内计算，适合作业与 3-4-5 型快速核对，并写明求直角边时斜边须更长于另一已知边。",
		"es": "Resuelve el lado faltante a, b o c con a²+b²=c². Ejemplo: a=3, b=4 → c=5. Introduce dos lados positivos; rechaza pares imposibles. En el navegador, para clase.",
		"ar": "حل الضلع المفقود a أو b أو c عبر a²+b²=c². مثال: a=3 وb=4 → c=5. أدخل ضلعين موجبين؛ تُرفض الأزواج المستحيلة. في المتصفح للتعلّم.",
		"pt": "Resolva o lado faltante a, b ou c com a²+b²=c². Exemplo: a=3, b=4 → c=5. Informe dois lados positivos; rejeita pares impossíveis. No navegador, para estudo.",
		"id": "Selesaikan sisi hilang a, b, atau c dengan a²+b²=c². Contoh: a=3, b=4 → c=5. Masukkan dua sisi positif; menolak pasangan mustahil. Di browser untuk tugas.",
		"fr": "Résolvez le côté manquant a, b ou c avec a²+b²=c². Exemple : a=3, b=4 → c=5. Entrez deux côtés positifs ; refuse les paires impossibles. Dans le navigateur.",
		"ja": "直角三角形の欠けた辺 a・b・c を a²+b²=c² で求めます。例：a=3、b=4 → c=5。既知の正の二辺を入力し、あり得ない斜辺/直角辺の組は拒否。ブラウザ内で宿題や 3-4-5 の検算向けで、直角辺を求めるときは斜辺が長いことを明示します。",
		"ru": "Найдите недостающую сторону a, b или c по a²+b²=c². Пример: a=3, b=4 → c=5. Введите две положительные стороны; невозможные пары отвергаются. В браузере для учёбы.",
		"de": "Berechnen Sie die fehlende Seite a, b oder c mit a²+b²=c². Beispiel: a=3, b=4 → c=5. Zwei positive Seiten; unmögliche Paare werden abgelehnt. Im Browser zum Lernen."
	},
	ui: _ui,
	fields: [
		{
			"id": "solve",
			"type": "select",
			"half": true,
			"labelKey": "solve_label",
			"options": [
				{
					"value": "c",
					"labelKey": "solve_c",
					"selected": true
				},
				{
					"value": "a",
					"labelKey": "solve_a"
				},
				{
					"value": "b",
					"labelKey": "solve_b"
				}
			]
		},
		{
			"id": "known1",
			"type": "number",
			"half": true,
			"labelKey": "known1_label",
			"phKey": "known1_ph"
		},
		{
			"id": "known2",
			"type": "number",
			"half": true,
			"labelKey": "known2_label",
			"phKey": "known2_ph"
		}
	],
	results: [
		{
			"id": "sideOut",
			"labelKey": "sideOut_label"
		}
	],
	refs: [
		{
			"labelKey": "ref_py_label",
			"href": "https://en.wikipedia.org/wiki/Pythagorean_theorem"
		},
		{
			"labelKey": "ref_rt_label",
			"href": "https://en.wikipedia.org/wiki/Right_triangle"
		}
	],
	computeJs: `
        var solve = solveEl.value;
        var k1 = parseFloat(known1El.value);
        var k2 = parseFloat(known2El.value);
        if (!(k1 > 0) || !(k2 > 0) || !Number.isFinite(k1) || !Number.isFinite(k2)) {
          return { ok: false, error: msgErr };
        }
        var out;
        if (solve === 'c') {
          out = Math.sqrt(k1 * k1 + k2 * k2);
        } else if (solve === 'a') {
          if (!(k2 > k1)) return { ok: false, error: msgErr };
          out = Math.sqrt(k2 * k2 - k1 * k1);
        } else {
          if (!(k2 > k1)) return { ok: false, error: msgErr };
          out = Math.sqrt(k2 * k2 - k1 * k1);
        }
        if (!Number.isFinite(out) || !(out > 0)) return { ok: false, error: msgErr };
        return { ok: true, values: { sideOut: fmt(out, 6) } };
`,
	sampleJs: `
        solveEl.value = 'c';
        known1El.value = '3';
        known2El.value = '4';
`,
};
