/**
 * §12 #44 how-to-calculate-rule-of-72
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"rate_label": "Annual rate %",
		"rate_ph": "e.g. 6",
		"yearsOut_label": "Approx. years to double",
		"result_note": "Years ≈ 72 / rate%. Rule-of-thumb only — not a precise compound forecast.",
		"err_generic": "Enter a rate > 0.",
		"how_title": "How it works",
		"how_body": "Enter an annual percentage rate. The classic Rule of 72 divides 72 by that rate to sketch doubling time.",
		"formula_title": "Formula",
		"formula_body": "Years ≈ 72 / r_percent. Notes:",
		"formula_item_1": "Works best for moderate rates; very high/low rates are less accurate.",
		"formula_item_2": "Assumes annual compounding style intuition, not a full schedule.",
		"formula_item_3": "Compare with compound-interest / CAGR tools for precise math.",
		"example_title": "Example",
		"example": "Example: rate 6% → 72/6 = 12 years.",
		"usecases_title": "When to use it",
		"usecase_1": "Classroom doubling-time intuition.",
		"usecase_2": "Quick sketch before precise FV math.",
		"usecase_3": "Pair with CAGR and compound interest.",
		"faq_q1": "Sample?",
		"faq_a1": "6% → 12 years.",
		"faq_q2": "Exact?",
		"faq_a2": "No — a teaching approximation.",
		"faq_q3": "Why 72?",
		"faq_a3": "A convenient number near the natural-log doubling math.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Rule of 72",
		"disclaimer": "Educational rule of 72 only — not financial, tax, or investment advice.",
		"references": "Investopedia and standard textbook formulas.",
		"ref_a_label": "Investopedia — Rule of 72",
		"ref_b_label": "Investopedia — Compound interest",
	}),
	zh: withBtns("zh", {
		"rate_label": "年化收益率 %",
		"rate_ph": "例如 6",
		"yearsOut_label": "约需年数（翻倍）",
		"result_note": "年数 ≈ 72 / 利率%。经验法则，非精确复利预测。",
		"err_generic": "请填写利率 > 0。",
		"how_title": "怎么用",
		"how_body": "填入年化百分比，用 72÷利率 估算翻倍年数。",
		"formula_title": "公式",
		"formula_body": "年数 ≈ 72 / r%。注意：",
		"formula_item_1": "中等利率更准；极高/极低误差大。",
		"formula_item_2": "不是完整复利表。",
		"formula_item_3": "精确计算请用复利/CAGR 工具。",
		"example_title": "示例",
		"example": "示例：6% → 72/6 = 12 年。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂翻倍直觉。",
		"usecase_2": "精确 FV 前的速算。",
		"usecase_3": "与 CAGR/复利对照。",
		"faq_q1": "样例？",
		"faq_a1": "6% → 12 年。",
		"faq_q2": "精确吗？",
		"faq_a2": "教学近似。",
		"faq_q3": "为何是 72？",
		"faq_a3": "接近对数翻倍的方便整数。",
		"faq_q4": "投资建议？",
		"faq_a4": "不是。",
		"article": "72 法则",
		"disclaimer": "结果仅为72法则学习演示，不构成投资、理财或税务建议。",
		"references": "Investopedia 与常见教材公式。",
		"ref_a_label": "Investopedia — Rule of 72",
		"ref_b_label": "Investopedia — Compound interest",
	}),
	es: withBtns("es", {
		"rate_label": "Tasa anual %",
		"rate_ph": "p. ej. 6",
		"yearsOut_label": "Años aprox. para duplicar",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce la tasa anual.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce la tasa anual.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: 6% → 12 años.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: 6% → 12 años.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de la regla del 72",
		"disclaimer": "Solo ilustración educativa (rule of 72); no es consejo financiero.",
		"references": "Investopedia y fórmulas de libro.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ar: withBtns("ar", {
		"rate_label": "المعدل السنوي %",
		"rate_ph": "مثال 6",
		"yearsOut_label": "سنوات تقريبية للمضاعفة",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل المعدل السنوي.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل المعدل السنوي.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: 6٪ → 12 سنة.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: 6٪ → 12 سنة.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة قاعدة 72",
		"disclaimer": "توضيح تعليمي فقط (rule of 72) وليس نصيحة مالية.",
		"references": "Investopedia وصيغ دراسية.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	pt: withBtns("pt", {
		"rate_label": "Taxa anual %",
		"rate_ph": "ex. 6",
		"yearsOut_label": "Anos aprox. para dobrar",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe a taxa anual.",
		"formula_title": "Fórmula",
		"formula_body": "Informe a taxa anual.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: 6% → 12 anos.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: 6% → 12 anos.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora da regra dos 72",
		"disclaimer": "Apenas ilustração educativa (rule of 72); não é conselho financeiro.",
		"references": "Investopedia e fórmulas didáticas.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	id: withBtns("id", {
		"rate_label": "Suku bunga tahunan %",
		"rate_ph": "mis. 6",
		"yearsOut_label": "Perkiraan tahun untuk dobel",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi suku bunga tahunan.",
		"formula_title": "Rumus",
		"formula_body": "Isi suku bunga tahunan.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: 6% → 12 tahun.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: 6% → 12 tahun.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator aturan 72",
		"disclaimer": "Hanya ilustrasi edukatif (rule of 72); bukan saran keuangan.",
		"references": "Investopedia dan rumus buku teks.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	fr: withBtns("fr", {
		"rate_label": "Taux annuel %",
		"rate_ph": "ex. 6",
		"yearsOut_label": "Années approx. pour doubler",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez le taux annuel.",
		"formula_title": "Formule",
		"formula_body": "Saisissez le taux annuel.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : 6 % → 12 ans.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : 6 % → 12 ans.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de la règle de 72",
		"disclaimer": "Illustration éducative (rule of 72) uniquement — pas un conseil financier.",
		"references": "Investopedia et formules de manuel.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ja: withBtns("ja", {
		"rate_label": "年利 %",
		"rate_ph": "例 6",
		"yearsOut_label": "倍増までのおおよその年数",
		"result_note": "年数 ≈ 72 / 利率%。経験則であり精密予測ではありません。",
		"err_generic": "利率 > 0 を入力。",
		"how_title": "使い方",
		"how_body": "年率を入れ、72÷利率で倍増年数をざっくり見ます。",
		"formula_title": "計算式",
		"formula_body": "年数 ≈ 72 / r%。注意:",
		"formula_item_1": "中程度の利率で精度が良い。",
		"formula_item_2": "完全な複利表ではない。",
		"formula_item_3": "精密計算は複利/CAGRへ。",
		"example_title": "例",
		"example": "例：6% → 72/6 = 12年。",
		"usecases_title": "こんなときに",
		"usecase_1": "授業での倍増の直感。",
		"usecase_2": "精密FVの前の速算。",
		"usecase_3": "CAGR/複利と併用。",
		"faq_q1": "例は？",
		"faq_a1": "6%→12年。",
		"faq_q2": "正確？",
		"faq_a2": "学習用の近似。",
		"faq_q3": "なぜ72？",
		"faq_a3": "対数的倍増に近い便利な数。",
		"faq_q4": "助言？",
		"faq_a4": "学習用です。",
		"article": "72の法則",
		"disclaimer": "72の法則の学習用試算であり、投資・税務の助言ではありません。",
		"references": "Investopedia と標準的な教科書公式。",
		"ref_a_label": "Investopedia — Rule of 72",
		"ref_b_label": "Investopedia — Compound interest",
	}),
	ru: withBtns("ru", {
		"rate_label": "Годовая ставка %",
		"rate_ph": "напр. 6",
		"yearsOut_label": "Прибл. годы до удвоения",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите годовую ставку.",
		"formula_title": "Формула",
		"formula_body": "Введите годовую ставку.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: 6% → 12 лет.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: 6% → 12 лет.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор правила 72",
		"disclaimer": "Только учебная иллюстрация (rule of 72) — не финансовый совет.",
		"references": "Investopedia и учебные формулы.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	de: withBtns("de", {
		"rate_label": "Jahreszins %",
		"rate_ph": "z. B. 6",
		"yearsOut_label": "Ca. Jahre bis Verdopplung",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Jahreszins eingeben.",
		"formula_title": "Formel",
		"formula_body": "Jahreszins eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: 6% → 12 Jahre.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: 6% → 12 Jahre.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "72er-Regel-Rechner",
		"disclaimer": "Nur zur Veranschaulichung (rule of 72) — keine Finanzberatung.",
		"references": "Investopedia und Lehrbuchformeln.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
};
export default {
	seq: 44,
	slug: "how-to-calculate-rule-of-72",
	prefix: "tool_rule_of_72",
	pageFile: "howToCalculateRuleOf72Page",
	pageExport: "renderHowToCalculateRuleOf72Page",
	nameZh: "72 法则计算器",
	ymyl: true,
	related: ["how-to-calculate-cagr","how-to-calculate-compound-interest"],
	anchor: "rule-of-72",
	glyph: "M8 8h16v4H8zm2 8h6v6h-6z",
	sampleHint: "rate 6% → 12 years",
	titles: {
		en: "Rule of 72 Calculator — Years to Double",
		zh: "72 法则计算器 — 多久翻倍",
		es: "Calculadora de la regla del 72",
		ar: "حاسبة قاعدة 72",
		pt: "Calculadora da regra dos 72",
		id: "Kalkulator aturan 72",
		fr: "Calculateur de la règle de 72",
		ja: "72の法則 — 倍増までの年数",
		ru: "Калькулятор правила 72",
		de: "72er-Regel-Rechner",
	},
	descriptions: {
		en: "Estimate years to double with the Rule of 72: years ≈ 72 ÷ annual rate%. Sample: 6% → about 12 years. A quick teaching approximation — not investment advice.",
		zh: "用 72 法则估算资金翻倍所需年数：年数 ≈ 72 ÷ 年化收益率%。示例：年化 6% → 约 12 年。教学近似；浏览器本地计算，非投资建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。",
		es: "Estima años para duplicar con la regla del 72: años ≈ 72 ÷ tasa%. Ejemplo: 6% → unos 12 años. Aproximación educativa.",
		ar: "قدّر سنوات المضاعفة بقاعدة 72: السنوات ≈ 72 ÷ المعدل%. مثال: 6٪ → نحو 12 سنة. تقريب تعليمي.",
		pt: "Estime anos para dobrar com a regra dos 72: anos ≈ 72 ÷ taxa%. Exemplo: 6% → cerca de 12 anos. Aproximação educativa.",
		id: "Perkirakan tahun untuk berlipat ganda dengan aturan 72: tahun ≈ 72 ÷ suku bunga%. Contoh: 6% → sekitar 12 tahun. Edukatif.",
		fr: "Estimez les années pour doubler avec la règle de 72 : années ≈ 72 ÷ taux%. Exemple : 6 % → environ 12 ans. Approximation éducative.",
		ja: "72の法則で倍増までの年数を見積もります：年数 ≈ 72 ÷ 年利%。例：6% → 約12年。学習用の近似であり投資助言ではありません。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり投資・税務・経営の助言ではありません。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり投資・税務・経営の助言ではありません。",
		ru: "Оцените годы удвоения по правилу 72: годы ≈ 72 ÷ ставка%. Пример: 6% → около 12 лет. Учебное приближение.",
		de: "Schätzen Sie Jahre bis zur Verdopplung mit der 72er-Regel: Jahre ≈ 72 ÷ Zinssatz%. Beispiel: 6% → etwa 12 Jahre. Bildungsnäherung.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "rate",
	    "type": "number",
	    "half": true,
	    "labelKey": "rate_label",
	    "phKey": "rate_ph"
	  }
	],
	results: [
	  {
	    "id": "yearsOut",
	    "labelKey": "yearsOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://www.investopedia.com/terms/r/ruleof72.asp"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.investopedia.com/terms/c/compoundinterest.asp"
	  }
	],
	computeJs: `
        var rate=parseFloat(rateEl.value);
        if(!(rate>0)) return {ok:false,error:msgErr};
        return {ok:true, values:{ yearsOut: fmt(72/rate) }};
`,
	sampleJs: `
        rateEl.value='6';
`,
};
