/**
 * §12 #22 how-to-calculate-salary-hourly 工具定义（十语独立 UI）。
 */
export default {
	seq: 22,
	slug: 'how-to-calculate-salary-hourly',
	prefix: 'tool_salary_hourly',
	nameZh: '年薪时薪计算器',
	category: 'calculator',
	ymyl: true,
	pageFile: 'howToCalculateSalaryHourlyPage',
	pageExport: 'renderHowToCalculateSalaryHourlyPage',
	anchor: 'salary-hourly',
	related: ['how-to-calculate-cagr', 'how-to-calculate-roi'],
	glyph: 'M8 22h16M10 10h12M10 14h8M10 18h10',
	titles: {
		en: "Salary to Hourly Calculator — How to Convert Pay Rates",
		zh: "年薪时薪计算器 — 如何换算薪资与时薪",
		es: "Calculadora de salario por hora — Convertir tasas de pago",
		ar: "حاسبة الراتب بالساعة — تحويل معدلات الأجر",
		pt: "Calculadora de salário por hora — Converter taxas de pagamento",
		id: "Kalkulator gaji per jam — Cara mengonversi tarif bayar",
		fr: "Calculateur salaire horaire — Convertir les taux de rémunération",
		ja: "時給換算計算機 — 年収・月給と時給の直し方",
		ru: "Калькулятор зарплаты в час — Пересчёт ставок оплаты",
		de: "Stundenlohn-Rechner — Gehaltssätze umrechnen"
	},
	descriptions: {
		en: "Convert annual, monthly, or hourly pay using hours per week and weeks per year (defaults 40 and 52). Example: annual 52,000 at 40 h/week → $25.00/hour. Runs in your browser; educational illustration only — not employment, payroll, or tax advice.",
		zh: "按每周工时与每年周数（默认 40 与 52）在年薪、月薪与时薪之间换算。示例：年薪 52000、每周 40 小时 → 时薪 25.00。计算在浏览器内完成，数字留在本机、不上传服务器；仅供教育示意，不构成雇佣、薪酬发放或税务建议。",
		es: "Convierte salario anual, mensual u horario con horas/semana y semanas/año (40 y 52 por defecto). Ejemplo: anual 52.000 a 40 h/semana → 25,00/hora. En el navegador; solo educativo, no es consejo laboral ni fiscal.",
		ar: "حوّل الراتب السنوي أو الشهري أو بالساعة باستخدام ساعات/أسبوع وأسابيع/سنة (الافتراضي 40 و52). مثال: سنوي 52000 عند 40 ساعة/أسبوع → 25.00 بالساعة. في المتصفح؛ للتعليم فقط وليس نصيحة توظيف أو ضرائب.",
		pt: "Converta salário anual, mensal ou horário com horas/semana e semanas/ano (padrão 40 e 52). Exemplo: anual 52.000 a 40 h/semana → 25,00/hora. No navegador; apenas educativo, não é conselho trabalhista nem fiscal.",
		id: "Ubah gaji tahunan, bulanan, atau per jam dengan jam/minggu dan minggu/tahun (bawaan 40 dan 52). Contoh: tahunan 52.000 pada 40 jam/minggu → 25,00/jam. Di browser; hanya edukasi, bukan saran kerja atau pajak.",
		fr: "Convertissez salaire annuel, mensuel ou horaire avec heures/semaine et semaines/an (40 et 52 par défaut). Exemple : annuel 52 000 à 40 h/semaine → 25,00/heure. Dans le navigateur ; usage pédagogique, pas un conseil emploi ou fiscal.",
		ja: "週の労働時間と年の週数（既定 40 と 52）で年収・月給・時給を換算します。例：年収 52000・週 40 時間 → 時給 25.00。ブラウザのタブ内で計算し、数値は端末に留まりサーバーへアップロードしません。学習用の試算であり、雇用・給与・税務の助言ではありません。",
		ru: "Переведите годовую, месячную или почасовую оплату с часами/неделю и неделями/год (по умолчанию 40 и 52). Пример: годовая 52 000 при 40 ч/неделю → 25,00 в час. В браузере; только обучение, не совет по найму или налогам.",
		de: "Rechnen Sie Jahres-, Monats- oder Stundenlohn mit Stunden/Woche und Wochen/Jahr um (Standard 40 und 52). Beispiel: Jahresgehalt 52.000 bei 40 h/Woche → 25,00/Stunde. Im Browser; nur zu Lernzwecken, keine Arbeits- oder Steuerberatung."
	},
	ui: {
		en: {
			calculate: "Calculate",
			sample: "Load sample",
			clear: "Clear",
			mode_label: "Pay input mode",
			mode_annual: "Annual salary",
			mode_monthly: "Monthly salary",
			mode_hourly: "Hourly rate",
			pay_label: "Pay amount",
			pay_ph: "e.g. 52000",
			hours_label: "Hours per week",
			hours_ph: "e.g. 40",
			weeks_label: "Weeks per year",
			weeks_ph: "e.g. 52",
			hourlyOut_label: "Hourly rate",
			annualOut_label: "Annual",
			monthlyOut_label: "Monthly",
			weeklyOut_label: "Weekly",
			result_note: "Educational illustration only — not employment, payroll, or tax advice.",
			err_generic: "Enter a positive pay amount, hours/week, and weeks/year.",
			how_title: "How it works",
			how_body: "Choose annual, monthly, or hourly as the starting figure. Enter hours per week and weeks per year (defaults 40 and 52). The tool derives hourly, annual, monthly, and weekly equivalents with the same work-time assumptions. Runs in your browser; not a job offer or tax estimate.",
			formula_title: "Formula and assumptions",
			formula_body: "Annual hours = hours/week × weeks/year. From that:",
			formula_item_1: "Hourly = annual ÷ (hours/week × weeks/year); annual = hourly × hours/week × weeks/year.",
			formula_item_2: "Monthly = annual ÷ 12; weekly = annual ÷ weeks/year (or hourly × hours/week).",
			formula_item_3: "Defaults 40×52 = 2,080 hours/year are common full-time sketches — overtime, unpaid leave, and local labor rules are not modeled.",
			formula_item_4: "Results are educational only and are not employment, payroll, or tax advice.",
			example_title: "Example",
			example: "Example: annual salary 52,000, 40 hours/week, 52 weeks/year → hourly = 52000 ÷ (40 × 52) = 52000 ÷ 2080 = $25.00/hour.",
			usecases_title: "When to use it",
			usecase_1: "Compare a posted annual salary with an hourly contractor rate using the same hour assumptions.",
			usecase_2: "Coursework: practice converting pay rates with explicit weeks/year.",
			usecase_3: "Rough offer sketch before HR or tax advice — not a substitute for either.",
			faq_q1: "How do you convert annual salary to hourly?",
			faq_a1: "Divide annual pay by hours/week × weeks/year. With 40 and 52, that is annual ÷ 2080.",
			faq_q2: "Can I start from hourly or monthly instead?",
			faq_a2: "Yes. Pick the matching mode; the page shows hourly, annual, monthly, and weekly side by side.",
			faq_q3: "Why default to 40 hours and 52 weeks?",
			faq_a3: "They are a common full-time sketch (2,080 hours/year). Change them if your schedule differs; unpaid leave and overtime are not modeled.",
			faq_q4: "Is this employment or tax advice?",
			faq_a4: "No. Numbers are educational illustrations only and are not employment, payroll, benefits, or tax advice.",
			disclaimer: "Salary and hourly conversions are educational illustrations only and are not employment, payroll, benefits, or tax advice. Real offers involve local labor law, overtime rules, taxes, and benefits this page does not model.",
			references: "U.S. BLS occupational wage context; Investopedia hourly rate overview; standard annual-hours conversion (hours/week × weeks/year).",
			ref_bls_label: "U.S. BLS — Occupational Employment and Wage Statistics",
			ref_investopedia_label: "Investopedia — Hourly rate",
			article: "Convert annual, monthly, or hourly pay with explicit hours/week and weeks/year. Defaults 40 and 52 yield a 2,080-hour year. Educational only — not employment or tax advice."
		},
		zh: {
			calculate: "计算",
			sample: "加载样例",
			clear: "清空",
			mode_label: "输入模式",
			mode_annual: "年薪",
			mode_monthly: "月薪",
			mode_hourly: "时薪",
			pay_label: "薪资金额",
			pay_ph: "例如 52000",
			hours_label: "每周工时（小时）",
			hours_ph: "例如 40",
			weeks_label: "每年工作周数",
			weeks_ph: "例如 52",
			hourlyOut_label: "时薪",
			annualOut_label: "年薪",
			monthlyOut_label: "月薪",
			weeklyOut_label: "周薪",
			result_note: "仅供教育示意，不构成雇佣、薪酬或税务建议。",
			err_generic: "请填写大于 0 的薪资、每周工时与每年周数。",
			how_title: "怎么用",
			how_body: "先选年薪、月薪或时薪作为起点，再填每周工时与每年周数（默认 40 与 52）。工具按同一工时假设给出时薪、年薪、月薪与周薪对照。计算在浏览器内完成；不是录用承诺，也不做税额估算。",
			formula_title: "公式与假设",
			formula_body: "年工时 = 每周工时 × 每年周数。据此：",
			formula_item_1: "时薪 = 年薪 ÷（每周工时 × 每年周数）；年薪 = 时薪 × 每周工时 × 每年周数。",
			formula_item_2: "月薪 = 年薪 ÷ 12；周薪 = 年薪 ÷ 每年周数（或时薪 × 每周工时）。",
			formula_item_3: "默认 40×52=2080 小时/年是常见全职粗算；加班、无薪假期与各地劳动法未建模。",
			formula_item_4: "结果仅供学习对照，不是雇佣、发薪或税务建议。",
			example_title: "示例",
			example: "示例：年薪 52000，每周 40 小时，每年 52 周 → 时薪 = 52000 ÷ (40 × 52) = 52000 ÷ 2080 = 25.00/小时。",
			usecases_title: "适合什么场景",
			usecase_1: "把岗位年薪与按小时报价用同一工时假设对照。",
			usecase_2: "课堂练习：带着明确「每年几周」做薪资换算。",
			usecase_3: "谈 offer 前的粗算草稿——不能替代人事或税务顾问。",
			faq_q1: "年薪怎么换算成时薪？",
			faq_a1: "用年薪除以「每周工时 × 每年周数」。在默认 40 与 52 时，即年薪 ÷ 2080。",
			faq_q2: "可以从时薪或月薪开始算吗？",
			faq_a2: "可以。选对应模式即可；页面会同时给出时薪、年薪、月薪与周薪。",
			faq_q3: "为什么默认 40 小时和 52 周？",
			faq_a3: "这是常见全职粗算（每年约 2080 小时）。作息不同就改这两个数；加班与无薪假未计入。",
			faq_q4: "这算雇佣或税务建议吗？",
			faq_a4: "不算。数字只是教育示意，不是雇佣、薪酬福利或税务建议。",
			disclaimer: "年薪与时薪换算结果仅供教育示意，不构成雇佣、薪酬、福利或税务建议。真实录用受当地劳动法、加班规则、税费与福利影响，本页均未建模。",
			references: "美国劳工统计局职业工资语境；Investopedia 时薪概述；标准年工时换算（每周工时×每年周数）。",
			ref_bls_label: "美国劳工统计局 — 职业就业与工资统计",
			ref_investopedia_label: "Investopedia — 时薪（Hourly rate）",
			article: "用每周工时与每年周数，在年薪、月薪与时薪之间换算。默认 40×52 对应约 2080 小时/年。仅供教育，非雇佣或税务建议。"
		},
		es: {
			calculate: "Calcular",
			sample: "Cargar ejemplo",
			clear: "Limpiar",
			mode_label: "Modo de entrada",
			mode_annual: "Salario anual",
			mode_monthly: "Salario mensual",
			mode_hourly: "Tarifa por hora",
			pay_label: "Importe",
			pay_ph: "p. ej. 52000",
			hours_label: "Horas por semana",
			hours_ph: "p. ej. 40",
			weeks_label: "Semanas por año",
			weeks_ph: "p. ej. 52",
			hourlyOut_label: "Por hora",
			annualOut_label: "Anual",
			monthlyOut_label: "Mensual",
			weeklyOut_label: "Semanal",
			result_note: "Solo ilustración educativa: no es consejo laboral ni fiscal.",
			err_generic: "Introduce un importe positivo, horas/semana y semanas/año.",
			how_title: "Cómo funciona",
			how_body: "Elige anual, mensual u horario como punto de partida. Indica horas por semana y semanas al año (40 y 52 por defecto). Verás equivalentes por hora, anuales, mensuales y semanales con las mismas hipótesis de jornada. Todo en el navegador; no es una oferta ni un cálculo fiscal.",
			formula_title: "Fórmula y supuestos",
			formula_body: "Horas anuales = horas/semana × semanas/año. A partir de ahí:",
			formula_item_1: "Por hora = anual ÷ (horas/semana × semanas/año); anual = por hora × horas/semana × semanas/año.",
			formula_item_2: "Mensual = anual ÷ 12; semanal = anual ÷ semanas/año (o por hora × horas/semana).",
			formula_item_3: "40×52 = 2080 h/año es un esquema a tiempo completo habitual; no modela horas extra ni vacaciones no pagadas.",
			formula_item_4: "Los resultados son educativos y no son consejo laboral, de nómina ni fiscal.",
			example_title: "Ejemplo",
			example: "Ejemplo: salario anual 52.000, 40 h/semana, 52 semanas/año → por hora = 52000 ÷ (40 × 52) = 25,00/hora.",
			usecases_title: "Cuándo usarlo",
			usecase_1: "Comparar un sueldo anual publicado con una tarifa por hora con las mismas horas.",
			usecase_2: "Práctica escolar: convertir tasas dejando explícitas las semanas/año.",
			usecase_3: "Borrador orientativo antes de hablar con RR. HH. o un asesor fiscal.",
			faq_q1: "¿Por qué 40 horas y 52 semanas?",
			faq_a1: "Es un esquema a tiempo completo habitual (2080 h/año). Cámbialo si tu jornada es distinta.",
			faq_q2: "¿Cómo paso de anual a por hora?",
			faq_a2: "Divide el anual entre horas/semana × semanas/año. Con 40 y 52: anual ÷ 2080.",
			faq_q3: "¿Puedo empezar desde mensual u horario?",
			faq_a3: "Sí. Elige el modo; la página muestra las cuatro tasas juntas.",
			faq_q4: "¿Es consejo laboral o fiscal?",
			faq_a4: "No. Solo ilustración educativa; no sustituye nómina, contrato ni impuestos.",
			disclaimer: "La conversión de salario es solo educativa y no constituye consejo laboral, de nómina, beneficios ni fiscal. Las ofertas reales dependen de la ley local, horas extra e impuestos no modelados aquí.",
			references: "Contexto salarial BLS (EE. UU.); visión general de tarifa horaria en Investopedia; conversión estándar por horas anuales.",
			ref_bls_label: "BLS (EE. UU.) — estadísticas de empleo y salarios",
			ref_investopedia_label: "Investopedia — Hourly rate",
			article: "Convierte salario anual, mensual u horario con horas/semana y semanas/año explícitas. Por defecto 40×52 ≈ 2080 h/año. Solo educativo."
		},
		ar: {
			calculate: "احسب",
			sample: "تحميل مثال",
			clear: "مسح",
			mode_label: "وضع الإدخال",
			mode_annual: "راتب سنوي",
			mode_monthly: "راتب شهري",
			mode_hourly: "أجر بالساعة",
			pay_label: "المبلغ",
			pay_ph: "مثال 52000",
			hours_label: "ساعات في الأسبوع",
			hours_ph: "مثال 40",
			weeks_label: "أسابيع في السنة",
			weeks_ph: "مثال 52",
			hourlyOut_label: "بالساعة",
			annualOut_label: "سنوي",
			monthlyOut_label: "شهري",
			weeklyOut_label: "أسبوعي",
			result_note: "للتوضيح التعليمي فقط — ليست نصيحة توظيف أو ضرائب.",
			err_generic: "أدخل مبلغًا موجبًا وساعات/أسبوع وأسابيع/سنة.",
			how_title: "طريقة الاستخدام",
			how_body: "اختر سنويًا أو شهريًا أو بالساعة كنقطة بداية، ثم أدخل ساعات الأسبوع وأسابيع السنة (الافتراضي 40 و52). تظهر المكافئات جنبًا إلى جنب بنفس افتراضات الوقت. الحساب في المتصفح؛ ليس عرض عمل ولا تقدير ضريبي.",
			formula_title: "الصيغة والافتراضات",
			formula_body: "ساعات السنة = ساعات/أسبوع × أسابيع/سنة. ومن ذلك:",
			formula_item_1: "الأجر بالساعة = السنوي ÷ (ساعات/أسبوع × أسابيع/سنة).",
			formula_item_2: "الشهري = السنوي ÷ 12؛ الأسبوعي = السنوي ÷ أسابيع/سنة.",
			formula_item_3: "40×52 = 2080 ساعة/سنة مخطط دوام كامل شائع؛ لا يشمل العمل الإضافي أو الإجازات غير المدفوعة.",
			formula_item_4: "النتائج تعليمية وليست نصيحة توظيف أو رواتب أو ضرائب.",
			example_title: "مثال",
			example: "مثال: راتب سنوي 52000، 40 ساعة/أسبوع، 52 أسبوعًا → بالساعة = 52000 ÷ 2080 = 25.00.",
			usecases_title: "متى تستخدمه",
			usecase_1: "مقارنة راتب سنوي معلن مع عرض بالساعة بنفس افتراض الساعات.",
			usecase_2: "تمارين دراسية لتحويل معدلات الأجر مع أسابيع واضحة.",
			usecase_3: "مسودة تقريبية قبل استشارة الموارد البشرية أو الضرائب.",
			faq_q1: "هل هذه نصيحة توظيف أو ضريبية؟",
			faq_a1: "لا. الأرقام للتوضيح التعليمي فقط.",
			faq_q2: "كيف أحول السنوي إلى بالساعة؟",
			faq_a2: "اقسم السنوي على ساعات/أسبوع × أسابيع/سنة. مع 40 و52: السنوي ÷ 2080.",
			faq_q3: "لماذا الافتراضي 40 و52؟",
			faq_a3: "مخطط دوام كامل شائع (2080 ساعة/سنة). غيّر القيم إن اختلف جدولك.",
			faq_q4: "هل يمكن البدء من الشهري أو بالساعة؟",
			faq_a4: "نعم. اختر الوضع المناسب؛ تظهر المعدلات الأربعة معًا.",
			disclaimer: "تحويل الراتب تعليمي فقط وليس نصيحة توظيف أو رواتب أو مزايا أو ضرائب. العروض الحقيقية تخضع لقوانين العمل والضرائب غير الممثلة هنا.",
			references: "سياق أجور BLS الأمريكي؛ نظرة Investopedia على الأجر بالساعة؛ تحويل ساعات السنة القياسي.",
			ref_bls_label: "مكتب إحصاءات العمل الأمريكي — أجور المهن",
			ref_investopedia_label: "Investopedia — Hourly rate",
			article: "حوّل الراتب السنوي أو الشهري أو بالساعة بساعات أسبوع وأسابيع سنة صريحة. الافتراضي 40×52. للتعليم فقط."
		},
		pt: {
			calculate: "Calcular",
			sample: "Carregar exemplo",
			clear: "Limpar",
			mode_label: "Modo de entrada",
			mode_annual: "Salário anual",
			mode_monthly: "Salário mensal",
			mode_hourly: "Taxa horária",
			pay_label: "Valor",
			pay_ph: "ex.: 52000",
			hours_label: "Horas por semana",
			hours_ph: "ex.: 40",
			weeks_label: "Semanas por ano",
			weeks_ph: "ex.: 52",
			hourlyOut_label: "Por hora",
			annualOut_label: "Anual",
			monthlyOut_label: "Mensal",
			weeklyOut_label: "Semanal",
			result_note: "Apenas ilustração educativa — não é conselho trabalhista nem fiscal.",
			err_generic: "Informe valor positivo, horas/semana e semanas/ano.",
			how_title: "Como funciona",
			how_body: "Escolha anual, mensal ou horário como ponto de partida. Informe horas por semana e semanas por ano (padrão 40 e 52). O resultado mostra equivalentes lado a lado com as mesmas hipóteses de jornada. No navegador; não é oferta nem cálculo de imposto.",
			formula_title: "Fórmula e premissas",
			formula_body: "Horas anuais = horas/semana × semanas/ano. Em seguida:",
			formula_item_1: "Por hora = anual ÷ (horas/semana × semanas/ano); anual = por hora × horas/semana × semanas/ano.",
			formula_item_2: "Mensal = anual ÷ 12; semanal = anual ÷ semanas/ano.",
			formula_item_3: "40×52 = 2080 h/ano é um esquema comum de tempo integral; horas extras e férias não pagas não entram.",
			formula_item_4: "Resultados são educativos e não são conselho trabalhista, de folha ou fiscal.",
			example_title: "Exemplo",
			example: "Exemplo: salário anual 52.000, 40 h/semana, 52 semanas/ano → por hora = 52000 ÷ 2080 = 25,00/hora.",
			usecases_title: "Quando usar",
			usecase_1: "Comparar salário anual anunciado com taxa horária nas mesmas horas.",
			usecase_2: "Exercício: converter taxas deixando semanas/ano explícitas.",
			usecase_3: "Rascunho antes de falar com RH ou contador — não substitui nenhum dos dois.",
			faq_q1: "Posso começar pelo mensal ou horário?",
			faq_a1: "Sim. Escolha o modo; a página mostra as quatro taxas juntas.",
			faq_q2: "Como converter anual em hora?",
			faq_a2: "Divida o anual por horas/semana × semanas/ano. Com 40 e 52: anual ÷ 2080.",
			faq_q3: "Por que 40 horas e 52 semanas?",
			faq_a3: "Esquema comum de tempo integral (2080 h/ano). Ajuste se sua jornada for diferente.",
			faq_q4: "Isto é conselho trabalhista ou fiscal?",
			faq_a4: "Não. Apenas ilustração educativa.",
			disclaimer: "Conversões de salário são apenas educativas e não constituem conselho trabalhista, de folha, benefícios ou fiscal. Ofertas reais dependem de leis locais e impostos não modelados aqui.",
			references: "Contexto salarial BLS (EUA); visão Investopedia de taxa horária; conversão padrão por horas anuais.",
			ref_bls_label: "BLS (EUA) — estatísticas de emprego e salários",
			ref_investopedia_label: "Investopedia — Hourly rate",
			article: "Converta salário anual, mensal ou horário com horas/semana e semanas/ano explícitas. Padrão 40×52. Apenas educativo."
		},
		id: {
			calculate: "Hitung",
			sample: "Muat contoh",
			clear: "Hapus",
			mode_label: "Mode masukan",
			mode_annual: "Gaji tahunan",
			mode_monthly: "Gaji bulanan",
			mode_hourly: "Tarif per jam",
			pay_label: "Jumlah bayar",
			pay_ph: "mis. 52000",
			hours_label: "Jam per minggu",
			hours_ph: "mis. 40",
			weeks_label: "Minggu per tahun",
			weeks_ph: "mis. 52",
			hourlyOut_label: "Per jam",
			annualOut_label: "Tahunan",
			monthlyOut_label: "Bulanan",
			weeklyOut_label: "Mingguan",
			result_note: "Hanya ilustrasi edukasi — bukan saran kerja atau pajak.",
			err_generic: "Masukkan jumlah positif, jam/minggu, dan minggu/tahun.",
			how_title: "Cara kerja",
			how_body: "Pilih tahunan, bulanan, atau per jam sebagai titik awal. Isi jam per minggu dan minggu per tahun (bawaan 40 dan 52). Hasil menampilkan setara per jam, tahunan, bulanan, dan mingguan dengan asumsi waktu yang sama. Di browser; bukan tawaran kerja atau estimasi pajak.",
			formula_title: "Rumus dan asumsi",
			formula_body: "Jam tahunan = jam/minggu × minggu/tahun. Lalu:",
			formula_item_1: "Per jam = tahunan ÷ (jam/minggu × minggu/tahun).",
			formula_item_2: "Bulanan = tahunan ÷ 12; mingguan = tahunan ÷ minggu/tahun.",
			formula_item_3: "40×52 = 2080 jam/tahun sketsa penuh waktu umum; lembur dan cuti tanpa bayar tidak dimodelkan.",
			formula_item_4: "Hasil bersifat edukasi, bukan saran kerja, payroll, atau pajak.",
			example_title: "Contoh",
			example: "Contoh: gaji tahunan 52.000, 40 jam/minggu, 52 minggu/tahun → per jam = 52000 ÷ 2080 = 25,00/jam.",
			usecases_title: "Kapan dipakai",
			usecase_1: "Membandingkan gaji tahunan dengan tarif per jam dengan jam yang sama.",
			usecase_2: "Latihan kelas: konversi tarif dengan minggu/tahun eksplisit.",
			usecase_3: "Sketsa kasar sebelum bicara ke HR atau konsultan pajak.",
			faq_q1: "Bagaimana mengubah gaji tahunan ke per jam?",
			faq_a1: "Bagi tahunan dengan jam/minggu × minggu/tahun. Dengan 40 dan 52: tahunan ÷ 2080.",
			faq_q2: "Mengapa bawaan 40 dan 52?",
			faq_a2: "Sketsa penuh waktu umum (2080 jam/tahun). Ubah jika jadwal Anda berbeda.",
			faq_q3: "Bisa mulai dari bulanan atau per jam?",
			faq_a3: "Bisa. Pilih mode; empat tarif ditampilkan bersama.",
			faq_q4: "Apakah ini saran kerja atau pajak?",
			faq_a4: "Bukan. Hanya ilustrasi edukasi.",
			disclaimer: "Konversi gaji hanya untuk edukasi dan bukan saran kerja, payroll, tunjangan, atau pajak. Tawaran nyata bergantung pada hukum setempat dan pajak yang tidak dimodelkan di sini.",
			references: "Konteks upah BLS AS; ringkasan tarif per jam Investopedia; konversi jam tahunan standar.",
			ref_bls_label: "BLS AS — statistik pekerjaan dan upah",
			ref_investopedia_label: "Investopedia — Hourly rate",
			article: "Konversi gaji tahunan, bulanan, atau per jam dengan jam/minggu dan minggu/tahun eksplisit. Bawaan 40×52. Hanya edukasi."
		},
		fr: {
			calculate: "Calculer",
			sample: "Charger l’exemple",
			clear: "Effacer",
			mode_label: "Mode de saisie",
			mode_annual: "Salaire annuel",
			mode_monthly: "Salaire mensuel",
			mode_hourly: "Taux horaire",
			pay_label: "Montant",
			pay_ph: "ex. 52000",
			hours_label: "Heures par semaine",
			hours_ph: "ex. 40",
			weeks_label: "Semaines par an",
			weeks_ph: "ex. 52",
			hourlyOut_label: "Horaire",
			annualOut_label: "Annuel",
			monthlyOut_label: "Mensuel",
			weeklyOut_label: "Hebdomadaire",
			result_note: "Illustration pédagogique uniquement — pas un conseil emploi ou fiscal.",
			err_generic: "Saisissez un montant positif, des heures/semaine et des semaines/an.",
			how_title: "Fonctionnement",
			how_body: "Choisissez annuel, mensuel ou horaire comme point de départ. Indiquez heures/semaine et semaines/an (40 et 52 par défaut). Les équivalents s’affichent côte à côte avec les mêmes hypothèses de temps. Dans le navigateur ; ce n’est ni une offre ni un calcul d’impôt.",
			formula_title: "Formule et hypothèses",
			formula_body: "Heures annuelles = heures/semaine × semaines/an. Ensuite :",
			formula_item_1: "Horaire = annuel ÷ (heures/semaine × semaines/an).",
			formula_item_2: "Mensuel = annuel ÷ 12 ; hebdomadaire = annuel ÷ semaines/an.",
			formula_item_3: "40×52 = 2080 h/an est un schéma temps plein courant ; heures supp. et congés non payés ne sont pas modélisés.",
			formula_item_4: "Résultats pédagogiques uniquement — pas un conseil emploi, paie ou fiscal.",
			example_title: "Exemple",
			example: "Exemple : salaire annuel 52 000, 40 h/semaine, 52 semaines/an → horaire = 52000 ÷ 2080 = 25,00/heure.",
			usecases_title: "Quand l’utiliser",
			usecase_1: "Comparer un salaire annuel affiché à un taux horaire avec les mêmes heures.",
			usecase_2: "Exercice : convertir des taux avec semaines/an explicites.",
			usecase_3: "Ébauche avant de parler RH ou fiscalité — ne remplace aucun conseil.",
			faq_q1: "Pourquoi 40 heures et 52 semaines ?",
			faq_a1: "Schéma temps plein courant (2080 h/an). Modifiez-les si votre rythme diffère.",
			faq_q2: "Comment passer de l’annuel à l’horaire ?",
			faq_a2: "Divisez l’annuel par heures/semaine × semaines/an. Avec 40 et 52 : annuel ÷ 2080.",
			faq_q3: "Puis-je partir du mensuel ou de l’horaire ?",
			faq_a3: "Oui. Choisissez le mode ; les quatre taux s’affichent ensemble.",
			faq_q4: "Est-ce un conseil emploi ou fiscal ?",
			faq_a4: "Non. Illustration pédagogique uniquement.",
			disclaimer: "Les conversions de salaire sont uniquement pédagogiques et ne constituent pas un conseil emploi, paie, avantages ou fiscal. Les offres réelles dépendent du droit local et des impôts non modélisés ici.",
			references: "Contexte salarial BLS (É.-U.) ; aperçu Investopedia du taux horaire ; conversion standard des heures annuelles.",
			ref_bls_label: "BLS (É.-U.) — statistiques d’emploi et de salaires",
			ref_investopedia_label: "Investopedia — Hourly rate",
			article: "Convertissez salaire annuel, mensuel ou horaire avec heures/semaine et semaines/an explicites. Défaut 40×52. Usage pédagogique seulement."
		},
		ja: {
			calculate: "計算する",
			sample: "サンプル",
			clear: "クリア",
			mode_label: "入力の種類",
			mode_annual: "年収",
			mode_monthly: "月給",
			mode_hourly: "時給",
			pay_label: "金額",
			pay_ph: "例: 52000",
			hours_label: "週あたりの労働時間",
			hours_ph: "例: 40",
			weeks_label: "年あたりの週数",
			weeks_ph: "例: 52",
			hourlyOut_label: "時給",
			annualOut_label: "年収換算",
			monthlyOut_label: "月給換算",
			weeklyOut_label: "週給換算",
			result_note: "学習用の試算です。雇用・給与・税務の助言ではありません。",
			err_generic: "正の金額・週あたり時間・年あたり週数を入力してください。",
			how_title: "使い方",
			how_body: "年収・月給・時給のいずれかを起点に選び、週の労働時間と年の週数（既定 40 と 52）を入れます。同じ前提で時給・年収・月給・週給を並べて表示します。ブラウザ内の試算で、内定や税額の見積もりではありません。",
			formula_title: "式と前提",
			formula_body: "年間時間 = 週時間 × 年の週数。ここから：",
			formula_item_1: "時給 = 年収 ÷（週時間 × 年の週数）。年収 = 時給 × 週時間 × 年の週数。",
			formula_item_2: "月給 = 年収 ÷ 12。週給 = 年収 ÷ 年の週数。",
			formula_item_3: "既定の 40×52=2080 時間/年はフルタイムのざっくり想定。残業や無給休暇は含みません。",
			formula_item_4: "結果は学習用であり、雇用・給与・税務の助言ではありません。",
			example_title: "例",
			example: "例：年収 52000、週 40 時間、年 52 週 → 時給 = 52000 ÷ 2080 = 25.00/時間。",
			usecases_title: "こんなときに",
			usecase_1: "求人の年収と時間単価を、同じ時間前提で見比べたいとき。",
			usecase_2: "授業で「年何週」を明示した換算練習。",
			usecase_3: "人事や税の相談前のラフな下書き（代替にはなりません）。",
			faq_q1: "年収から時給はどう出しますか？",
			faq_a1: "年収を「週時間×年の週数」で割ります。既定なら年収 ÷ 2080 です。",
			faq_q2: "月給や時給からでも始められますか？",
			faq_a2: "はい。モードを選ぶと四つの換算が並びます。",
			faq_q3: "なぜ 40 時間・52 週が既定ですか？",
			faq_a3: "よく使うフルタイムのざっくり想定（年 2080 時間）です。予定が違えば変更してください。",
			faq_q4: "これは雇用や税の助言ですか？",
			faq_a4: "いいえ。学習用の試算だけです。",
			disclaimer: "年収と時給の換算は学習用の試算であり、雇用・給与・福利厚生・税務の助言ではありません。実際の条件は現地の労働法や税金に依存し、本ページでは扱いません。",
			references: "米国 BLS の賃金コンテキスト；Investopedia の時給解説；標準的な年間時間換算。",
			ref_bls_label: "米国 BLS — 職業別雇用・賃金統計",
			ref_investopedia_label: "Investopedia — Hourly rate",
			article: "週の労働時間と年の週数を明示して、年収・月給・時給を換算します。既定は 40×52。学習用であり雇用・税務の助言ではありません。"
		},
		ru: {
			calculate: "Рассчитать",
			sample: "Загрузить пример",
			clear: "Очистить",
			mode_label: "Режим ввода",
			mode_annual: "Годовая зарплата",
			mode_monthly: "Месячная зарплата",
			mode_hourly: "Ставка в час",
			pay_label: "Сумма",
			pay_ph: "напр. 52000",
			hours_label: "Часов в неделю",
			hours_ph: "напр. 40",
			weeks_label: "Недель в году",
			weeks_ph: "напр. 52",
			hourlyOut_label: "В час",
			annualOut_label: "В год",
			monthlyOut_label: "В месяц",
			weeklyOut_label: "В неделю",
			result_note: "Только учебная иллюстрация — не совет по найму или налогам.",
			err_generic: "Введите положительную сумму, часы/неделю и недели/год.",
			how_title: "Как пользоваться",
			how_body: "Выберите годовой, месячный или почасовой ввод. Укажите часы в неделю и недели в году (по умолчанию 40 и 52). Страница покажет эквиваленты рядом с теми же допущениями о времени. В браузере; это не оффер и не налоговый расчёт.",
			formula_title: "Формула и допущения",
			formula_body: "Часы в году = часы/неделю × недели/год. Далее:",
			formula_item_1: "В час = годовая ÷ (часы/неделю × недели/год).",
			formula_item_2: "В месяц = годовая ÷ 12; в неделю = годовая ÷ недели/год.",
			formula_item_3: "40×52 = 2080 ч/год — обычная схема полной занятости; сверхурочные и неоплачиваемый отпуск не учтены.",
			formula_item_4: "Результаты учебные и не являются советом по найму, зарплате или налогам.",
			example_title: "Пример",
			example: "Пример: годовая 52 000, 40 ч/неделю, 52 недели/год → в час = 52000 ÷ 2080 = 25,00.",
			usecases_title: "Когда применять",
			usecase_1: "Сравнить объявленную годовую зарплату с почасовой ставкой при тех же часах.",
			usecase_2: "Учебное упражнение: перевод ставок с явными неделями/год.",
			usecase_3: "Черновик до разговора с HR или налоговым консультантом.",
			faq_q1: "Можно начать с месячной или почасовой?",
			faq_a1: "Да. Выберите режим — четыре ставки показываются вместе.",
			faq_q2: "Как перевести годовую в почасовую?",
			faq_a2: "Разделите годовую на часы/неделю × недели/год. При 40 и 52: годовая ÷ 2080.",
			faq_q3: "Почему по умолчанию 40 и 52?",
			faq_a3: "Обычная схема полной занятости (2080 ч/год). Измените, если график другой.",
			faq_q4: "Это совет по найму или налогам?",
			faq_a4: "Нет. Только учебная иллюстрация.",
			disclaimer: "Пересчёт зарплаты носит учебный характер и не является советом по найму, расчёту зарплаты, льготам или налогам. Реальные условия зависят от местного права и налогов, не моделируемых здесь.",
			references: "Контекст зарплат BLS (США); обзор почасовой ставки Investopedia; стандартный перевод через годовые часы.",
			ref_bls_label: "BLS (США) — статистика занятости и зарплат",
			ref_investopedia_label: "Investopedia — Hourly rate",
			article: "Переведите годовую, месячную или почасовую оплату с явными часами/неделю и неделями/год. По умолчанию 40×52. Только обучение."
		},
		de: {
			calculate: "Berechnen",
			sample: "Beispiel laden",
			clear: "Leeren",
			mode_label: "Eingabemodus",
			mode_annual: "Jahresgehalt",
			mode_monthly: "Monatsgehalt",
			mode_hourly: "Stundenlohn",
			pay_label: "Betrag",
			pay_ph: "z. B. 52000",
			hours_label: "Stunden pro Woche",
			hours_ph: "z. B. 40",
			weeks_label: "Wochen pro Jahr",
			weeks_ph: "z. B. 52",
			hourlyOut_label: "Stundenlohn",
			annualOut_label: "Jahresgehalt",
			monthlyOut_label: "Monatsgehalt",
			weeklyOut_label: "Wochenlohn",
			result_note: "Nur zur Veranschaulichung — keine Arbeits- oder Steuerberatung.",
			err_generic: "Bitte positiven Betrag, Stunden/Woche und Wochen/Jahr eingeben.",
			how_title: "So funktioniert’s",
			how_body: "Wählen Sie Jahres-, Monats- oder Stundenlohn als Ausgangspunkt. Geben Sie Stunden/Woche und Wochen/Jahr ein (Standard 40 und 52). Die Seite zeigt stündliche, jährliche, monatliche und wöchentliche Äquivalente mit denselben Zeitannahmen. Im Browser; kein Stellenangebot und keine Steuerberechnung.",
			formula_title: "Formel und Annahmen",
			formula_body: "Jahresstunden = Stunden/Woche × Wochen/Jahr. Daraus:",
			formula_item_1: "Stundenlohn = Jahresgehalt ÷ (Stunden/Woche × Wochen/Jahr).",
			formula_item_2: "Monatsgehalt = Jahresgehalt ÷ 12; Wochenlohn = Jahresgehalt ÷ Wochen/Jahr.",
			formula_item_3: "40×52 = 2080 h/Jahr ist ein übliches Vollzeit-Schema; Überstunden und unbezahlter Urlaub fehlen.",
			formula_item_4: "Ergebnisse sind nur zur Veranschaulichung — keine Arbeits-, Lohn- oder Steuerberatung.",
			example_title: "Beispiel",
			example: "Beispiel: Jahresgehalt 52.000, 40 h/Woche, 52 Wochen/Jahr → Stundenlohn = 52000 ÷ 2080 = 25,00/Stunde.",
			usecases_title: "Wann sinnvoll",
			usecase_1: "Ausgeschriebenes Jahresgehalt mit Stundenhonorar bei gleichen Stunden vergleichen.",
			usecase_2: "Übungsaufgabe: Sätze mit klaren Wochen/Jahr umrechnen.",
			usecase_3: "Grobe Skizze vor HR- oder Steuerberatung — ersetzt beides nicht.",
			faq_q1: "Warum standardmäßig 40 Stunden und 52 Wochen?",
			faq_a1: "Übliches Vollzeit-Schema (2080 h/Jahr). Anpassen, wenn Ihr Pensum abweicht.",
			faq_q2: "Wie rechne ich Jahresgehalt in Stundenlohn um?",
			faq_a2: "Jahresgehalt durch Stunden/Woche × Wochen/Jahr teilen. Bei 40 und 52: Jahresgehalt ÷ 2080.",
			faq_q3: "Kann ich mit Monat oder Stunde starten?",
			faq_a3: "Ja. Modus wählen — alle vier Sätze erscheinen nebeneinander.",
			faq_q4: "Ist das Arbeits- oder Steuerberatung?",
			faq_a4: "Nein. Nur zur Veranschaulichung.",
			disclaimer: "Gehaltsumrechnungen dienen nur der Veranschaulichung und sind keine Arbeits-, Lohn-, Sozialleistungs- oder Steuerberatung. Reale Angebote hängen von lokalem Recht und Steuern ab, die hier nicht modelliert werden.",
			references: "BLS-Lohnkontext (USA); Investopedia-Überblick Stundenlohn; Standardumrechnung über Jahresstunden.",
			ref_bls_label: "BLS (USA) — Beschäftigungs- und Lohnstatistik",
			ref_investopedia_label: "Investopedia — Hourly rate",
			article: "Rechnen Sie Jahres-, Monats- oder Stundenlohn mit expliziten Stunden/Woche und Wochen/Jahr um. Standard 40×52. Nur zu Lernzwecken."
		}
	},
	fields: [
		{
			id: 'mode',
			type: 'select',
			half: true,
			labelKey: 'mode_label',
			options: [
				{ value: 'annual', labelKey: 'mode_annual', selected: true },
				{ value: 'monthly', labelKey: 'mode_monthly' },
				{ value: 'hourly', labelKey: 'mode_hourly' },
			],
		},
		{ id: 'pay', type: 'number', half: true, labelKey: 'pay_label', phKey: 'pay_ph' },
		{ id: 'hours', type: 'number', half: true, labelKey: 'hours_label', phKey: 'hours_ph' },
		{ id: 'weeks', type: 'number', half: true, labelKey: 'weeks_label', phKey: 'weeks_ph' },
	],
	results: [
		{ id: 'hourlyOut', labelKey: 'hourlyOut_label' },
		{ id: 'annualOut', labelKey: 'annualOut_label' },
		{ id: 'monthlyOut', labelKey: 'monthlyOut_label' },
		{ id: 'weeklyOut', labelKey: 'weeklyOut_label' },
	],
	refs: [
		{ labelKey: 'ref_bls_label', href: 'https://www.bls.gov/oes/' },
		{ labelKey: 'ref_investopedia_label', href: 'https://www.investopedia.com/terms/h/hourlyrate.asp' },
	],
	computeJs: `
        var mode = modeEl.value;
        var pay = parseFloat(payEl.value);
        var hpw = parseFloat(hoursEl.value);
        var wpy = parseFloat(weeksEl.value);
        if (!(pay > 0 && hpw > 0 && wpy > 0)) {
          return { ok: false, error: msgErr };
        }
        var annualHours = hpw * wpy;
        var annual, monthly, hourly, weekly;
        if (mode === 'annual') {
          annual = pay;
          hourly = annual / annualHours;
          monthly = annual / 12;
          weekly = annual / wpy;
        } else if (mode === 'monthly') {
          monthly = pay;
          annual = monthly * 12;
          hourly = annual / annualHours;
          weekly = annual / wpy;
        } else {
          hourly = pay;
          annual = hourly * annualHours;
          monthly = annual / 12;
          weekly = hourly * hpw;
        }
        return {
          ok: true,
          values: {
            hourlyOut: fmt(hourly),
            annualOut: fmt(annual),
            monthlyOut: fmt(monthly),
            weeklyOut: fmt(weekly)
          }
        };
`,
	sampleJs: `
        modeEl.value = 'annual';
        payEl.value = '52000';
        hoursEl.value = '40';
        weeksEl.value = '52';
`,
};
