/**
 * §12 #26 how-to-calculate-sample-size 工具定义（十语独立 UI）。
 * prefix: tool_sample_size；page: howToCalculateSampleSizePage / renderHowToCalculateSampleSizePage。
 */
import { withBtns } from '../locale-ui-common.mjs';

/** 十语 UI（how/formula/faq/usecase 等须独立重写，禁止英模同构）。 */
const _ui = {
	en: withBtns('en', {
		"conf_label": "Confidence level",
		"conf_90": "90% (Z = 1.645)",
		"conf_95": "95% (Z = 1.96)",
		"conf_99": "99% (Z = 2.576)",
		"p_label": "Expected proportion (p)",
		"p_ph": "e.g. 0.5",
		"E_label": "Margin of error (E)",
		"E_ph": "e.g. 0.05",
		"nOut_label": "Required sample size (n)",
		"result_note": "n = ceil(Z²·p·(1−p)/E²) for a proportion — normal approximation, infinite population.",
		"err_generic": "Enter p in [0, 1], E > 0, and a confidence level.",
		"how_title": "How it works",
		"how_body": "Choose 90%, 95%, or 99% confidence, then enter the planning proportion p and the desired margin of error E. The page maps confidence to Z and returns ceil of Z² p (1−p) / E². Runs in your browser for survey homework.",
		"formula_title": "Formula and assumptions",
		"formula_body": "n = Z² · p · (1 − p) / E², then round up. Keep in mind:",
		"formula_item_1": "Z comes from the selected level: 1.645 / 1.96 / 2.576 for 90 / 95 / 99%.",
		"formula_item_2": "Uses a normal approximation for a single proportion; not a finite-population correction.",
		"formula_item_3": "p = 0.5 maximizes n for a fixed E — a common conservative plan.",
		"formula_item_4": "Design effects, clustering, or multiple outcomes need a fuller study plan.",
		"example_title": "Example",
		"example": "Example: 95% (Z = 1.96), p = 0.5, E = 0.05 → n = ceil(384.16) = 385.",
		"usecases_title": "When to use it",
		"usecase_1": "Homework: size a simple proportion survey.",
		"usecase_2": "Compare how tighter E inflates required n.",
		"usecase_3": "Pair with confidence-interval pages after you have data.",
		"faq_q1": "Why use p = 0.5 when unsure?",
		"faq_a1": "For a fixed E, p(1−p) peaks at 0.5, so the plan is most conservative.",
		"faq_q2": "Is the result always an integer?",
		"faq_a2": "Yes here: the raw n is ceiled so you never under-sample the formula.",
		"faq_q3": "Does this include finite population correction?",
		"faq_a3": "No. It assumes a large or infinite population relative to n.",
		"faq_q4": "Can I enter Z instead of a confidence level?",
		"faq_a4": "This page uses the 90/95/99 select that maps to standard Z values.",
		"disclaimer": "Educational proportion sample-size formula only. Not a substitute for survey methodology or power analysis software.",
		"references": "Wikipedia on sample size determination and margin of error.",
		"ref_ss_label": "Wikipedia — Sample size determination",
		"ref_prop_label": "Wikipedia — Margin of error",
		"article": "Estimate required n for a proportion with n = Z² p (1−p) / E² and 90/95/99% levels on one page.",
	}),
	zh: withBtns('zh', {
		"conf_label": "置信水平",
		"conf_90": "90%（Z = 1.645）",
		"conf_95": "95%（Z = 1.96）",
		"conf_99": "99%（Z = 2.576）",
		"p_label": "预期比例 p",
		"p_ph": "例如 0.5",
		"E_label": "允许误差 E",
		"E_ph": "例如 0.05",
		"nOut_label": "所需样本量 n",
		"result_note": "比例样本量 n = ceil(Z²·p·(1−p)/E²)——正态近似，未做有限总体校正。",
		"err_generic": "请填写 [0,1] 内的 p、大于 0 的 E，并选择置信水平。",
		"how_title": "怎么用",
		"how_body": "选择 90%、95% 或 99%，再填规划用比例 p 与允许误差 E。页面把置信水平映射为 Z，并返回 Z² p (1−p)/E² 的向上取整。浏览器内计算，适合问卷作业。",
		"formula_title": "公式与假设",
		"formula_body": "n = Z² · p · (1 − p) / E²，再向上取整。注意：",
		"formula_item_1": "Z 由水平决定：90/95/99% 对应 1.645/1.96/2.576。",
		"formula_item_2": "单比例正态近似；不含有限总体校正。",
		"formula_item_3": "固定 E 时 p=0.5 使 n 最大，常作保守规划。",
		"formula_item_4": "复杂抽样、多终点或功效分析需更完整方案。",
		"example_title": "示例",
		"example": "示例：95%（Z=1.96）、p=0.5、E=0.05 → n = ceil(384.16) = 385。",
		"usecases_title": "适合什么场景",
		"usecase_1": "作业：估算简单比例调查的样本量。",
		"usecase_2": "观察缩小 E 会如何抬高所需 n。",
		"usecase_3": "有数据后可配合置信区间页对照。",
		"faq_q1": "结果一定是整数吗？",
		"faq_a1": "本页会对公式结果向上取整，避免按公式欠采样。",
		"faq_q2": "不确定 p 时为什么常用 0.5？",
		"faq_a2": "固定 E 时 p(1−p) 在 0.5 最大，规划最保守。",
		"faq_q3": "包含有限总体校正吗？",
		"faq_a3": "不包含；默认总体相对 n 很大。",
		"faq_q4": "能直接输入自定义 Z 吗？",
		"faq_a4": "本页用 90/95/99 下拉映射到常用 Z。",
		"disclaimer": "结果仅为教育用比例样本量公式，不能替代调查方法学或功效分析软件。",
		"references": "维基百科样本量确定与误差幅度条目。",
		"ref_ss_label": "维基百科 — 样本量确定",
		"ref_prop_label": "维基百科 — 误差幅度",
		"article": "用 n = Z² p (1−p)/E² 与 90/95/99% 水平估算比例调查所需样本量。",
	}),
	es: withBtns('es', {
		"conf_label": "Nivel de confianza",
		"conf_90": "90% (Z = 1,645)",
		"conf_95": "95% (Z = 1,96)",
		"conf_99": "99% (Z = 2,576)",
		"p_label": "Proporción esperada (p)",
		"p_ph": "p. ej. 0,5",
		"E_label": "Margen de error (E)",
		"E_ph": "p. ej. 0,05",
		"nOut_label": "Tamaño muestral requerido (n)",
		"result_note": "n = ceil(Z²·p·(1−p)/E²) para una proporción — aproximación normal, población infinita.",
		"err_generic": "Introduce p en [0, 1], E > 0 y un nivel de confianza.",
		"how_title": "Cómo funciona",
		"how_body": "Elige 90%, 95% o 99%, luego p de planificación y el margen E. La página asigna Z y devuelve el techo de Z² p (1−p)/E². En el navegador, para encuestas de clase.",
		"formula_title": "Fórmula y supuestos",
		"formula_body": "n = Z² · p · (1 − p) / E² y luego se redondea hacia arriba. Límites:",
		"formula_item_1": "Z: 1,645 / 1,96 / 2,576 para 90 / 95 / 99%.",
		"formula_item_2": "Aproximación normal de una proporción; sin corrección de población finita.",
		"formula_item_3": "p = 0,5 maximiza n para un E fijo.",
		"formula_item_4": "Diseños complejos necesitan un plan más completo.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: 95% (Z = 1,96), p = 0,5, E = 0,05 → n = 385.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Deberes: dimensionar una encuesta de proporción.",
		"usecase_2": "Ver cómo un E más pequeño dispara n.",
		"usecase_3": "Combinarlo luego con una página de intervalo de confianza.",
		"faq_q1": "¿Incluye corrección por población finita?",
		"faq_a1": "No; supone población grande frente a n.",
		"faq_q2": "¿Por qué p = 0,5 si no sé la proporción?",
		"faq_a2": "Maximiza p(1−p) y da el plan más conservador para ese E.",
		"faq_q3": "¿Siempre sale un entero?",
		"faq_a3": "Sí: se aplica techo (ceil) al resultado de la fórmula.",
		"faq_q4": "¿Puedo escribir Z a mano?",
		"faq_a4": "Aquí el desplegable 90/95/99 fija los Z habituales.",
		"disclaimer": "Solo fórmula educativa de tamaño muestral de proporción. No sustituye metodología de encuestas.",
		"references": "Wikipedia sobre determinación del tamaño muestral y margen de error.",
		"ref_ss_label": "Wikipedia — Determinación del tamaño muestral",
		"ref_prop_label": "Wikipedia — Margen de error",
		"article": "Estima n para una proporción con n = Z² p (1−p)/E² y niveles 90/95/99%.",
	}),
	ar: withBtns('ar', {
		"conf_label": "مستوى الثقة",
		"conf_90": "90٪ (Z = 1.645)",
		"conf_95": "95٪ (Z = 1.96)",
		"conf_99": "99٪ (Z = 2.576)",
		"p_label": "النسبة المتوقعة p",
		"p_ph": "مثال 0.5",
		"E_label": "هامش الخطأ E",
		"E_ph": "مثال 0.05",
		"nOut_label": "حجم العينة المطلوب n",
		"result_note": "n = ceil(Z²·p·(1−p)/E²) لنسبة — تقريب طبيعي ومجتمع لانهائي.",
		"err_generic": "أدخل p ضمن [0,1] وE > 0 واختر مستوى الثقة.",
		"how_title": "طريقة الاستخدام",
		"how_body": "اختر 90 أو 95 أو 99٪ ثم أدخل p وهامش E. تُحوَّل الثقة إلى Z ويُرجع سقف Z² p (1−p)/E². في المتصفح لواجبات الاستطلاع.",
		"formula_title": "الصيغة والافتراضات",
		"formula_body": "n = Z² · p · (1 − p) / E² ثم السقف. حدود:",
		"formula_item_1": "Z: 1.645 / 1.96 / 2.576 للمستويات 90 / 95 / 99٪.",
		"formula_item_2": "تقريب طبيعي لنسبة واحدة؛ بلا تصحيح مجتمع محدود.",
		"formula_item_3": "p = 0.5 يعظّم n عند تثبيت E.",
		"formula_item_4": "التصاميم المعقّدة تحتاج خطة أشمل.",
		"example_title": "مثال",
		"example": "مثال: 95٪ (Z=1.96) وp=0.5 وE=0.05 → n = 385.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "واجب: تقدير حجم استطلاع نسبة بسيط.",
		"usecase_2": "مقارنة أثر تصغير E على n.",
		"usecase_3": "ربطه لاحقًا بصفحة فترة ثقة.",
		"faq_q1": "هل الناتج دائمًا عدد صحيح؟",
		"faq_a1": "نعم؛ تُطبَّق دالة السقف على نتيجة الصيغة.",
		"faq_q2": "هل يوجد تصحيح لمجتمع محدود؟",
		"faq_a2": "لا؛ يفترض مجتمعًا كبيرًا بالنسبة إلى n.",
		"faq_q3": "لماذا يُستخدم p=0.5 عند الجهل؟",
		"faq_a3": "لأنه يعطي أكبر n لنفس E فيكون التخطيط أكثر تحفظًا.",
		"faq_q4": "هل أُدخل Z يدويًا؟",
		"faq_a4": "هذه الصفحة تعتمد قائمة 90/95/99 للقيم الشائعة.",
		"disclaimer": "صيغة تعليمية لحجم عينة النسبة فقط ولا تغني عن منهجية المسح.",
		"references": "ويكيبيديا تحديد حجم العينة وهامش الخطأ.",
		"ref_ss_label": "ويكيبيديا — تحديد حجم العينة",
		"ref_prop_label": "ويكيبيديا — هامش الخطأ",
		"article": "قدّر n لنسبة عبر n = Z² p (1−p)/E² ومستويات 90/95/99٪ في صفحة واحدة.",
	}),
	pt: withBtns('pt', {
		"conf_label": "Nível de confiança",
		"conf_90": "90% (Z = 1,645)",
		"conf_95": "95% (Z = 1,96)",
		"conf_99": "99% (Z = 2,576)",
		"p_label": "Proporção esperada (p)",
		"p_ph": "ex.: 0,5",
		"E_label": "Margem de erro (E)",
		"E_ph": "ex.: 0,05",
		"nOut_label": "Tamanho amostral necessário (n)",
		"result_note": "n = ceil(Z²·p·(1−p)/E²) para proporção — aproximação normal, população infinita.",
		"err_generic": "Informe p em [0, 1], E > 0 e um nível de confiança.",
		"how_title": "Como funciona",
		"how_body": "Escolha 90%, 95% ou 99%, depois a proporção p de planejamento e a margem E. A página mapeia o nível para Z e devolve o teto de Z² p (1−p)/E². No navegador, para tarefas de pesquisa.",
		"formula_title": "Fórmula e pressupostos",
		"formula_body": "n = Z² · p · (1 − p) / E² e depois arredonda para cima. Limites:",
		"formula_item_1": "Z: 1,645 / 1,96 / 2,576 para 90 / 95 / 99%.",
		"formula_item_2": "Aproximação normal de uma proporção; sem correção de população finita.",
		"formula_item_3": "p = 0,5 maximiza n para um E fixo.",
		"formula_item_4": "Amostragens complexas pedem um plano mais completo.",
		"example_title": "Exemplo",
		"example": "Exemplo: 95% (Z = 1,96), p = 0,5, E = 0,05 → n = 385.",
		"usecases_title": "Quando usar",
		"usecase_1": "Tarefa: dimensionar pesquisa de proporção simples.",
		"usecase_2": "Ver como E menor aumenta n.",
		"usecase_3": "Depois cruzar com uma página de intervalo de confiança.",
		"faq_q1": "Posso digitar Z livremente?",
		"faq_a1": "Aqui o seletor 90/95/99 fixa os Z usuais.",
		"faq_q2": "O resultado é sempre inteiro?",
		"faq_a2": "Sim: aplicamos teto (ceil) ao valor da fórmula.",
		"faq_q3": "Por que p = 0,5 quando não sei a proporção?",
		"faq_a3": "Maximiza p(1−p) e deixa o plano mais conservador para aquele E.",
		"faq_q4": "Há correção para população finita?",
		"faq_a4": "Não; assume população grande em relação a n.",
		"disclaimer": "Apenas fórmula educativa de tamanho amostral de proporção. Não substitui metodologia de pesquisa.",
		"references": "Wikipedia sobre determinação de tamanho amostral e margem de erro.",
		"ref_ss_label": "Wikipedia — Determinação do tamanho da amostra",
		"ref_prop_label": "Wikipedia — Margem de erro",
		"article": "Estime n para uma proporção com n = Z² p (1−p)/E² e níveis 90/95/99%.",
	}),
	id: withBtns('id', {
		"conf_label": "Tingkat kepercayaan",
		"conf_90": "90% (Z = 1,645)",
		"conf_95": "95% (Z = 1,96)",
		"conf_99": "99% (Z = 2,576)",
		"p_label": "Proporsi yang diharapkan (p)",
		"p_ph": "mis. 0,5",
		"E_label": "Margin of error (E)",
		"E_ph": "mis. 0,05",
		"nOut_label": "Ukuran sampel yang dibutuhkan (n)",
		"result_note": "n = ceil(Z²·p·(1−p)/E²) untuk proporsi — pendekatan normal, populasi tak hingga.",
		"err_generic": "Masukkan p di [0, 1], E > 0, dan tingkat kepercayaan.",
		"how_title": "Cara kerja",
		"how_body": "Pilih 90%, 95%, atau 99%, lalu masukkan p perencanaan dan margin E. Halaman memetakan tingkat ke Z dan mengembalikan ceil dari Z² p (1−p)/E². Di browser untuk tugas survei.",
		"formula_title": "Rumus dan asumsi",
		"formula_body": "n = Z² · p · (1 − p) / E² lalu dibulatkan ke atas. Batasan:",
		"formula_item_1": "Z: 1,645 / 1,96 / 2,576 untuk 90 / 95 / 99%.",
		"formula_item_2": "Pendekatan normal proporsi tunggal; tanpa koreksi populasi terbatas.",
		"formula_item_3": "p = 0,5 memaksimalkan n untuk E tetap.",
		"formula_item_4": "Desain kompleks butuh rencana yang lebih lengkap.",
		"example_title": "Contoh",
		"example": "Contoh: 95% (Z = 1,96), p = 0,5, E = 0,05 → n = 385.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "PR: menghitung ukuran survei proporsi sederhana.",
		"usecase_2": "Melihat dampak E yang lebih ketat terhadap n.",
		"usecase_3": "Menyandingkan dengan halaman interval kepercayaan setelah ada data.",
		"faq_q1": "Mengapa p = 0,5 jika proporsi tidak diketahui?",
		"faq_a1": "Karena p(1−p) maksimal di 0,5 sehingga rencana paling konservatif.",
		"faq_q2": "Apakah ada koreksi populasi terbatas?",
		"faq_a2": "Tidak; mengasumsikan populasi besar relatif terhadap n.",
		"faq_q3": "Bisakah saya mengisi Z sendiri?",
		"faq_a3": "Halaman ini memakai pilihan 90/95/99 untuk Z standar.",
		"faq_q4": "Apakah hasil selalu bilangan bulat?",
		"faq_a4": "Ya; nilai rumus dibulatkan ke atas (ceil).",
		"disclaimer": "Hanya rumus edukasi ukuran sampel proporsi. Bukan pengganti metodologi survei.",
		"references": "Wikipedia penentuan ukuran sampel dan margin of error.",
		"ref_ss_label": "Wikipedia — Penentuan ukuran sampel",
		"ref_prop_label": "Wikipedia — Margin of error",
		"article": "Perkirakan n untuk proporsi dengan n = Z² p (1−p)/E² dan tingkat 90/95/99%.",
	}),
	fr: withBtns('fr', {
		"conf_label": "Niveau de confiance",
		"conf_90": "90 % (Z = 1,645)",
		"conf_95": "95 % (Z = 1,96)",
		"conf_99": "99 % (Z = 2,576)",
		"p_label": "Proportion attendue (p)",
		"p_ph": "ex. 0,5",
		"E_label": "Marge d’erreur (E)",
		"E_ph": "ex. 0,05",
		"nOut_label": "Taille d’échantillon requise (n)",
		"result_note": "n = ceil(Z²·p·(1−p)/E²) pour une proportion — approximation normale, population infinie.",
		"err_generic": "Saisissez p dans [0, 1], E > 0 et un niveau de confiance.",
		"how_title": "Fonctionnement",
		"how_body": "Choisissez 90 %, 95 % ou 99 %, puis la proportion p de planification et la marge E. La page mappe le niveau vers Z et renvoie le plafond de Z² p (1−p)/E². Dans le navigateur, pour devoirs d’enquête.",
		"formula_title": "Formule et hypothèses",
		"formula_body": "n = Z² · p · (1 − p) / E² puis arrondi vers le haut. Limites :",
		"formula_item_1": "Z : 1,645 / 1,96 / 2,576 pour 90 / 95 / 99 %.",
		"formula_item_2": "Approximation normale d’une proportion ; pas de correction de population finie.",
		"formula_item_3": "p = 0,5 maximise n pour un E fixé.",
		"formula_item_4": "Les plans complexes demandent une étude plus complète.",
		"example_title": "Exemple",
		"example": "Exemple : 95 % (Z = 1,96), p = 0,5, E = 0,05 → n = 385.",
		"usecases_title": "Quand l’utiliser",
		"usecase_1": "Devoir : dimensionner une enquête de proportion simple.",
		"usecase_2": "Voir comment un E plus serré gonfle n.",
		"usecase_3": "Le relier ensuite à une page d’intervalle de confiance.",
		"faq_q1": "Y a-t-il une correction de population finie ?",
		"faq_a1": "Non ; on suppose une population grande par rapport à n.",
		"faq_q2": "Puis-je saisir Z librement ?",
		"faq_a2": "Cette page utilise le sélecteur 90/95/99 pour les Z courants.",
		"faq_q3": "Pourquoi p = 0,5 en cas d’incertitude ?",
		"faq_a3": "Parce que p(1−p) est maximal en 0,5 : plan le plus prudent pour cet E.",
		"faq_q4": "Le résultat est-il toujours entier ?",
		"faq_a4": "Oui : on applique un plafond (ceil) au résultat de la formule.",
		"disclaimer": "Formule pédagogique de taille d’échantillon pour une proportion uniquement. Ne remplace pas une méthodologie d’enquête.",
		"references": "Wikipedia sur la détermination de la taille d’échantillon et la marge d’erreur.",
		"ref_ss_label": "Wikipedia — Détermination de la taille d’échantillon",
		"ref_prop_label": "Wikipedia — Marge d’erreur",
		"article": "Estimez n pour une proportion avec n = Z² p (1−p)/E² et les niveaux 90/95/99 %.",
	}),
	ja: withBtns('ja', {
		"conf_label": "信頼水準",
		"conf_90": "90%（Z = 1.645）",
		"conf_95": "95%（Z = 1.96）",
		"conf_99": "99%（Z = 2.576）",
		"p_label": "想定比率 p",
		"p_ph": "例: 0.5",
		"E_label": "許容誤差 E",
		"E_ph": "例: 0.05",
		"nOut_label": "必要な標本数 n",
		"result_note": "比率の n = ceil(Z²·p·(1−p)/E²)。正規近似で、有限母集団補正なし。",
		"err_generic": "p は [0,1]、E > 0、信頼水準を選んでください。",
		"how_title": "使い方",
		"how_body": "90・95・99% を選び、計画用の比率 p と許容誤差 E を入れます。信頼水準を Z に写し、Z² p (1−p)/E² を切り上げて返します。ブラウザ内で調査の宿題向けです。",
		"formula_title": "式と前提",
		"formula_body": "n = Z² · p · (1 − p) / E² を切り上げ。注意点：",
		"formula_item_1": "Z は 90/95/99% で 1.645/1.96/2.576。",
		"formula_item_2": "単一比率の正規近似。有限母集団補正は含みません。",
		"formula_item_3": "E 固定なら p=0.5 で n が最大（保守的）。",
		"formula_item_4": "複雑設計や検出力分析は別途の計画が必要です。",
		"example_title": "例",
		"example": "例：95%（Z=1.96）、p=0.5、E=0.05 → n = 385。",
		"usecases_title": "こんなときに",
		"usecase_1": "簡単な比率調査の標本数を見積もる宿題。",
		"usecase_2": "E を締めると n がどう膨らむかを比較。",
		"usecase_3": "データ取得後は信頼区間ページと併用。",
		"faq_q1": "結果は必ず整数？",
		"faq_a1": "はい。式の値を切り上げ（ceil）します。",
		"faq_q2": "Z を直接入力できますか？",
		"faq_a2": "このページは 90/95/99 の選択で標準 Z を使います。",
		"faq_q3": "有限母集団補正は？",
		"faq_a3": "ありません。母集団が n に対して大きいとみなします。",
		"faq_q4": "p が不明なら 0.5 でよい？",
		"faq_a4": "同じ E なら最も保守的な n になるため、よく使います。",
		"disclaimer": "教育用の比率標本数公式のみで、調査方法論や検出力ソフトの代わりにはなりません。",
		"references": "Wikipedia の標本サイズの決定と誤差の範囲。",
		"ref_ss_label": "Wikipedia — 標本サイズの決定",
		"ref_prop_label": "Wikipedia — 誤差の範囲",
		"article": "n = Z² p (1−p)/E² と 90/95/99% で比率調査に必要な標本数を見積もります。",
	}),
	ru: withBtns('ru', {
		"conf_label": "Уровень доверия",
		"conf_90": "90% (Z = 1,645)",
		"conf_95": "95% (Z = 1,96)",
		"conf_99": "99% (Z = 2,576)",
		"p_label": "Ожидаемая доля (p)",
		"p_ph": "напр. 0,5",
		"E_label": "Предельная ошибка (E)",
		"E_ph": "напр. 0,05",
		"nOut_label": "Необходимый размер выборки (n)",
		"result_note": "n = ceil(Z²·p·(1−p)/E²) для доли — нормальная аппроксимация, бесконечная генеральная совокупность.",
		"err_generic": "Введите p в [0, 1], E > 0 и уровень доверия.",
		"how_title": "Как пользоваться",
		"how_body": "Выберите 90%, 95% или 99%, затем плановую долю p и погрешность E. Страница сопоставляет уровень с Z и возвращает ceil от Z² p (1−p)/E². В браузере — для учебных опросов.",
		"formula_title": "Формула и допущения",
		"formula_body": "n = Z² · p · (1 − p) / E² с округлением вверх. Ограничения:",
		"formula_item_1": "Z: 1,645 / 1,96 / 2,576 для 90 / 95 / 99%.",
		"formula_item_2": "Нормальная аппроксимация одной доли; без поправки на конечную совокупность.",
		"formula_item_3": "При фиксированном E значение p = 0,5 даёт максимальный n.",
		"formula_item_4": "Сложные дизайны требуют более полного плана.",
		"example_title": "Пример",
		"example": "Пример: 95% (Z = 1,96), p = 0,5, E = 0,05 → n = 385.",
		"usecases_title": "Когда применять",
		"usecase_1": "Домашнее задание: оценить n для опроса доли.",
		"usecase_2": "Сравнить, как меньший E увеличивает n.",
		"usecase_3": "Затем сопоставить со страницей доверительного интервала.",
		"faq_q1": "Можно ли ввести Z вручную?",
		"faq_a1": "На этой странице селектор 90/95/99 задаёт обычные Z.",
		"faq_q2": "Есть ли поправка на конечную совокупность?",
		"faq_a2": "Нет; предполагается большая генеральная совокупность относительно n.",
		"faq_q3": "Почему при неизвестной доле берут p = 0,5?",
		"faq_a3": "Так максимален p(1−p), план наиболее консервативен при данном E.",
		"faq_q4": "Результат всегда целое?",
		"faq_a4": "Да; к результату формулы применяется ceil.",
		"disclaimer": "Только учебная формула размера выборки для доли. Не заменяет методологию опросов.",
		"references": "Wikipedia об определении размера выборки и предельной ошибке.",
		"ref_ss_label": "Wikipedia — Определение размера выборки",
		"ref_prop_label": "Wikipedia — Предельная ошибка",
		"article": "Оцените n для доли по n = Z² p (1−p)/E² и уровням 90/95/99%.",
	}),
	de: withBtns('de', {
		"conf_label": "Konfidenzniveau",
		"conf_90": "90 % (Z = 1,645)",
		"conf_95": "95 % (Z = 1,96)",
		"conf_99": "99 % (Z = 2,576)",
		"p_label": "Erwarteter Anteil (p)",
		"p_ph": "z. B. 0,5",
		"E_label": "Fehlerspanne (E)",
		"E_ph": "z. B. 0,05",
		"nOut_label": "Erforderlicher Stichprobenumfang (n)",
		"result_note": "n = ceil(Z²·p·(1−p)/E²) für einen Anteil — Normalnäherung, unendliche Grundgesamtheit.",
		"err_generic": "Bitte p in [0, 1], E > 0 und ein Konfidenzniveau eingeben.",
		"how_title": "So funktioniert’s",
		"how_body": "Wählen Sie 90 %, 95 % oder 99 %, dann den Planungsanteil p und die Fehlerspanne E. Die Seite mappt das Niveau auf Z und liefert die Aufrundung von Z² p (1−p)/E². Im Browser für Umfrage-Übungen.",
		"formula_title": "Formel und Annahmen",
		"formula_body": "n = Z² · p · (1 − p) / E², danach aufrunden. Grenzen:",
		"formula_item_1": "Z: 1,645 / 1,96 / 2,576 für 90 / 95 / 99 %.",
		"formula_item_2": "Normalnäherung eines Anteils; keine Korrektur für endliche Grundgesamtheit.",
		"formula_item_3": "Bei festem E maximiert p = 0,5 den Wert n.",
		"formula_item_4": "Komplexe Designs brauchen einen vollständigeren Plan.",
		"example_title": "Beispiel",
		"example": "Beispiel: 95 % (Z = 1,96), p = 0,5, E = 0,05 → n = 385.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Hausaufgabe: n für eine einfache Anteilsbefragung schätzen.",
		"usecase_2": "Sehen, wie engeres E das nötige n aufbläht.",
		"usecase_3": "Danach mit einer Konfidenzintervall-Seite kombinieren.",
		"faq_q1": "Ist das Ergebnis immer ganzzahlig?",
		"faq_a1": "Ja; der Formelwert wird aufgerundet (ceil).",
		"faq_q2": "Gibt es eine Korrektur für endliche Grundgesamtheiten?",
		"faq_a2": "Nein; es wird eine große Grundgesamtheit relativ zu n angenommen.",
		"faq_q3": "Kann ich Z frei eingeben?",
		"faq_a3": "Diese Seite nutzt die Auswahl 90/95/99 für übliche Z-Werte.",
		"faq_q4": "Warum p = 0,5 bei Unsicherheit?",
		"faq_a4": "Weil p(1−p) dort maximal ist — konservativster Plan für dieses E.",
		"disclaimer": "Nur Lernformel für den Stichprobenumfang eines Anteils. Ersetzt keine Umfragemethodik.",
		"references": "Wikipedia zu Stichprobenumfang und Fehlerspanne.",
		"ref_ss_label": "Wikipedia — Bestimmung des Stichprobenumfangs",
		"ref_prop_label": "Wikipedia — Fehlerspanne",
		"article": "Schätzen Sie n für einen Anteil mit n = Z² p (1−p)/E² und 90/95/99 %.",
	}),
};

export default {
	seq: 26,
	slug: "how-to-calculate-sample-size",
	prefix: "tool_sample_size",
	nameZh: "样本量计算器",
	category: 'calculator',
	ymyl: false,
	pageFile: "howToCalculateSampleSizePage",
	pageExport: "renderHowToCalculateSampleSizePage",
	anchor: "sample-size",
	related: ["how-to-calculate-confidence-interval","how-to-calculate-p-value"],
	glyph: "M6 24h20M10 20V10h4v10M18 20V6h4v14",
	sampleHint: "95% (Z=1.96), p=0.5, E=0.05 → n≈385 (ceil)",
	titles: {
		"en": "Sample Size Calculator — How to Estimate Required n",
		"zh": "样本量计算器 — 如何估算所需样本量",
		"es": "Calculadora de tamaño muestral — Cómo estimar la n necesaria",
		"ar": "حاسبة حجم العينة — كيفية تقدير الحجم المطلوب",
		"pt": "Calculadora de tamanho amostral — Como estimar o n necessário",
		"id": "Kalkulator ukuran sampel — Cara memperkirakan n yang dibutuhkan",
		"fr": "Calculateur de taille d’échantillon — Comment estimer n",
		"ja": "サンプルサイズ計算ツール — 必要標本数の見積もり方",
		"ru": "Калькулятор размера выборки — Как оценить необходимый n",
		"de": "Stichprobenumfang-Rechner — Erforderliches n schätzen"
	},
	descriptions: {
		"en": "Estimate required sample size for a proportion with n = Z²·p·(1−p)/E². Pick 90/95/99% confidence (Z = 1.645/1.96/2.576), enter p and margin of error E. Example: 95%, p = 0.5, E = 0.05 → n ≈ 385 (ceil). Browser-only learning tool.",
		"zh": "用比例样本量公式 n = Z²·p·(1−p)/E² 估算所需样本量。可选 90%/95%/99% 置信水平（对应 Z = 1.645/1.96/2.576），输入总体比例 p 与允许误差 E。示例：95%、p = 0.5、E = 0.05 → 向上取整后 n ≈ 385。浏览器内计算，适合作业与抽样设计粗算，并写明正态近似与有限总体等边界。",
		"es": "Estima el tamaño muestral de una proporción con n = Z²·p·(1−p)/E². Elige 90/95/99% (Z = 1,645/1,96/2,576), introduce p y el error E. Ejemplo: 95%, p = 0,5, E = 0,05 → n ≈ 385 (ceil). En el navegador, para clase.",
		"ar": "قدّر حجم العينة لنسبة بـ n = Z²·p·(1−p)/E². اختر ثقة 90/95/99٪ (Z = 1.645/1.96/2.576) وأدخل p وهامش الخطأ E. مثال: 95٪ وp=0.5 وE=0.05 → n≈385 بعد السقف. في المتصفح للتعلّم.",
		"pt": "Estime o tamanho amostral de uma proporção com n = Z²·p·(1−p)/E². Escolha 90/95/99% (Z = 1,645/1,96/2,576), informe p e a margem E. Exemplo: 95%, p = 0,5, E = 0,05 → n ≈ 385 (ceil). No navegador, para estudo.",
		"id": "Perkirakan ukuran sampel proporsi dengan n = Z²·p·(1−p)/E². Pilih 90/95/99% (Z = 1,645/1,96/2,576), masukkan p dan margin E. Contoh: 95%, p = 0,5, E = 0,05 → n ≈ 385 (ceil). Di browser untuk tugas.",
		"fr": "Estimez la taille d’échantillon pour une proportion avec n = Z²·p·(1−p)/E². Choisissez 90/95/99 % (Z = 1,645/1,96/2,576), saisissez p et l’erreur E. Exemple : 95 %, p = 0,5, E = 0,05 → n ≈ 385 (ceil). Dans le navigateur.",
		"ja": "比率の必要標本数を n = Z²·p·(1−p)/E² で見積もります。信頼水準 90/95/99%（Z = 1.645/1.96/2.576）を選び、比率 p と許容誤差 E を入力。例：95%、p = 0.5、E = 0.05 → 切り上げで n ≈ 385。ブラウザ内で宿題や調査設計の粗い確認向けで、正規近似などの前提も明示します。",
		"ru": "Оцените размер выборки для доли по n = Z²·p·(1−p)/E². Выберите 90/95/99% (Z = 1,645/1,96/2,576), введите p и погрешность E. Пример: 95%, p = 0,5, E = 0,05 → n ≈ 385 (ceil). В браузере для учёбы.",
		"de": "Schätzen Sie den Stichprobenumfang für einen Anteil mit n = Z²·p·(1−p)/E². Wählen Sie 90/95/99 % (Z = 1,645/1,96/2,576), geben Sie p und Fehlerspanne E ein. Beispiel: 95 %, p = 0,5, E = 0,05 → n ≈ 385 (ceil). Im Browser zum Lernen."
	},
	ui: _ui,
	fields: [
		{
			"id": "conf",
			"type": "select",
			"half": true,
			"labelKey": "conf_label",
			"options": [
				{
					"value": "90",
					"labelKey": "conf_90"
				},
				{
					"value": "95",
					"labelKey": "conf_95",
					"selected": true
				},
				{
					"value": "99",
					"labelKey": "conf_99"
				}
			]
		},
		{
			"id": "p",
			"type": "number",
			"half": true,
			"labelKey": "p_label",
			"phKey": "p_ph"
		},
		{
			"id": "E",
			"type": "number",
			"half": true,
			"labelKey": "E_label",
			"phKey": "E_ph"
		}
	],
	results: [
		{
			"id": "nOut",
			"labelKey": "nOut_label"
		}
	],
	refs: [
		{
			"labelKey": "ref_ss_label",
			"href": "https://en.wikipedia.org/wiki/Sample_size_determination"
		},
		{
			"labelKey": "ref_prop_label",
			"href": "https://en.wikipedia.org/wiki/Margin_of_error"
		}
	],
	computeJs: `
        /** 置信水平 → 双侧正态临界 Z。 */
        var zMap = { '90': 1.645, '95': 1.96, '99': 2.576 };
        var z = zMap[confEl.value];
        var p = parseFloat(pEl.value);
        var E = parseFloat(EEl.value);
        if (!z || !Number.isFinite(p) || p < 0 || p > 1 || !Number.isFinite(E) || !(E > 0)) {
          return { ok: false, error: msgErr };
        }
        /** 比例样本量：n = Z² p (1-p) / E²，再向上取整。 */
        var nRaw = (z * z * p * (1 - p)) / (E * E);
        var n = Math.ceil(nRaw - 1e-12);
        if (!Number.isFinite(n) || n < 1) {
          return { ok: false, error: msgErr };
        }
        return { ok: true, values: { nOut: String(n) } };
`,
	sampleJs: `
        confEl.value = '95';
        pEl.value = '0.5';
        EEl.value = '0.05';
`,
};
