/**
 * §12 #31 how-to-calculate-slope 工具定义（十语独立 UI）。
 * prefix: tool_slope；page: howToCalculateSlopePage / renderHowToCalculateSlopePage。
 */
import { withBtns } from '../locale-ui-common.mjs';

/** 十语 UI（how/formula/faq/usecase 等须独立重写，禁止英模同构）。 */
const _ui = {
	ar: withBtns('ar', {
		"x1_label": "x₁",
		"x1_ph": "مثال 1",
		"y1_label": "y₁",
		"y1_ph": "مثال 2",
		"x2_label": "x₂",
		"x2_ph": "مثال 3",
		"y2_label": "y₂",
		"y2_ph": "مثال 6",
		"slopeOut_label": "الميل m",
		"result_note": "m=(y₂−y₁)/(x₂−x₁). الخطوط الرأسية (Δx=0) تُرفض كغير معرّفة.",
		"err_generic": "أدخل أربع إحداثيات محدودة مع x₂≠x₁.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل نقطتين مختلفتين. تُرجع الميل؛ إن تطابقت x يظهر خطأ.",
		"formula_title": "الصيغة",
		"formula_body": "الميل بين نقطتين:",
		"formula_item_1": "m=(y₂−y₁)/(x₂−x₁).",
		"formula_item_2": "m الموجب يصعد يسار→يمين والسالب يهبط.",
		"formula_item_3": "Δx=0 خط رأسي — غير معرّف هنا.",
		"formula_item_4": "تبديل النقطتين يبقي النسبة.",
		"example_title": "مثال",
		"example": "مثال: (1,2) و(3,6) → m=2.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "جبر: ميل من نقطتين.",
		"usecase_2": "التحقق قبل الرسم.",
		"usecase_3": "مقارنة مع نسبة Δy:Δx.",
		"disclaimer": "ميل ثنائي الأبعاد تعليمي فقط.",
		"references": "ويكيبيديا الميل.",
		"ref_slope_label": "ويكيبيديا — الميل",
		"ref_line_label": "ويكيبيديا — المعادلة الخطية",
		"article": "احسب الميل m بين نقطتين عبر (y₂−y₁)/(x₂−x₁).",
		"faq_q1": "ماذا لو x₁=x₂؟",
		"faq_a1": "الميل غير معرّف (خط رأسي)؛ تظهر رسالة خطأ.",
		"faq_q2": "هل الترتيب مهم؟",
		"faq_a2": "تبديل النقطتين يبقي m نفسه.",
		"faq_q3": "هل الخط الأفقي مسموح؟",
		"faq_a3": "نعم؛ إذا y₁=y₂ وx مختلف فإن m=0.",
		"faq_q4": "ماذا يعني m=2؟",
		"faq_a4": "لكل +1 في x تزداد y بمقدار 2.",
	}),
	de: withBtns('de', {
		"x1_label": "x₁",
		"x1_ph": "z. B. 1",
		"y1_label": "y₁",
		"y1_ph": "z. B. 2",
		"x2_label": "x₂",
		"x2_ph": "z. B. 3",
		"y2_label": "y₂",
		"y2_ph": "z. B. 6",
		"slopeOut_label": "Steigung m",
		"result_note": "m=(y₂−y₁)/(x₂−x₁). Vertikale (Δx=0) werden als undefiniert abgelehnt.",
		"err_generic": "Vier endliche Koordinaten mit x₂≠x₁ eingeben.",
		"how_title": "So funktioniert’s",
		"how_body": "Geben Sie zwei verschiedene Punkte ein. Liefert die Steigung; bei gleichen x-Werten Fehler.",
		"formula_title": "Formel",
		"formula_body": "Steigung zwischen zwei Punkten:",
		"formula_item_1": "m=(y₂−y₁)/(x₂−x₁).",
		"formula_item_2": "m>0 steigt links→rechts; m<0 fällt.",
		"formula_item_3": "Δx=0 ist vertikal — hier undefiniert.",
		"formula_item_4": "Vertauschen beider Punkte lässt das Verhältnis gleich.",
		"example_title": "Beispiel",
		"example": "Beispiel: (1,2) und (3,6) → m=2.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Algebra: Steigung aus zwei Punkten.",
		"usecase_2": "Rise/Run vor dem Zeichnen prüfen.",
		"usecase_3": "Mit Δy:Δx-Aspektgedanken vergleichen.",
		"disclaimer": "Nur 2D-Lernsteigung — kein vollständiger Geradenlöser.",
		"references": "Wikipedia Steigung.",
		"ref_slope_label": "Wikipedia — Steigung",
		"ref_line_label": "Wikipedia — Lineare Gleichung",
		"article": "Berechnen Sie die Steigung m zwischen zwei Punkten mit (y₂−y₁)/(x₂−x₁).",
		"faq_q1": "Was bedeutet m=2?",
		"faq_a1": "Pro +1 in x steigt y um 2.",
		"faq_q2": "Wenn x₁=x₂?",
		"faq_a2": "Steigung undefiniert (vertikal); hier Fehler.",
		"faq_q3": "Reihenfolge der Punkte?",
		"faq_a3": "Vertauschen beider Punkte lässt m gleich.",
		"faq_q4": "Horizontale Gerade?",
		"faq_a4": "Ja — m=0 wenn y₁=y₂ und x verschieden.",
	}),
	en: withBtns('en', {
		"x1_label": "x₁",
		"x1_ph": "e.g. 1",
		"y1_label": "y₁",
		"y1_ph": "e.g. 2",
		"x2_label": "x₂",
		"x2_ph": "e.g. 3",
		"y2_label": "y₂",
		"y2_ph": "e.g. 6",
		"slopeOut_label": "Slope m",
		"result_note": "m = (y₂ − y₁) / (x₂ − x₁). Vertical lines (Δx = 0) are rejected as undefined.",
		"err_generic": "Enter four finite coordinates with x₂ ≠ x₁.",
		"how_title": "How it works",
		"how_body": "Enter two distinct points (x₁,y₁) and (x₂,y₂). The tool returns the slope of the line through them. If the x-coordinates match, the slope is undefined and the page shows an error.",
		"formula_title": "Formula",
		"formula_body": "Slope between two points:",
		"formula_item_1": "m = (y₂ − y₁) / (x₂ − x₁).",
		"formula_item_2": "Positive m rises left→right; negative m falls.",
		"formula_item_3": "Δx = 0 means a vertical line — undefined slope here.",
		"formula_item_4": "Order of points cancels in the ratio if swapped consistently.",
		"example_title": "Example",
		"example": "Example: (1,2) and (3,6) → m = (6−2)/(3−1) = 2.",
		"usecases_title": "When to use it",
		"usecase_1": "Algebra homework: slope from two points.",
		"usecase_2": "Check rise-over-run before graphing.",
		"usecase_3": "Compare with aspect-ratio ideas of Δy:Δx.",
		"disclaimer": "Educational 2D slope only — not a full line-equation solver.",
		"references": "Wikipedia slope.",
		"ref_slope_label": "Wikipedia — Slope",
		"ref_line_label": "Wikipedia — Linear equation",
		"article": "Calculate the slope m between two points with (y₂−y₁)/(x₂−x₁).",
		"faq_q1": "What if x₁ equals x₂?",
		"faq_a1": "The slope is undefined (vertical line); this page errors.",
		"faq_q2": "Does point order matter?",
		"faq_a2": "Swapping both points keeps the same m.",
		"faq_q3": "What does m = 2 mean?",
		"faq_a3": "For each +1 in x, y increases by 2.",
		"faq_q4": "Is a horizontal line allowed?",
		"faq_a4": "Yes — then m = 0 when y₁ = y₂ and x differs.",
	}),
	es: withBtns('es', {
		"x1_label": "x₁",
		"x1_ph": "p. ej. 1",
		"y1_label": "y₁",
		"y1_ph": "p. ej. 2",
		"x2_label": "x₂",
		"x2_ph": "p. ej. 3",
		"y2_label": "y₂",
		"y2_ph": "p. ej. 6",
		"slopeOut_label": "Pendiente m",
		"result_note": "m=(y₂−y₁)/(x₂−x₁). Las verticales (Δx=0) se rechazan como indefinidas.",
		"err_generic": "Introduce cuatro coordenadas finitas con x₂≠x₁.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce dos puntos distintos. Devuelve la pendiente; si coinciden las x, error por indefinida.",
		"formula_title": "Fórmula",
		"formula_body": "Pendiente entre dos puntos:",
		"formula_item_1": "m=(y₂−y₁)/(x₂−x₁).",
		"formula_item_2": "m>0 sube de izquierda a derecha; m<0 baja.",
		"formula_item_3": "Δx=0 es vertical — indefinida aquí.",
		"formula_item_4": "Intercambiar ambos puntos deja el mismo cociente.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: (1,2) y (3,6) → m=2.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Álgebra: pendiente desde dos puntos.",
		"usecase_2": "Comprobar rise/run antes de graficar.",
		"usecase_3": "Comparar con ideas de razón de aspecto Δy:Δx.",
		"disclaimer": "Solo pendiente 2D educativa, no un solver completo de rectas.",
		"references": "Wikipedia pendiente.",
		"ref_slope_label": "Wikipedia — Pendiente",
		"ref_line_label": "Wikipedia — Ecuación lineal",
		"article": "Calcula la pendiente m entre dos puntos con (y₂−y₁)/(x₂−x₁).",
		"faq_q1": "¿Línea horizontal?",
		"faq_a1": "Sí; si y₁=y₂ y x difiere, m=0.",
		"faq_q2": "¿Si x₁=x₂?",
		"faq_a2": "Pendiente indefinida (vertical); error aquí.",
		"faq_q3": "¿Importa el orden?",
		"faq_a3": "Intercambiar ambos puntos deja el mismo m.",
		"faq_q4": "¿Qué significa m=2?",
		"faq_a4": "Por cada +1 en x, y sube 2.",
	}),
	fr: withBtns('fr', {
		"x1_label": "x₁",
		"x1_ph": "ex. 1",
		"y1_label": "y₁",
		"y1_ph": "ex. 2",
		"x2_label": "x₂",
		"x2_ph": "ex. 3",
		"y2_label": "y₂",
		"y2_ph": "ex. 6",
		"slopeOut_label": "Pente m",
		"result_note": "m=(y₂−y₁)/(x₂−x₁). Les verticales (Δx=0) sont rejetées comme indéfinies.",
		"err_generic": "Saisissez quatre coordonnées finies avec x₂≠x₁.",
		"how_title": "Fonctionnement",
		"how_body": "Entrez deux points distincts. Renvoie la pente ; si les x coïncident, erreur.",
		"formula_title": "Formule",
		"formula_body": "Pente entre deux points :",
		"formula_item_1": "m=(y₂−y₁)/(x₂−x₁).",
		"formula_item_2": "m>0 monte de gauche à droite ; m<0 descend.",
		"formula_item_3": "Δx=0 est vertical — indéfini ici.",
		"formula_item_4": "Échanger les deux points conserve le rapport.",
		"example_title": "Exemple",
		"example": "Exemple : (1,2) et (3,6) → m=2.",
		"usecases_title": "Quand l’utiliser",
		"usecase_1": "Algèbre : pente depuis deux points.",
		"usecase_2": "Vérifier rise/run avant de tracer.",
		"usecase_3": "Comparer avec des idées de ratio Δy:Δx.",
		"disclaimer": "Pente 2D pédagogique seulement.",
		"references": "Wikipedia pente.",
		"ref_slope_label": "Wikipedia — Pente",
		"ref_line_label": "Wikipedia — Équation linéaire",
		"article": "Calculez la pente m entre deux points avec (y₂−y₁)/(x₂−x₁).",
		"faq_q1": "Que signifie m=2 ?",
		"faq_a1": "Pour chaque +1 en x, y augmente de 2.",
		"faq_q2": "Si x₁=x₂ ?",
		"faq_a2": "Pente indéfinie (verticale) ; erreur ici.",
		"faq_q3": "Ordre des points ?",
		"faq_a3": "Échanger les deux points conserve m.",
		"faq_q4": "Droite horizontale ?",
		"faq_a4": "Oui — m=0 si y₁=y₂ et x diffère.",
	}),
	id: withBtns('id', {
		"x1_label": "x₁",
		"x1_ph": "mis. 1",
		"y1_label": "y₁",
		"y1_ph": "mis. 2",
		"x2_label": "x₂",
		"x2_ph": "mis. 3",
		"y2_label": "y₂",
		"y2_ph": "mis. 6",
		"slopeOut_label": "Kemiringan m",
		"result_note": "m=(y₂−y₁)/(x₂−x₁). Garis vertikal (Δx=0) ditolak sebagai tak terdefinisi.",
		"err_generic": "Masukkan empat koordinat hingga dengan x₂≠x₁.",
		"how_title": "Cara kerja",
		"how_body": "Masukkan dua titik berbeda. Mengembalikan kemiringan; jika x sama, error.",
		"formula_title": "Rumus",
		"formula_body": "Kemiringan antara dua titik:",
		"formula_item_1": "m=(y₂−y₁)/(x₂−x₁).",
		"formula_item_2": "m positif naik kiri→kanan; m negatif turun.",
		"formula_item_3": "Δx=0 berarti vertikal — tak terdefinisi di sini.",
		"formula_item_4": "Menukar kedua titik menjaga rasio.",
		"example_title": "Contoh",
		"example": "Contoh: (1,2) dan (3,6) → m=2.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Aljabar: kemiringan dari dua titik.",
		"usecase_2": "Cek rise-over-run sebelum menggambar.",
		"usecase_3": "Bandingkan dengan gagasan rasio Δy:Δx.",
		"disclaimer": "Hanya kemiringan 2D edukasi.",
		"references": "Wikipedia slope.",
		"ref_slope_label": "Wikipedia — Slope",
		"ref_line_label": "Wikipedia — Linear equation",
		"article": "Hitung kemiringan m antara dua titik dengan (y₂−y₁)/(x₂−x₁).",
		"faq_q1": "Garis horizontal?",
		"faq_a1": "Ya — m=0 jika y₁=y₂ dan x berbeda.",
		"faq_q2": "Jika x₁=x₂?",
		"faq_a2": "Kemiringan tak terdefinisi (vertikal); halaman ini error.",
		"faq_q3": "Urutan titik?",
		"faq_a3": "Menukar keduanya tetap memberi m sama.",
		"faq_q4": "Arti m=2?",
		"faq_a4": "Setiap +1 pada x, y naik 2.",
	}),
	ja: withBtns('ja', {
		"x1_label": "x₁",
		"x1_ph": "例: 1",
		"y1_label": "y₁",
		"y1_ph": "例: 2",
		"x2_label": "x₂",
		"x2_ph": "例: 3",
		"y2_label": "y₂",
		"y2_ph": "例: 6",
		"slopeOut_label": "傾き m",
		"result_note": "m=(y₂−y₁)/(x₂−x₁)。垂直線（Δx=0）は未定義として拒否。",
		"err_generic": "有限な四座標を入力し、x₂≠x₁ にしてください。",
		"how_title": "使い方",
		"how_body": "異なる二点 (x₁,y₁) と (x₂,y₂) を入れます。通る直線の傾きを返します。x が同じなら未定義でエラーです。",
		"formula_title": "式",
		"formula_body": "二点の傾き：",
		"formula_item_1": "m=(y₂−y₁)/(x₂−x₁)。",
		"formula_item_2": "m>0 は左から右へ上昇、m<0 は下降。",
		"formula_item_3": "Δx=0 は垂直——ここでは未定義。",
		"formula_item_4": "二点を入れ替えても比は同じ。",
		"example_title": "例",
		"example": "例：(1,2) と (3,6) → m=2。",
		"usecases_title": "こんなときに",
		"usecase_1": "代数：二点から傾きを求める宿題。",
		"usecase_2": "グラフ前に立ち上がり/走りを確認。",
		"usecase_3": "アスペクト比の Δy:Δx と見比べる。",
		"disclaimer": "二次元の学習用傾きのみで、直線方程式の総合ソルバーではありません。",
		"references": "Wikipedia の傾き。",
		"ref_slope_label": "Wikipedia — 傾き",
		"ref_line_label": "Wikipedia — 一次方程式",
		"article": "二点間の傾き m を (y₂−y₁)/(x₂−x₁) で計算します。",
		"faq_q1": "点の順序は影響する？",
		"faq_a1": "両方入れ替えても m は同じです。",
		"faq_q2": "x₁=x₂ のとき？",
		"faq_a2": "傾きは未定義（垂直）。このページはエラーにします。",
		"faq_q3": "水平線は？",
		"faq_a3": "可能。y が等しく x が異なれば m=0。",
		"faq_q4": "m=2 の意味は？",
		"faq_a4": "x が 1 増えると y が 2 増えます。",
	}),
	pt: withBtns('pt', {
		"x1_label": "x₁",
		"x1_ph": "ex.: 1",
		"y1_label": "y₁",
		"y1_ph": "ex.: 2",
		"x2_label": "x₂",
		"x2_ph": "ex.: 3",
		"y2_label": "y₂",
		"y2_ph": "ex.: 6",
		"slopeOut_label": "Inclinação m",
		"result_note": "m=(y₂−y₁)/(x₂−x₁). Verticais (Δx=0) são rejeitadas como indefinidas.",
		"err_generic": "Informe quatro coordenadas finitas com x₂≠x₁.",
		"how_title": "Como funciona",
		"how_body": "Digite dois pontos distintos. Devolve a inclinação; se as x coincidem, erro.",
		"formula_title": "Fórmula",
		"formula_body": "Inclinação entre dois pontos:",
		"formula_item_1": "m=(y₂−y₁)/(x₂−x₁).",
		"formula_item_2": "m>0 sobe da esquerda para a direita; m<0 desce.",
		"formula_item_3": "Δx=0 é vertical — indefinida aqui.",
		"formula_item_4": "Trocar ambos os pontos mantém a razão.",
		"example_title": "Exemplo",
		"example": "Exemplo: (1,2) e (3,6) → m=2.",
		"usecases_title": "Quando usar",
		"usecase_1": "Álgebra: inclinação a partir de dois pontos.",
		"usecase_2": "Checar rise/run antes de graficar.",
		"usecase_3": "Comparar com ideias de proporção Δy:Δx.",
		"disclaimer": "Apenas inclinação 2D educativa.",
		"references": "Wikipedia inclinação.",
		"ref_slope_label": "Wikipedia — Inclinação",
		"ref_line_label": "Wikipedia — Equação linear",
		"article": "Calcule a inclinação m entre dois pontos com (y₂−y₁)/(x₂−x₁).",
		"faq_q1": "O que significa m=2?",
		"faq_a1": "Para cada +1 em x, y sobe 2.",
		"faq_q2": "E se x₁=x₂?",
		"faq_a2": "Inclinação indefinida (vertical); erro nesta página.",
		"faq_q3": "Ordem dos pontos?",
		"faq_a3": "Trocar ambos mantém o mesmo m.",
		"faq_q4": "Reta horizontal?",
		"faq_a4": "Sim — m=0 quando y₁=y₂ e x difere.",
	}),
	ru: withBtns('ru', {
		"x1_label": "x₁",
		"x1_ph": "напр. 1",
		"y1_label": "y₁",
		"y1_ph": "напр. 2",
		"x2_label": "x₂",
		"x2_ph": "напр. 3",
		"y2_label": "y₂",
		"y2_ph": "напр. 6",
		"slopeOut_label": "Наклон m",
		"result_note": "m=(y₂−y₁)/(x₂−x₁). Вертикали (Δx=0) отвергаются как неопределённые.",
		"err_generic": "Введите четыре конечные координаты с x₂≠x₁.",
		"how_title": "Как пользоваться",
		"how_body": "Введите две различные точки. Возвращает наклон; при совпадении x — ошибка.",
		"formula_title": "Формула",
		"formula_body": "Наклон между двумя точками:",
		"formula_item_1": "m=(y₂−y₁)/(x₂−x₁).",
		"formula_item_2": "m>0 растёт слева направо; m<0 падает.",
		"formula_item_3": "Δx=0 — вертикаль, здесь не определено.",
		"formula_item_4": "Перестановка обеих точек сохраняет отношение.",
		"example_title": "Пример",
		"example": "Пример: (1,2) и (3,6) → m=2.",
		"usecases_title": "Когда применять",
		"usecase_1": "Алгебра: наклон по двум точкам.",
		"usecase_2": "Проверить rise/run перед графиком.",
		"usecase_3": "Сравнить с идеями отношения Δy:Δx.",
		"disclaimer": "Только учебный 2D-наклон.",
		"references": "Wikipedia о наклоне.",
		"ref_slope_label": "Wikipedia — Угловой коэффициент",
		"ref_line_label": "Wikipedia — Линейное уравнение",
		"article": "Считайте наклон m между двумя точками по (y₂−y₁)/(x₂−x₁).",
		"faq_q1": "Что значит m=2?",
		"faq_a1": "При росте x на 1 y растёт на 2.",
		"faq_q2": "Если x₁=x₂?",
		"faq_a2": "Наклон не определён (вертикаль); здесь ошибка.",
		"faq_q3": "Важен ли порядок точек?",
		"faq_a3": "Перестановка обеих точек сохраняет m.",
		"faq_q4": "Горизонтальная линия?",
		"faq_a4": "Да — m=0 при y₁=y₂ и разных x.",
	}),
	zh: withBtns('zh', {
		"x1_label": "x₁",
		"x1_ph": "例如 1",
		"y1_label": "y₁",
		"y1_ph": "例如 2",
		"x2_label": "x₂",
		"x2_ph": "例如 3",
		"y2_label": "y₂",
		"y2_ph": "例如 6",
		"slopeOut_label": "斜率 m",
		"result_note": "m=(y₂−y₁)/(x₂−x₁)。竖直线（Δx=0）视为未定义并拒绝。",
		"err_generic": "请输入四个有限坐标，且 x₂≠x₁。",
		"how_title": "怎么用",
		"how_body": "输入两个不同点 (x₁,y₁) 与 (x₂,y₂)。工具返回连线斜率；若 x 相同则斜率未定义并报错。",
		"formula_title": "公式",
		"formula_body": "两点斜率：",
		"formula_item_1": "m=(y₂−y₁)/(x₂−x₁)。",
		"formula_item_2": "m>0 从左到右上升；m<0 下降。",
		"formula_item_3": "Δx=0 为竖直线——本页视为未定义。",
		"formula_item_4": "两点对调后比值不变。",
		"example_title": "示例",
		"example": "示例：(1,2) 与 (3,6) → m=(6−2)/(3−1)=2。",
		"usecases_title": "适合什么场景",
		"usecase_1": "代数作业：由两点求斜率。",
		"usecase_2": "画图前核对升降比。",
		"usecase_3": "与宽高比中的 Δy:Δx 对照。",
		"disclaimer": "仅为二维斜率教育用途，不是完整直线方程求解器。",
		"references": "维基百科斜率条目。",
		"ref_slope_label": "维基百科 — 斜率",
		"ref_line_label": "维基百科 — 一次方程",
		"article": "用 (y₂−y₁)/(x₂−x₁) 计算两点间斜率 m。",
		"faq_q1": "m=2 表示什么？",
		"faq_a1": "x 每增加 1，y 增加 2。",
		"faq_q2": "x₁=x₂ 会怎样？",
		"faq_a2": "斜率为未定义（竖直线），本页报错。",
		"faq_q3": "点的顺序有影响吗？",
		"faq_a3": "两点对调后比值不变。",
		"faq_q4": "水平线可以吗？",
		"faq_a4": "可以，y 相同且 x 不同时 m=0。",
	}),
};

export default {
	seq: 31,
	slug: "how-to-calculate-slope",
	prefix: "tool_slope",
	nameZh: "斜率计算器",
	category: 'calculator',
	ymyl: false,
	pageFile: "howToCalculateSlopePage",
	pageExport: "renderHowToCalculateSlopePage",
	anchor: "slope",
	related: ["how-to-calculate-pythagorean-theorem", "how-to-calculate-aspect-ratio"],
	glyph: "M6 24L26 8",
	sampleHint: "(1,2)(3,6)\u21922",
	titles: {
		"en": "Slope Calculator — How to Calculate Slope Between Two Points",
		"zh": "斜率计算器 — 如何计算两点斜率",
		"es": "Calculadora de pendiente — Cómo calcular la pendiente entre dos puntos",
		"ar": "حاسبة الميل — كيفية حساب الميل بين نقطتين",
		"pt": "Calculadora de inclinação — Como calcular a inclinação entre dois pontos",
		"id": "Kalkulator kemiringan — Cara menghitung kemiringan dua titik",
		"fr": "Calculateur de pente — Comment calculer la pente entre deux points",
		"ja": "傾き計算ツール — 二点間の傾きの求め方",
		"ru": "Калькулятор наклона — Как найти наклон между двумя точками",
		"de": "Steigungsrechner — Steigung zwischen zwei Punkten"
	},
	descriptions: {
		"en": "Calculate slope m = (y₂ − y₁)/(x₂ − x₁) between two points. Example: (1,2) and (3,6) → m = 2. Rejects vertical lines where Δx = 0. Browser learning tool for algebra coursework.",
		"zh": "用 m=(y₂−y₁)/(x₂−x₁) 计算两点连线斜率。示例：(1,2) 与 (3,6) → m=2。Δx=0 的竖直线视为未定义并拒绝。浏览器内计算，适合作业与画图前核对升降比，并说明水平线 m=0、两点对调后比值不变，以及同一单位下的坐标输入。",
		"es": "Calcula la pendiente m=(y₂−y₁)/(x₂−x₁) entre dos puntos. Ejemplo: (1,2) y (3,6) → m=2. Rechaza verticales con Δx=0. En el navegador, para clase de álgebra.",
		"ar": "احسب الميل m=(y₂−y₁)/(x₂−x₁) بين نقطتين على المستوي. مثال: (1,2) و(3,6) → m=2. ترفض الخطوط الرأسية حيث Δx=0 وتوضّح أن الخط الأفقي له ميل صفر. في المتصفح للتعلّم والجبر.",
		"pt": "Calcule a inclinação m=(y₂−y₁)/(x₂−x₁) entre dois pontos. Exemplo: (1,2) e (3,6) → m=2. Rejeita verticais com Δx=0. No navegador, para álgebra.",
		"id": "Hitung kemiringan m=(y₂−y₁)/(x₂−x₁) antara dua titik. Contoh: (1,2) dan (3,6) → m=2. Menolak vertikal dengan Δx=0. Di browser untuk aljabar.",
		"fr": "Calculez la pente m=(y₂−y₁)/(x₂−x₁) entre deux points. Exemple : (1,2) et (3,6) → m=2. Refuse les verticales avec Δx=0. Dans le navigateur, pour l’algèbre.",
		"ja": "二点間の傾き m=(y₂−y₁)/(x₂−x₁) を計算します。例：(1,2) と (3,6) → m=2。Δx=0 の垂直線は未定義として拒否。ブラウザ内で代数の宿題向けで、水平線 m=0、点の順序入れ替え後も比が同じこと、同一単位の座標入力を明示します。",
		"ru": "Считайте наклон m=(y₂−y₁)/(x₂−x₁) между двумя точками. Пример: (1,2) и (3,6) → m=2. Отвергает вертикали с Δx=0. В браузере для алгебры.",
		"de": "Berechnen Sie die Steigung m=(y₂−y₁)/(x₂−x₁) zwischen zwei Punkten. Beispiel: (1,2) und (3,6) → m=2. Lehnt Vertikale mit Δx=0 ab. Im Browser für Algebra."
	},
	ui: _ui,
	fields: [
		{
			"id": "x1",
			"type": "number",
			"half": true,
			"labelKey": "x1_label",
			"phKey": "x1_ph"
		},
		{
			"id": "y1",
			"type": "number",
			"half": true,
			"labelKey": "y1_label",
			"phKey": "y1_ph"
		},
		{
			"id": "x2",
			"type": "number",
			"half": true,
			"labelKey": "x2_label",
			"phKey": "x2_ph"
		},
		{
			"id": "y2",
			"type": "number",
			"half": true,
			"labelKey": "y2_label",
			"phKey": "y2_ph"
		}
	],
	results: [
		{
			"id": "slopeOut",
			"labelKey": "slopeOut_label"
		}
	],
	refs: [
		{
			"labelKey": "ref_slope_label",
			"href": "https://en.wikipedia.org/wiki/Slope"
		},
		{
			"labelKey": "ref_line_label",
			"href": "https://en.wikipedia.org/wiki/Linear_equation"
		}
	],
	computeJs: `
        var x1 = parseFloat(x1El.value);
        var y1 = parseFloat(y1El.value);
        var x2 = parseFloat(x2El.value);
        var y2 = parseFloat(y2El.value);
        if (![x1,y1,x2,y2].every(Number.isFinite) || x2 === x1) {
          return { ok: false, error: msgErr };
        }
        var m = (y2 - y1) / (x2 - x1);
        return { ok: true, values: { slopeOut: fmt(m, 6) } };
`,
	sampleJs: `
        x1El.value = '1';
        y1El.value = '2';
        x2El.value = '3';
        y2El.value = '6';
`,
};
