/**
 * §12 #45 how-to-calculate-tip
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"bill_label": "Bill amount",
		"bill_ph": "e.g. 80",
		"tip_label": "Tip %",
		"tip_ph": "e.g. 15",
		"split_label": "Split between (people)",
		"split_ph": "e.g. 1",
		"tipOut_label": "Tip",
		"totalOut_label": "Total",
		"eachOut_label": "Per person",
		"result_note": "Tip = bill × tip%; total = bill + tip; per person = total / people.",
		"err_generic": "Enter bill > 0, tip % ≥ 0, and people ≥ 1.",
		"how_title": "How it works",
		"how_body": "Enter the bill, tip percent, and how many people split the total. Customs vary by country — this is arithmetic only.",
		"formula_title": "Formula",
		"formula_body": "Tip = bill × p; total = bill + tip; each = total / n. Notes:",
		"formula_item_1": "Does not auto-add tax; add tax into the bill if needed.",
		"formula_item_2": "Rounding at restaurants may differ.",
		"formula_item_3": "Not a payment processor.",
		"example_title": "Example",
		"example": "Example: bill 80, tip 15%, 1 person → tip 12, total 92.",
		"usecases_title": "When to use it",
		"usecase_1": "Restaurant checkout tip math.",
		"usecase_2": "Split a shared bill after tip.",
		"usecase_3": "Pair with VAT/discount for receipt drills.",
		"faq_q1": "Sample?",
		"faq_a1": "80 at 15% → tip 12, total 92.",
		"faq_q2": "Include tax?",
		"faq_a2": "Add tax into the bill first if you tip on tax-inclusive totals.",
		"faq_q3": "Split 0 people?",
		"faq_a3": "People must be ≥ 1.",
		"faq_q4": "Payment app?",
		"faq_a4": "No — local arithmetic only.",
		"article": "Tip and split",
		"disclaimer": "Educational tip only — not financial, tax, or investment advice.",
		"references": "Investopedia and standard textbook formulas.",
		"ref_a_label": "Wikipedia — Gratuity",
		"ref_b_label": "Investopedia — Tip",
	}),
	zh: withBtns("zh", {
		"bill_label": "账单金额",
		"bill_ph": "例如 80",
		"tip_label": "小费比例 %",
		"tip_ph": "例如 15",
		"split_label": "分摊人数",
		"split_ph": "例如 1",
		"tipOut_label": "小费",
		"totalOut_label": "合计",
		"eachOut_label": "人均",
		"result_note": "小费=账单×比例；合计=账单+小费；人均=合计/人数。",
		"err_generic": "账单>0、小费%≥0、人数≥1。",
		"how_title": "怎么用",
		"how_body": "填入账单、小费比例与分摊人数。各国习惯不同，本页只做算术。",
		"formula_title": "公式",
		"formula_body": "小费=账单×p；合计=账单+小费；人均=合计/n。注意：",
		"formula_item_1": "不含自动加税；若按含税小费请把税并入账单。",
		"formula_item_2": "餐厅四舍五入可能不同。",
		"formula_item_3": "不是支付工具。",
		"example_title": "示例",
		"example": "示例：账单 80、15%、1 人 → 小费 12、合计 92。",
		"usecases_title": "适合什么场景",
		"usecase_1": "餐厅结账小费。",
		"usecase_2": "加小费后分摊。",
		"usecase_3": "与增值税/折扣页对照小票。",
		"faq_q1": "样例？",
		"faq_a1": "80 的 15% → 小费 12、合计 92。",
		"faq_q2": "含税吗？",
		"faq_a2": "需要时请先把税加进账单。",
		"faq_q3": "人数 0？",
		"faq_a3": "人数须 ≥1。",
		"faq_q4": "支付 App？",
		"faq_a4": "不是，仅本地算术。",
		"article": "小费与分摊",
		"disclaimer": "结果仅为小费学习演示，不构成投资、理财或税务建议。",
		"references": "Investopedia 与常见教材公式。",
		"ref_a_label": "Wikipedia — Gratuity",
		"ref_b_label": "Investopedia — Tip",
	}),
	es: withBtns("es", {
		"bill_label": "Cuenta",
		"bill_ph": "p. ej. 80",
		"tip_label": "Propina %",
		"tip_ph": "p. ej. 15",
		"split_label": "Personas",
		"split_ph": "p. ej. 1",
		"tipOut_label": "Propina",
		"totalOut_label": "Total",
		"eachOut_label": "Por persona",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce cuenta, % y personas.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce cuenta, % y personas.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: 80 con 15% → 12 / total 92.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: 80 con 15% → 12 / total 92.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de propina",
		"disclaimer": "Solo ilustración educativa (tip); no es consejo financiero.",
		"references": "Investopedia y fórmulas de libro.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ar: withBtns("ar", {
		"bill_label": "الفاتورة",
		"bill_ph": "مثال 80",
		"tip_label": "البقشيش %",
		"tip_ph": "مثال 15",
		"split_label": "الأشخاص",
		"split_ph": "مثال 1",
		"tipOut_label": "البقشيش",
		"totalOut_label": "الإجمالي",
		"eachOut_label": "للشخص",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل الفاتورة والنسبة والأشخاص.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل الفاتورة والنسبة والأشخاص.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: 80 و15٪ → 12 / الإجمالي 92.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: 80 و15٪ → 12 / الإجمالي 92.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة البقشيش",
		"disclaimer": "توضيح تعليمي فقط (tip) وليس نصيحة مالية.",
		"references": "Investopedia وصيغ دراسية.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	pt: withBtns("pt", {
		"bill_label": "Conta",
		"bill_ph": "ex. 80",
		"tip_label": "Gorjeta %",
		"tip_ph": "ex. 15",
		"split_label": "Pessoas",
		"split_ph": "ex. 1",
		"tipOut_label": "Gorjeta",
		"totalOut_label": "Total",
		"eachOut_label": "Por pessoa",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe conta, % e pessoas.",
		"formula_title": "Fórmula",
		"formula_body": "Informe conta, % e pessoas.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: 80 com 15% → 12 / total 92.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: 80 com 15% → 12 / total 92.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de gorjeta",
		"disclaimer": "Apenas ilustração educativa (tip); não é conselho financeiro.",
		"references": "Investopedia e fórmulas didáticas.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	id: withBtns("id", {
		"bill_label": "Tagihan",
		"bill_ph": "mis. 80",
		"tip_label": "Tip %",
		"tip_ph": "mis. 15",
		"split_label": "Jumlah orang",
		"split_ph": "mis. 1",
		"tipOut_label": "Tip",
		"totalOut_label": "Total",
		"eachOut_label": "Per orang",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi tagihan, persen, dan orang.",
		"formula_title": "Rumus",
		"formula_body": "Isi tagihan, persen, dan orang.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: 80 tip 15% → 12 / total 92.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: 80 tip 15% → 12 / total 92.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator tip / tip",
		"disclaimer": "Hanya ilustrasi edukatif (tip); bukan saran keuangan.",
		"references": "Investopedia dan rumus buku teks.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	fr: withBtns("fr", {
		"bill_label": "Addition",
		"bill_ph": "ex. 80",
		"tip_label": "Pourboire %",
		"tip_ph": "ex. 15",
		"split_label": "Personnes",
		"split_ph": "ex. 1",
		"tipOut_label": "Pourboire",
		"totalOut_label": "Total",
		"eachOut_label": "Par personne",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez addition, % et personnes.",
		"formula_title": "Formule",
		"formula_body": "Saisissez addition, % et personnes.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : 80 avec 15 % → 12 / total 92.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : 80 avec 15 % → 12 / total 92.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de pourboire",
		"disclaimer": "Illustration éducative (tip) uniquement — pas un conseil financier.",
		"references": "Investopedia et formules de manuel.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ja: withBtns("ja", {
		"bill_label": "会計金額",
		"bill_ph": "例 80",
		"tip_label": "チップ率 %",
		"tip_ph": "例 15",
		"split_label": "割り勘人数",
		"split_ph": "例 1",
		"tipOut_label": "チップ",
		"totalOut_label": "合計",
		"eachOut_label": "一人あたり",
		"result_note": "チップ=会計×率；合計=会計+チップ；一人=合計/人数。",
		"err_generic": "会計>0、率≥0、人数≥1。",
		"how_title": "使い方",
		"how_body": "会計・チップ率・人数を入力。国ごとの習慣は算術の範囲外です。",
		"formula_title": "計算式",
		"formula_body": "チップ=会計×p；合計=会計+チップ。注意:",
		"formula_item_1": "税の自動加算なし。税込みでチップするなら税を会計に含めてください。",
		"formula_item_2": "店舗の端数処理は異なる場合あり。",
		"formula_item_3": "決済アプリではありません。",
		"example_title": "例",
		"example": "例：会計80、15%、1人 → チップ12、合計92。",
		"usecases_title": "こんなときに",
		"usecase_1": "レストラン会計のチップ。",
		"usecase_2": "チップ後の割り勘。",
		"usecase_3": "VAT/割引ページと併用。",
		"faq_q1": "例は？",
		"faq_a1": "80の15%→チップ12、合計92。",
		"faq_q2": "税込み？",
		"faq_a2": "必要なら税を会計に足してから。",
		"faq_q3": "人数0？",
		"faq_a3": "1以上。",
		"faq_q4": "決済？",
		"faq_a4": "いいえ、ローカル計算のみ。",
		"article": "チップと割り勘",
		"disclaimer": "チップの学習用試算であり、投資・税務の助言ではありません。",
		"references": "Investopedia と標準的な教科書公式。",
		"ref_a_label": "Wikipedia — Gratuity",
		"ref_b_label": "Investopedia — Tip",
	}),
	ru: withBtns("ru", {
		"bill_label": "Счёт",
		"bill_ph": "напр. 80",
		"tip_label": "Чаевые %",
		"tip_ph": "напр. 15",
		"split_label": "Человек",
		"split_ph": "напр. 1",
		"tipOut_label": "Чаевые",
		"totalOut_label": "Итого",
		"eachOut_label": "На человека",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите счёт, % и число людей.",
		"formula_title": "Формула",
		"formula_body": "Введите счёт, % и число людей.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: 80 и 15% → 12 / итог 92.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: 80 и 15% → 12 / итог 92.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор чаевых",
		"disclaimer": "Только учебная иллюстрация (tip) — не финансовый совет.",
		"references": "Investopedia и учебные формулы.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	de: withBtns("de", {
		"bill_label": "Rechnung",
		"bill_ph": "z. B. 80",
		"tip_label": "Trinkgeld %",
		"tip_ph": "z. B. 15",
		"split_label": "Personen",
		"split_ph": "z. B. 1",
		"tipOut_label": "Trinkgeld",
		"totalOut_label": "Gesamt",
		"eachOut_label": "Pro Person",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Rechnung, % und Personen eingeben.",
		"formula_title": "Formel",
		"formula_body": "Rechnung, % und Personen eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: 80 bei 15% → 12 / Gesamt 92.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: 80 bei 15% → 12 / Gesamt 92.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Trinkgeld-Rechner",
		"disclaimer": "Nur zur Veranschaulichung (tip) — keine Finanzberatung.",
		"references": "Investopedia und Lehrbuchformeln.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
};
export default {
	seq: 45,
	slug: "how-to-calculate-tip",
	prefix: "tool_tip",
	pageFile: "howToCalculateTipPage",
	pageExport: "renderHowToCalculateTipPage",
	nameZh: "小费计算器",
	ymyl: false,
	related: ["how-to-calculate-vat","how-to-calculate-discount"],
	anchor: "tip",
	glyph: "M8 10h16v12H8zM12 6h8v4h-8z",
	sampleHint: "bill 80 tip 15% → tip 12 total 92",
	titles: {
		en: "Tip Calculator — Tip Amount and Split",
		zh: "小费计算器 — 小费与分摊",
		es: "Calculadora de propina",
		ar: "حاسبة البقشيش",
		pt: "Calculadora de gorjeta",
		id: "Kalkulator tip / tip",
		fr: "Calculateur de pourboire",
		ja: "チップ計算ツール — チップと割り勘",
		ru: "Калькулятор чаевых",
		de: "Trinkgeld-Rechner",
	},
	descriptions: {
		en: "Calculate tip from bill and tip percent, then optionally split the total. Sample: bill 80 with 15% tip → tip 12, total 92. Everyday receipt math in your browser.",
		zh: "按账单与小费比例计算小费，并可按人数分摊合计。示例：账单 80、小费 15% → 小费 12、合计 92。浏览器本地计算，数据不上传服务器；日常结账速算。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。",
		es: "Calcula la propina con cuenta y % y reparte el total. Ejemplo: cuenta 80 con 15% → propina 12, total 92. En el navegador.",
		ar: "احسب البقشيش من الفاتورة والنسبة ثم اقسم الإجمالي. مثال: فاتورة 80 و15٪ → بقشيش 12 والإجمالي 92. في المتصفح.",
		pt: "Calcule a gorjeta com conta e % e divida o total. Exemplo: conta 80 com 15% → gorjeta 12, total 92. No navegador.",
		id: "Hitung tip dari tagihan dan persen, lalu bagi total. Contoh: tagihan 80 tip 15% → tip 12, total 92. Di browser.",
		fr: "Calculez le pourboire avec l’addition et le %, puis partagez. Exemple : 80 avec 15 % → pourboire 12, total 92. Dans le navigateur.",
		ja: "会計とチップ率からチップ額を出し、人数で割り勘できます。例：会計 80、チップ 15% → チップ 12、合計 92。ブラウザ内の日常計算です。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり投資・税務・経営の助言ではありません。",
		ru: "Считайте чаевые от счёта и процента и делите итог. Пример: счёт 80, 15% → чаевые 12, итог 92. В браузере.",
		de: "Berechnen Sie Trinkgeld aus Rechnung und Prozent und teilen Sie optional. Beispiel: 80 bei 15% → 12 Trinkgeld, Gesamt 92. Im Browser.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "bill",
	    "type": "number",
	    "half": true,
	    "labelKey": "bill_label",
	    "phKey": "bill_ph"
	  },
	  {
	    "id": "tip",
	    "type": "number",
	    "half": true,
	    "labelKey": "tip_label",
	    "phKey": "tip_ph"
	  },
	  {
	    "id": "split",
	    "type": "number",
	    "half": true,
	    "labelKey": "split_label",
	    "phKey": "split_ph"
	  }
	],
	results: [
	  {
	    "id": "tipOut",
	    "labelKey": "tipOut_label"
	  },
	  {
	    "id": "totalOut",
	    "labelKey": "totalOut_label"
	  },
	  {
	    "id": "eachOut",
	    "labelKey": "eachOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Gratuity"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.investopedia.com/terms/t/tip.asp"
	  }
	],
	computeJs: `
        var bill=parseFloat(billEl.value), tipPct=parseFloat(tipEl.value), people=parseFloat(splitEl.value);
        if(!(bill>0)||!Number.isFinite(tipPct)||tipPct<0||!(people>=1)) return {ok:false,error:msgErr};
        var tipAmt=bill*tipPct/100, total=bill+tipAmt, each=total/people;
        return {ok:true, values:{ tipOut:fmt(tipAmt), totalOut:fmt(total), eachOut:fmt(each) }};
`,
	sampleJs: `
        billEl.value='80';
        tipEl.value='15';
        splitEl.value='1';
`,
};
