/**
 * §12 #52 how-to-calculate-triangle-area
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"mode_label": "Mode",
		"mode_bh": "Base × height",
		"base_label": "Base",
		"base_ph": "e.g. 10",
		"height_label": "Height",
		"height_ph": "e.g. 6",
		"areaOut_label": "Area",
		"result_note": "Area = base × height / 2 (base-height mode).",
		"err_generic": "Enter base > 0 and height > 0.",
		"how_title": "How it works",
		"how_body": "Choose base-height mode, enter base and perpendicular height, then calculate.",
		"formula_title": "Formula",
		"formula_body": "A = (b×h)/2. Notes:",
		"formula_item_1": "Height must be perpendicular to the chosen base.",
		"formula_item_2": "Other modes are not included in this page.",
		"formula_item_3": "Pair with circle / volume tools.",
		"example_title": "Example",
		"example": "Example: base 10, height 6 → 30.",
		"usecases_title": "When to use it",
		"usecase_1": "Geometry homework.",
		"usecase_2": "Quick area sketch.",
		"usecase_3": "Compare related shape tools.",
		"faq_q1": "Sample?",
		"faq_a1": "10×6/2=30.",
		"faq_q2": "Units?",
		"faq_a2": "Same units as inputs squared.",
		"faq_q3": "Oblique?",
		"faq_a3": "Still use perpendicular height.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Triangle area",
		"disclaimer": "Educational triangle area only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — Triangle",
		"ref_b_label": "Wikipedia — Area",
	}),
	zh: withBtns("zh", {
		"mode_label": "模式",
		"mode_bh": "底×高",
		"base_label": "底边",
		"base_ph": "例如 10",
		"height_label": "高",
		"height_ph": "例如 6",
		"areaOut_label": "面积",
		"result_note": "结果按三角形面积公式在浏览器本地计算。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算三角形面积。",
		"formula_title": "公式",
		"formula_body": "三角形面积相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：底 10、高 6 → 30。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：底 10、高 6 → 30。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "三角形面积",
		"disclaimer": "结果仅为三角形面积学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"mode_label": "Modo",
		"mode_bh": "Base × altura",
		"base_label": "Base",
		"base_ph": "p. ej. 10",
		"height_label": "Altura",
		"height_ph": "p. ej. 6",
		"areaOut_label": "Área",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce base y altura.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce base y altura.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: área 30.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: área 30.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de área de triángulo",
		"disclaimer": "Solo ilustración educativa (triangle area).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"mode_label": "الوضع",
		"mode_bh": "قاعدة × ارتفاع",
		"base_label": "القاعدة",
		"base_ph": "مثال 10",
		"height_label": "الارتفاع",
		"height_ph": "مثال 6",
		"areaOut_label": "المساحة",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل القاعدة والارتفاع.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل القاعدة والارتفاع.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: المساحة 30.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: المساحة 30.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة مساحة المثلث",
		"disclaimer": "توضيح تعليمي فقط (triangle area).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"mode_label": "Modo",
		"mode_bh": "Base × altura",
		"base_label": "Base",
		"base_ph": "ex. 10",
		"height_label": "Altura",
		"height_ph": "ex. 6",
		"areaOut_label": "Área",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe base e altura.",
		"formula_title": "Fórmula",
		"formula_body": "Informe base e altura.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: área 30.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: área 30.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de área do triângulo",
		"disclaimer": "Apenas ilustração educativa (triangle area).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"mode_label": "Mode",
		"mode_bh": "Alas × tinggi",
		"base_label": "Alas",
		"base_ph": "mis. 10",
		"height_label": "Tinggi",
		"height_ph": "mis. 6",
		"areaOut_label": "Luas",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi alas dan tinggi.",
		"formula_title": "Rumus",
		"formula_body": "Isi alas dan tinggi.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: luas 30.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: luas 30.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator luas segitiga",
		"disclaimer": "Hanya ilustrasi edukatif (triangle area).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"mode_label": "Mode",
		"mode_bh": "Base × hauteur",
		"base_label": "Base",
		"base_ph": "ex. 10",
		"height_label": "Hauteur",
		"height_ph": "ex. 6",
		"areaOut_label": "Aire",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez base et hauteur.",
		"formula_title": "Formule",
		"formula_body": "Saisissez base et hauteur.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : aire 30.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : aire 30.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur d’aire de triangle",
		"disclaimer": "Illustration éducative (triangle area) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"mode_label": "モード",
		"mode_bh": "底×高さ",
		"base_label": "底辺",
		"base_ph": "例 10",
		"height_label": "高さ",
		"height_ph": "例 6",
		"areaOut_label": "面積",
		"result_note": "三角形の面積の公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れて三角形の面積を計算します。",
		"formula_title": "計算式",
		"formula_body": "三角形の面積の式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：底10、高さ6 → 30。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：底10、高さ6 → 30。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "三角形の面積",
		"disclaimer": "三角形の面積の学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"mode_label": "Режим",
		"mode_bh": "Основание × высота",
		"base_label": "Основание",
		"base_ph": "напр. 10",
		"height_label": "Высота",
		"height_ph": "напр. 6",
		"areaOut_label": "Площадь",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите основание и высоту.",
		"formula_title": "Формула",
		"formula_body": "Введите основание и высоту.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: площадь 30.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: площадь 30.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор площади треугольника",
		"disclaimer": "Только учебная иллюстрация (triangle area).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"mode_label": "Modus",
		"mode_bh": "Grundseite × Höhe",
		"base_label": "Grundseite",
		"base_ph": "z. B. 10",
		"height_label": "Höhe",
		"height_ph": "z. B. 6",
		"areaOut_label": "Fläche",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Grundseite und Höhe eingeben.",
		"formula_title": "Formel",
		"formula_body": "Grundseite und Höhe eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: Fläche 30.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: Fläche 30.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Dreiecksflächen-Rechner",
		"disclaimer": "Nur zur Veranschaulichung (triangle area).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 52,
	slug: "how-to-calculate-triangle-area",
	prefix: "tool_triangle_area",
	pageFile: "howToCalculateTriangleAreaPage",
	pageExport: "renderHowToCalculateTriangleAreaPage",
	nameZh: "三角形面积计算器",
	ymyl: false,
	related: ["how-to-calculate-circle","how-to-calculate-volume"],
	anchor: "triangle-area",
	glyph: "M16 6 L26 22 L6 22 Z",
	sampleHint: "base 10 height 6 → 30",
	titles: {
		en: "Triangle Area Calculator",
		zh: "三角形面积计算器",
		es: "Calculadora de área de triángulo",
		ar: "حاسبة مساحة المثلث",
		pt: "Calculadora de área do triângulo",
		id: "Kalkulator luas segitiga",
		fr: "Calculateur d’aire de triangle",
		ja: "三角形の面積計算ツール",
		ru: "Калькулятор площади треугольника",
		de: "Dreiecksflächen-Rechner",
	},
	descriptions: {
		en: "Compute triangle area from base and height (area = base×height/2). Sample: base 10, height 6 → 30. Browser-only.",
		zh: "按底×高/2 计算三角形面积。示例：底 10、高 6 → 30。浏览器本地计算，数据不上传。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Calcula el área con base y altura. Ejemplo: 10 y 6 → 30.",
		ar: "احسب المساحة بالقاعدة والارتفاع. مثال: 10 و6 → 30.",
		pt: "Calcule a área com base e altura. Exemplo: 10 e 6 → 30.",
		id: "Hitung luas dengan alas dan tinggi. Contoh: 10 dan 6 → 30.",
		fr: "Calculez l’aire avec base et hauteur. Exemple : 10 et 6 → 30.",
		ja: "底辺×高さ÷2で三角形の面積を計算します。例：底10、高さ6 → 30。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Считайте площадь по основанию и высоте. Пример: 10 и 6 → 30.",
		de: "Fläche aus Grundseite und Höhe. Beispiel: 10 und 6 → 30.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "mode",
	    "type": "select",
	    "half": true,
	    "labelKey": "mode_label",
	    "options": [
	      {
	        "value": "bh",
	        "labelKey": "mode_bh",
	        "selected": true
	      }
	    ]
	  },
	  {
	    "id": "base",
	    "type": "number",
	    "half": true,
	    "labelKey": "base_label",
	    "phKey": "base_ph"
	  },
	  {
	    "id": "height",
	    "type": "number",
	    "half": true,
	    "labelKey": "height_label",
	    "phKey": "height_ph"
	  }
	],
	results: [
	  {
	    "id": "areaOut",
	    "labelKey": "areaOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Triangle"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Area"
	  }
	],
	computeJs: `
        var base=parseFloat(baseEl.value), height=parseFloat(heightEl.value);
        if(!(base>0)||!(height>0)) return {ok:false,error:msgErr};
        return {ok:true, values:{ areaOut:fmt(base*height/2) }};
`,
	sampleJs: `
        modeEl.value='bh';
        baseEl.value='10';
        heightEl.value='6';
`,
};
