/**
 * §12 #42 how-to-calculate-vat
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"mode_label": "Mode",
		"mode_add": "Add tax to net",
		"mode_extract": "Extract tax from gross",
		"amount_label": "Amount",
		"amount_ph": "e.g. 100",
		"rate_label": "VAT/GST %",
		"rate_ph": "e.g. 20",
		"grossOut_label": "Gross",
		"netOut_label": "Net",
		"taxOut_label": "Tax",
		"result_note": "Add: gross=net×(1+r). Extract: net=gross/(1+r). Enter your own rate.",
		"err_generic": "Enter amount > 0 and tax rate ≥ 0.",
		"how_title": "How it works",
		"how_body": "Choose add or extract, enter amount and rate. No per-country rate pages — you supply the percent.",
		"formula_title": "Formula",
		"formula_body": "Gross = net × (1+r); net = gross / (1+r); tax = gross − net. Notes:",
		"formula_item_1": "r is a decimal from the percent you enter.",
		"formula_item_2": "Multi-rate invoices and exemptions are not modeled.",
		"formula_item_3": "Not a filing or compliance tool.",
		"example_title": "Example",
		"example": "Example: net 100, 20% → gross 120, tax 20.",
		"usecases_title": "When to use it",
		"usecase_1": "Homework VAT add/extract.",
		"usecase_2": "Quick check before bookkeeping.",
		"usecase_3": "Pair with discount/tip pages for receipt math.",
		"faq_q1": "Sample?",
		"faq_a1": "Net 100 at 20% → gross 120.",
		"faq_q2": "Country rates?",
		"faq_a2": "Enter your rate; we do not ship a matrix.",
		"faq_q3": "Filing help?",
		"faq_a3": "No — educational arithmetic only.",
		"faq_q4": "GST vs VAT?",
		"faq_a4": "Same add/extract math; labels differ by region.",
		"article": "VAT/GST add-extract",
		"disclaimer": "Educational VAT only — not financial, tax, or investment advice.",
		"references": "Investopedia and standard textbook formulas.",
		"ref_a_label": "Investopedia — VAT",
		"ref_b_label": "Investopedia — Sales tax",
	}),
	zh: withBtns("zh", {
		"mode_label": "模式",
		"mode_add": "净价加税",
		"mode_extract": "含税拆税",
		"amount_label": "金额",
		"amount_ph": "例如 100",
		"rate_label": "税率 %",
		"rate_ph": "例如 20",
		"grossOut_label": "含税价",
		"netOut_label": "净价",
		"taxOut_label": "税额",
		"result_note": "加税：含税=净价×(1+r)；拆税：净价=含税/(1+r)。请自填税率。",
		"err_generic": "金额>0，税率≥0。",
		"how_title": "怎么用",
		"how_body": "选择加税或拆税，填金额与税率。不提供各国税率矩阵。",
		"formula_title": "公式",
		"formula_body": "含税=净价×(1+r)；净价=含税/(1+r)；税额=含税−净价。注意：",
		"formula_item_1": "r 由百分比换算。",
		"formula_item_2": "多档税率与减免不建模。",
		"formula_item_3": "不是申报合规工具。",
		"example_title": "示例",
		"example": "示例：净价 100、20% → 含税 120、税 20。",
		"usecases_title": "适合什么场景",
		"usecase_1": "增值税加减作业。",
		"usecase_2": "记账前速算。",
		"usecase_3": "与折扣/小费页对照小票。",
		"faq_q1": "样例？",
		"faq_a1": "100 加 20% → 120。",
		"faq_q2": "各国税率？",
		"faq_a2": "请自填；无矩阵。",
		"faq_q3": "申报？",
		"faq_a3": "不做。",
		"faq_q4": "GST 与 VAT？",
		"faq_a4": "加减算法相同，名称因地而异。",
		"article": "增值税互算",
		"disclaimer": "结果仅为增值税学习演示，不构成投资、理财或税务建议。",
		"references": "Investopedia 与常见教材公式。",
		"ref_a_label": "Investopedia — VAT",
		"ref_b_label": "Investopedia — Sales tax",
	}),
	es: withBtns("es", {
		"mode_label": "Modo",
		"mode_add": "Añadir al neto",
		"mode_extract": "Extraer del bruto",
		"amount_label": "Importe",
		"amount_ph": "p. ej. 100",
		"rate_label": "IVA/GST %",
		"rate_ph": "p. ej. 20",
		"grossOut_label": "Bruto",
		"netOut_label": "Neto",
		"taxOut_label": "Impuesto",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Elige modo, importe y tasa.",
		"formula_title": "Fórmula",
		"formula_body": "Elige modo, importe y tasa.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: neto 100 al 20% → 120.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: neto 100 al 20% → 120.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de IVA / GST",
		"disclaimer": "Solo ilustración educativa (VAT); no es consejo financiero.",
		"references": "Investopedia y fórmulas de libro.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ar: withBtns("ar", {
		"mode_label": "الوضع",
		"mode_add": "إضافة إلى الصافي",
		"mode_extract": "استخراج من الإجمالي",
		"amount_label": "المبلغ",
		"amount_ph": "مثال 100",
		"rate_label": "VAT/GST %",
		"rate_ph": "مثال 20",
		"grossOut_label": "الإجمالي",
		"netOut_label": "الصافي",
		"taxOut_label": "الضريبة",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "اختر الوضع والمبلغ والمعدل.",
		"formula_title": "الصيغة",
		"formula_body": "اختر الوضع والمبلغ والمعدل.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: صافٍ 100 بنسبة 20٪ → 120.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: صافٍ 100 بنسبة 20٪ → 120.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة ضريبة القيمة المضافة VAT/GST",
		"disclaimer": "توضيح تعليمي فقط (VAT) وليس نصيحة مالية.",
		"references": "Investopedia وصيغ دراسية.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	pt: withBtns("pt", {
		"mode_label": "Modo",
		"mode_add": "Somar ao líquido",
		"mode_extract": "Extrair do bruto",
		"amount_label": "Valor",
		"amount_ph": "ex. 100",
		"rate_label": "IVA/GST %",
		"rate_ph": "ex. 20",
		"grossOut_label": "Bruto",
		"netOut_label": "Líquido",
		"taxOut_label": "Imposto",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Escolha modo, valor e alíquota.",
		"formula_title": "Fórmula",
		"formula_body": "Escolha modo, valor e alíquota.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: líquido 100 a 20% → 120.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: líquido 100 a 20% → 120.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de IVA / GST",
		"disclaimer": "Apenas ilustração educativa (VAT); não é conselho financeiro.",
		"references": "Investopedia e fórmulas didáticas.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	id: withBtns("id", {
		"mode_label": "Mode",
		"mode_add": "Tambah ke net",
		"mode_extract": "Ekstrak dari gross",
		"amount_label": "Jumlah",
		"amount_ph": "mis. 100",
		"rate_label": "PPN/VAT %",
		"rate_ph": "mis. 20",
		"grossOut_label": "Gross",
		"netOut_label": "Net",
		"taxOut_label": "Pajak",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Pilih mode, jumlah, dan tarif.",
		"formula_title": "Rumus",
		"formula_body": "Pilih mode, jumlah, dan tarif.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: net 100 pada 20% → 120.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: net 100 pada 20% → 120.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator PPN / VAT / GST",
		"disclaimer": "Hanya ilustrasi edukatif (VAT); bukan saran keuangan.",
		"references": "Investopedia dan rumus buku teks.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	fr: withBtns("fr", {
		"mode_label": "Mode",
		"mode_add": "Ajouter au HT",
		"mode_extract": "Extraire du TTC",
		"amount_label": "Montant",
		"amount_ph": "ex. 100",
		"rate_label": "TVA %",
		"rate_ph": "ex. 20",
		"grossOut_label": "TTC",
		"netOut_label": "HT",
		"taxOut_label": "Taxe",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Choisissez mode, montant et taux.",
		"formula_title": "Formule",
		"formula_body": "Choisissez mode, montant et taux.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : HT 100 à 20 % → TTC 120.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : HT 100 à 20 % → TTC 120.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de TVA / GST",
		"disclaimer": "Illustration éducative (VAT) uniquement — pas un conseil financier.",
		"references": "Investopedia et formules de manuel.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	ja: withBtns("ja", {
		"mode_label": "モード",
		"mode_add": "税抜に加算",
		"mode_extract": "税込から抽出",
		"amount_label": "金額",
		"amount_ph": "例 100",
		"rate_label": "税率 %",
		"rate_ph": "例 20",
		"grossOut_label": "税込",
		"netOut_label": "税抜",
		"taxOut_label": "税額",
		"result_note": "加算: 税込=税抜×(1+r)。抽出: 税抜=税込/(1+r)。税率は自分で入力。",
		"err_generic": "金額>0、税率≥0。",
		"how_title": "使い方",
		"how_body": "加算/抽出を選び金額と税率を入力。国別税率表はありません。",
		"formula_title": "計算式",
		"formula_body": "税込=税抜×(1+r)；税抜=税込/(1+r)。注意:",
		"formula_item_1": "rは百分率から換算。",
		"formula_item_2": "複数税率や免除は扱いません。",
		"formula_item_3": "申告ツールではありません。",
		"example_title": "例",
		"example": "例：税抜100、20% → 税込120、税20。",
		"usecases_title": "こんなときに",
		"usecase_1": "VAT加減の宿題。",
		"usecase_2": "記帳前の速算。",
		"usecase_3": "割引/チップ計算と併用。",
		"faq_q1": "例は？",
		"faq_a1": "100に20%で120。",
		"faq_q2": "国別税率は？",
		"faq_a2": "自分で入力。",
		"faq_q3": "申告支援？",
		"faq_a3": "いいえ。",
		"faq_q4": "GSTとVATは？",
		"faq_a4": "計算は同じで名称が地域で違う。",
		"article": "VAT/GST互算",
		"disclaimer": "付加価値税の学習用試算であり、投資・税務の助言ではありません。",
		"references": "Investopedia と標準的な教科書公式。",
		"ref_a_label": "Investopedia — VAT",
		"ref_b_label": "Investopedia — Sales tax",
	}),
	ru: withBtns("ru", {
		"mode_label": "Режим",
		"mode_add": "Добавить к нетто",
		"mode_extract": "Извлечь из брутто",
		"amount_label": "Сумма",
		"amount_ph": "напр. 100",
		"rate_label": "НДС %",
		"rate_ph": "напр. 20",
		"grossOut_label": "Брутто",
		"netOut_label": "Нетто",
		"taxOut_label": "Налог",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Выберите режим, сумму и ставку.",
		"formula_title": "Формула",
		"formula_body": "Выберите режим, сумму и ставку.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: нетто 100 при 20% → 120.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: нетто 100 при 20% → 120.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор НДС / VAT / GST",
		"disclaimer": "Только учебная иллюстрация (VAT) — не финансовый совет.",
		"references": "Investopedia и учебные формулы.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
	de: withBtns("de", {
		"mode_label": "Modus",
		"mode_add": "Auf Netto aufschlagen",
		"mode_extract": "Aus Brutto herausrechnen",
		"amount_label": "Betrag",
		"amount_ph": "z. B. 100",
		"rate_label": "MwSt %",
		"rate_ph": "z. B. 20",
		"grossOut_label": "Brutto",
		"netOut_label": "Netto",
		"taxOut_label": "Steuer",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Modus, Betrag und Satz wählen.",
		"formula_title": "Formel",
		"formula_body": "Modus, Betrag und Satz wählen.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: Netto 100 bei 20% → 120.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: Netto 100 bei 20% → 120.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "MwSt-/VAT-Rechner",
		"disclaimer": "Nur zur Veranschaulichung (VAT) — keine Finanzberatung.",
		"references": "Investopedia und Lehrbuchformeln.",
		"ref_a_label": "Investopedia",
		"ref_b_label": "Wikipedia",
	}),
};
export default {
	seq: 42,
	slug: "how-to-calculate-vat",
	prefix: "tool_vat",
	pageFile: "howToCalculateVatPage",
	pageExport: "renderHowToCalculateVatPage",
	nameZh: "增值税/GST 计算器",
	ymyl: false,
	related: ["how-to-calculate-discount","how-to-calculate-tip"],
	anchor: "vat",
	glyph: "M8 6h16v6H8zm0 10h10v6H8z",
	sampleHint: "net 100 VAT 20% → gross 120",
	titles: {
		en: "VAT / GST Calculator — Add or Extract Tax",
		zh: "增值税计算器 — 含税与未税互算",
		es: "Calculadora de IVA / GST",
		ar: "حاسبة ضريبة القيمة المضافة VAT/GST",
		pt: "Calculadora de IVA / GST",
		id: "Kalkulator PPN / VAT / GST",
		fr: "Calculateur de TVA / GST",
		ja: "VAT/GST（付加価値税）計算ツール",
		ru: "Калькулятор НДС / VAT / GST",
		de: "MwSt-/VAT-Rechner",
	},
	descriptions: {
		en: "Add VAT/GST to a net amount or extract tax from a gross amount. Sample: net 100 at 20% → gross 120. Enter your own rate — no country tax matrix. Browser-only.",
		zh: "按自填税率给净价加增值税/GST，或从含税价反推税额。示例：净价 100、税率 20% → 含税价 120。不按国家拆页；浏览器本地计算，数据不上传服务器。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，不构成投资、理财或经营建议。",
		es: "Añade IVA/GST a un neto o extrae el impuesto de un bruto. Ejemplo: neto 100 al 20% → bruto 120. Tú eliges la tasa. En el navegador.",
		ar: "أضف VAT/GST إلى صافٍ أو استخرج الضريبة من الإجمالي. مثال: صافٍ 100 بنسبة 20٪ → إجمالي 120. أدخل معدلك. في المتصفح.",
		pt: "Some IVA/GST a um líquido ou extraia o imposto de um bruto. Exemplo: líquido 100 a 20% → bruto 120. Você informa a alíquota. No navegador.",
		id: "Tambahkan PPN/VAT ke net atau ekstrak pajak dari gross. Contoh: net 100 pada 20% → gross 120. Anda isi tarif. Di browser.",
		fr: "Ajoutez la TVA à un HT ou extrayez la taxe d’un TTC. Exemple : HT 100 à 20 % → TTC 120. Vous saisissez le taux. Dans le navigateur.",
		ja: "税抜に VAT/GST を加算、または税込から税額を逆算します。例：税抜 100、税率 20% → 税込 120。国別税率表はなく自分で入力。ブラウザ内計算です。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり投資・税務・経営の助言ではありません。",
		ru: "Добавьте НДС к нетто или извлеките налог из брутто. Пример: нетто 100 при 20% → брутто 120. Ставку вводите сами. В браузере.",
		de: "MwSt/VAT auf Netto aufschlagen oder aus Brutto herausrechnen. Beispiel: Netto 100 bei 20% → Brutto 120. Satz selbst eingeben. Im Browser.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "mode",
	    "type": "select",
	    "half": true,
	    "labelKey": "mode_label",
	    "options": [
	      {
	        "value": "add",
	        "labelKey": "mode_add",
	        "selected": true
	      },
	      {
	        "value": "extract",
	        "labelKey": "mode_extract"
	      }
	    ]
	  },
	  {
	    "id": "amount",
	    "type": "number",
	    "half": true,
	    "labelKey": "amount_label",
	    "phKey": "amount_ph"
	  },
	  {
	    "id": "rate",
	    "type": "number",
	    "half": true,
	    "labelKey": "rate_label",
	    "phKey": "rate_ph"
	  }
	],
	results: [
	  {
	    "id": "grossOut",
	    "labelKey": "grossOut_label"
	  },
	  {
	    "id": "netOut",
	    "labelKey": "netOut_label"
	  },
	  {
	    "id": "taxOut",
	    "labelKey": "taxOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://www.investopedia.com/terms/v/valueaddedtax.asp"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://www.investopedia.com/terms/s/salestax.asp"
	  }
	],
	computeJs: `
        var mode=modeEl.value, amount=parseFloat(amountEl.value), ratePct=parseFloat(rateEl.value);
        if(!(amount>0)||!Number.isFinite(ratePct)||ratePct<0) return {ok:false,error:msgErr};
        var r=ratePct/100, net, gross, tax;
        if(mode==='extract'){ gross=amount; net=gross/(1+r); tax=gross-net; }
        else { net=amount; gross=net*(1+r); tax=gross-net; }
        return {ok:true, values:{ grossOut:fmt(gross), netOut:fmt(net), taxOut:fmt(tax) }};
`,
	sampleJs: `
        modeEl.value='add';
        amountEl.value='100';
        rateEl.value='20';
`,
};
