/**
 * §12 #61 how-to-calculate-velocity
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"dist_label": "Distance",
		"dist_ph": "e.g. 100",
		"time_label": "Time",
		"time_ph": "e.g. 20",
		"velOut_label": "Velocity",
		"result_note": "v = distance / time (average speed along the path in 1D teaching form).",
		"err_generic": "Enter distance ≥ 0 and time > 0.",
		"how_title": "How it works",
		"how_body": "Enter distance and time in consistent units (e.g., m and s → m/s).",
		"formula_title": "Formula",
		"formula_body": "v=d/t. Notes:",
		"formula_item_1": "This is a scalar average-speed form for homework.",
		"formula_item_2": "Direction/vector velocity is not modeled.",
		"formula_item_3": "Pair with acceleration / density tools.",
		"example_title": "Example",
		"example": "Example: d=100, t=20 → v=5.",
		"usecases_title": "When to use it",
		"usecase_1": "Physics homework.",
		"usecase_2": "Quick v check.",
		"usecase_3": "Compare with acceleration.",
		"faq_q1": "Sample?",
		"faq_a1": "100/20=5.",
		"faq_q2": "Vectors?",
		"faq_a2": "Not here.",
		"faq_q3": "t=0?",
		"faq_a3": "Rejected.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Velocity",
		"disclaimer": "Educational velocity only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — Velocity",
		"ref_b_label": "Wikipedia — Speed",
	}),
	zh: withBtns("zh", {
		"dist_label": "距离",
		"dist_ph": "例如 100",
		"time_label": "时间",
		"time_ph": "例如 20",
		"velOut_label": "速度",
		"result_note": "结果按速度公式在浏览器本地计算。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算速度。",
		"formula_title": "公式",
		"formula_body": "速度相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：d=100、t=20 → v=5。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：d=100、t=20 → v=5。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "速度",
		"disclaimer": "结果仅为速度学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"dist_label": "Distancia",
		"dist_ph": "p. ej. 100",
		"time_label": "Tiempo",
		"time_ph": "p. ej. 20",
		"velOut_label": "Velocidad",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce distancia y tiempo.",
		"formula_title": "Fórmula",
		"formula_body": "Introduce distancia y tiempo.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: v=5.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: v=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de velocidad",
		"disclaimer": "Solo ilustración educativa (velocity).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"dist_label": "المسافة",
		"dist_ph": "مثال 100",
		"time_label": "الوقت",
		"time_ph": "مثال 20",
		"velOut_label": "السرعة",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل المسافة والوقت.",
		"formula_title": "الصيغة",
		"formula_body": "أدخل المسافة والوقت.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: v=5.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: v=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة السرعة",
		"disclaimer": "توضيح تعليمي فقط (velocity).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"dist_label": "Distância",
		"dist_ph": "ex. 100",
		"time_label": "Tempo",
		"time_ph": "ex. 20",
		"velOut_label": "Velocidade",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Informe distância e tempo.",
		"formula_title": "Fórmula",
		"formula_body": "Informe distância e tempo.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: v=5.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: v=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de velocidade",
		"disclaimer": "Apenas ilustração educativa (velocity).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"dist_label": "Jarak",
		"dist_ph": "mis. 100",
		"time_label": "Waktu",
		"time_ph": "mis. 20",
		"velOut_label": "Kecepatan",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Isi jarak dan waktu.",
		"formula_title": "Rumus",
		"formula_body": "Isi jarak dan waktu.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: v=5.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: v=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator kecepatan",
		"disclaimer": "Hanya ilustrasi edukatif (velocity).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"dist_label": "Distance",
		"dist_ph": "ex. 100",
		"time_label": "Temps",
		"time_ph": "ex. 20",
		"velOut_label": "Vitesse",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Saisissez distance et temps.",
		"formula_title": "Formule",
		"formula_body": "Saisissez distance et temps.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : v=5.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : v=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de vitesse",
		"disclaimer": "Illustration éducative (velocity) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"dist_label": "距離",
		"dist_ph": "例 100",
		"time_label": "時間",
		"time_ph": "例 20",
		"velOut_label": "速度",
		"result_note": "速度の公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れて速度を計算します。",
		"formula_title": "計算式",
		"formula_body": "速度の式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：d=100、t=20 → v=5。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：d=100、t=20 → v=5。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "速度",
		"disclaimer": "速度の学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"dist_label": "Расстояние",
		"dist_ph": "напр. 100",
		"time_label": "Время",
		"time_ph": "напр. 20",
		"velOut_label": "Скорость",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Введите путь и время.",
		"formula_title": "Формула",
		"formula_body": "Введите путь и время.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: v=5.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: v=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор скорости",
		"disclaimer": "Только учебная иллюстрация (velocity).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"dist_label": "Weg",
		"dist_ph": "z. B. 100",
		"time_label": "Zeit",
		"time_ph": "z. B. 20",
		"velOut_label": "Geschwindigkeit",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Weg und Zeit eingeben.",
		"formula_title": "Formel",
		"formula_body": "Weg und Zeit eingeben.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: v=5.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: v=5.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Geschwindigkeitsrechner — Weg durch Zeit",
		"disclaimer": "Nur zur Veranschaulichung (velocity).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 61,
	slug: "how-to-calculate-velocity",
	prefix: "tool_velocity",
	pageFile: "howToCalculateVelocityPage",
	pageExport: "renderHowToCalculateVelocityPage",
	nameZh: "速度计算器",
	ymyl: false,
	related: ["how-to-calculate-acceleration","how-to-calculate-density"],
	anchor: "velocity",
	glyph: "M6 16h14l4-4",
	sampleHint: "d=100 t=20 → v=5",
	titles: {
		en: "Velocity Calculator — Distance over Time",
		zh: "速度计算器 — 距离÷时间",
		es: "Calculadora de velocidad",
		ar: "حاسبة السرعة",
		pt: "Calculadora de velocidade",
		id: "Kalkulator kecepatan",
		fr: "Calculateur de vitesse",
		ja: "速度計算ツール — 距離÷時間",
		ru: "Калькулятор скорости",
		de: "Geschwindigkeitsrechner — Weg durch Zeit",
	},
	descriptions: {
		en: "Compute average velocity v = d/t. Sample: distance 100, time 20 → velocity 5. Browser-only.",
		zh: "计算平均速度 v = d/t。示例：距离 100、时间 20 → 速度 5。浏览器本地计算。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Calcula velocidad media v=d/t. Ejemplo: 100 / 20 → 5.",
		ar: "احسب السرعة المتوسطة v=d/t. مثال: 100 / 20 → 5.",
		pt: "Calcule velocidade média v=d/t. Exemplo: 100 / 20 → 5.",
		id: "Hitung kecepatan rata-rata v=d/t. Contoh: 100 / 20 → 5.",
		fr: "Calculez la vitesse moyenne v=d/t. Exemple : 100 / 20 → 5.",
		ja: "平均速度 v=d/t を計算します。例：距離100、時間20 → 速度5。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Считайте среднюю скорость v=d/t. Пример: 100 / 20 → 5.",
		de: "Mittlere Geschwindigkeit v=d/t. Beispiel: 100 / 20 → 5.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "dist",
	    "type": "number",
	    "half": true,
	    "labelKey": "dist_label",
	    "phKey": "dist_ph"
	  },
	  {
	    "id": "time",
	    "type": "number",
	    "half": true,
	    "labelKey": "time_label",
	    "phKey": "time_ph"
	  }
	],
	results: [
	  {
	    "id": "velOut",
	    "labelKey": "velOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Velocity"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Speed"
	  }
	],
	computeJs: `
        var dist=parseFloat(distEl.value), time=parseFloat(timeEl.value);
        if(!(dist>=0)||!(time>0)) return {ok:false,error:msgErr};
        return {ok:true, values:{ velOut:fmt(dist/time) }};
`,
	sampleJs: `
        distEl.value='100';
        timeEl.value='20';
`,
};
