/**
 * §12 #54 how-to-calculate-volume
 */
import { withBtns } from '../locale-ui-common.mjs';
const _ui = {
	en: withBtns("en", {
		"shape_label": "Shape",
		"shape_box": "Box",
		"shape_sphere": "Sphere",
		"l_label": "Length",
		"l_ph": "e.g. 2",
		"w_label": "Width",
		"w_ph": "e.g. 3",
		"h_label": "Height",
		"h_ph": "e.g. 4",
		"radius_label": "Radius",
		"radius_ph": "e.g. 1",
		"volOut_label": "Volume",
		"result_note": "Box: L×W×H. Sphere: (4/3)πr³.",
		"err_generic": "Enter positive dimensions for the selected shape.",
		"how_title": "How it works",
		"how_body": "Choose box or sphere. For a box enter L,W,H; for a sphere enter radius.",
		"formula_title": "Formula",
		"formula_body": "V_box=LWH; V_sphere=4/3 πr³. Notes:",
		"formula_item_1": "Unused fields for the other shape are ignored.",
		"formula_item_2": "Uses Math.PI for spheres.",
		"formula_item_3": "Pair with triangle / circle tools.",
		"example_title": "Example",
		"example": "Example: box L=2, W=3, H=4 → 24.",
		"usecases_title": "When to use it",
		"usecase_1": "Geometry homework.",
		"usecase_2": "Packaging sketch.",
		"usecase_3": "Compare related shape tools.",
		"faq_q1": "Sample?",
		"faq_a1": "2×3×4=24.",
		"faq_q2": "Sphere sample?",
		"faq_a2": "Enter radius and choose sphere.",
		"faq_q3": "Units?",
		"faq_a3": "Cubed units of inputs.",
		"faq_q4": "Advice?",
		"faq_a4": "Educational only.",
		"article": "Volume",
		"disclaimer": "Educational volume only — not professional advice.",
		"references": "Standard textbook formulas.",
		"ref_a_label": "Wikipedia — Volume",
		"ref_b_label": "Wikipedia — Sphere",
	}),
	zh: withBtns("zh", {
		"shape_label": "形状",
		"shape_box": "长方体",
		"shape_sphere": "球",
		"l_label": "长",
		"l_ph": "例如 2",
		"w_label": "宽",
		"w_ph": "例如 3",
		"h_label": "高",
		"h_ph": "例如 4",
		"radius_label": "半径",
		"radius_ph": "例如 1",
		"volOut_label": "体积",
		"result_note": "结果按体积公式在浏览器本地计算。",
		"err_generic": "请检查输入是否有效。",
		"how_title": "怎么用",
		"how_body": "填写所需字段后计算体积。",
		"formula_title": "公式",
		"formula_body": "体积相关公式见 Formula 节。注意：",
		"formula_item_1": "核对单位与符号。",
		"formula_item_2": "边界输入可能无定义。",
		"formula_item_3": "仅供学习对照。",
		"example_title": "示例",
		"example": "示例：长方体 2×3×4 → 24。",
		"usecases_title": "适合什么场景",
		"usecase_1": "课堂作业。",
		"usecase_2": "快速验算。",
		"usecase_3": "与相关工具对照。",
		"faq_q1": "样例？",
		"faq_a1": "示例：长方体 2×3×4 → 24。",
		"faq_q2": "公式？",
		"faq_a2": "见公式节。",
		"faq_q3": "专业建议？",
		"faq_a3": "不是。",
		"faq_q4": "相关？",
		"faq_a4": "见相关工具。",
		"article": "体积",
		"disclaimer": "结果仅为体积学习演示，不构成专业建议。",
		"references": "常见教材公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	es: withBtns("es", {
		"shape_label": "Forma",
		"shape_box": "Caja",
		"shape_sphere": "Esfera",
		"l_label": "Largo",
		"l_ph": "p. ej. 2",
		"w_label": "Ancho",
		"w_ph": "p. ej. 3",
		"h_label": "Alto",
		"h_ph": "p. ej. 4",
		"radius_label": "Radio",
		"radius_ph": "p. ej. 1",
		"volOut_label": "Volumen",
		"result_note": "Educativo.",
		"err_generic": "Revisa los datos.",
		"how_title": "Cómo funciona",
		"how_body": "Elige forma e introduce dimensiones.",
		"formula_title": "Fórmula",
		"formula_body": "Elige forma e introduce dimensiones.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: caja 24.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "¿Ejemplo?",
		"faq_a1": "Ejemplo: caja 24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de volumen",
		"disclaimer": "Solo ilustración educativa (volume).",
		"references": "Fórmulas de libro.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ar: withBtns("ar", {
		"shape_label": "الشكل",
		"shape_box": "صندوق",
		"shape_sphere": "كرة",
		"l_label": "الطول",
		"l_ph": "مثال 2",
		"w_label": "العرض",
		"w_ph": "مثال 3",
		"h_label": "الارتفاع",
		"h_ph": "مثال 4",
		"radius_label": "نصف القطر",
		"radius_ph": "مثال 1",
		"volOut_label": "الحجم",
		"result_note": "تعليمي.",
		"err_generic": "تحقق من المدخلات.",
		"how_title": "طريقة الاستخدام",
		"how_body": "اختر الشكل وأدخل الأبعاد.",
		"formula_title": "الصيغة",
		"formula_body": "اختر الشكل وأدخل الأبعاد.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "مثال",
		"example": "مثال: صندوق 24.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "المثال؟",
		"faq_a1": "مثال: صندوق 24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "حاسبة الحجم",
		"disclaimer": "توضيح تعليمي فقط (volume).",
		"references": "صيغ دراسية.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	pt: withBtns("pt", {
		"shape_label": "Forma",
		"shape_box": "Caixa",
		"shape_sphere": "Esfera",
		"l_label": "Comprimento",
		"l_ph": "ex. 2",
		"w_label": "Largura",
		"w_ph": "ex. 3",
		"h_label": "Altura",
		"h_ph": "ex. 4",
		"radius_label": "Raio",
		"radius_ph": "ex. 1",
		"volOut_label": "Volume",
		"result_note": "Educativo.",
		"err_generic": "Verifique os dados.",
		"how_title": "Como funciona",
		"how_body": "Escolha a forma e as dimensões.",
		"formula_title": "Fórmula",
		"formula_body": "Escolha a forma e as dimensões.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemplo",
		"example": "Exemplo: caixa 24.",
		"usecases_title": "Quando usar",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemplo?",
		"faq_a1": "Exemplo: caixa 24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculadora de volume",
		"disclaimer": "Apenas ilustração educativa (volume).",
		"references": "Fórmulas didáticas.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	id: withBtns("id", {
		"shape_label": "Bentuk",
		"shape_box": "Kotak",
		"shape_sphere": "Bola",
		"l_label": "Panjang",
		"l_ph": "mis. 2",
		"w_label": "Lebar",
		"w_ph": "mis. 3",
		"h_label": "Tinggi",
		"h_ph": "mis. 4",
		"radius_label": "Jari-jari",
		"radius_ph": "mis. 1",
		"volOut_label": "Volume",
		"result_note": "Edukatif.",
		"err_generic": "Periksa input.",
		"how_title": "Cara kerja",
		"how_body": "Pilih bentuk dan isi ukuran.",
		"formula_title": "Rumus",
		"formula_body": "Pilih bentuk dan isi ukuran.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Contoh",
		"example": "Contoh: kotak 24.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Contoh?",
		"faq_a1": "Contoh: kotak 24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Kalkulator volume",
		"disclaimer": "Hanya ilustrasi edukatif (volume).",
		"references": "Rumus buku teks.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	fr: withBtns("fr", {
		"shape_label": "Forme",
		"shape_box": "Boîte",
		"shape_sphere": "Sphère",
		"l_label": "Longueur",
		"l_ph": "ex. 2",
		"w_label": "Largeur",
		"w_ph": "ex. 3",
		"h_label": "Hauteur",
		"h_ph": "ex. 4",
		"radius_label": "Rayon",
		"radius_ph": "ex. 1",
		"volOut_label": "Volume",
		"result_note": "Éducatif.",
		"err_generic": "Vérifiez les entrées.",
		"how_title": "Fonctionnement",
		"how_body": "Choisissez la forme et les dimensions.",
		"formula_title": "Formule",
		"formula_body": "Choisissez la forme et les dimensions.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Exemple",
		"example": "Exemple : boîte 24.",
		"usecases_title": "Cas d’usage",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Exemple ?",
		"faq_a1": "Exemple : boîte 24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Calculateur de volume",
		"disclaimer": "Illustration éducative (volume) uniquement.",
		"references": "Formules de manuel.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ja: withBtns("ja", {
		"shape_label": "形状",
		"shape_box": "直方体",
		"shape_sphere": "球",
		"l_label": "長さ",
		"l_ph": "例 2",
		"w_label": "幅",
		"w_ph": "例 3",
		"h_label": "高さ",
		"h_ph": "例 4",
		"radius_label": "半径",
		"radius_ph": "例 1",
		"volOut_label": "体積",
		"result_note": "体積の公式でブラウザ内計算します。",
		"err_generic": "入力を確認してください。",
		"how_title": "使い方",
		"how_body": "必要な項目を入れて体積を計算します。",
		"formula_title": "計算式",
		"formula_body": "体積の式は Formula を参照。注意:",
		"formula_item_1": "単位と符号を確認。",
		"formula_item_2": "境界値は未定義の場合あり。",
		"formula_item_3": "学習用です。",
		"example_title": "例",
		"example": "例：直方体 2×3×4 → 24。",
		"usecases_title": "こんなときに",
		"usecase_1": "宿題。",
		"usecase_2": "速算チェック。",
		"usecase_3": "関連ツールと比較。",
		"faq_q1": "例は？",
		"faq_a1": "例：直方体 2×3×4 → 24。",
		"faq_q2": "式は？",
		"faq_a2": "公式セクションへ。",
		"faq_q3": "助言？",
		"faq_a3": "学習用。",
		"faq_q4": "関連？",
		"faq_a4": "関連ツールへ。",
		"article": "体積",
		"disclaimer": "体積の学習用試算であり、専門的助言ではありません。",
		"references": "標準的な教科書公式。",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	ru: withBtns("ru", {
		"shape_label": "Форма",
		"shape_box": "Ящик",
		"shape_sphere": "Сфера",
		"l_label": "Длина",
		"l_ph": "напр. 2",
		"w_label": "Ширина",
		"w_ph": "напр. 3",
		"h_label": "Высота",
		"h_ph": "напр. 4",
		"radius_label": "Радиус",
		"radius_ph": "напр. 1",
		"volOut_label": "Объём",
		"result_note": "Учебно.",
		"err_generic": "Проверьте ввод.",
		"how_title": "Как пользоваться",
		"how_body": "Выберите форму и размеры.",
		"formula_title": "Формула",
		"formula_body": "Выберите форму и размеры.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Пример",
		"example": "Пример: ящик 24.",
		"usecases_title": "Когда использовать",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Пример?",
		"faq_a1": "Пример: ящик 24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Калькулятор объёма",
		"disclaimer": "Только учебная иллюстрация (volume).",
		"references": "Учебные формулы.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
	de: withBtns("de", {
		"shape_label": "Form",
		"shape_box": "Quader",
		"shape_sphere": "Kugel",
		"l_label": "Länge",
		"l_ph": "z. B. 2",
		"w_label": "Breite",
		"w_ph": "z. B. 3",
		"h_label": "Höhe",
		"h_ph": "z. B. 4",
		"radius_label": "Radius",
		"radius_ph": "z. B. 1",
		"volOut_label": "Volumen",
		"result_note": "Bildungszweck.",
		"err_generic": "Eingaben prüfen.",
		"how_title": "So funktioniert’s",
		"how_body": "Form und Maße wählen.",
		"formula_title": "Formel",
		"formula_body": "Form und Maße wählen.",
		"formula_item_1": "See formula notes.",
		"formula_item_2": "Check inputs.",
		"formula_item_3": "Educational only.",
		"example_title": "Beispiel",
		"example": "Beispiel: Quader 24.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Homework.",
		"usecase_2": "Quick sketch.",
		"usecase_3": "Compare related tools.",
		"faq_q1": "Beispiel?",
		"faq_a1": "Beispiel: Quader 24.",
		"faq_q2": "Formula?",
		"faq_a2": "See Formula section.",
		"faq_q3": "Advice?",
		"faq_a3": "Educational only.",
		"faq_q4": "Related?",
		"faq_a4": "See related tools.",
		"article": "Volumenrechner — Quader und Kugel",
		"disclaimer": "Nur zur Veranschaulichung (volume).",
		"references": "Lehrbuchformeln.",
		"ref_a_label": "Wikipedia",
		"ref_b_label": "Textbook formula",
	}),
};
export default {
	seq: 54,
	slug: "how-to-calculate-volume",
	prefix: "tool_volume",
	pageFile: "howToCalculateVolumePage",
	pageExport: "renderHowToCalculateVolumePage",
	nameZh: "体积计算器",
	ymyl: false,
	related: ["how-to-calculate-triangle-area","how-to-calculate-circle"],
	anchor: "volume",
	glyph: "M8 10h16v12H8z",
	sampleHint: "box 2×3×4 → 24",
	titles: {
		en: "Volume Calculator — Box and Sphere",
		zh: "体积计算器 — 长方体与球",
		es: "Calculadora de volumen",
		ar: "حاسبة الحجم",
		pt: "Calculadora de volume",
		id: "Kalkulator volume",
		fr: "Calculateur de volume",
		ja: "体積計算ツール — 直方体と球",
		ru: "Калькулятор объёма",
		de: "Volumenrechner — Quader und Kugel",
	},
	descriptions: {
		en: "Compute volume for a box (L×W×H) or sphere (4/3 πr³). Sample: box 2×3×4 → 24. Browser-only.",
		zh: "计算长方体（长×宽×高）或球（4/3 πr³）体积。示例：长方体 2×3×4 → 24。浏览器本地计算。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。；全程浏览器本地计算，数据不上传服务器；结果仅供学习对照，请核对公式假设。",
		es: "Calcula volumen de caja o esfera. Ejemplo: caja 2×3×4 → 24.",
		ar: "احسب حجم الصندوق أو الكرة. مثال: صندوق 2×3×4 → 24.",
		pt: "Calcule volume de caixa ou esfera. Exemplo: caixa 2×3×4 → 24.",
		id: "Hitung volume kotak atau bola. Contoh: kotak 2×3×4 → 24.",
		fr: "Calculez le volume d’une boîte ou d’une sphère. Exemple : boîte 2×3×4 → 24.",
		ja: "直方体（L×W×H）または球（4/3 πr³）の体積を計算します。例：直方体 2×3×4 → 24。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。。計算はブラウザ内で行いサーバーにアップロードしません。学習用の目安であり公式の前提を確認してください。",
		ru: "Считайте объём ящика или сферы. Пример: ящик 2×3×4 → 24.",
		de: "Volumen von Quader oder Kugel. Beispiel: Quader 2×3×4 → 24.",
	},
	ui: _ui,
	fields: [
	  {
	    "id": "shape",
	    "type": "select",
	    "half": true,
	    "labelKey": "shape_label",
	    "options": [
	      {
	        "value": "box",
	        "labelKey": "shape_box",
	        "selected": true
	      },
	      {
	        "value": "sphere",
	        "labelKey": "shape_sphere"
	      }
	    ]
	  },
	  {
	    "id": "l",
	    "type": "number",
	    "half": true,
	    "labelKey": "l_label",
	    "phKey": "l_ph"
	  },
	  {
	    "id": "w",
	    "type": "number",
	    "half": true,
	    "labelKey": "w_label",
	    "phKey": "w_ph"
	  },
	  {
	    "id": "h",
	    "type": "number",
	    "half": true,
	    "labelKey": "h_label",
	    "phKey": "h_ph"
	  },
	  {
	    "id": "radius",
	    "type": "number",
	    "half": true,
	    "labelKey": "radius_label",
	    "phKey": "radius_ph"
	  }
	],
	results: [
	  {
	    "id": "volOut",
	    "labelKey": "volOut_label"
	  }
	],
	refs: [
	  {
	    "labelKey": "ref_a_label",
	    "href": "https://en.wikipedia.org/wiki/Volume"
	  },
	  {
	    "labelKey": "ref_b_label",
	    "href": "https://en.wikipedia.org/wiki/Sphere"
	  }
	],
	computeJs: `
        var shape=shapeEl.value;
        if(shape==='sphere'){
          var radius=parseFloat(radiusEl.value);
          if(!(radius>0)) return {ok:false,error:msgErr};
          return {ok:true, values:{ volOut:fmt((4/3)*Math.PI*radius*radius*radius) }};
        }
        var L=parseFloat(lEl.value), W=parseFloat(wEl.value), H=parseFloat(hEl.value);
        if(!(L>0)||!(W>0)||!(H>0)) return {ok:false,error:msgErr};
        return {ok:true, values:{ volOut:fmt(L*W*H) }};
`,
	sampleJs: `
        shapeEl.value='box';
        lEl.value='2';
        wEl.value='3';
        hEl.value='4';
`,
};
