/**
 * §12 #25 how-to-calculate-z-score 工具定义（十语独立 UI）。
 */
import { withBtns } from '../locale-ui-common.mjs';

const _ui = {
	en: withBtns('en', {
		"x_label": "Raw score (x)",
		"x_ph": "e.g. 85",
		"mean_label": "Mean (μ)",
		"mean_ph": "e.g. 70",
		"sd_label": "Standard deviation (σ)",
		"sd_ph": "e.g. 10",
		"zOut_label": "Z-score",
		"result_note": "z = (x − mean) / SD for learning — assumes a finite mean and SD > 0.",
		"err_generic": "Enter finite x and mean, and SD > 0.",
		"how_title": "How it works",
		"how_body": "Enter a raw score, the distribution mean, and the standard deviation. The tool returns z = (x − mean) / SD so you can see how many SDs the score sits above or below the mean. Runs in your browser for coursework.",
		"formula_title": "Formula and assumptions",
		"formula_body": "z = (x − μ) / σ. Keep these limits in mind:",
		"formula_item_1": "SD (σ) must be positive; zero or negative SD is rejected.",
		"formula_item_2": "This is a linear rescaling of x relative to the given mean and SD, not a full normality test.",
		"formula_item_3": "Units cancel: z is dimensionless.",
		"formula_item_4": "Pair with a p-value page if you next need a normal-tail probability from z.",
		"example_title": "Example",
		"example": "Example: x = 85, mean = 70, SD = 10 → z = (85 − 70) / 10 = 1.5.",
		"usecases_title": "When to use it",
		"usecase_1": "Homework: convert a test score to a standard score.",
		"usecase_2": "Compare two scores from distributions with different means or spreads.",
		"usecase_3": "Prepare a z to feed into a two-tailed p-value check.",
		"faq_q1": "What does z = 1.5 mean?",
		"faq_a1": "The raw score is 1.5 standard deviations above the stated mean.",
		"faq_q2": "Can SD be zero?",
		"faq_a2": "No. Division by zero is undefined; enter SD > 0.",
		"faq_q3": "Is a large |z| always “significant”?",
		"faq_a3": "Not by itself. Significance needs a model and a p-value or critical value, not only the z number.",
		"faq_q4": "Does this assume a normal distribution?",
		"faq_a4": "The algebra of z does not require normality, but many follow-on uses (like normal p-values) do.",
		"disclaimer": "Educational z = (x − mean) / SD only. Not a substitute for statistical software or study design.",
		"references": "Wikipedia standard score and standard deviation.",
		"ref_z_label": "Wikipedia — Standard score",
		"ref_sd_label": "Wikipedia — Standard deviation",
		"article": "Compute a z-score from a raw value, mean, and SD with z = (x − mean) / SD for learning."
	}),
	zh: withBtns('zh', {
		"x_label": "原始分 x",
		"x_ph": "例如 85",
		"mean_label": "均值 μ",
		"mean_ph": "例如 70",
		"sd_label": "标准差 σ",
		"sd_ph": "例如 10",
		"zOut_label": "Z 分数",
		"result_note": "z = (x − 均值) / 标准差，供学习——要求均值有限且 SD>0。",
		"err_generic": "请填写有限的 x 与均值，且标准差 > 0。",
		"how_title": "怎么用",
		"how_body": "输入原始分、均值与标准差。工具返回 z = (x − 均值) / 标准差，便于看出该分高于或低于均值多少个标准差。浏览器内计算，适合作业。",
		"formula_title": "公式与假设",
		"formula_body": "z = (x − μ) / σ。请注意：",
		"formula_item_1": "标准差必须为正；零或负值会被拒绝。",
		"formula_item_2": "这是相对给定均值与标准差的线性换算，不是正态性检验。",
		"formula_item_3": "量纲会消掉：z 无量纲。",
		"formula_item_4": "若还要由 z 求正态尾概率，可配合 p 值页。",
		"example_title": "示例",
		"example": "示例：x = 85，均值 = 70，SD = 10 → z = (85 − 70) / 10 = 1.5。",
		"usecases_title": "适合什么场景",
		"usecase_1": "作业：把考试分数换成标准分。",
		"usecase_2": "比较均值或离散程度不同的两组分数。",
		"usecase_3": "先算 z，再去做双侧 p 值对照。",
		"faq_q1": "z = 1.5 表示什么？",
		"faq_a1": "原始分比给定均值高出 1.5 个标准差。",
		"faq_q2": "标准差可以为 0 吗？",
		"faq_a2": "不可以。除以零无定义，请输入 SD>0。",
		"faq_q3": "|z| 大就一定“显著”吗？",
		"faq_a3": "不一定。显著性还需要模型与 p 值或临界值，不能只看 z。",
		"faq_q4": "一定要假定正态分布吗？",
		"faq_a4": "z 的代数本身不要求正态；但后续用正态 p 值时常假设正态。",
		"disclaimer": "结果仅为教育用的 z = (x − 均值) / 标准差，不能替代统计软件或研究设计。",
		"references": "维基百科标准分数与标准差条目。",
		"ref_z_label": "维基百科 — 标准分数",
		"ref_sd_label": "维基百科 — 标准差",
		"article": "用原始分、均值与标准差按 z = (x − 均值) / 标准差计算 Z 分数，供学习。"
	}),
	es: withBtns('es', {
		"x_label": "Puntuación bruta (x)",
		"x_ph": "p. ej. 85",
		"mean_label": "Media (μ)",
		"mean_ph": "p. ej. 70",
		"sd_label": "Desviación estándar (σ)",
		"sd_ph": "p. ej. 10",
		"zOut_label": "Puntuación z",
		"result_note": "z = (x − media) / DE para aprender — media finita y DE > 0.",
		"err_generic": "Introduce x y media finitos, y DE > 0.",
		"how_title": "Cómo funciona",
		"how_body": "Introduce la puntuación, la media y la desviación. La herramienta devuelve z = (x − media) / DE para ver cuántas DE queda por encima o por debajo. En el navegador, para clase.",
		"formula_title": "Fórmula y supuestos",
		"formula_body": "z = (x − μ) / σ. Límites:",
		"formula_item_1": "La DE debe ser positiva.",
		"formula_item_2": "Es un reescalado lineal, no una prueba de normalidad.",
		"formula_item_3": "z es adimensional.",
		"formula_item_4": "Combínalo con una página de valor p si necesitas la cola normal.",
		"example_title": "Ejemplo",
		"example": "Ejemplo: x = 85, media = 70, DE = 10 → z = 1,5.",
		"usecases_title": "Cuándo usarlo",
		"usecase_1": "Deberes: pasar una nota a puntuación estándar.",
		"usecase_2": "Comparar notas de distribuciones distintas.",
		"usecase_3": "Preparar un z para un contraste a dos colas.",
		"faq_q1": "¿Qué significa z = 1,5?",
		"faq_a1": "La puntuación está 1,5 DE por encima de la media indicada.",
		"faq_q2": "¿Puede ser DE = 0?",
		"faq_a2": "No; la división por cero no está definida.",
		"faq_q3": "¿Un |z| grande ya es “significativo”?",
		"faq_a3": "No por sí solo; hace falta un modelo y un p-valor o valor crítico.",
		"faq_q4": "¿Exige normalidad?",
		"faq_a4": "El álgebra de z no; muchos usos posteriores con colas normales sí.",
		"disclaimer": "Solo z educativo = (x − media) / DE. No sustituye software estadístico.",
		"references": "Wikipedia sobre puntuación estándar y desviación estándar.",
		"ref_z_label": "Wikipedia — Puntuación estándar",
		"ref_sd_label": "Wikipedia — Desviación estándar",
		"article": "Calcula una puntuación z a partir de x, media y DE con z = (x − media) / DE."
	}),
	ar: withBtns('ar', {
		"x_label": "الدرجة الخام x",
		"x_ph": "مثال 85",
		"mean_label": "المتوسط μ",
		"mean_ph": "مثال 70",
		"sd_label": "الانحراف المعياري σ",
		"sd_ph": "مثال 10",
		"zOut_label": "درجة z",
		"result_note": "z = (x − المتوسط) / الانحراف للتعلّم — متوسط محدود وانحراف > 0.",
		"err_generic": "أدخل x ومتوسطًا محدودين وانحرافًا > 0.",
		"how_title": "طريقة الاستخدام",
		"how_body": "أدخل الدرجة والمتوسط والانحراف. تُرجع الأداة z = (x − المتوسط) / الانحراف لمعرفة بعدك بعدد الانحرافات. في المتصفح للتعلّم.",
		"formula_title": "الصيغة والافتراضات",
		"formula_body": "z = (x − μ) / σ. حدود:",
		"formula_item_1": "يجب أن يكون الانحراف موجبًا.",
		"formula_item_2": "إعادة مقياس خطية وليست اختبار طبيعية.",
		"formula_item_3": "z بلا أبعاد.",
		"formula_item_4": "اربطها بصفحة قيمة p إن احتجت احتمال الذيل.",
		"example_title": "مثال",
		"example": "مثال: x = 85 والمتوسط = 70 والانحراف = 10 → z = 1.5.",
		"usecases_title": "متى تستخدمه",
		"usecase_1": "واجبات: تحويل درجة إلى معيارية.",
		"usecase_2": "مقارنة درجات من توزيعات مختلفة.",
		"usecase_3": "تجهيز z لفحص p ثنائي الطرف.",
		"faq_q1": "ماذا يعني z = 1.5؟",
		"faq_a1": "الدرجة أعلى من المتوسط بمقدار 1.5 انحراف معياري.",
		"faq_q2": "هل يمكن أن يكون الانحراف صفرًا؟",
		"faq_a2": "لا؛ القسمة على صفر غير معرّفة.",
		"faq_q3": "هل |z| الكبير يعني الدلالة دائمًا؟",
		"faq_a3": "لا وحده؛ تحتاج نموذجًا وp أو قيمة حرجة.",
		"faq_q4": "هل يفترض التوزيع الطبيعي؟",
		"faq_a4": "جبر z لا يشترط ذلك؛ كثير من الاستخدامات اللاحقة نعم.",
		"disclaimer": "z تعليمي فقط = (x − المتوسط) / الانحراف ولا يغني عن برمجيات إحصائية.",
		"references": "ويكيبيديا الدرجة المعيارية والانحراف المعياري.",
		"ref_z_label": "ويكيبيديا — الدرجة المعيارية",
		"ref_sd_label": "ويكيبيديا — الانحراف المعياري",
		"article": "احسب درجة z من القيمة والمتوسط والانحراف عبر z = (x − المتوسط) / الانحراف."
	}),
	pt: withBtns('pt', {
		"x_label": "Escore bruto (x)",
		"x_ph": "ex.: 85",
		"mean_label": "Média (μ)",
		"mean_ph": "ex.: 70",
		"sd_label": "Desvio padrão (σ)",
		"sd_ph": "ex.: 10",
		"zOut_label": "Escore z",
		"result_note": "z = (x − média) / DP para estudar — média finita e DP > 0.",
		"err_generic": "Informe x e média finitos e DP > 0.",
		"how_title": "Como funciona",
		"how_body": "Digite o escore, a média e o desvio. A ferramenta devolve z = (x − média) / DP para ver quantos DP está acima ou abaixo. No navegador, para aula.",
		"formula_title": "Fórmula e pressupostos",
		"formula_body": "z = (x − μ) / σ. Limites:",
		"formula_item_1": "O DP deve ser positivo.",
		"formula_item_2": "É um reescalonamento linear, não um teste de normalidade.",
		"formula_item_3": "z é adimensional.",
		"formula_item_4": "Combine com uma página de valor-p se precisar da cauda normal.",
		"example_title": "Exemplo",
		"example": "Exemplo: x = 85, média = 70, DP = 10 → z = 1,5.",
		"usecases_title": "Quando usar",
		"usecase_1": "Tarefa: converter nota em escore padrão.",
		"usecase_2": "Comparar notas de distribuições diferentes.",
		"usecase_3": "Preparar um z para um teste bicaudal.",
		"faq_q1": "O que significa z = 1,5?",
		"faq_a1": "O escore está 1,5 DP acima da média indicada.",
		"faq_q2": "DP pode ser zero?",
		"faq_a2": "Não; divisão por zero é indefinida.",
		"faq_q3": "|z| grande já é “significativo”?",
		"faq_a3": "Não sozinho; faltam modelo e p-valor ou valor crítico.",
		"faq_q4": "Exige normalidade?",
		"faq_a4": "A álgebra de z não; muitos usos posteriores com caudas normais sim.",
		"disclaimer": "Apenas z educacional = (x − média) / DP. Não substitui software estatístico.",
		"references": "Wikipedia sobre escore padrão e desvio padrão.",
		"ref_z_label": "Wikipedia — Escore padrão",
		"ref_sd_label": "Wikipedia — Desvio padrão",
		"article": "Calcule um escore z a partir de x, média e DP com z = (x − média) / DP."
	}),
	id: withBtns('id', {
		"x_label": "Skor mentah (x)",
		"x_ph": "mis. 85",
		"mean_label": "Mean (μ)",
		"mean_ph": "mis. 70",
		"sd_label": "Simpangan baku (σ)",
		"sd_ph": "mis. 10",
		"zOut_label": "Skor-z",
		"result_note": "z = (x − mean) / SD untuk belajar — mean hingga dan SD > 0.",
		"err_generic": "Masukkan x dan mean hingga, serta SD > 0.",
		"how_title": "Cara kerja",
		"how_body": "Masukkan skor, mean, dan simpangan baku. Alat mengembalikan z = (x − mean) / SD agar terlihat berapa SD di atas atau di bawah mean. Di browser untuk tugas.",
		"formula_title": "Rumus dan asumsi",
		"formula_body": "z = (x − μ) / σ. Batasan:",
		"formula_item_1": "SD harus positif.",
		"formula_item_2": "Ini penskalaan linear, bukan uji kenormalan.",
		"formula_item_3": "z tanpa satuan.",
		"formula_item_4": "Gabungkan dengan halaman p-value bila perlu peluang ekor normal.",
		"example_title": "Contoh",
		"example": "Contoh: x = 85, mean = 70, SD = 10 → z = 1,5.",
		"usecases_title": "Kapan dipakai",
		"usecase_1": "PR: ubah nilai ujian menjadi skor standar.",
		"usecase_2": "Bandingkan skor dari sebaran berbeda.",
		"usecase_3": "Siapkan z untuk cek p dua sisi.",
		"faq_q1": "Arti z = 1,5?",
		"faq_a1": "Skor berada 1,5 SD di atas mean yang dinyatakan.",
		"faq_q2": "Boleh SD = 0?",
		"faq_a2": "Tidak; pembagian nol tidak terdefinisi.",
		"faq_q3": "|z| besar otomatis “signifikan”?",
		"faq_a3": "Tidak sendiri; perlu model dan p-value atau nilai kritis.",
		"faq_q4": "Wajib normal?",
		"faq_a4": "Aljabar z tidak; banyak pemakaian lanjutan dengan ekor normal ya.",
		"disclaimer": "Hanya z edukasi = (x − mean) / SD. Bukan pengganti perangkat lunak statistik.",
		"references": "Wikipedia skor standar dan simpangan baku.",
		"ref_z_label": "Wikipedia — Skor standar",
		"ref_sd_label": "Wikipedia — Simpangan baku",
		"article": "Hitung skor-z dari x, mean, dan SD dengan z = (x − mean) / SD."
	}),
	fr: withBtns('fr', {
		"x_label": "Score brut (x)",
		"x_ph": "ex. 85",
		"mean_label": "Moyenne (μ)",
		"mean_ph": "ex. 70",
		"sd_label": "Écart-type (σ)",
		"sd_ph": "ex. 10",
		"zOut_label": "Score z",
		"result_note": "z = (x − moyenne) / écart-type pour apprendre — moyenne finie et écart-type > 0.",
		"err_generic": "Saisissez x et moyenne finis, et écart-type > 0.",
		"how_title": "Fonctionnement",
		"how_body": "Entrez le score, la moyenne et l’écart-type. L’outil renvoie z = (x − moyenne) / écart-type pour voir de combien d’écarts-types vous êtes au-dessus ou en dessous. Dans le navigateur, pour les cours.",
		"formula_title": "Formule et hypothèses",
		"formula_body": "z = (x − μ) / σ. Limites :",
		"formula_item_1": "L’écart-type doit être positif.",
		"formula_item_2": "Rescale linéaire, pas un test de normalité.",
		"formula_item_3": "z est sans dimension.",
		"formula_item_4": "Associez une page de p-valeur si vous voulez la queue normale.",
		"example_title": "Exemple",
		"example": "Exemple : x = 85, moyenne = 70, écart-type = 10 → z = 1,5.",
		"usecases_title": "Quand l’utiliser",
		"usecase_1": "Devoir : convertir une note en score standard.",
		"usecase_2": "Comparer des scores issus de lois différentes.",
		"usecase_3": "Préparer un z pour un test bilatéral.",
		"faq_q1": "Que signifie z = 1,5 ?",
		"faq_a1": "Le score est 1,5 écart-type au-dessus de la moyenne indiquée.",
		"faq_q2": "L’écart-type peut-il être nul ?",
		"faq_a2": "Non ; division par zéro indéfinie.",
		"faq_q3": "Un grand |z| est-il forcément « significatif » ?",
		"faq_a3": "Pas seul ; il faut un modèle et une p-valeur ou une valeur critique.",
		"faq_q4": "Faut-il la normalité ?",
		"faq_a4": "L’algèbre de z non ; beaucoup d’usages suivants avec queues normales oui.",
		"disclaimer": "z pédagogique seulement = (x − moyenne) / écart-type. Ne remplace pas un logiciel statistique.",
		"references": "Wikipedia score standard et écart-type.",
		"ref_z_label": "Wikipedia — Score standard",
		"ref_sd_label": "Wikipedia — Écart-type",
		"article": "Calculez un score z à partir de x, moyenne et écart-type avec z = (x − moyenne) / écart-type."
	}),
	ja: withBtns('ja', {
		"x_label": "素点 x",
		"x_ph": "例: 85",
		"mean_label": "平均 μ",
		"mean_ph": "例: 70",
		"sd_label": "標準偏差 σ",
		"sd_ph": "例: 10",
		"zOut_label": "Zスコア",
		"result_note": "学習用の z = (x − 平均) / SD。平均は有限、SD > 0。",
		"err_generic": "有限の x と平均、および SD > 0 を入力してください。",
		"how_title": "使い方",
		"how_body": "素点・平均・標準偏差を入れます。z = (x − 平均) / SD で、平均から何 SD 離れているかを見ます。ブラウザ内で宿題向けです。",
		"formula_title": "式と前提",
		"formula_body": "z = (x − μ) / σ。注意点：",
		"formula_item_1": "SD は正であること。",
		"formula_item_2": "線形の尺度変換であり、正規性の検定ではありません。",
		"formula_item_3": "z は無次元です。",
		"formula_item_4": "正規の裾確率が必要なら p 値ページと併用。",
		"example_title": "例",
		"example": "例：x = 85、平均 = 70、SD = 10 → z = 1.5。",
		"usecases_title": "こんなときに",
		"usecase_1": "テスト得点を標準得点にする宿題。",
		"usecase_2": "平均やばらつきが違う分布の得点比較。",
		"usecase_3": "両側 p 値の前段として z を用意する。",
		"faq_q1": "z = 1.5 の意味は？",
		"faq_a1": "素点が与えられた平均より 1.5 SD 上です。",
		"faq_q2": "SD = 0 は？",
		"faq_a2": "不可。ゼロ除算になります。",
		"faq_q3": "|z| が大きければ有意？",
		"faq_a3": "それだけでは決まりません。モデルと p 値や臨界値が必要です。",
		"faq_q4": "正規分布が必須？",
		"faq_a4": "z の式自体は必須ではありません。正規の p 値など後続ではよく仮定します。",
		"disclaimer": "教育用の z = (x − 平均) / SD のみで、統計ソフトや研究設計の代わりにはなりません。",
		"references": "Wikipedia の標準得点と標準偏差。",
		"ref_z_label": "Wikipedia — 標準得点",
		"ref_sd_label": "Wikipedia — 標準偏差",
		"article": "素点・平均・SD から z = (x − 平均) / SD で Zスコアを求めます。"
	}),
	ru: withBtns('ru', {
		"x_label": "Сырой балл (x)",
		"x_ph": "напр. 85",
		"mean_label": "Среднее (μ)",
		"mean_ph": "напр. 70",
		"sd_label": "СКО (σ)",
		"sd_ph": "напр. 10",
		"zOut_label": "Z-оценка",
		"result_note": "z = (x − среднее) / СКО для обучения — конечное среднее и СКО > 0.",
		"err_generic": "Введите конечные x и среднее, и СКО > 0.",
		"how_title": "Как пользоваться",
		"how_body": "Введите балл, среднее и СКО. Инструмент считает z = (x − среднее) / СКО, чтобы увидеть, на сколько СКО выше или ниже среднего. В браузере — для учёбы.",
		"formula_title": "Формула и допущения",
		"formula_body": "z = (x − μ) / σ. Ограничения:",
		"formula_item_1": "СКО должно быть положительным.",
		"formula_item_2": "Линейное перемасштабирование, не проверка нормальности.",
		"formula_item_3": "z безразмерна.",
		"formula_item_4": "Для вероятности хвоста свяжите со страницей p-value.",
		"example_title": "Пример",
		"example": "Пример: x = 85, среднее = 70, СКО = 10 → z = 1,5.",
		"usecases_title": "Когда применять",
		"usecase_1": "Домашнее задание: перевести балл в стандартный.",
		"usecase_2": "Сравнить баллы из разных распределений.",
		"usecase_3": "Подготовить z для двустороннего p.",
		"faq_q1": "Что значит z = 1,5?",
		"faq_a1": "Балл на 1,5 СКО выше указанного среднего.",
		"faq_q2": "Может ли СКО быть нулём?",
		"faq_a2": "Нет; деление на ноль не определено.",
		"faq_q3": "Большой |z| уже «значим»?",
		"faq_a3": "Не сам по себе; нужны модель и p или критическое значение.",
		"faq_q4": "Нужна нормальность?",
		"faq_a4": "Для алгебры z — нет; для многих последующих нормальных хвостов — да.",
		"disclaimer": "Только учебный z = (x − среднее) / СКО. Не заменяет статистическое ПО.",
		"references": "Wikipedia о стандартной оценке и СКО.",
		"ref_z_label": "Wikipedia — Стандартная оценка",
		"ref_sd_label": "Wikipedia — Среднеквадратическое отклонение",
		"article": "Считайте z из x, среднего и СКО по z = (x − среднее) / СКО."
	}),
	de: withBtns('de', {
		"x_label": "Rohwert (x)",
		"x_ph": "z. B. 85",
		"mean_label": "Mittelwert (μ)",
		"mean_ph": "z. B. 70",
		"sd_label": "Standardabweichung (σ)",
		"sd_ph": "z. B. 10",
		"zOut_label": "Z-Wert",
		"result_note": "z = (x − Mittelwert) / SD zum Lernen — endlicher Mittelwert und SD > 0.",
		"err_generic": "Bitte endliche x und Mittelwert sowie SD > 0 eingeben.",
		"how_title": "So funktioniert’s",
		"how_body": "Geben Sie Rohwert, Mittelwert und SD ein. Das Tool liefert z = (x − Mittelwert) / SD, damit Sie sehen, wie viele SD über oder unter dem Mittelwert liegen. Im Browser für Übungen.",
		"formula_title": "Formel und Annahmen",
		"formula_body": "z = (x − μ) / σ. Grenzen:",
		"formula_item_1": "SD muss positiv sein.",
		"formula_item_2": "Lineare Umskalierung, kein Normalitätstest.",
		"formula_item_3": "z ist dimensionslos.",
		"formula_item_4": "Für die Normal-Schwanzwahrscheinlichkeit mit einer p-Wert-Seite kombinieren.",
		"example_title": "Beispiel",
		"example": "Beispiel: x = 85, Mittelwert = 70, SD = 10 → z = 1,5.",
		"usecases_title": "Wann sinnvoll",
		"usecase_1": "Hausaufgabe: Note in Standardwert umrechnen.",
		"usecase_2": "Werte aus Verteilungen mit anderem Mittel/Streuung vergleichen.",
		"usecase_3": "z für einen zweiseitigen p-Check vorbereiten.",
		"faq_q1": "Was bedeutet z = 1,5?",
		"faq_a1": "Der Rohwert liegt 1,5 SD über dem angegebenen Mittelwert.",
		"faq_q2": "Darf SD = 0 sein?",
		"faq_a2": "Nein; Division durch null ist undefiniert.",
		"faq_q3": "Ist großes |z| automatisch „signifikant“?",
		"faq_a3": "Nicht allein; Modell und p-Wert oder kritischer Wert fehlen sonst.",
		"faq_q4": "Ist Normalverteilung nötig?",
		"faq_a4": "Für die z-Algebra nicht; für viele spätere Normal-Schwanz-Anwendungen oft ja.",
		"disclaimer": "Nur Lern-z = (x − Mittelwert) / SD. Ersetzt keine Statistiksoftware.",
		"references": "Wikipedia Standardwert und Standardabweichung.",
		"ref_z_label": "Wikipedia — Standardwert",
		"ref_sd_label": "Wikipedia — Standardabweichung",
		"article": "Berechnen Sie einen z-Wert aus x, Mittelwert und SD mit z = (x − Mittelwert) / SD."
	})
};

export default {
	seq: 25,
	slug: 'how-to-calculate-z-score',
	prefix: 'tool_z_score',
	nameZh: "Z 分数计算器",
	category: 'calculator',
	ymyl: false,
	pageFile: 'howToCalculateZScorePage',
	pageExport: 'renderHowToCalculateZScorePage',
	anchor: 'z-score',
	related: ["how-to-calculate-p-value","how-to-calculate-standard-deviation"],
	glyph: "M6 24L12 8l6 12 4-8 4 12",
	sampleHint: "x=85, mean=70, sd=10 → z=1.5",
	titles: {
	"en": "Z-Score Calculator — How to Calculate a Standard Score",
	"zh": "Z 分数计算器 — 如何计算标准分数",
	"es": "Calculadora de puntuación z — Cómo calcular un valor estándar",
	"ar": "حاسبة درجة z — كيفية حساب الدرجة المعيارية",
	"pt": "Calculadora de escore z — Como calcular um escore padrão",
	"id": "Kalkulator skor-z — Cara menghitung skor standar",
	"fr": "Calculateur de score z — Comment calculer un score standard",
	"ja": "Zスコア計算ツール — 標準得点の求め方",
	"ru": "Калькулятор z-оценки — Как рассчитать стандартный балл",
	"de": "Z-Wert-Rechner — Standardwert berechnen"
},
	descriptions: {
	"en": "Convert a raw score to a z-score with z = (x − mean) / SD. Example: x = 85, mean = 70, SD = 10 → z = 1.5. States the linear scaling assumption and SD > 0. Runs in your browser for coursework and quick checks.",
	"zh": "用 z = (x − 均值) / 标准差把原始分换成标准分（Z 分数）。示例：x = 85、均值 = 70、标准差 = 10 → z = 1.5。写明线性尺度与 SD>0。浏览器内计算，适合作业与快速对照。标准分数帮助比较不同分布上的位置。",
	"es": "Convierte una puntuación bruta en z con z = (x − media) / DE. Ejemplo: x = 85, media = 70, DE = 10 → z = 1,5. Deja claros el escalado lineal y DE > 0. En el navegador, para clase y comprobaciones rápidas.",
	"ar": "حوّل درجة خام إلى درجة z عبر z = (x − المتوسط) / الانحراف. مثال: x = 85 والمتوسط = 70 والانحراف = 10 → z = 1.5. يوضح المقياس الخطي وشرط الانحراف > 0. في المتصفح للتعلّم والتحقق السريع.",
	"pt": "Converta um escore bruto em z com z = (x − média) / DP. Exemplo: x = 85, média = 70, DP = 10 → z = 1,5. Deixa claros o escalonamento linear e DP > 0. No navegador, para estudo e checagens rápidas.",
	"id": "Ubah skor mentah menjadi skor-z dengan z = (x − mean) / SD. Contoh: x = 85, mean = 70, SD = 10 → z = 1,5. Menuliskan asumsi skala linear dan SD > 0. Di browser untuk tugas dan cek cepat.",
	"fr": "Convertissez un score brut en z avec z = (x − moyenne) / écart-type. Exemple : x = 85, moyenne = 70, écart-type = 10 → z = 1,5. Hypothèses d’échelle linéaire et écart-type > 0. Dans le navigateur, pour cours et vérifications.",
	"ja": "z = (x − 平均) / 標準偏差 で素点を標準得点（Zスコア）にします。例：x = 85、平均 = 70、SD = 10 → z = 1.5。線形尺度と SD>0 を明示。ブラウザ内で、宿題やざっくり確認向けです。異なる分布上の位置を比べる学習にも使えます。",
	"ru": "Переведите сырой балл в z по z = (x − среднее) / СКО. Пример: x = 85, среднее = 70, СКО = 10 → z = 1,5. Явно указывает линейное масштабирование и СКО > 0. В браузере для учёбы и быстрой проверки.",
	"de": "Wandeln Sie einen Rohwert in einen z-Wert um: z = (x − Mittelwert) / SD. Beispiel: x = 85, Mittelwert = 70, SD = 10 → z = 1,5. Macht lineare Skalierung und SD > 0 klar. Im Browser für Übungen und schnelle Checks."
},
	ui: _ui,
	fields: [
	{
		"id": "x",
		"type": "number",
		"half": true,
		"labelKey": "x_label",
		"phKey": "x_ph"
	},
	{
		"id": "mean",
		"type": "number",
		"half": true,
		"labelKey": "mean_label",
		"phKey": "mean_ph"
	},
	{
		"id": "sd",
		"type": "number",
		"half": true,
		"labelKey": "sd_label",
		"phKey": "sd_ph"
	}
],
	results: [
	{
		"id": "zOut",
		"labelKey": "zOut_label"
	}
],
	refs: [
	{
		"labelKey": "ref_z_label",
		"href": "https://en.wikipedia.org/wiki/Standard_score"
	},
	{
		"labelKey": "ref_sd_label",
		"href": "https://en.wikipedia.org/wiki/Standard_deviation"
	}
],
	computeJs: "\n        var x = parseFloat(xEl.value);\n        var mean = parseFloat(meanEl.value);\n        var sd = parseFloat(sdEl.value);\n        if (!Number.isFinite(x) || !Number.isFinite(mean) || !Number.isFinite(sd) || sd <= 0) {\n          return { ok: false, error: msgErr };\n        }\n        var z = (x - mean) / sd;\n        return { ok: true, values: { zOut: fmt(z, 6) } };\n",
	sampleJs: "\n        xEl.value = '85';\n        meanEl.value = '70';\n        sdEl.value = '10';\n",
};
