#!/usr/bin/env node
/**
 * 合并工具分片为运行时产物（生成文件请勿手改）：
 * - src/site/tool-catalog.d/*.json → src/site/tool-catalog.json
 * - i18n/core + i18n/tools/* → src/site/i18n/{lang}.ts（GENERATED）
 * - page 注册表 → src/site/toolPageRegistry.generated.ts（仅构建期预渲染使用）
 * - slug 列表 → src/site/toolSlugs.generated.ts（Worker 轻量路由校验）
 * - 首页工具文案 → scripts/site/i18n-tools.generated.mjs
 *
 * `build:site` / `start:dev` 会自动调用；改分片后本地也可直接 `npm run merge:tools`。
 */
import fs from 'node:fs';
import path from 'node:path';
import {
	LANGS,
	CATALOG_PATH,
	I18N_DIR,
	I18N_CORE_DIR,
	I18N_TOOLS_DIR,
	REGISTRY_OUT,
	HOME_I18N_OUT,
	ensureDir,
	writeJson,
	loadCatalogShards,
	toPublicCatalogEntry,
	parseLocaleDict,
	writeLocaleTs,
	escapeSingleQuoted,
	defaultPageMeta,
} from './lib.mjs';

/**
 * Merge catalog shards.
 */
function mergeCatalog() {
	const shards = loadCatalogShards();
	if (!shards.length) {
		throw new Error('No catalog shards in src/site/tool-catalog.d — run npm run split:tools first');
	}
	const publicCatalog = shards.map(toPublicCatalogEntry);
	writeJson(CATALOG_PATH, publicCatalog);
	console.log(`merged catalog: ${publicCatalog.length} tools → tool-catalog.json`);
	return shards;
}

/**
 * Merge i18n core + tool shards into generated locale files.
 * @param {Array<{slug:string,faqPrefix:string,homeTitleKey?:string,homeDescKey?:string}>} shards
 */
function mergeI18n(shards) {
	/** @type {Record<string, Record<string, string>>} */
	const homeByLang = Object.fromEntries(LANGS.map((l) => [l, {}]));

	for (const lang of LANGS) {
		const corePath = path.join(I18N_CORE_DIR, `${lang}.ts`);
		if (!fs.existsSync(corePath)) {
			throw new Error(`Missing i18n core: ${corePath}`);
		}
		/** @type {Record<string, string>} */
		const merged = { ...parseLocaleDict(fs.readFileSync(corePath, 'utf8')) };

		for (const tool of shards) {
			const shardPath = path.join(I18N_TOOLS_DIR, tool.slug, `${lang}.ts`);
			if (!fs.existsSync(shardPath)) continue;
			const shard = parseLocaleDict(fs.readFileSync(shardPath, 'utf8'));
			Object.assign(merged, shard);
			const titleKey = tool.homeTitleKey || tool.i18nKey;
			const descKey = tool.homeDescKey;
			if (titleKey && shard[titleKey]) homeByLang[lang][titleKey] = shard[titleKey];
			if (descKey && shard[descKey]) homeByLang[lang][descKey] = shard[descKey];
		}

		writeLocaleTs(
			path.join(I18N_DIR, `${lang}.ts`),
			lang,
			merged,
			`GENERATED by scripts/tool-modules/merge-all.mjs — DO NOT EDIT.\n * Edit src/site/i18n/core/${lang}.ts or src/site/i18n/tools/{slug}/${lang}.ts instead.`
		);
	}

	writeHomeI18n(homeByLang);
	console.log(`merged i18n: ${LANGS.length} locales`);
}

/**
 * Write home-build overlay for tool title/desc keys.
 * @param {Record<string, Record<string, string>>} homeByLang
 */
function writeHomeI18n(homeByLang) {
	const chunks = LANGS.map((lang) => {
		const entries = Object.entries(homeByLang[lang] || {})
			.sort(([a], [b]) => a.localeCompare(b))
			.map(([k, v]) => `    ${k}: '${escapeSingleQuoted(v)}',`)
			.join('\n');
		return `  ${lang}: {\n${entries}\n  }`;
	});
	const body = `/**
 * GENERATED by scripts/tool-modules/merge-all.mjs — DO NOT EDIT.
 * Tool home title/desc keys merged from src/site/i18n/tools/{slug}/{lang}.ts
 */
export const toolHomeTranslations = {
${chunks.join(',\n')}
};
`;
	fs.writeFileSync(HOME_I18N_OUT, body, 'utf8');
	console.log(`wrote ${path.relative(process.cwd(), HOME_I18N_OUT)}`);
}

/**
 * Generate tool page registry from catalog shard `page` meta.
 * @param {Array<Record<string, any>>} shards
 */
function mergeRegistry(shards) {
	const imports = [];
	const entries = [];
	const seenExports = new Set();

	for (const tool of shards) {
		const page = tool.page || defaultPageMeta(tool.slug);
		const modPath = page.module.startsWith('.') ? page.module : `../pages/${page.module}`;
		const exp = page.export;
		if (!seenExports.has(exp)) {
			imports.push(`import { ${exp} } from '${modPath}';`);
			seenExports.add(exp);
		}
		if (page.style === 'pair') {
			entries.push(
				`\t'${tool.slug}': (lang, defaultLang, _enabled) => ${exp}(lang, defaultLang),`
			);
		} else {
			entries.push(
				`\t'${tool.slug}': (lang, defaultLang, enabled) => ${exp}({ lang, defaultLang, enabledLangs: enabled }),`
			);
		}
	}

	const body = `/**
 * GENERATED by scripts/tool-modules/merge-all.mjs — DO NOT EDIT.
 * Source of truth: src/site/tool-catalog.d/{slug}.json → page.module / page.export / page.style
 */
import type { SiteLang } from './i18n';
${imports.join('\n')}

export type ToolPageRenderFn = (
	lang: SiteLang,
	defaultLang: SiteLang,
	enabledLangs: SiteLang[]
) => string | void;

/** slug → render function for registerToolPage */
export const TOOL_PAGE_RENDERERS: Record<string, ToolPageRenderFn> = {
${entries.join('\n')}
};
`;
	fs.writeFileSync(REGISTRY_OUT, body, 'utf8');
	console.log(`wrote ${path.relative(process.cwd(), REGISTRY_OUT)} (${shards.length} tools)`);
}

/**
 * 写出轻量 slug 列表（Worker 运行时只用此文件，避免打入全量 Page SSR）。
 * @param {Array<Record<string, any>>} shards
 */
function mergeToolSlugs(shards) {
	const slugs = shards.map((t) => t.slug).filter(Boolean).sort();
	const out = path.join(path.dirname(REGISTRY_OUT), 'toolSlugs.generated.ts');
	const body = `/**
 * GENERATED by scripts/tool-modules/merge-all.mjs — DO NOT EDIT.
 * Source of truth: src/site/tool-catalog.d/{slug}.json
 */
export const TOOL_SLUGS = ${JSON.stringify(slugs, null, '\t')} as const;

export type ToolSlug = (typeof TOOL_SLUGS)[number];

/** O(1) 校验公开 /tools/:slug 是否存在 */
export const TOOL_SLUG_SET: ReadonlySet<string> = new Set(TOOL_SLUGS);
`;
	fs.writeFileSync(out, body, 'utf8');
	console.log(`wrote ${path.relative(process.cwd(), out)} (${slugs.length} slugs)`);
}

const shards = mergeCatalog();
mergeI18n(shards);
mergeRegistry(shards);
mergeToolSlugs(shards);
console.log('merge:tools OK');
