/** i18n tool shard (magnet-link-decoder / es). */
import type { SiteLangDict } from '../../../types';
const es: SiteLangDict = {
  tool_magnet_link_decoder_article: 'Examina un URI magnet sin abrir un cliente torrent. El parser conserva parámetros repetidos, reconoce temas exactos de BitTorrent v1 y v2, comprueba trackers y tamaños, y mantiene visibles los valores dañados junto a sus avisos.',
  tool_magnet_link_decoder_clear: 'Limpiar', tool_magnet_link_decoder_copy_done: 'Copiado', tool_magnet_link_decoder_copy_hash: 'Copiar info hash', tool_magnet_link_decoder_copy_json: 'Copiar JSON', tool_magnet_link_decoder_copy_normalized: 'Copiar URI normalizado', tool_magnet_link_decoder_copy_trackers: 'Copiar trackers', tool_magnet_link_decoder_decode: 'Decodificar',
  tool_magnet_link_decoder_desc: 'Decodifica un enlace magnet localmente para ver info hash, nombre, tamaño, trackers, web seeds, peers y avisos sin iniciar una descarga.',
  tool_magnet_link_decoder_description: 'Pega un enlace magnet para decodificar campos con porcentaje, agrupar trackers repetidos y revisar info hashes btih o btmh dentro del navegador. El ejemplo muestra sample-linux.iso, 1 MiB, un info hash y dos trackers; el enlace no se sube ni se consulta ningún tracker, DHT o peer.',
  tool_magnet_link_decoder_disclaimer: 'Solo inspecciona la estructura: no descarga contenido, obtiene metadatos, contacta trackers, DHT o peers, crea archivos .torrent ni decide si el contenido es seguro o legal.',
  tool_magnet_link_decoder_empty: 'Primero pega un URI magnet.', tool_magnet_link_decoder_error_scheme: 'La entrada debe comenzar por magnet:?.',
  tool_magnet_link_decoder_example: 'Entrada: URI con xt=urn:btih:0123456789abcdef0123456789abcdef01234567, dn=sample-linux.iso, xl=1048576 y dos tr. Salida: btih válido, nombre sample-linux.iso, 1.048.576 bytes (1 MiB), dos trackers y ningún aviso.', tool_magnet_link_decoder_example_title: 'Ejemplo',
  tool_magnet_link_decoder_faq_a1: 'No. El análisis se limita al texto que ya está en el navegador. La página no consulta trackers, nodos DHT, peers, web seeds o servicios de metadatos, ni abre un cliente torrent.',
  tool_magnet_link_decoder_faq_a2: 'xt significa tema exacto. En BitTorrent, urn:btih suele contener un info hash v1 de 40 caracteres hexadecimales o 32 Base32. Para v2 se usa habitualmente urn:btmh con un multihash hexadecimal.',
  tool_magnet_link_decoder_faq_a3: 'tr se puede repetir para anunciar trackers alternativos. El parser conserva todos en su orden original, avisa si un valor no parece una URL válida y copia la lista con una dirección por línea.',
  tool_magnet_link_decoder_faq_a4: 'No. Un URI magnet puede identificar contenido sin incluir los metadatos necesarios para un .torrent. La conversión exige recuperar esos datos de una red de peers u otra fuente, algo que esta herramienta local no hace.',
  tool_magnet_link_decoder_faq_a5: 'No. La decodificación, agrupación, validación, normalización y creación del JSON ocurren en esta pestaña. El enlace no se envía al servidor; evita pegar enlaces privados en equipos compartidos.',
  tool_magnet_link_decoder_faq_q1: '¿Decodificar un enlace magnet descarga algo?', tool_magnet_link_decoder_faq_q2: '¿Qué significa xt=urn:btih o urn:btmh?', tool_magnet_link_decoder_faq_q3: '¿Por qué aparecen varios trackers tr?', tool_magnet_link_decoder_faq_q4: '¿Convierte el enlace magnet en un archivo .torrent?', tool_magnet_link_decoder_faq_q5: '¿Se sube mi enlace magnet?',
  tool_magnet_link_decoder_field_display_name: 'Nombre (dn)', tool_magnet_link_decoder_field_exact_topics: 'Temas exactos (xt)', tool_magnet_link_decoder_field_exact_sources: 'Fuentes exactas (xs)', tool_magnet_link_decoder_field_other: 'Otros parámetros', tool_magnet_link_decoder_field_peer_hints: 'Peers sugeridos (x.pe)', tool_magnet_link_decoder_field_size: 'Tamaño exacto (xl)', tool_magnet_link_decoder_field_trackers: 'Trackers (tr)', tool_magnet_link_decoder_field_web_seeds: 'Web seeds (ws)',
  tool_magnet_link_decoder_how_body: 'Pega un URI magnet completo y pulsa Decodificar. El parser separa sus pares en orden, decodifica porcentajes y signos más, agrupa claves repetidas, clasifica los temas exactos, comprueba URL y tamaños y genera un URI normalizado y JSON. Si una secuencia codificada está dañada, conserva el texto para poder diagnosticarla.', tool_magnet_link_decoder_how_title: 'Cómo funciona',
  tool_magnet_link_decoder_input_label: 'URI magnet', tool_magnet_link_decoder_input_placeholder: 'magnet:?xt=urn:btih:...&dn=...&tr=...', tool_magnet_link_decoder_json_label: 'JSON analizado', tool_magnet_link_decoder_normalized_label: 'URI normalizado', tool_magnet_link_decoder_privacy: 'Funciona en el navegador: no sube datos ni consulta trackers, DHT, peers, web seeds o metadatos.', tool_magnet_link_decoder_result_empty: 'Aquí aparecerán los campos decodificados.', tool_magnet_link_decoder_results_title: 'Campos decodificados',
  tool_magnet_link_decoder_rules_body: 'Los parámetros magnet forman un mapa de consulta repetible. Se conserva cada aparición y se revisa su forma sin afirmar que el contenido exista.',
  tool_magnet_link_decoder_rules_item_1: 'Campos: xt identifica el tema; dn da el nombre; tr el tracker; xl la longitud en bytes; ws un web seed; xs una fuente exacta; x.pe un peer sugerido. Las claves desconocidas permanecen.',
  tool_magnet_link_decoder_rules_item_2: 'Hashes: btih admite 40 caracteres hexadecimales o 32 Base32. btmh admite un multihash hexadecimal de longitud par; 1220 seguido de 64 hex es la forma SHA-256 habitual en BitTorrent v2.',
  tool_magnet_link_decoder_rules_item_3: 'Decodificación: las claves y valores usan escapes de porcentaje y + equivale a espacio. Un escape % mal formado se conserva como texto y genera un aviso.',
  tool_magnet_link_decoder_rules_item_4: 'Límite: las pruebas de URL y entero solo detectan sintaxis sospechosa; no prueban que un tracker responda, existan metadatos, el archivo sea seguro o compartirlo esté permitido.', tool_magnet_link_decoder_rules_title: 'Reglas del URI magnet',
  tool_magnet_link_decoder_sample: 'Cargar ejemplo', tool_magnet_link_decoder_size_bytes: '{bytes} bytes ({human})', tool_magnet_link_decoder_status_invalid: 'No válido', tool_magnet_link_decoder_status_valid: 'Válido', tool_magnet_link_decoder_status_warning: 'Con avisos', tool_magnet_link_decoder_summary: '{fields} campos, {trackers} trackers, {warnings} avisos', tool_magnet_link_decoder_title: 'Decodificador de enlaces magnet — Info hash y trackers en el navegador', tool_magnet_link_decoder_unknown_value: '(valor vacío)',
  tool_magnet_link_decoder_usecase_1: 'Desarrollo: revisa un URI generado, su codificación, tema exacto y lista de trackers repetidos antes de publicarlo.', tool_magnet_link_decoder_usecase_2: 'Soporte y moderación: comprueba trackers, web seeds, fuentes o peers que expone un enlace sin abrir el cliente torrent.', tool_magnet_link_decoder_usecase_3: 'Documentación: usa el ejemplo inocuo para explicar cómo un extractor de info hash interpreta xt, dn, xl y varios tr.', tool_magnet_link_decoder_usecases_title: 'Comprobaciones útiles',
  tool_magnet_link_decoder_warn_bad_encoding: 'Codificación de porcentaje incorrecta en {key}; se conservó el texto.', tool_magnet_link_decoder_warn_bad_hash: 'Info hash no compatible o incorrecto: {value}', tool_magnet_link_decoder_warn_bad_peer: 'x.pe debe tener el formato host:puerto o [IPv6]:puerto: {value}', tool_magnet_link_decoder_warn_bad_size: 'xl debe ser una cantidad entera no negativa de bytes.', tool_magnet_link_decoder_warn_bad_url: '{key} no es una URL absoluta válida: {value}', tool_magnet_link_decoder_warn_missing_xt: 'No se encontró el parámetro xt de tema exacto.',
};
export default es;
