/** i18n tool shard (magnet-link-decoder / pt). */
import type { SiteLangDict } from '../../../types';
const pt: SiteLangDict = {
  tool_magnet_link_decoder_article: 'Inspecione um URI magnet sem abrir um cliente torrent. O parser preserva parâmetros repetidos, reconhece tópicos exatos BitTorrent v1/v2, confere trackers e tamanhos e mantém valores malformados visíveis com avisos.',
  tool_magnet_link_decoder_clear: 'Limpar', tool_magnet_link_decoder_copy_done: 'Copiado', tool_magnet_link_decoder_copy_hash: 'Copiar info hash', tool_magnet_link_decoder_copy_json: 'Copiar JSON', tool_magnet_link_decoder_copy_normalized: 'Copiar URI normalizado', tool_magnet_link_decoder_copy_trackers: 'Copiar trackers', tool_magnet_link_decoder_decode: 'Decodificar',
  tool_magnet_link_decoder_desc: 'Decodifique um link magnet localmente e veja info hash, nome, tamanho, trackers, web seeds, peers e avisos sem iniciar download.',
  tool_magnet_link_decoder_description: 'Cole um link magnet para decodificar campos percentuais, agrupar trackers repetidos e conferir info hashes btih ou btmh no navegador. O exemplo mostra sample-linux.iso, 1 MiB, um info hash e dois trackers; o link não é enviado e nenhum tracker, DHT ou peer é consultado.',
  tool_magnet_link_decoder_disclaimer: 'Somente inspeção: não baixa conteúdo, busca metadata, contata trackers, DHT ou peers, cria arquivo .torrent nem determina se o conteúdo é seguro ou legal.',
  tool_magnet_link_decoder_empty: 'Cole primeiro um URI magnet.', tool_magnet_link_decoder_error_scheme: 'A entrada deve começar com magnet:?.',
  tool_magnet_link_decoder_example: 'Entrada: URI com xt=urn:btih:0123456789abcdef0123456789abcdef01234567, dn=sample-linux.iso, xl=1048576 e dois tr. Saída: btih válido, nome, 1.048.576 bytes (1 MiB), dois trackers e nenhum aviso.', tool_magnet_link_decoder_example_title: 'Exemplo',
  tool_magnet_link_decoder_faq_a1: 'Não. A análise usa apenas o texto já presente no navegador. A página não contata tracker, nó DHT, peer, web seed ou serviço de metadata e não abre cliente torrent.',
  tool_magnet_link_decoder_faq_a2: 'xt significa tópico exato. Em BitTorrent, urn:btih costuma trazer o info hash v1 em 40 caracteres hex ou 32 Base32. Para v2, urn:btmh geralmente carrega um multihash hexadecimal.',
  tool_magnet_link_decoder_faq_a3: 'tr pode se repetir para anunciar trackers alternativos. O parser mantém todos na ordem original, avisa sobre valores que não são URLs válidas e copia um endereço por linha.',
  tool_magnet_link_decoder_faq_a4: 'Não. Um URI magnet pode identificar o conteúdo sem incluir a metadata exigida por um .torrent. Converter requer buscar esses dados em peers ou outra fonte, o que esta ferramenta local não faz.',
  tool_magnet_link_decoder_faq_a5: 'Não. Decodificação, agrupamento, validação, normalização e JSON acontecem nesta aba. O link não vai para o servidor; mesmo assim, evite links privados em dispositivos compartilhados.',
  tool_magnet_link_decoder_faq_q1: 'Decodificar um link magnet inicia download?', tool_magnet_link_decoder_faq_q2: 'O que significa xt=urn:btih ou urn:btmh?', tool_magnet_link_decoder_faq_q3: 'Por que há vários trackers tr?', tool_magnet_link_decoder_faq_q4: 'É possível converter para um arquivo .torrent?', tool_magnet_link_decoder_faq_q5: 'O link magnet é enviado ao servidor?',
  tool_magnet_link_decoder_field_display_name: 'Nome exibido (dn)', tool_magnet_link_decoder_field_exact_topics: 'Tópicos exatos (xt)', tool_magnet_link_decoder_field_exact_sources: 'Fontes exatas (xs)', tool_magnet_link_decoder_field_other: 'Outros parâmetros', tool_magnet_link_decoder_field_peer_hints: 'Peers sugeridos (x.pe)', tool_magnet_link_decoder_field_size: 'Tamanho exato (xl)', tool_magnet_link_decoder_field_trackers: 'Trackers (tr)', tool_magnet_link_decoder_field_web_seeds: 'Web seeds (ws)',
  tool_magnet_link_decoder_how_body: 'Cole um URI magnet completo e decodifique. O parser separa os pares em ordem, decodifica percentuais e sinais de +, agrupa chaves repetidas, classifica tópicos exatos, confere URLs e tamanhos e gera URI normalizado e JSON. Um escape quebrado fica visível para facilitar o diagnóstico.', tool_magnet_link_decoder_how_title: 'Como funciona',
  tool_magnet_link_decoder_input_label: 'URI magnet', tool_magnet_link_decoder_input_placeholder: 'magnet:?xt=urn:btih:...&dn=...&tr=...', tool_magnet_link_decoder_json_label: 'JSON analisado', tool_magnet_link_decoder_normalized_label: 'URI normalizado', tool_magnet_link_decoder_privacy: 'Executado no navegador: sem upload e sem chamadas a tracker, DHT, peer, web seed ou metadata.', tool_magnet_link_decoder_result_empty: 'Os campos decodificados aparecerão aqui.', tool_magnet_link_decoder_results_title: 'Campos decodificados',
  tool_magnet_link_decoder_rules_body: 'Parâmetros magnet formam um mapa de consulta repetível. Cada ocorrência é mantida e sua forma é conferida sem afirmar que o conteúdo existe.',
  tool_magnet_link_decoder_rules_item_1: 'Campos: xt identifica o tópico; dn é o nome; tr é tracker; xl é o tamanho em bytes; ws é web seed; xs é fonte exata; x.pe é dica de peer. Chaves desconhecidas permanecem.',
  tool_magnet_link_decoder_rules_item_2: 'Hashes: btih aceita 40 caracteres hex ou 32 Base32. btmh aceita multihash hexadecimal de tamanho par; 1220 seguido de 64 hex é a forma SHA-256 comum no BitTorrent v2.',
  tool_magnet_link_decoder_rules_item_3: 'Decodificação: chaves e valores usam percent decoding e + significa espaço. Um escape % malformado é preservado como texto e gera aviso.',
  tool_magnet_link_decoder_rules_item_4: 'Limite: testes de URL e inteiro só detectam sintaxe suspeita; não provam resposta do tracker, existência de metadata, segurança do arquivo ou permissão para compartilhar.', tool_magnet_link_decoder_rules_title: 'Regras do URI magnet',
  tool_magnet_link_decoder_sample: 'Carregar exemplo', tool_magnet_link_decoder_size_bytes: '{bytes} bytes ({human})', tool_magnet_link_decoder_status_invalid: 'Inválido', tool_magnet_link_decoder_status_valid: 'Válido', tool_magnet_link_decoder_status_warning: 'Com avisos', tool_magnet_link_decoder_summary: '{fields} campos, {trackers} trackers, {warnings} avisos', tool_magnet_link_decoder_title: 'Decodificador de link magnet — Info hash e trackers no navegador', tool_magnet_link_decoder_unknown_value: '(valor vazio)',
  tool_magnet_link_decoder_usecase_1: 'Desenvolvimento: confira URI gerado, codificação, tópico exato e trackers repetidos antes de publicar.', tool_magnet_link_decoder_usecase_2: 'Suporte e moderação: veja trackers, web seeds, fontes e peers expostos por um link sem abrir cliente torrent.', tool_magnet_link_decoder_usecase_3: 'Documentação: use o exemplo seguro para explicar extração de info hash e como xt, dn, xl e vários tr são interpretados.', tool_magnet_link_decoder_usecases_title: 'Verificações úteis',
  tool_magnet_link_decoder_warn_bad_encoding: 'Codificação percentual inválida em {key}; o texto original foi mantido.', tool_magnet_link_decoder_warn_bad_hash: 'Info hash incompatível ou malformado: {value}', tool_magnet_link_decoder_warn_bad_peer: 'x.pe deve usar host:porta ou [IPv6]:porta: {value}', tool_magnet_link_decoder_warn_bad_size: 'xl deve ser um tamanho inteiro não negativo em bytes.', tool_magnet_link_decoder_warn_bad_url: '{key} não é uma URL absoluta válida: {value}', tool_magnet_link_decoder_warn_missing_xt: 'Nenhum parâmetro xt de tópico exato foi encontrado.',
};
export default pt;
