/**
 * GENERATED by scripts/tool-modules/merge-all.mjs — DO NOT EDIT.
 * Source of truth: src/site/tool-catalog.d/{slug}.json → page.module / page.export / page.style
 */
import type { SiteLang } from './i18n';
import { renderAddWatermarkPage } from '../pages/addWatermarkPage';
import { renderAddWwwToDnsPage } from '../pages/addWwwToDnsPage';
import { renderArchiveExtractorPage } from '../pages/archiveExtractorPage';
import { renderBase64Page } from '../pages/base64Page';
import { renderBrandColorTokenPackPage } from '../pages/brandColorTokenPackPage';
import { renderBrandStyleGuidePage } from '../pages/brandStyleGuidePage';
import { renderCidrToIpRangePage } from '../pages/cidrToIpRangePage';
import { renderColorFromImagePage } from '../pages/colorFromImagePage';
import { renderCompressPdfPage } from '../pages/compressPdfPage';
import { renderCoreWebVitalsCheckerPage } from '../pages/coreWebVitalsCheckerPage';
import { renderCropPdfPage } from '../pages/cropPdfPage';
import { renderCsvJsonPage } from '../pages/csvJsonPage';
import { renderDomainLookupPage } from '../pages/domainLookupPage';
import { renderFileHashPage } from '../pages/fileHashPage';
import { renderFlipImagePage } from '../pages/flipImagePage';
import { renderHowToCalculateAccelerationPage } from '../pages/howToCalculateAccelerationPage';
import { renderHowToCalculateAgePage } from '../pages/howToCalculateAgePage';
import { renderHowToCalculateAspectRatioPage } from '../pages/howToCalculateAspectRatioPage';
import { renderHowToCalculateBmiPage } from '../pages/howToCalculateBmiPage';
import { renderHowToCalculateBmrTdeePage } from '../pages/howToCalculateBmrTdeePage';
import { renderHowToCalculateBodyFatPage } from '../pages/howToCalculateBodyFatPage';
import { renderHowToCalculateBreakEvenPage } from '../pages/howToCalculateBreakEvenPage';
import { renderHowToCalculateCagrPage } from '../pages/howToCalculateCagrPage';
import { renderHowToCalculateCirclePage } from '../pages/howToCalculateCirclePage';
import { renderHowToCalculateCompoundInterestPage } from '../pages/howToCalculateCompoundInterestPage';
import { renderHowToCalculateConcretePage } from '../pages/howToCalculateConcretePage';
import { renderHowToCalculateConfidenceIntervalPage } from '../pages/howToCalculateConfidenceIntervalPage';
import { renderHowToCalculateContributionMarginPage } from '../pages/howToCalculateContributionMarginPage';
import { renderHowToCalculateDateDifferencePage } from '../pages/howToCalculateDateDifferencePage';
import { renderHowToCalculateDebtPayoffPage } from '../pages/howToCalculateDebtPayoffPage';
import { renderHowToCalculateDensityPage } from '../pages/howToCalculateDensityPage';
import { renderHowToCalculateDiscountPage } from '../pages/howToCalculateDiscountPage';
import { renderHowToCalculateEmiPage } from '../pages/howToCalculateEmiPage';
import { renderHowToCalculateExponentPage } from '../pages/howToCalculateExponentPage';
import { renderHowToCalculateGpaPage } from '../pages/howToCalculateGpaPage';
import { renderHowToCalculateGradientPage } from '../pages/howToCalculateGradientPage';
import { renderHowToCalculateGrossMarginPage } from '../pages/howToCalculateGrossMarginPage';
import { renderHowToCalculateHeartRatePage } from '../pages/howToCalculateHeartRatePage';
import { renderHowToCalculateIdealWeightPage } from '../pages/howToCalculateIdealWeightPage';
import { renderHowToCalculateInflationPage } from '../pages/howToCalculateInflationPage';
import { renderHowToCalculateIrrPage } from '../pages/howToCalculateIrrPage';
import { renderHowToCalculateLogarithmPage } from '../pages/howToCalculateLogarithmPage';
import { renderHowToCalculateMacrosPage } from '../pages/howToCalculateMacrosPage';
import { renderMarginalRevenuePage } from '../pages/marginalRevenuePage';
import { renderHowToCalculateMarkupPage } from '../pages/howToCalculateMarkupPage';
import { renderHowToCalculateMeanPage } from '../pages/howToCalculateMeanPage';
import { renderHowToCalculateMedianPage } from '../pages/howToCalculateMedianPage';
import { renderHowToCalculateNpvPage } from '../pages/howToCalculateNpvPage';
import { renderHowToCalculateOhmsLawPage } from '../pages/howToCalculateOhmsLawPage';
import { renderHowToCalculateOneRepMaxPage } from '../pages/howToCalculateOneRepMaxPage';
import { renderHowToCalculatePValuePage } from '../pages/howToCalculatePValuePage';
import { renderHowToCalculatePacePage } from '../pages/howToCalculatePacePage';
import { renderHowToCalculatePaintPage } from '../pages/howToCalculatePaintPage';
import { renderHowToCalculatePaybackPeriodPage } from '../pages/howToCalculatePaybackPeriodPage';
import { renderHowToCalculatePercentageChangePage } from '../pages/howToCalculatePercentageChangePage';
import { renderHowToCalculatePermutationCombinationPage } from '../pages/howToCalculatePermutationCombinationPage';
import { renderHowToCalculatePresentValuePage } from '../pages/howToCalculatePresentValuePage';
import { renderHowToCalculateProfitMarginPage } from '../pages/howToCalculateProfitMarginPage';
import { renderHowToCalculatePythagoreanTheoremPage } from '../pages/howToCalculatePythagoreanTheoremPage';
import { renderHowToCalculateQuadraticEquationPage } from '../pages/howToCalculateQuadraticEquationPage';
import { renderHowToCalculateRoiPage } from '../pages/howToCalculateRoiPage';
import { renderHowToCalculateRuleOf72Page } from '../pages/howToCalculateRuleOf72Page';
import { renderHowToCalculateSalaryHourlyPage } from '../pages/howToCalculateSalaryHourlyPage';
import { renderHowToCalculateSampleSizePage } from '../pages/howToCalculateSampleSizePage';
import { renderHowToCalculateScientificNotationPage } from '../pages/howToCalculateScientificNotationPage';
import { renderHowToCalculateSignificantFiguresPage } from '../pages/howToCalculateSignificantFiguresPage';
import { renderHowToCalculateSlopePage } from '../pages/howToCalculateSlopePage';
import { renderHowToCalculateStandardDeviationPage } from '../pages/howToCalculateStandardDeviationPage';
import { renderHowToCalculateTilePage } from '../pages/howToCalculateTilePage';
import { renderHowToCalculateTipPage } from '../pages/howToCalculateTipPage';
import { renderHowToCalculateTriangleAreaPage } from '../pages/howToCalculateTriangleAreaPage';
import { renderHowToCalculateVatPage } from '../pages/howToCalculateVatPage';
import { renderHowToCalculateVelocityPage } from '../pages/howToCalculateVelocityPage';
import { renderHowToCalculateVolumePage } from '../pages/howToCalculateVolumePage';
import { renderHowToCalculateZScorePage } from '../pages/howToCalculateZScorePage';
import { renderHreflangGeneratorPage } from '../pages/hreflangGeneratorPage';
import { renderHtmlEntityPage } from '../pages/htmlEntityPage';
import { renderImageBorderPage } from '../pages/imageBorderPage';
import { renderImageCompressPage } from '../pages/imageCompressPage';
import { renderImageCropPage } from '../pages/imageCropPage';
import { renderImageExifPage } from '../pages/imageExifPage';
import { renderImageFormatConverterPage } from '../pages/imageFormatConverterPage';
import { renderImageGrayscalePage } from '../pages/imageGrayscalePage';
import { renderImageMergePage } from '../pages/imageMergePage';
import { renderImageOptimizerPage } from '../pages/imageOptimizerPage';
import { renderImageOverlayPage } from '../pages/imageOverlayPage';
import { renderImageToBase64Page } from '../pages/imageToBase64Page';
import { renderImagesToGifPage } from '../pages/imagesToGifPage';
import { renderImagesToPdfPage } from '../pages/imagesToPdfPage';
import { renderImagesToPptPage } from '../pages/imagesToPptPage';
import { renderImagesToWordPage } from '../pages/imagesToWordPage';
import { renderIndexNowPage } from '../pages/indexNowPage';
import { renderIpAddressPage } from '../pages/ipAddressPage';
import { renderIpRangeToCidrPage } from '../pages/ipRangeToCidrPage';
import { renderJsonSchemaValidatorPage } from '../pages/jsonSchemaValidatorPage';
import { renderJwtDecoderPage } from '../pages/jwtDecoderPage';
import { renderMagnetLinkDecoderPage } from '../pages/magnetLinkDecoderPage';
import { renderMarkdownToHtmlPage } from '../pages/markdownToHtmlPage';
import { renderMeasuringMagneticFieldsPage } from '../pages/measuringMagneticFieldsPage';
import { renderMergePdfPage } from '../pages/mergePdfPage';
import { renderMetaSerpPreviewPage } from '../pages/metaSerpPreviewPage';
import { renderMetaTagGeneratorPage } from '../pages/metaTagGeneratorPage';
import { renderOnPageSeoCheckerPage } from '../pages/onPageSeoCheckerPage';
import { renderOpenGraphPreviewPage } from '../pages/openGraphPreviewPage';
import { renderOrganizePdfPage } from '../pages/organizePdfPage';
import { renderPasswordGeneratorPage } from '../pages/passwordGeneratorPage';
import { renderPdfPageNumbersPage } from '../pages/pdfPageNumbersPage';
import { renderPdfPageToImageSizesPage } from '../pages/pdfPageToImageSizesPage';
import { renderPdfToJpgPage } from '../pages/pdfToJpgPage';
import { renderPdfToMarkdownPage } from '../pages/pdfToMarkdownPage';
import { renderPdfWatermarkPage } from '../pages/pdfWatermarkPage';
import { renderPrivateCidrRangesPage } from '../pages/privateCidrRangesPage';
import { renderProtectPdfPage } from '../pages/protectPdfPage';
import { renderRobotsTxtGeneratorPage } from '../pages/robotsTxtGeneratorPage';
import { renderRotatePdfPage } from '../pages/rotatePdfPage';
import { renderSchemaJsonldGeneratorPage } from '../pages/schemaJsonldGeneratorPage';
import { renderSitemapXmlGeneratorPage } from '../pages/sitemapXmlGeneratorPage';
import { renderSmartWebsiteColorSchemePage } from '../pages/smartWebsiteColorSchemePage';
import { renderSplitPdfPage } from '../pages/splitPdfPage';
import { renderSquareFeetPage } from '../pages/squareFeetPage';
import { renderTerraformCidrsubnetPage } from '../pages/terraformCidrsubnetPage';
import { renderTextDiffPage } from '../pages/textDiffPage';
import { renderTimezoneConverterPage } from '../pages/timezoneConverterPage';
import { renderUnitConverterPage } from '../pages/unitConverterPage';
import { renderUnixTimestampPage } from '../pages/unixTimestampPage';
import { renderUnlockPdfPage } from '../pages/unlockPdfPage';
import { renderUnzipFilePage } from '../pages/unzipFilePage';
import { renderUtmBuilderPage } from '../pages/utmBuilderPage';
import { renderUuidGeneratorPage } from '../pages/uuidGeneratorPage';
import { renderWcagContrastCheckerPage } from '../pages/wcagContrastCheckerPage';
import { renderWebsiteHeadersPage } from '../pages/websiteHeadersPage';
import { renderYamlJsonPage } from '../pages/yamlJsonPage';

export type ToolPageRenderFn = (
	lang: SiteLang,
	defaultLang: SiteLang,
	enabledLangs: SiteLang[]
) => string | void;

/** slug → render function for registerToolPage */
export const TOOL_PAGE_RENDERERS: Record<string, ToolPageRenderFn> = {
	'add-watermark': (lang, defaultLang, enabled) => renderAddWatermarkPage({ lang, defaultLang, enabledLangs: enabled }),
	'add-www-to-dns': (lang, defaultLang, enabled) => renderAddWwwToDnsPage({ lang, defaultLang, enabledLangs: enabled }),
	'archive-extractor': (lang, defaultLang, enabled) => renderArchiveExtractorPage({ lang, defaultLang, enabledLangs: enabled }),
	'base64': (lang, defaultLang, enabled) => renderBase64Page({ lang, defaultLang, enabledLangs: enabled }),
	'brand-color-token-pack': (lang, defaultLang, enabled) => renderBrandColorTokenPackPage({ lang, defaultLang, enabledLangs: enabled }),
	'brand-style-guide': (lang, defaultLang, enabled) => renderBrandStyleGuidePage({ lang, defaultLang, enabledLangs: enabled }),
	'cidr-to-ip-range': (lang, defaultLang, enabled) => renderCidrToIpRangePage({ lang, defaultLang, enabledLangs: enabled }),
	'color-from-image': (lang, defaultLang, enabled) => renderColorFromImagePage({ lang, defaultLang, enabledLangs: enabled }),
	'compress-pdf': (lang, defaultLang, enabled) => renderCompressPdfPage({ lang, defaultLang, enabledLangs: enabled }),
	'core-web-vitals-checker': (lang, defaultLang, enabled) => renderCoreWebVitalsCheckerPage({ lang, defaultLang, enabledLangs: enabled }),
	'crop-pdf': (lang, defaultLang, enabled) => renderCropPdfPage({ lang, defaultLang, enabledLangs: enabled }),
	'csv-json': (lang, defaultLang, enabled) => renderCsvJsonPage({ lang, defaultLang, enabledLangs: enabled }),
	'domain-lookup': (lang, defaultLang, _enabled) => renderDomainLookupPage(lang, defaultLang),
	'file-hash': (lang, defaultLang, enabled) => renderFileHashPage({ lang, defaultLang, enabledLangs: enabled }),
	'flip-image': (lang, defaultLang, enabled) => renderFlipImagePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-acceleration': (lang, defaultLang, enabled) => renderHowToCalculateAccelerationPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-age': (lang, defaultLang, enabled) => renderHowToCalculateAgePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-aspect-ratio': (lang, defaultLang, enabled) => renderHowToCalculateAspectRatioPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-bmi': (lang, defaultLang, enabled) => renderHowToCalculateBmiPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-bmr-tdee': (lang, defaultLang, enabled) => renderHowToCalculateBmrTdeePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-body-fat': (lang, defaultLang, enabled) => renderHowToCalculateBodyFatPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-break-even': (lang, defaultLang, enabled) => renderHowToCalculateBreakEvenPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-cagr': (lang, defaultLang, enabled) => renderHowToCalculateCagrPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-circle': (lang, defaultLang, enabled) => renderHowToCalculateCirclePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-compound-interest': (lang, defaultLang, enabled) => renderHowToCalculateCompoundInterestPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-concrete': (lang, defaultLang, enabled) => renderHowToCalculateConcretePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-confidence-interval': (lang, defaultLang, enabled) => renderHowToCalculateConfidenceIntervalPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-contribution-margin': (lang, defaultLang, enabled) => renderHowToCalculateContributionMarginPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-date-difference': (lang, defaultLang, enabled) => renderHowToCalculateDateDifferencePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-debt-payoff': (lang, defaultLang, enabled) => renderHowToCalculateDebtPayoffPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-density': (lang, defaultLang, enabled) => renderHowToCalculateDensityPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-discount': (lang, defaultLang, enabled) => renderHowToCalculateDiscountPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-emi': (lang, defaultLang, enabled) => renderHowToCalculateEmiPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-exponent': (lang, defaultLang, enabled) => renderHowToCalculateExponentPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-gpa': (lang, defaultLang, enabled) => renderHowToCalculateGpaPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-gradient': (lang, defaultLang, enabled) => renderHowToCalculateGradientPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-gross-margin': (lang, defaultLang, enabled) => renderHowToCalculateGrossMarginPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-heart-rate': (lang, defaultLang, enabled) => renderHowToCalculateHeartRatePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-ideal-weight': (lang, defaultLang, enabled) => renderHowToCalculateIdealWeightPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-inflation': (lang, defaultLang, enabled) => renderHowToCalculateInflationPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-irr': (lang, defaultLang, enabled) => renderHowToCalculateIrrPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-logarithm': (lang, defaultLang, enabled) => renderHowToCalculateLogarithmPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-macros': (lang, defaultLang, enabled) => renderHowToCalculateMacrosPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-marginal-revenue': (lang, defaultLang, enabled) => renderMarginalRevenuePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-markup': (lang, defaultLang, enabled) => renderHowToCalculateMarkupPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-mean': (lang, defaultLang, enabled) => renderHowToCalculateMeanPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-median': (lang, defaultLang, enabled) => renderHowToCalculateMedianPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-npv': (lang, defaultLang, enabled) => renderHowToCalculateNpvPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-ohms-law': (lang, defaultLang, enabled) => renderHowToCalculateOhmsLawPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-one-rep-max': (lang, defaultLang, enabled) => renderHowToCalculateOneRepMaxPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-p-value': (lang, defaultLang, enabled) => renderHowToCalculatePValuePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-pace': (lang, defaultLang, enabled) => renderHowToCalculatePacePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-paint': (lang, defaultLang, enabled) => renderHowToCalculatePaintPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-payback-period': (lang, defaultLang, enabled) => renderHowToCalculatePaybackPeriodPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-percentage-change': (lang, defaultLang, enabled) => renderHowToCalculatePercentageChangePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-permutation-combination': (lang, defaultLang, enabled) => renderHowToCalculatePermutationCombinationPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-present-value': (lang, defaultLang, enabled) => renderHowToCalculatePresentValuePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-profit-margin': (lang, defaultLang, enabled) => renderHowToCalculateProfitMarginPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-pythagorean-theorem': (lang, defaultLang, enabled) => renderHowToCalculatePythagoreanTheoremPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-quadratic-equation': (lang, defaultLang, enabled) => renderHowToCalculateQuadraticEquationPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-roi': (lang, defaultLang, enabled) => renderHowToCalculateRoiPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-rule-of-72': (lang, defaultLang, enabled) => renderHowToCalculateRuleOf72Page({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-salary-hourly': (lang, defaultLang, enabled) => renderHowToCalculateSalaryHourlyPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-sample-size': (lang, defaultLang, enabled) => renderHowToCalculateSampleSizePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-scientific-notation': (lang, defaultLang, enabled) => renderHowToCalculateScientificNotationPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-significant-figures': (lang, defaultLang, enabled) => renderHowToCalculateSignificantFiguresPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-slope': (lang, defaultLang, enabled) => renderHowToCalculateSlopePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-standard-deviation': (lang, defaultLang, enabled) => renderHowToCalculateStandardDeviationPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-tile': (lang, defaultLang, enabled) => renderHowToCalculateTilePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-tip': (lang, defaultLang, enabled) => renderHowToCalculateTipPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-triangle-area': (lang, defaultLang, enabled) => renderHowToCalculateTriangleAreaPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-vat': (lang, defaultLang, enabled) => renderHowToCalculateVatPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-velocity': (lang, defaultLang, enabled) => renderHowToCalculateVelocityPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-volume': (lang, defaultLang, enabled) => renderHowToCalculateVolumePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-z-score': (lang, defaultLang, enabled) => renderHowToCalculateZScorePage({ lang, defaultLang, enabledLangs: enabled }),
	'hreflang-generator': (lang, defaultLang, enabled) => renderHreflangGeneratorPage({ lang, defaultLang, enabledLangs: enabled }),
	'html-entity': (lang, defaultLang, enabled) => renderHtmlEntityPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-border': (lang, defaultLang, enabled) => renderImageBorderPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-compress': (lang, defaultLang, enabled) => renderImageCompressPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-crop': (lang, defaultLang, enabled) => renderImageCropPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-exif': (lang, defaultLang, enabled) => renderImageExifPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-format-converter': (lang, defaultLang, enabled) => renderImageFormatConverterPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-grayscale': (lang, defaultLang, enabled) => renderImageGrayscalePage({ lang, defaultLang, enabledLangs: enabled }),
	'image-merge': (lang, defaultLang, enabled) => renderImageMergePage({ lang, defaultLang, enabledLangs: enabled }),
	'image-optimizer': (lang, defaultLang, enabled) => renderImageOptimizerPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-overlay': (lang, defaultLang, enabled) => renderImageOverlayPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-to-base64': (lang, defaultLang, enabled) => renderImageToBase64Page({ lang, defaultLang, enabledLangs: enabled }),
	'images-to-gif': (lang, defaultLang, enabled) => renderImagesToGifPage({ lang, defaultLang, enabledLangs: enabled }),
	'images-to-pdf': (lang, defaultLang, enabled) => renderImagesToPdfPage({ lang, defaultLang, enabledLangs: enabled }),
	'images-to-ppt': (lang, defaultLang, enabled) => renderImagesToPptPage({ lang, defaultLang, enabledLangs: enabled }),
	'images-to-word': (lang, defaultLang, enabled) => renderImagesToWordPage({ lang, defaultLang, enabledLangs: enabled }),
	'indexnow': (lang, defaultLang, enabled) => renderIndexNowPage({ lang, defaultLang, enabledLangs: enabled }),
	'ip-address': (lang, defaultLang, _enabled) => renderIpAddressPage(lang, defaultLang),
	'ip-range-to-cidr': (lang, defaultLang, enabled) => renderIpRangeToCidrPage({ lang, defaultLang, enabledLangs: enabled }),
	'json-schema-validator': (lang, defaultLang, enabled) => renderJsonSchemaValidatorPage({ lang, defaultLang, enabledLangs: enabled }),
	'jwt-decoder': (lang, defaultLang, enabled) => renderJwtDecoderPage({ lang, defaultLang, enabledLangs: enabled }),
	'magnet-link-decoder': (lang, defaultLang, enabled) => renderMagnetLinkDecoderPage({ lang, defaultLang, enabledLangs: enabled }),
	'markdown-to-html': (lang, defaultLang, enabled) => renderMarkdownToHtmlPage({ lang, defaultLang, enabledLangs: enabled }),
	'measuring-magnetic-fields': (lang, defaultLang, enabled) => renderMeasuringMagneticFieldsPage({ lang, defaultLang, enabledLangs: enabled }),
	'merge-pdf': (lang, defaultLang, enabled) => renderMergePdfPage({ lang, defaultLang, enabledLangs: enabled }),
	'meta-serp-preview': (lang, defaultLang, enabled) => renderMetaSerpPreviewPage({ lang, defaultLang, enabledLangs: enabled }),
	'meta-tag-generator': (lang, defaultLang, enabled) => renderMetaTagGeneratorPage({ lang, defaultLang, enabledLangs: enabled }),
	'on-page-seo-checker': (lang, defaultLang, enabled) => renderOnPageSeoCheckerPage({ lang, defaultLang, enabledLangs: enabled }),
	'open-graph-preview': (lang, defaultLang, enabled) => renderOpenGraphPreviewPage({ lang, defaultLang, enabledLangs: enabled }),
	'organize-pdf': (lang, defaultLang, enabled) => renderOrganizePdfPage({ lang, defaultLang, enabledLangs: enabled }),
	'password-generator': (lang, defaultLang, enabled) => renderPasswordGeneratorPage({ lang, defaultLang, enabledLangs: enabled }),
	'pdf-page-numbers': (lang, defaultLang, enabled) => renderPdfPageNumbersPage({ lang, defaultLang, enabledLangs: enabled }),
	'pdf-page-to-image-sizes': (lang, defaultLang, enabled) => renderPdfPageToImageSizesPage({ lang, defaultLang, enabledLangs: enabled }),
	'pdf-to-jpg': (lang, defaultLang, enabled) => renderPdfToJpgPage({ lang, defaultLang, enabledLangs: enabled }),
	'pdf-to-markdown': (lang, defaultLang, enabled) => renderPdfToMarkdownPage({ lang, defaultLang, enabledLangs: enabled }),
	'pdf-watermark': (lang, defaultLang, enabled) => renderPdfWatermarkPage({ lang, defaultLang, enabledLangs: enabled }),
	'private-cidr-ranges': (lang, defaultLang, enabled) => renderPrivateCidrRangesPage({ lang, defaultLang, enabledLangs: enabled }),
	'protect-pdf': (lang, defaultLang, enabled) => renderProtectPdfPage({ lang, defaultLang, enabledLangs: enabled }),
	'robots-txt-generator': (lang, defaultLang, enabled) => renderRobotsTxtGeneratorPage({ lang, defaultLang, enabledLangs: enabled }),
	'rotate-pdf': (lang, defaultLang, enabled) => renderRotatePdfPage({ lang, defaultLang, enabledLangs: enabled }),
	'schema-jsonld-generator': (lang, defaultLang, enabled) => renderSchemaJsonldGeneratorPage({ lang, defaultLang, enabledLangs: enabled }),
	'sitemap-xml-generator': (lang, defaultLang, enabled) => renderSitemapXmlGeneratorPage({ lang, defaultLang, enabledLangs: enabled }),
	'smart-website-color-scheme': (lang, defaultLang, enabled) => renderSmartWebsiteColorSchemePage({ lang, defaultLang, enabledLangs: enabled }),
	'split-pdf': (lang, defaultLang, enabled) => renderSplitPdfPage({ lang, defaultLang, enabledLangs: enabled }),
	'square-feet': (lang, defaultLang, enabled) => renderSquareFeetPage({ lang, defaultLang, enabledLangs: enabled }),
	'terraform-cidrsubnet': (lang, defaultLang, enabled) => renderTerraformCidrsubnetPage({ lang, defaultLang, enabledLangs: enabled }),
	'text-diff': (lang, defaultLang, enabled) => renderTextDiffPage({ lang, defaultLang, enabledLangs: enabled }),
	'timezone-converter': (lang, defaultLang, enabled) => renderTimezoneConverterPage({ lang, defaultLang, enabledLangs: enabled }),
	'unit-converter': (lang, defaultLang, enabled) => renderUnitConverterPage({ lang, defaultLang, enabledLangs: enabled }),
	'unix-timestamp': (lang, defaultLang, enabled) => renderUnixTimestampPage({ lang, defaultLang, enabledLangs: enabled }),
	'unlock-pdf': (lang, defaultLang, enabled) => renderUnlockPdfPage({ lang, defaultLang, enabledLangs: enabled }),
	'unzip-file': (lang, defaultLang, enabled) => renderUnzipFilePage({ lang, defaultLang, enabledLangs: enabled }),
	'utm-builder': (lang, defaultLang, enabled) => renderUtmBuilderPage({ lang, defaultLang, enabledLangs: enabled }),
	'uuid-generator': (lang, defaultLang, enabled) => renderUuidGeneratorPage({ lang, defaultLang, enabledLangs: enabled }),
	'wcag-contrast-checker': (lang, defaultLang, enabled) => renderWcagContrastCheckerPage({ lang, defaultLang, enabledLangs: enabled }),
	'website-headers': (lang, defaultLang, _enabled) => renderWebsiteHeadersPage(lang, defaultLang),
	'yaml-json': (lang, defaultLang, enabled) => renderYamlJsonPage({ lang, defaultLang, enabledLangs: enabled }),
};
