/**
 * GENERATED by scripts/tool-modules/merge-all.mjs — DO NOT EDIT.
 * Source of truth: src/site/tool-catalog.d/{slug}.json → page.module / page.export / page.style
 */
import type { SiteLang } from './i18n';
import { renderAddWatermarkPage } from '../pages/addWatermarkPage';
import { renderAddWwwToDnsPage } from '../pages/addWwwToDnsPage';
import { renderBrandColorTokenPackPage } from '../pages/brandColorTokenPackPage';
import { renderBrandStyleGuidePage } from '../pages/brandStyleGuidePage';
import { renderColorFromImagePage } from '../pages/colorFromImagePage';
import { renderCsvJsonPage } from '../pages/csvJsonPage';
import { renderFlipImagePage } from '../pages/flipImagePage';
import { renderHowToCalculateBmiPage } from '../pages/howToCalculateBmiPage';
import { renderHowToCalculateGradientPage } from '../pages/howToCalculateGradientPage';
import { renderMarginalRevenuePage } from '../pages/marginalRevenuePage';
import { renderHowToCalculatePercentageChangePage } from '../pages/howToCalculatePercentageChangePage';
import { renderHowToCalculateRoiPage } from '../pages/howToCalculateRoiPage';
import { renderHtmlEntityPage } from '../pages/htmlEntityPage';
import { renderImageBorderPage } from '../pages/imageBorderPage';
import { renderImageCompressPage } from '../pages/imageCompressPage';
import { renderImageCropPage } from '../pages/imageCropPage';
import { renderImageExifPage } from '../pages/imageExifPage';
import { renderImageFormatConverterPage } from '../pages/imageFormatConverterPage';
import { renderImageGrayscalePage } from '../pages/imageGrayscalePage';
import { renderImageMergePage } from '../pages/imageMergePage';
import { renderImageOptimizerPage } from '../pages/imageOptimizerPage';
import { renderImageOverlayPage } from '../pages/imageOverlayPage';
import { renderImageToBase64Page } from '../pages/imageToBase64Page';
import { renderImagesToGifPage } from '../pages/imagesToGifPage';
import { renderImagesToPdfPage } from '../pages/imagesToPdfPage';
import { renderImagesToPptPage } from '../pages/imagesToPptPage';
import { renderImagesToWordPage } from '../pages/imagesToWordPage';
import { renderIndexNowPage } from '../pages/indexNowPage';
import { renderIpAddressPage } from '../pages/ipAddressPage';
import { renderJsonSchemaValidatorPage } from '../pages/jsonSchemaValidatorPage';
import { renderMarkdownToHtmlPage } from '../pages/markdownToHtmlPage';
import { renderSmartWebsiteColorSchemePage } from '../pages/smartWebsiteColorSchemePage';
import { renderSquareFeetPage } from '../pages/squareFeetPage';
import { renderTextDiffPage } from '../pages/textDiffPage';
import { renderWcagContrastCheckerPage } from '../pages/wcagContrastCheckerPage';
import { renderWebsiteHeadersPage } from '../pages/websiteHeadersPage';
import { renderYamlJsonPage } from '../pages/yamlJsonPage';

export type ToolPageRenderFn = (
	lang: SiteLang,
	defaultLang: SiteLang,
	enabledLangs: SiteLang[]
) => string | void;

/** slug → render function for registerToolPage */
export const TOOL_PAGE_RENDERERS: Record<string, ToolPageRenderFn> = {
	'add-watermark': (lang, defaultLang, enabled) => renderAddWatermarkPage({ lang, defaultLang, enabledLangs: enabled }),
	'add-www-to-dns': (lang, defaultLang, enabled) => renderAddWwwToDnsPage({ lang, defaultLang, enabledLangs: enabled }),
	'brand-color-token-pack': (lang, defaultLang, enabled) => renderBrandColorTokenPackPage({ lang, defaultLang, enabledLangs: enabled }),
	'brand-style-guide': (lang, defaultLang, enabled) => renderBrandStyleGuidePage({ lang, defaultLang, enabledLangs: enabled }),
	'color-from-image': (lang, defaultLang, enabled) => renderColorFromImagePage({ lang, defaultLang, enabledLangs: enabled }),
	'csv-json': (lang, defaultLang, enabled) => renderCsvJsonPage({ lang, defaultLang, enabledLangs: enabled }),
	'flip-image': (lang, defaultLang, enabled) => renderFlipImagePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-bmi': (lang, defaultLang, enabled) => renderHowToCalculateBmiPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-gradient': (lang, defaultLang, enabled) => renderHowToCalculateGradientPage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-marginal-revenue': (lang, defaultLang, enabled) => renderMarginalRevenuePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-percentage-change': (lang, defaultLang, enabled) => renderHowToCalculatePercentageChangePage({ lang, defaultLang, enabledLangs: enabled }),
	'how-to-calculate-roi': (lang, defaultLang, enabled) => renderHowToCalculateRoiPage({ lang, defaultLang, enabledLangs: enabled }),
	'html-entity': (lang, defaultLang, enabled) => renderHtmlEntityPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-border': (lang, defaultLang, enabled) => renderImageBorderPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-compress': (lang, defaultLang, enabled) => renderImageCompressPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-crop': (lang, defaultLang, enabled) => renderImageCropPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-exif': (lang, defaultLang, enabled) => renderImageExifPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-format-converter': (lang, defaultLang, enabled) => renderImageFormatConverterPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-grayscale': (lang, defaultLang, enabled) => renderImageGrayscalePage({ lang, defaultLang, enabledLangs: enabled }),
	'image-merge': (lang, defaultLang, enabled) => renderImageMergePage({ lang, defaultLang, enabledLangs: enabled }),
	'image-optimizer': (lang, defaultLang, enabled) => renderImageOptimizerPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-overlay': (lang, defaultLang, enabled) => renderImageOverlayPage({ lang, defaultLang, enabledLangs: enabled }),
	'image-to-base64': (lang, defaultLang, enabled) => renderImageToBase64Page({ lang, defaultLang, enabledLangs: enabled }),
	'images-to-gif': (lang, defaultLang, enabled) => renderImagesToGifPage({ lang, defaultLang, enabledLangs: enabled }),
	'images-to-pdf': (lang, defaultLang, enabled) => renderImagesToPdfPage({ lang, defaultLang, enabledLangs: enabled }),
	'images-to-ppt': (lang, defaultLang, enabled) => renderImagesToPptPage({ lang, defaultLang, enabledLangs: enabled }),
	'images-to-word': (lang, defaultLang, enabled) => renderImagesToWordPage({ lang, defaultLang, enabledLangs: enabled }),
	'indexnow': (lang, defaultLang, enabled) => renderIndexNowPage({ lang, defaultLang, enabledLangs: enabled }),
	'ip-address': (lang, defaultLang, _enabled) => renderIpAddressPage(lang, defaultLang),
	'json-schema-validator': (lang, defaultLang, enabled) => renderJsonSchemaValidatorPage({ lang, defaultLang, enabledLangs: enabled }),
	'markdown-to-html': (lang, defaultLang, enabled) => renderMarkdownToHtmlPage({ lang, defaultLang, enabledLangs: enabled }),
	'smart-website-color-scheme': (lang, defaultLang, enabled) => renderSmartWebsiteColorSchemePage({ lang, defaultLang, enabledLangs: enabled }),
	'square-feet': (lang, defaultLang, enabled) => renderSquareFeetPage({ lang, defaultLang, enabledLangs: enabled }),
	'text-diff': (lang, defaultLang, enabled) => renderTextDiffPage({ lang, defaultLang, enabledLangs: enabled }),
	'wcag-contrast-checker': (lang, defaultLang, enabled) => renderWcagContrastCheckerPage({ lang, defaultLang, enabledLangs: enabled }),
	'website-headers': (lang, defaultLang, _enabled) => renderWebsiteHeadersPage(lang, defaultLang),
	'yaml-json': (lang, defaultLang, enabled) => renderYamlJsonPage({ lang, defaultLang, enabledLangs: enabled }),
};
